### ISSUE TITLE
Support for --skip-crds when using Helm.

### ISSUE THREAD

**Issue by servo1x** [argoproj/argo-cd#4723] opened 2020-11-02 04:17 UTC
# Summary

When deploying duplicate helm charts with crds, there should be an option to skip rendering crds.

# Motivation

We have a helm v3 chart that has crds but also supports deploying controllers that are namespaced, so there can be cases where the chart could be deployed under separate releases. We're not sure it makes sense to have every chart render with the crd, how would ArgoCD handle this anyway? The crds become owned by the last chart to sync?

# Proposal

Provide support for `--skip-crds` to skip rendering of crds.

**Comment by jessesuen** [comment] 2020-11-02 21:51
This proposal makes sense with helm 3. We'll need a new helm setting `helm.skipCRDs` and honor that in `helm template` command 

@servo1x are you willing to put forward a fix?

Relevant documentation:
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

**Comment by wmgroot** [comment] 2020-11-20 19:15
Would it make sense to allow a generic `extraArgs` field? That might help future-proof against new helm features.
```
helm:
  extraArgs:
    - --skip-crds
```

**Comment by wmgroot** [comment] 2020-11-20 19:17
This is a large pain when dealing with the kube-prometheus-stack chart, which can easily be applied multiple times in the same cluster to create additional prometheus clusters.

**Comment by infa-kparida** [comment] 2020-11-23 08:16
Agree with @wmgroot . While dealing with kube-prometheus-stack this option will be life saviour

**Comment by diranged** [comment] 2020-12-08 22:10
:+1: this is also critical when using argo to deploy argo with helmv3... you don't want deletions of one of your argo stacks to try to tear out the CRDs.

**Comment by diranged** [comment] 2020-12-08 22:28
Just to add to this - it seems impossible to force the API version to use HelmV2. If you use a `Chart.yaml` and a `requirements.yaml` file, then ArgoCD 1.7.9 will always use HelmV3 it seems. Even if I go into the Application and add `spec.source.helm.version: v2`, Argo goes and _deletes it_ from the resource.

**Comment by servo1x** [comment] 2020-12-09 04:34
For the Chart.yaml the api version needs to be v1 to use helm v2, helm v3 uses api v2.

**Comment by diranged** [comment] 2020-12-09 05:17
Hmm. I definitely am aware of that and was careful to test that. However, now I cannot reproduce it. I will go back and see if I can roll this back to HelmV2 properly. I still support the idea of adding the ability to skip-crd's for HelmV3.

**Comment by wrdls** [comment] 2021-01-19 06:57
I'd need to be able to set this flag for https://github.com/external-secrets/kubernetes-external-secrets/tree/master/charts/kubernetes-external-secrets

They have their own controller to install CRDs and recommend installing with `--skip-crds`.

**Comment by shinebayar-g** [comment] 2022-01-10 22:15
Any progress on this? kube-prometheus-stack is causing huge pain..

**Comment by shinebayar-g** [comment] 2022-01-14 22:01
This is now implemented in https://github.com/argoproj/argo-cd/pull/8012 Duplicate of https://github.com/argoproj/argo-cd/issues/6252

**Closed** 2022-01-14 22:30 UTC
Labels: enhancement
