### ISSUE TITLE
[UI] Filters not applied correctly when UI refresh app list

### ISSUE THREAD

**Issue by gaeljw** [argoproj/argo-cd#9690] opened 2022-06-16 11:38 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The ArgoCD UI (dashboard) displays applications that belongs to a project Y even though filters are set to show only applications of project X.

See below screenshot.

**To Reproduce**

At first, apps only of project X (matching the filter) are displayed, but then every few seconds, apps from other projects appear.

- Have 2 ArgoCD projects X and Y, with at least one ArgoCD application in each project
- Filter for project = X on the left menu
- Only app for project X is displayed
- Wait few seconds
- App of other projects appear ignoring the filter on project X

This seems to appear quickier (or maybe it's just a feeling) when there apps in "progressing" state.

**Expected behavior**

When filters are set, only apps matching the filter should be displayed.

**Screenshots**

In below screenshot, after several seconds, we don't even see any application that match the filter:

![image](https://user-images.githubusercontent.com/18280708/174061359-2d50b939-fd76-4ab9-815f-6b9c799a12ea.png)

**Version**

```shell
v2.4.0+91aefab
```

**Logs**

**Comment by rouke-broersma** [comment] 2022-06-16 13:33
Seems like a duplicate of #9651

**Comment by crenshaw-dev** [comment] 2022-06-16 14:11
Agreed. @gaeljw closing as duplicate, lmk if I'm incorrect and that it should be reopened.  :-)

**Closed by crenshaw-dev** 2022-06-16 14:11 UTC
Labels: bug
