### ISSUE TITLE
ArgoCD Application  display OutOfSync and repeatedly synchronized

### ISSUE THREAD

**Issue by shifeichen** [argoproj/argo-cd#17964] opened 2024-04-25 08:08 UTC
**argocd version**

v2.9.6+ba62a0a

**what is the bug**

Application OutOfSync, The HPA resources in the application is repeatedly synchronized.

**To Reproduce**

Adjust the order of these two parameters in your code

**Expected behavior**

sync ok

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/33510601/78c31bc1-5d39-4f1d-85a3-9528ac4606a2)

![image](https://github.com/argoproj/argo-cd/assets/33510601/27b929c5-e58e-48a0-9aad-64f2b25d780b)

![image](https://github.com/argoproj/argo-cd/assets/33510601/a03b7b7f-dfcb-4aec-8329-14189fcb766a)

**Comment by rumstead** [comment] 2024-04-25 19:54
https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#diffing-customization should cover this

> For Horizontal Pod Autoscaling (HPA) objects, the HPA controller is known to reorder spec.metrics in a specific order. See [kubernetes issue #74099](https://github.com/kubernetes/kubernetes/issues/74099). To work around this, you can order spec.metrics in Git in the same order that the controller prefers.

**Comment by Sineaggi** [comment] 2024-04-25 20:44
Duplicate of https://github.com/argoproj/argo-cd/issues/7846

**Comment by blakepettersson** [comment] 2024-05-09 12:10
Indeed a duplicate of #7846

**Closed by blakepettersson** 2024-05-09 12:10 UTC
Labels: bug
