### ISSUE TITLE
Updage the imagePullPolicy

### ISSUE THREAD

**Issue by warjiang** [argoproj/argo-cd#20495] opened 2024-10-23 03:40 UTC
# Summary

What change you think needs making.
Optimize imagePullPolicy for some image. I've grep the image pullPolicy in the `manifests/install.yaml`, result as following:
![image](https://github.com/user-attachments/assets/5e11e575-6caf-4b95-b478-04a777758592)

for short:
| image name   | pullPolicy | 
| ------ | ---- |
| quay.io/argoproj/argocd:v2.12.6   | Always   | 
| ghcr.io/dexidp/dex:v2.38.0   | Always   | 
| redis:7.0.15-alpine   | Always   | 

I think there is no need to pull the image always. At least the default policy should not be 'Always', default policy 'IfNotPresent' is better.

# Motivation

Please give examples of your use case, e.g. when would you use this.

I've use the argocd for some offline case， so policy indicated always pull image will not be suitable for me. For most cases, I think default policy 'IfNotPresent' is better.

# Proposal

How do you think this should be implemented?

**Comment by crenshaw-dev** [comment] 2024-10-23 03:43
Duplicate of https://github.com/argoproj/argo-cd/issues/20252

**Closed by crenshaw-dev** 2024-10-23 03:43 UTC
Labels: enhancement
