### ISSUE TITLE
Argo 2.3.0 does not remember type of view selection

### ISSUE THREAD

**Issue by alen-z** [argoproj/argo-cd#8713] opened 2022-03-08 09:43 UTC
**Describe the bug**

List view is reset back to block (big blocks) view after returning to `/applications` in Argo CD.

**To Reproduce**

1. Select list view of applications in the main Argo CD page
2. Go to any application
3. Return to main `/applications` page
-> list view is reset back to block view

**Expected behavior**

Keep selected view type after changing it.

**Screenshots**

**Version**

Argo CD 2.3.0

**Comment by rodrigo14miguel** [comment] 2022-03-08 11:31
duplicate of #8702

**Closed** 2022-03-08 12:49 UTC
Labels: bug
