### ISSUE TITLE
Argocd UI crashing when im creating apps 

### ISSUE THREAD

**Issue by AyoSal** [argoproj/argo-cd#15939] opened 2023-10-13 01:36 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Argocd UI crashing when im creating apps, I created an application using app of apps pattern with other apps.
The first one is created, when i do a sync on this app it works within the app wherein i can see the apps created there. but when i click on applications in ArgoCD  it crashes..

**To Reproduce**

All apps should work as normal
<img width="547" alt="Screenshot 2023-10-12 at 9 35 30 PM" src="https://github.com/argoproj/argo-cd/assets/27664278/5ce2b053-50ed-4a47-ba4c-77f88bbfc6cc">

**Screenshots**
screenshot attached
**Version**

```shell
Paste the output from `argocd version` here.
```
argocd version output is >>>>

argocd: v2.7.10+469f257
  BuildDate: 2023-07-31T22:22:19Z
  GitCommit: 469f25753b2be7ef0905a11632a6382060bcae99
  GitTreeState: clean
  GoVersion: go1.19.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.4+c279299

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment] 2023-10-13 18:31
Maybe a duplicate: https://github.com/argoproj/argo-cd/issues/15545

**Comment by jgwest** [comment] 2024-02-10 11:41
Dupe of #15545

**Closed by jgwest** 2024-02-10 11:41 UTC
Labels: bug
