### ISSUE TITLE
Cookie too long when using Dex with LDAP

### ISSUE THREAD

**Issue by rimasgo** [argoproj/argo-cd#7012] opened 2021-08-18 09:51 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ yes ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ yes ] I've included steps to reproduce the bug.
* [ yes ] I've pasted the output of `argocd version`.

**Describe the bug**

I have added LDAP configuration for login to argocd console and it was forking just fine for a while. Then I got added to multiple new groups on AD server.  It seems that with these new groups added I am hitting cookie size limit. 

The user is part of 610 groups and the average group name length is 27 characters. 

Dex configuration:

 dex.config: |
    connectors:
      # LDAP
      - type: ldap
        name: OpenLDAP
        id: ldap
        config:
          host: ldaps.int.domain.com:636
          insecureNoSSL: false
          insecureSkipVerify: false
          rootCAData: "base64CAstring"
          bindDN: readonly@int.domain.com
          bindPW: password
          usernamePrompt: INT Account
          userSearch:
            baseDN: DC=INT,DC=DOMAIN,DC=COM
            filter: "(objectClass=user)"
            username: sAMAccountName
            idAttr: DN
            emailAttr: name
            nameAttr: sAMAccountName
          groupSearch:
            baseDN: DC=INT,DC=DOMAIN,DC=COM
            filter: "(objectClass=group)"
            userMatchers:
            - userAttr: DN
              groupAttr: member
            nameAttr: sAMAccountName

**To Reproduce**

1.  Configure LDAP for Dex
2.  Create a user that can login
3.  Add user to multiple groups to increase cookie size during login. As mentioned above group count on my case is 610 for the user and the average group name length is 27 characters

**Expected behavior**

Login should work with any amount of groups.

**Screenshots**

n/a

**Version**

```shell
>argocd version
argocd: v2.0.5+4c94d88
  BuildDate: 2021-07-22T20:56:29Z
  GitCommit: 4c94d886f56bcb2f9d5b3251fdc049c2d1354b88
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.0.3+8d2b13d
  BuildDate: 2021-05-27T17:38:37Z
  GitCommit: 8d2b13d733e1dff7d1ad2c110ed31be4804406e2
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
Logs from dex server:

 

time="2021-08-18T07:54:23Z" level=info msg="performing ldap search DC=INT,DC=DOMAIN,DC=COM sub (&(objectClass=user)(sAMAccountName=butkus))"
time="2021-08-18T07:54:23Z" level=info msg="username \"butkus\" mapped to entry CN=Butkus\\, R,OU=Users,OU=LDN,OU=EMEA,OU=GLB,DC=INT,DC=DOMAIN,DC=com"
time="2021-08-18T07:54:23Z" level=info msg="performing ldap search DC=INT,DC=DOMAIN,DC=COM sub (&(objectClass=group)(member=CN=Butkus\\,OU=Users,OU=LDN,OU=EMEA,OU=GLB,DC=INT,DC=DOMAIN,DC=com))"
time="2021-08-18T07:54:23Z" level=info msg="login successful: connector \"ldap\", username=\"butkus\", preferred_username=\"\", email=\"email\", groups=["somewhat 610 groups"]

Log from browser:

claims={"at_hash":"hash","aud":"argo-cd","email":"email","email_verified":true,"exp":1629366147,"groups":["somewhat 610 groups"],"iat":1629279747,"iss":"https://argocd-argocd.apps.cluster.int.domain.com/api/dex","name":"butkus","sub":"NOTACTUALNcLCBSaW1hbnRhczogSVQgKExETiks"}, err=invalid cookie value, at 25858 long it is longer than the max length of 20190
```

**Comment by mccrackend** [comment] 2021-08-23 13:38
What ingress controller are you using?  I've had to battle this issue with Dex and users have tons of ldap groups before using nginx-ingress.  Bumping some of those properties was what resolved that for me, particularly these guys if I recall:

```
  client-header-buffer-size: 256k
  large-client-header-buffers: 4 256k
  proxy-buffer-size: 16k
```

**Comment by wtam2018** [comment] 2021-08-23 14:17
component:sso

**Comment by alexmt** [comment] 2021-08-23 21:59
The long cookie issue was supposed to be fixed by https://github.com/argoproj/argo-cd/pull/5497 . Argo CD is supposed to split long cookie into longer chunks. I'm pretty sure functionality works but probably we don't handle some edge case correctly.

**Comment by wtam2018** [comment] 2021-08-24 04:56
It looks like the cookie length exceeds the max length.
```
 at 25858 long it is longer than the max length of 20190
```

```
const maxCookieNumber = 5
const maxCookieLength = 4093
```

**Comment by mateustanaka** [comment] 2021-09-02 11:52
@mccrackend We've added those properties in our nginx-ingress but still didn't work. We are using Azure AD and facing a similar error, but with the headers, probably caused by the amount of groups too.

> 2021/09/02 11:38:24 [error] 56#56: *35863 upstream sent too big header while reading response header from upstream, client: xxx.xxx.xx.xxx, server: myargowebsite.com, request: "GET /auth/callback?code=xxxxx

**Comment by mateustanaka** [comment] 2021-09-02 14:22
We had a similar issue but regarding a big header, probably because of the amount of groups (we are using Azure AD). 

> 2021/09/02 11:38:24 [error] 56#56: *35863 upstream sent too big header while reading response header from upstream, client: xxx.xxx.xx.xxx, server: myargowebsite.com, request: "GET /auth/callback?code=xxxxx

We also using nginx-ingress for ArgoCD server and we have increased the [proxy-buffer-size](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/configmap.md#proxy-buffer-size) and it worked for us.

```
nginx-ingress:
    config:
      proxy-buffer-size: "128k"
```

**Closed** 2021-10-21 21:37 UTC
Labels: bug, good first issue
