### ISSUE TITLE
Pull-Based Deployment Model with Argo CD

### ISSUE THREAD

**Issue by riteshnanda09** [argoproj/argo-cd#16841] opened 2024-01-12 01:54 UTC
#Summary

I am interested in exploring the possibility of Argo CD supporting a pull-based deployment model, utilizing an 'Argo CD Agent'. This model would serve as a complement to the existing push-based approach, providing an alternative solution for specific deployment environments.

#Motivation

The current push-based model of Argo CD is versatile and caters to a wide array of use cases. However, it falls short in scenarios where the Kubernetes cluster's control plane API endpoint is not externally routable. This can be a critical limitation in environments prioritizing high security and privacy, where access to the control plane is intentionally restricted. A pull-based model could effectively address this limitation, making Argo CD viable in more secure and isolated setups.

I am reaching out to the Argo CD community and core contributors to initiate a conversation on this topic. I am curious if there have been any previous discussions about implementing a pull-based deployment model. Furthermore, I seek the community's perspective on the feasibility and relevance of introducing an 'Argo CD Agent' for this purpose, within the broader scope of Argo CD's evolution and user needs.

**Comment by omgapuppy** [comment] 2024-01-12 12:19
There's a good bit of insight re same from a commercial product - it'd be nice to have this also in the OSS Argo CD https://akuity.io/blog/argo-cd-architecture-redesigned

**Comment by blakepettersson** [comment] 2024-01-12 21:47
Duplicate of #4512

**Closed by blakepettersson** 2024-01-12 21:47 UTC
Labels: enhancement
