### ISSUE TITLE
valuesObject Refresh button get stuck 

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj/argo-cd#15191] opened 2023-08-23 16:55 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have migrated all my ArgoCD application to use valuesObject and randomly the refresh button get stuck but the sync is still hapenning in the background and the UI still show outdated components.

![Screenshot from 2023-08-23 12-25-58](https://github.com/argoproj/argo-cd/assets/17641873/bc83a3e1-16fe-41bf-801f-7487bf5eb480)
![Screenshot from 2023-08-23 12-25-47](https://github.com/argoproj/argo-cd/assets/17641873/0a260c96-6c02-47a3-9619-f6830b5ba1d6)

To fix the problem I need to remove the valuesObject path that is being show in the error log of the application-controller and then re add the value again (I guess it clear the cache).

**Expected behavior**
The refresh button and the UI components should by synced correctly.

**Version**
ArgoCD v2.8.1+2bc94af

**Logs**

```
time="2023-08-23T16:46:11Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:22Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:32Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:11Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:22Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:32Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:41Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:47Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
time="2023-08-23T16:46:52Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"postgresql\"" application=argocd/keycloak
```

**Comment by crenshaw-dev** [comment] 2023-08-23 17:29
I believe this is a duplicate of https://github.com/argoproj/argo-cd/issues/15126, let me know if I'm wrong!

**Closed by crenshaw-dev** 2023-08-23 17:29 UTC
Labels: bug
