### ISSUE TITLE
Agrocd diff problem

### ISSUE THREAD

**Issue by Shahard2** [argoproj/argo-cd#3643] opened 2020-05-25 11:40 UTC
Hello, I've recently installed agro, and I have the next issue:
It always shows that on the diff and makes the status 'OutOfSync':

![image](https://user-images.githubusercontent.com/34960759/82809791-9710d580-9e95-11ea-8a13-d3e44ae27f95.png)

And those values are already there in the 'LIVE MANIFEST'

Any clue?

**Comment by jutley** [comment] 2020-05-26 15:45
This appears to be the same issue as what I reported in #2865. This bug has been around for quite a long time, unfortunately.

**Comment by Shahard2** [comment] 2020-05-26 16:13
> This appears to be the same issue as what I reported in #2865. This bug has been around for quite a long time, unfortunately.

So what's the workaround for now?

**Comment by jutley** [comment] 2020-05-26 17:01
It's been a while since I looked into this, so I'm a little rusty.

Are all the environment variables in the live manifest also in the source manifest? I think we specifically saw issues when there were environment variables that were only in the live manifest.

**Comment by alexmt** [comment] 2020-05-27 18:19
I'm pretty sure this is a duplicate of https://github.com/argoproj/argo-cd/issues/2865 . 

I agree that bug is pretty bad. Just to explain why it is taking so much time to fix it:  After implementing the fix we've discovered that update diff implementation always detects a deviation in StatefulSet due to (https://github.com/kubernetes/kubernetes/issues/74819) . ( `kubectl diff` does it too ) . It won't be easy to fix it in Kubernetes so we have to add workaround and test **all** built-in kubernetes types :( .

We've discussed the bug with the team and agreed to fix it as a first priority in v1.7 .  1.6 testing has started already, but it still might take at least a month to get first 1.7 rc.

**Comment by alexmt** [comment] 2020-05-27 18:19
Lets use #2865  to track the fix.

**Closed by alexmt** 2020-05-27 18:19 UTC
Labels: bug
