### ISSUE TITLE
path not supported when using ref with multiple sources

### ISSUE THREAD

**Issue by axel7083** [argoproj/argo-cd#14567] opened 2023-07-18 08:03 UTC
**Describe the bug**

- considering git repository with a file located at `content/hello/helm-values.yaml`

When using `path`, with a ref defined, the ref is not pointing to the path. It is still reference to the root of the source.
The following would give an error. 

```yaml
      - repoURL: <helm-repo>
        targetRevision: <rev>
        chart: <chart>
        helm:
          valueFiles:
            - $values/helm-values.yaml
      - repoURL: <git>
        targetRevision: HEAD
        ref: values
        path: content/hello
```

To fix it, we would have to use `$values/content/hello/helm-values.yaml`.

**Version**

```shell
argocd: v2.7.6+00c914a.dirty
  BuildDate: 2023-06-20T20:51:13Z
  GitCommit: 00c914a948d9e8ad99be8bd82a368fbdeba12f88
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Comment by crenshaw-dev** [comment] 2023-07-18 13:58
This is expected behavior and is documented here: https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

> In the above example, the prometheus chart will use the value file from git.example.gom/org/value-files.git. $values resolves to the root of the value-files repository. 

If the docs need more clarity, I'd be happy to review a clarifying PR! Closing for now, since it's not technically a bug, but I can reopen if you want to reuse this issue to track a docs update.

**Closed by crenshaw-dev** 2023-07-18 13:58 UTC
Labels: bug
