### ISSUE TITLE
Cannot create private repo with empty credentials field

### ISSUE THREAD

**Issue by rkt2spc** [argoproj/argo-cd#3291] opened 2020-03-26 05:21 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I use AWS CodeCommit and IAM Role to authenticate git remote calls
This is done via [git credentials.helper](https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html)

Using this, the credentials fields must be empty when I create the repo (will be fetched by credentials.helper)

This upsets the ArgoCD server as it forces private repo to have credentials fields explicitly configured.
![image](https://user-images.githubusercontent.com/17026876/77612710-ca051e80-6f63-11ea-8fbe-003a1b4023f6.png)

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.

**Expected behavior**

Credentials should be optional as are indicated on the UI.
![image](https://user-images.githubusercontent.com/17026876/77612760-e739ed00-6f63-11ea-9c40-e629fa9ec872.png)

**Version**

```shell
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment] 2020-03-26 08:37
Hi @rocketspacer, can you share a little more about your setup please? 

ArgoCD does not make use of credential helper, and supports only HTTP basic auth and SSH for authentication to Git repositories. The authentication required error comes from the repository server, not because the credentials are left empty.

I believe you modified the repo-server image to include your AWS IAM configuration?

**Comment by rocketspacer** [comment] 2020-03-27 08:13
@jannfis Yes I modified the repo-server image. I exec-ed in into the container I checked that I'm able to clone the project using [credentials.helper](https://git-scm.com/docs/gitcredentials)

Does the git interface (go-git I presume?) that ArgoCD uses respect the git configurations?

**Comment by jannfis** [comment] 2020-03-27 08:50
@rocketspacer I fear that your use-case is not supported then, as ArgoCD does not honour any custom Git configuration made in i.e. `~/.gitconfig`. ArgoCD uses a combination of go-git and a native Git client - the former is used for simple operations from the API server (like, getting details about the repository) while the latter is used for all the dirty work in the Repository server. The repository server uses the `./hack/git-ask-pass.sh` wrapper as the script passed to `GIT_ASKPASS` when running Git, so you might want to take a look there.

As I said, the only current methods for authentication are Basic Auth and SSH. But feel free to open an Enhancement Proposal for supporting AWS IAM with Git.

**Comment by rocketspacer** [comment] 2020-03-27 09:06
From https://git-scm.com/docs/gitcredentials
```
Without any credential helpers defined, Git will try the following strategies to ask the user for usernames and passwords
```

But I defined it 🤔 Let me take a closer look

**Comment by jannfis** [comment] 2020-03-27 09:16
You might want to configure your credential helper in the repository server's system Git configuration at `/etc/gitconfig` and see if that works (ArgoCD sets `HOME` to `/dev/null` before executing the Git binary for various reasons), but it will still not solve the problem with the API server - which is used to connect the repository in the first place, and uses go-git for that.

**Comment by rocketspacer** [comment] 2020-03-29 22:08
I tried 
`git config --system credentials.helper '!f() { HOME=/home/argocd aws codecommit credential-helper $@ ; }; f'`
to fix the `HOME` directory issue and also the system-wide git config.

Manual cloning works but argo-cd still doesn't. The error is too verbose but I suspect the part where it uses go-git didn't work.

The logs from the repo-server
```
time="2020-03-29T21:58:50Z" level=error msg="finished unary call with code Unknown" error="authentication required" grpc.code=Unknown grpc.method=GenerateManifest grpc.request.deadline="2020-03-29T21:59:49Z" grpc.service=repository.RepoServerService grpc.start_time="2020-03-29T21:58:49Z" grpc.time_ms=20.344 span.kind=server system=grpc
```

**Comment by jannfis** [comment] 2020-04-11 09:23
@rocketspacer I think this is not a bug, and can be either closed or converted to a feature request. Please feel free to open an enhancement proposal, with the requirements you might have for AWS IAM connected Git repositories.

**Comment by rocketspacer** [comment] 2021-04-08 22:52
Confirmed go git doesn't support credentials helper scripts
https://github.com/go-git/go-git/issues/28
https://github.com/go-git/go-git/issues/250

**Comment by jgwest** [comment] 2024-02-08 21:21
Closing based on Jann's comment above.

**Closed by jgwest** 2024-02-08 21:21 UTC
Labels: bug, invalid, type:usability, component:git
