### ISSUE TITLE
Wildcard Support for Namespace Selection in Linked Clusters

### ISSUE THREAD

**Issue by ykoer** [argoproj/argo-cd#20307] opened 2024-10-09 09:17 UTC
# Proposal
In my organization, we have many team-based ArgoCD instances. Each instance should only have access to namespaces that start with the corresponding team name. Keeping the list of namespaces up to date in the cluster secrets field is quite a challenge. This proposal aims to introduce wildcard support for specifying namespaces in the cluster secret, as shown in the example below. Have you included this feature in your roadmap?

```
kind: Secret
apiVersion: v1
metadata:
  name: argocd-prod-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: ...
  name: prod-cluster
  namespaces: team1--*
  server: ...
```

**Comment by blakepettersson** [comment] 2024-10-09 09:45
Duplicate of #10054

It makes sense to have this feature (the previous proposal asks for regex, but globbing IMO is more consistent with how it's done elsewhere in Argo CD). There's no roadmap for it, so if you want it a PR is always welcome.

**Closed** 2024-10-17 14:18 UTC
Labels: enhancement, component:multi-cluster, component:namespaced-apps
