### ISSUE TITLE
Fails to sync application with hook included.

### ISSUE THREAD

**Issue by AndriMar** [argoproj/argo-cd#2734] opened 2019-11-18 10:00 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When syncing application with hooks it fails when it comes to the hook.
This worked in v1.2 but failed after update of argocd

**To Reproduce**

Create an application with hook included and use `generateName` in the hook template.

**Expected behavior**

Is to sync the application.

**Version**

argocd:v1.3.0-rc5

**Logs**

```
Recovered from panic: runtime error: slice bounds out of range
goroutine 125 [running]:
runtime/debug.Stack(0xc001c919f8, 0x18518a0, 0x2d05a60)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation.func1(0xc00c8ff680, 0xc001c939b8, 0xc000373320, 0xc001c93a38)
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:590 +0x60
panic(0x18518a0, 0x2d05a60)
    /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/argoproj/argo-cd/controller.(*syncContext).getSyncTasks(0xc000615380, 0xc001c92b50, 0x1, 0x1, 0xc001c92e58)
    /go/src/github.com/argoproj/argo-cd/controller/sync.go:419 +0x2389
github.com/argoproj/argo-cd/controller.(*syncContext).sync(0xc000615380)
    /go/src/github.com/argoproj/argo-cd/controller/sync.go:209 +0x2b9
github.com/argoproj/argo-cd/controller.(*appStateManager).SyncAppState(0xc00033d700, 0xc009d1b500, 0xc00c8ff6d0)
    /go/src/github.com/argoproj/argo-cd/controller/sync.go:193 +0x101c
github.com/argoproj/argo-cd/controller.(*ApplicationController).processRequestedAppOperation(0xc000373320, 0xc009d1b500)
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:623 +0x3df
github.com/argoproj/argo-cd/controller.(*ApplicationController).processAppOperationQueueItem(0xc000373320, 0x1)
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:464 +0x644
github.com/argoproj/argo-cd/controller.(*ApplicationController).Run.func4()
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:411 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005102a0)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005102a0, 0x3b9aca00, 0x0, 0x1, 0xc00008ad20)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005102a0, 0x3b9aca00, 0xc00008ad20)
    /go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo-cd/controller.(*ApplicationController).Run
    /go/src/github.com/argoproj/argo-cd/controller/appcontroller.go:410 +0x370

```

Looks like this line is the problem:
https://github.com/argoproj/argo-cd/blob/release-1.3/controller/sync.go#L419
And to  be more specific `sc.syncRes.Revision[0:7]`

**Comment by alexec** [comment] 2019-11-18 18:13
Hi,

Can you please provide some repro steps? 

Alex

**Comment by rajatjindal** [comment] 2019-12-31 11:12
I ran into same issue today. 

here is what my syncResult looks like:

```yaml
    syncResult:
      revision: 1.59.0
      source:
        chart: tools-api
        helm:
          parameters:
          - name: ingress.fqdn
            value: some-domain.example.com
          - name: global.cluster.name
            value: dev-test3-labawsuse
          valueFiles:
          - values-test5.yaml
        repoURL: https://some-helm-url
        targetRevision: 1.59.0
```

In the app, I was trying to use a postsync hook (type Pod) with pod.metadata.name == "" and generateName = "tools-api-tests-"

I was expecting it to generate the new name, but it ran into this issue.

Now looking at that code, its trying to get the slice out of syncResult.Revision[0:7], and if i read it correctly, syncResult.Revision in my case is "1.59.0", and possibly that is why it ran into this issue.

Please let me know if I can provide more info.

Thanks
Rajat Jindal

**Comment by alexec** [comment] 2019-12-31 17:50
This should be fixed @alexmt

**Comment by rajatjindal** [comment] 2019-12-31 18:37
I am willing to submit PR for this. do we know why we want part of revision in there and not the complete revision?

**Comment by rajatjindal** [comment] 2019-12-31 19:24
I've added a unit test to reproduce the crash.

looking for some advice on what fix would u recommend, and then I can submit a PR with the fix.

**Comment by alexmt** [comment] 2019-12-31 22:25
thank you for adding the unit test @rajatjindal ! will look into bug as well

**Comment by alexmt** [comment] 2020-06-24 14:48
Issue is fixed by https://github.com/argoproj/argo-cd/commit/9fdd782854f08ce5dc475199293a3b2661860a14

**Closed by alexmt** 2020-06-24 14:48 UTC
Labels: bug, component:core
