### ISSUE TITLE
go mod vendor not fetching latest argocd packages

### ISSUE THREAD

**Issue by samuel-sujith** [argoproj/argo-cd#4873] opened 2020-11-20 09:50 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ Yes] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ Yes] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Latest argocd packages not being pulled from VCS

**A clear and concise description of what the bug is.**

My go.mod file has the below requirement coded
go 1.14

require (
	github.com/argoproj/argo-cd v1.7.9

However when I run the go mod vendor, it does not fetch the latest api versions. One of the examples is the types.go in v1alpha1 folder where the EnableOCI flag in the repository type is missing.

This is causing issues in the argo-cd cli repo.go since the program expects repo.EnableOCI flag.

There are more such errors which I could see but then this is one of them.

**A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.**

Use the below line in go.mod and run go mod vendor
go 1.14

require (
	github.com/argoproj/argo-cd v1.7.9

**Expected behavior**

The latest code should be present in the APi types.go 

**Screenshots**

**Version**
1.7.9

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment] 2020-11-20 21:43
Duplicate of https://github.com/argoproj/argo-cd/issues/4055

**Closed by jessesuen** 2020-11-20 21:43 UTC
Labels: bug

**Comment by samuel-sujith** [comment] 2020-11-23 08:17
I dont think this is the same as #4055 .

WHen i try to vendor argo-cd into the vendor folder, I am not getting the latest source code.

One of the examples is the types.go in v1alpha1 folder where the EnableOCI flag in the repository type is missing.

Even go get github.com/argoproj/argo-cd is not retrieving the latest source code from github.

Sujith.
