### ISSUE TITLE
Not able to terminate the syncing operation and fails with an error on UI

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [argoproj/argo-cd#16254] opened 2023-11-06 20:35 UTC
**Describe the bug**

Not able to terminate the syncing operation through UI

**To Reproduce**

The argocd UI shows the sync in progress and cannot able to terminate and when I try to terminate it says no operation in progress

**Expected behavior**

The syncing should stop and when i see the status through console the status is correct.

**Screenshots**

<img width="283" alt="image" src="https://github.com/argoproj/argo-cd/assets/6253303/4c51fe52-0595-44c5-a0f0-0686165d56b3">

<img width="316" alt="image" src="https://github.com/argoproj/argo-cd/assets/6253303/9de769ec-b5ac-4abc-99d8-0e1da3da8f90">

**Version**
2.9.0

**Comment by s-u-b-h-a-k-a-r** [comment] 2023-11-07 05:07
It happens with consul and cert-manager helm charts
<img width="343" alt="image" src="https://github.com/argoproj/argo-cd/assets/6253303/4644f8f4-5d76-400f-87cd-e9d62a79c784">

**Comment by jgwest** [comment] 2024-02-10 11:24
Dupe of https://github.com/argoproj/argo-cd/issues/11088

**Closed by jgwest** 2024-02-10 11:24 UTC
Labels: bug
