### ISSUE TITLE
Persistent ignoreDifferences change in application status leads to overconsumption

### ISSUE THREAD

**Issue by Kneas** [argoproj/argo-cd#20107] opened 2024-09-25 14:36 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Removing a compare specific information from the application manifest generated a large amount of reconciliations.
We believe that it's triggered by [this function](https://github.com/argoproj/argo-cd/blob/master/controller/appcontroller.go#L1762) which continually checks for differences between the application live state and the comparedTo state. 
Once the app is refreshed, the comparedTo doesn't change and keeps on triggering this function.
Including all of the application controller pods, this led the CPU consumption from 6 cores to 36.
We've worked around it by removing the application's status and waiting for its regeneration, which comparedTo field didn't contain this ignoreDifferences anymore.

**To Reproduce**

We encountered the issue after removing 
```
                "ignoreDifferences": [
                    {
                        "group": "apps",
                        "kind": "Deployment",
                        "jsonPointers": ["/spec/revisionHistoryLimit"],
                    }
                 ]
```
                    
From our applications manifest's spec, to centralize it in the argocd-cm.

**Expected behavior**

This change should be reconciled then removed from the comparedTo in the app's status

**Version**

```shell
argocd: v2.11.4+e1284e1
  BuildDate: 2024-07-02T19:17:02Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.4+e1284e1```
```
**Logs**

```
time="2024-09-24T14:13:37Z" level=debug msg=specChanged application=argocd/<appName> useDiffCache=false
time="2024-09-24T14:13:40Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"server\":\"<endpoint>\"},\"ignoreDifferences\":[{\"group\":\"apps\",\"jsonPointers\":[\"/spec/revisionHistoryLimit\"],\"kind\":\"Deployment\"}],\"source\":{\"repoURL\":\"\"},\"sources\":[{\"helm\":{\"valueFiles\":[\"$values/global/values.yaml\",\"$values/envs/dev/values.yaml\",\"$values/clusters/<appName>/values.yaml\"]},\"path\":\"helm/\",\"repoURL\":\"git@github.com:<repoPath>\",\"targetRevision\":\"main\"},{\"ref\":\"values\",\"repoURL\":\"git@github.com:<valuesRepoPath>\",\"targetRevision\":\"main\"}]}}}}" application=argocd/<appName>
time="2024-09-24T14:13:41Z" level=info msg="Update successful" application=argocd/<appName>
time="2024-09-24T14:13:41Z" level=info msg="Reconciliation completed" application=argocd/<appName> dedup_ms=7 dest-name= dest-namespace= dest-server="<endpoint>" diff_ms=2177 fields.level=2 git_ms=94 health_ms=28 live_ms=54 patch_ms=208 setop_ms=0 settings_ms=0 sync_ms=4 time_ms=3642
time="2024-09-24T14:13:41Z" level=info msg="Refreshing app status (spec.ignoreDifferences differs), level (2)" application=argocd/<appName>
time="2024-09-24T14:13:41Z" level=info msg="Comparing app state (cluster: <endpoint>, namespace: )" application=argocd/<appName>
time="2024-09-24T14:13:41Z" level=debug msg="Generating Manifest for source {git@github.com:<repoPath> helm/ main &ApplicationSourceHelm{ValueFiles:[$values/global/values.yaml $values/envs/dev/values.yaml $values/clusters/<appName>/values.yaml],Parameters:[]HelmParameter{},ReleaseName:,Values:,FileParameters:[]HelmFileParameter{},Version:,PassCredentials:false,IgnoreMissingValueFiles:false,SkipCrds:false,ValuesObject:nil,} nil nil nil  } revision main"
time="2024-09-24T14:13:41Z" level=info msg="GetRepoObjs stats" application=argocd/<appName> build_options_ms=0 helm_ms=96 plugins_ms=0 repo_ms=0 time_ms=101 unmarshal_ms=3 version_ms=0
time="2024-09-24T14:13:41Z" level=debug msg="Retrieved live manifests" application=argocd/<appName>
time="2024-09-24T14:13:41Z" level=debug msg=specChanged application=argocd/<appName> useDiffCache=false
time="2024-09-24T14:13:43Z" level=info msg="Normalized app spec: {\"status\":{\"sync\":{\"comparedTo\":{\"destination\":{\"server\":\"<endpoint>\"},\"ignoreDifferences\":[{\"group\":\"apps\",\"jsonPointers\":[\"/spec/revisionHistoryLimit\"],\"kind\":\"Deployment\"}],\"source\":{\"repoURL\":\"\"},\"sources\":[{\"helm\":{\"valueFiles\":[\"$values/global/values.yaml\",\"$values/envs/dev/values.yaml\",\"$values/clusters/<appName>/values.yaml\"]},\"path\":\"helm/\",\"repoURL\":\"git@github.com:<repoPath>\",\"targetRevision\":\"main\"},{\"ref\":\"values\",\"repoURL\":\"git@github.com:<valuesRepoPath>\",\"targetRevision\":\"main\"}]}}}}" application=argocd/<appName>
time="2024-09-24T14:13:44Z" level=info msg="Update successful" application=argocd/<appName>
time="2024-09-24T14:13:44Z" level=info msg="Reconciliation completed" application=argocd/<appName> dedup_ms=7 dest-name= dest-namespace= dest-server="<endpoint>" diff_ms=2125 fields.level=2 git_ms=102 health_ms=27 live_ms=44 patch_ms=215 setop_ms=0 settings_ms=0 sync_ms=4 time_ms=3552
time="2024-09-24T14:13:44Z" level=info msg="Refreshing app status (spec.ignoreDifferences differs), level (2)" application=argocd/<appName>
time="2024-09-24T14:13:44Z" level=info msg="Comparing app state (cluster: <endpoint>, namespace: )" application=argocd/<appName>
```

**Comment by crenshaw-dev** [comment] 2024-09-25 15:01
Looks like a duplicate of https://github.com/argoproj/argo-cd/issues/18151. Please try 2.11.8, which should include the fix.

**Closed by crenshaw-dev** 2024-09-25 15:01 UTC
Labels: bug
