### ISSUE TITLE
Bannercontent not shown after update

### ISSUE THREAD

**Issue by FredrikAugust** [argoproj/argo-cd#17477] opened 2024-03-12 11:35 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After updating from v2.9.5 to v.2.10.2 I can no longer see the bannercontent in the banner at the top of the screen. The space for it is there, however.

**To Reproduce**

I have the two following banner-related lines in my `cm` config:

```yaml
ui.bannercontent: "You are now in the staging environment"
ui.bannerpermanent: true
```

**Expected behavior**

The `bannercontent` should be shown.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/7691547/3046c896-3bc4-41ae-b051-eb380baf277a)

**Version**

```json
{
    "Version": "v2.10.2+fcf5d8c",
    "BuildDate": "2024-03-01T21:24:51Z",
    "GitCommit": "fcf5d8c2381b68ab1621b90be63913b12cca2eb7",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.2+gc309b6f",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Comment by mcyrrer** [comment] 2024-03-24 13:54
Just a observation
It looks like it is broken but a workaround that works for me is to add

ui.bannerposition: "top"

Then the banner pops up again.

**Comment by mfischler** [comment] 2024-04-02 17:19
Ran into the same issue updating from 2.8.9 to 2.10.5. Adding 'ui.bannerposition: "top"' to the argocd-cm fixed the issue.

I also inject an additional CSS to use a custom background color and font color.

`ui.bannerposition: "top"`

**Comment by yahel2410** [comment] 2024-04-03 10:19
Happened to me as well on `2.10.5`

**Comment by tomerle03** [comment] 2024-09-05 13:23
> Ran into the same issue updating from 2.8.9 to 2.10.5. Adding 'ui.bannerposition: "top"' to the argocd-cm fixed the issue.
> 
> 
> 
> I also inject an additional CSS to use a custom background color and font color.
> 
> 
> 
> `ui.bannerposition: "top"`

It happed to me too on version 2.10.5 but this solved it. Thanks!

**Comment by andrii-korotkov-verkada** [comment] 2024-11-11 12:13
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by mcyrrer** [comment] 2024-11-17 15:51
Looks like
    ui.bannercontent: "Banner message linked to a URL"
    ui.bannerpermanent: "true"

Works fine again.

Tested with only those to lines but also with 
ui.bannerposition: "top" 
and  "bottom" and both. All test ok.

{
    "Version": "v2.13.0+347f221",
    "BuildDate": "2024-11-04T12:09:06Z",
    "GitCommit": "347f221adba5599ef4d5f12ee572b2c17d01db4d",
    "GitTreeState": "clean",
    "GoVersion": "go1.23.1",
    "Compiler": "gc",
    "Platform": "linux/arm64",
    "KustomizeVersion": "v5.4.3 2024-07-19T16:40:33Z",
    "HelmVersion": "v3.15.4+gfa9efb0",
    "KubectlVersion": "v0.31.0",
    "JsonnetVersion": "v0.20.0"
}

**Comment by andrii-korotkov-verkada** [comment] 2024-11-17 17:54
Sounds good. I'll close this then, but let me know if the issue still happens.

**Closed by andrii-korotkov-verkada** 2024-11-17 17:54 UTC
Labels: bug, workaround, regression, component:ui, version:EOL
