### ISSUE TITLE
Add cluster via API Rest and deploy Application Fails

### ISSUE THREAD

**Issue by facundoalarcon** [argoproj/argo-cd#7944] opened 2021-12-15 15:29 UTC
I'm trying to add cluster via the [API](https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/) and works, but when try to deploy an application this fails. This works if I add the cluster via CLI. For example.

If I'm login via the terminal `argocd login localhost:8080` 
and then use  `argocd cluster arn:aws:eks:region:account-id:cluster/name`

I think this use my kubeconfig file, but I not sure.

I can deploy new applications.

but If I add the cluster via API, In the first place I'm logging and get the session token using the `POST` method in `https://localhost:8080/api/v1/session` 
with this body:
```
{
  "username": "user"
   "password": "password"
}

```
 And trying to deploy an application, for example, executing `POST` method in this endpoint  `https://localhost:8080/api/v1/clusters?upsert=true` with this body:
```
{
    "server": "https://server.gr7.region.eks.amazonaws.com",
    "name": "arn:aws:eks:region:account-id:cluster/name",
    "config": {
        "tlsClientConfig": {
            "insecure": false,
            "caData": "ca-from-kubeconfig"
        }
    },
    "info": {
        "serverVersion": "1.21+"
    }
}
```
the cluster is added but, when I try to deploy an application, this action fails and "unknow" error message is returned
![image](https://user-images.githubusercontent.com/12551772/146213938-9c88aaf6-5b5e-42cc-8a1c-3a80278647c6.png)

![image](https://user-images.githubusercontent.com/12551772/146214098-1f2cad57-d80b-4448-9b17-b23114bf7ea5.png)

I'm trying to deploy this application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://server.gr7.region.eks.amazonaws.com'
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
```
The same app via API (using `POST` method in `https://localhost:8080/api/v1/applications`) is
```
 {
            "metadata": {
                "name": "guestbook",
                "namespace": "argocd",
                "managedFields": [
                    {
                        "manager": "argocd-application-controller",
                        "operation": "Update",
                        "apiVersion": "argoproj.io/v1alpha1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:status": {
                                "f:conditions": {},
                                "f:health": {
                                    "f:status": {}
                                },
                                "f:reconciledAt": {},
                                "f:sync": {
                                    "f:comparedTo": {
                                        "f:destination": {
                                            "f:namespace": {},
                                            "f:server": {}
                                        },
                                        "f:source": {
                                            "f:path": {},
                                            "f:repoURL": {},
                                            "f:targetRevision": {}
                                        }
                                    },
                                    "f:status": {}
                                }
                            }
                        }
                    },
                    {
                        "manager": "argocd-server",
                        "operation": "Update",
                        "apiVersion": "argoproj.io/v1alpha1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:spec": {
                                ".": {},
                                "f:destination": {
                                    ".": {},
                                    "f:namespace": {},
                                    "f:server": {}
                                },
                                "f:project": {},
                                "f:source": {
                                    ".": {},
                                    "f:path": {},
                                    "f:repoURL": {},
                                    "f:targetRevision": {}
                                },
                                "f:syncPolicy": {
                                    ".": {},
                                    "f:automated": {}
                                }
                            },
                            "f:status": {
                                ".": {},
                                "f:health": {
                                    ".": {},
                                    "f:status": {}
                                },
                                "f:summary": {},
                                "f:sync": {
                                    ".": {},
                                    "f:comparedTo": {
                                        ".": {},
                                        "f:destination": {
                                            ".": {},
                                            "f:namespace": {},
                                            "f:server": {}
                                        },
                                        "f:source": {
                                            ".": {},
                                            "f:path": {},
                                            "f:repoURL": {},
                                            "f:targetRevision": {}
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            },
            "spec": {
                "source": {
                    "repoURL": "https://github.com/argoproj/argocd-example-apps",
                    "path": "guestbook",
                    "targetRevision": "HEAD"
                },
                "destination": {
                    "server": "https://server.gr7.region.eks.amazonaws.com",
                    "namespace": "default"
                },
                "project": "default",
                "syncPolicy": {
                    "automated": {}
                }
            }
        }

```
I'm trying to add the cluster via sale and use `GET` method in `https://localhost:8080/api/v1/clusters` to get the cluster config, delete from Argo and add via `POST` in `https://localhost:8080/api/v1/clusters?upsert=true` endpoint to use the same configuration, but also fails. I think is for certificates reasons, but really I don't know.

_Originally posted by @facundoalarcon in https://github.com/argoproj/argo-cd/discussions/7943_

**Comment by todaywasawesome** [comment] 2023-06-28 22:32
Duplicate of https://github.com/argoproj/argo-cd/issues/13571

**Closed by todaywasawesome** 2023-06-28 22:32 UTC
