### ISSUE TITLE
Upon upgrading from EKS 1.29 to 1.30 argocd is marking assigned nodeports as out of sync

### ISSUE THREAD

**Issue by ssilbory** [argoproj/argo-cd#18764] opened 2024-06-21 17:32 UTC
**Describe the bug**

We don't assign a nodeport service's node port.  Since the upgrade argocd believes that the undefined nodeport means it's out of sync.

**To Reproduce**

- upgrade to eks 1.30

**Expected behavior**

The node port should be ignored. This does not seem to only only effect node ports as I see it in a few deployments as well.  Mainly it's node ports for us.

**Screenshots**
![Screenshot 2024-06-21 at 10 15 40 AM](https://github.com/argoproj/argo-cd/assets/5289120/578f504a-ca3c-498e-aacc-af3192e06be1)

**Version**

```
argocd: v2.11.3+3f344d5
  BuildDate: 2024-06-06T09:27:36Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.3+3f344d5
  BuildDate: 2024-06-06T08:42:00Z
  GitCommit: 3f344d54a4e0bbbb4313e1c19cfe1e544b162598
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0

Cluster version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0-eks-036c24b
```

**Comment by ssilbory** [comment] 2024-06-21 17:39
I see this in a handful of deployments as well.
![deployment](https://github.com/argoproj/argo-cd/assets/5289120/6428acc4-7252-4d94-8a52-59040e792725)

**Comment by ssilbory** [comment] 2024-06-21 18:37
Extra step to reproduce.
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - ServerSideApply=true

Removing ServerSideApply=true  fixes the issue.

**Comment by wanddynosios** [comment] 2024-06-26 07:01
We are seeing the same thing for different deployments, as well as in the clientConfig.caBundle field of mutating/validatingwebhookconfigurations.

**Comment by PG2000** [comment] 2024-06-26 07:44
+1

**Comment by pkruk** [comment] 2024-06-26 09:22
I have the same issue in few components:

Deployment:
```

- name:xxxx_CM_CONFIGMAP |   |  
-- | -- | --
229 | value: 51faa14c9ebebf7424f46b337d03dd5b3a9fbf65

```

Nginx ingress service:

```
nodePort: 31917
```

And ofc caBundles.

**Comment by ssilbory** [comment] 2024-06-26 22:44
Note that we initially thought this was triggered by upgrading the final node groups to 1.30 in staging.  We have been running with the cluster backplane at 1.30 for a while.  We also starting seeing this with the prod clusters that still have 1.29 node groups and 1.30 backplanes.  Prod has been running this way for at least a week.  So I assume there was some upgrade rolled out to 1.30 cluster back planes by AWS that triggered this.  We removed server apply from the app definitions in git and we had no issues with either prod or staging.  Although I expect we'll eventual see odd patching issues and failures to apply at some point without server side apply.

**Comment by crenshaw-dev** [comment] 2024-06-26 22:51
Likely a duplicate of https://github.com/argoproj/argo-cd/issues/18213

**Comment by pkruk** [comment] 2024-07-04 07:14
thx for a fix!

**Comment by tooptoop4** [comment] 2024-08-31 04:51
can close?

**Closed** 2024-11-11 06:12 UTC
Labels: bug, type:bug, component:server, component:server-side-apply
