### ISSUE TITLE
ArgoCD fails to create the nginx-ingress webhook

### ISSUE THREAD

**Issue by estahn** [argoproj/argo-cd#3714] opened 2020-06-04 23:40 UTC
**Describe the bug**

ArgoCD fails to create the nginx-ingress webhook due to the cluster role not being installed.

See slack conversation [here](https://argoproj.slack.com/archives/CASHNF6MS/p1591182575389500).

https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml

**To Reproduce**

Install nginx-ingress with webhook enabled.

**Expected behavior**

Install webhook.

**Version**

```shell
v1.5.1+8a3b36b
```

**Logs**

The output on the pods seems to be fine, so I guess the hooks are not executed correctly:
```
argocd@argocd-repo-server-5df4d5fb89-dwpqr:/tmp/https:__kubernetes-charts.storage.googleapis.com_$ helm template nginx-ingress-1.39.0.tgz --set controller.admissionWebhooks.enabled=true | grep -A3 job-patch/clusterrole.yaml
# Source: nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
argocd@argocd-repo-server-5df4d5fb89-dwpqr:/tmp/https:__kubernetes-charts.storage.googleapis.com_$ helm2 template nginx-ingress-1.39.0.tgz --set controller.admissionWebhooks.enabled=true | grep -A3 job-patch/clusterrole.yaml
# Source: nginx-ingress/templates/admission-webhooks/job-patch/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
argocd@argocd-repo-server-5df4d5fb89-dwpqr:/tmp/https:__kubernetes-charts.storage.googleapis.com_$
```

**Comment by alexmt** [comment] 2020-06-16 00:38
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/2737 . I really hope to get it fixed in 1.7 release. 

Closing this ticket as a duplicate. @estahn let me know please if I'm missing something and ticket has to be reopened

**Closed by alexmt** 2020-06-16 00:38 UTC
Labels: bug

**Comment by foxracle** [comment] 2020-10-29 11:39
@alexmt  Is there a timeline for this fix to be released? I am still running into this issue with ingress Nginx.

argocd version: 1.7.7

**Comment by TheAggressive** [comment] 2021-01-25 13:58
Ran into this too.
