### ISSUE TITLE
Persistent sync error: Unexpected error &http.httpError{err:"context deadline exceeded (Client.Timeout exceeded while reading body)"

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-cd#1683] opened 2019-06-04 07:15 UTC
**Describe the bug**

One cluster appears to keep hitting the following error during sync:

`Unexpected error &http.httpError{err:"context deadline exceeded (Client.Timeout exceeded while reading body)", timeout:true} when reading response body. Please retry`

The error happens at a cluster level -- once the cluster hits this situation, Argo CD can no longer sync to the cluster. Other clusters registered to Argo CD appear to work fine. Also applications refreshes/reconciliations work perfectly fine. It is only the sync operations that fail.

In that respect the behavior is almost identical in behavior to:
https://github.com/argoproj/argo-cd/issues/1291

A controller restart seems to relieve the situation, however sometime later (minutes) the issue happens again, and another controller restart is needed.

**Comment by jessesuen** [comment] 2019-06-04 07:31
```
time="2019-06-04T07:29:42Z" level=info msg="updated 'argocd-test' operation (phase: Running)"
time="2019-06-04T07:29:42Z" level=info msg="Initialized new operation: {&SyncOperation{Revision:37ca7538ba4798250a379cbf76d845c389d07d9a,Prune:false,DryRun:false,SyncStrategy:nil,Resources:[],Source:nil,}}" application=argocd-test
time="2019-06-04T07:29:42Z" level=info msg="Comparing app state (cluster: REDACTED, namespace: default)" application=argocd-test
time="2019-06-04T07:29:42Z" level=debug msg="Generated config manifests" application=argocd-test
time="2019-06-04T07:29:42Z" level=debug msg="Retrieved lived manifests" application=argocd-test
time="2019-06-04T07:29:42Z" level=debug msg="built managed objects list" application=argocd-test
time="2019-06-04T07:30:14Z" level=info msg="added resource ServiceAccount/argocd-test-serviceaccount status: SyncFailed, message: Unexpected error &http.httpError{err:\"context deadline exceeded (Client.Timeout exceeded while reading body)\", timeout:true} when reading response body. Please retry." application=argocd-test
time="2019-06-04T07:30:14Z" level=info msg="Updating operation state. phase: Running -> Failed, message: '' -> 'one or more synchronization tasks are not valid'" application=argocd-test
time="2019-06-04T07:30:14Z" level=info msg="updated 'argocd-test' operation (phase: Failed)"
time="2019-06-04T07:30:14Z" level=info msg="Sync operation to 37ca7538ba4798250a379cbf76d845c389d07d9a failed: one or more synchronization tasks are not valid" application=argocd-test reason=OperationCompleted type=Warning
```

**Comment by jessesuen** [comment] 2019-06-04 09:24
The problem happens when we are generating sync tasks and performing resource discovery. I noticed when the timeout occurs, it always times out at 32 seconds. Looking at client-go discovery code, 32 seconds is the exact default timeout of the discovery client. From discovery_client.go in go-client:

```golang
	// defaultTimeout is the maximum amount of time per request when no timeout has been set on a RESTClient.
	// Defaults to 32s in order to have a distinguishable length of time, relative to other timeouts that exist.
	defaultTimeout = 32 * time.Second
)
```

Furthermore, the overall sync error message: `one or more synchronization tasks are not valid` is another indication that it happens during sync task generation.

```golang
func (sc *syncContext) sync() {
	syncTasks, successful := sc.generateSyncTasks()
	if !successful {
		sc.setOperationPhase(appv1.OperationFailed, "one or more synchronization tasks are not valid")
		return
	}
```

Here is the code performing discovery:

```golang
func ServerResourceForGroupVersionKind(disco discovery.DiscoveryInterface, gvk schema.GroupVersionKind) (*metav1.APIResource, error) {
	resources, err := disco.ServerResourcesForGroupVersion(gvk.GroupVersion().String()) // must be failing here
	if err != nil {
		return nil, err
	}
	for _, r := range resources.APIResources {
		if r.Kind == gvk.Kind {
			log.Debugf("Chose API '%s' for %s", r.Name, gvk)
			return &r, nil
		}
	}
	return nil, apierr.NewNotFound(schema.GroupResource{Group: gvk.Group, Resource: gvk.Kind}, "")
}
```

**Comment by jessesuen** [comment] 2019-06-04 09:27
We should not be making so many calls to `disco.ServerResourcesForGroupVersion`. Server resources are not something that changes often. They only change during cluster upgrades, CRD installations, or API registrations. I believe when I wrote this code, I used to cache the result of discovery, but it seems to be gone.

**Comment by jessesuen** [comment] 2019-06-04 09:50
I tried increasing timeout from 32 seconds to 2 minutes. It did not help.

**Comment by alexec** [comment] 2019-06-04 14:55
@jessesuen - do we want this fix in v1.1?

**Comment by jessesuen** [comment] 2019-06-04 17:17
Yes, we have users completely unable to deploy their apps.

**Comment by alexec** [comment] 2019-06-04 18:10
Added to v1.1 and assigned to @alexmt .

**Comment by alexmt** [comment] 2019-06-04 20:48
Issue was caused by a cronjob which had 10k active jobs. The cron job definition did not fit into 1mb, 
k8s golang client failed to deserialize the job and argocd stop getting updates for the whole cluster. 

Ticket to gracefully handle large objects: https://github.com/argoproj/argo-cd/issues/1685

**Closed by alexmt** 2019-06-04 20:48 UTC
Labels: bug
