### ISSUE TITLE
Problemes with Sync tasks in multi application environment still fails in 2.11.0 version - Chart 6.8.x and 6.9.x affected

### ISSUE THREAD

**Issue by DevSecOps-Isotrol** [argoproj/argo-cd#18209] opened 2024-05-14 09:51 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Related to [#18120](https://github.com/argoproj/argo-cd/issues/18120) case, after upgrade to Argocd Chart 6.9.1 (app 2.11.0) from 6.7.18 (app 2.10.9) the error "resolv repo version" is shown during a manual sync. After apply a downgrade to 6.7.18 it works properly. The same problem with 6.8.x (also app 2.11.0) Chart version.

**To Reproduce**

When a manual sync starts the error is shown in a pop-up.

**Expected behavior**

It should starts to sync all components, if any of them has changes to apply. It only works when at least chart version 6.7.18 (app 2.10.9) is deployed.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/144797150/c455c188-4fbc-4a45-926f-963a14adefb4)

**Version**

Versions affected 6.8.x and 6.9.x:

![image](https://github.com/argoproj/argo-cd/assets/144797150/69fc188b-e279-4de1-94b7-ae47ef7f9dca)

Last version without this problem:

![image](https://github.com/argoproj/argo-cd/assets/144797150/50c18161-a046-4f96-9e59-8715d1391c6c)

**Logs**

```
Paste any relevant application logs here.
```

**Comment by sincorchetes** [comment] 2024-05-15 15:47
Confirmed... in 6.9.2

**Comment by LordGaav** [comment] 2024-05-17 09:01
Just adding a comment with the exact error message, because it took me a while to find this issue:

`time="2024-05-17T08:57:26Z" level=error msg="finished unary call with code Unknown" error="repository not found" grpc.code=Unknown grpc.method=ResolveRevision grpc.service=repository.RepoServerService grpc.start_time="2024-05-17T08:57:26Z" grpc.time_ms=54.14 span.kind=server system=grpc`

**Comment by LordGaav** [comment] 2024-05-17 09:02
Is downgrading an option to work around this in the mean time? I would assume just changing the `repo-server` image would be enough.

**Comment by DevSecOps-Isotrol** [comment] 2024-05-22 09:50
It seems that with the last Chart  6.10.1 (app version 2.11.1) the problem was solved. It is working fine for me.

Take care about the upgrade steps https://artifacthub.io/packages/helm/argo-cd-oci/argo-cd#X-10-0, I had to delete the **argocd-redis** secret before apply the `helm upgrade ...` command.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-11 06:39
Looks like this was fixed, closing.

**Closed by andrii-korotkov-verkada** 2024-11-11 06:39 UTC
Labels: bug, component:sync, version:2.11

**Comment by sincorchetes** [comment] 2024-11-11 08:32
I think it might have been resolved in later minor versions.
