### ISSUE TITLE
App stuck in loop while deleting endpoints / services

### ISSUE THREAD

**Issue by Paragon1970** [argoproj/argo-cd#4138] opened 2020-08-21 11:31 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Version: v1.6.1
Deployment not deleting as expected when employing `cascade`
Enters a redeploy loop.
Appears to hang when deleting services.

Requires either forced  deletion of svc (ArgoCD UI) 
or
``` shell
kubectl -n <ns> delete service --all
```
At which point ArgoCD removes app from UI.

I think whats happening is:
`cascade delete` is stuck in a cycle deleting endpoints.
It rarely gets to delete the underlying service, since the service redeploys its endpoint to match desired state of k8s cluster.
Suspect fix would be to ignore / skip endpoint deletion and delete the underlying associated service. 

**To Reproduce**

Install app, sync, delete app
Tested with helm chart stable prometheus-operator and harbor both showed similar issue on delete.

**Expected behavior**

App delete to run to completion, no unwanted artifacts to be left on cluster.

**Screenshots**

Prior to delete:
![Argocd-delete-before](https://user-images.githubusercontent.com/3257594/90884747-3a478d00-e3a8-11ea-9646-338ca2b3740d.png)
Selecting `cascade` delete:
![Argo-cascade](https://user-images.githubusercontent.com/3257594/90884771-43d0f500-e3a8-11ea-8e20-bd20cdb03b28.png)
Hanging at SVC delete:
![argocd-deleting](https://user-images.githubusercontent.com/3257594/90884789-4b909980-e3a8-11ea-9a43-462a5ef6d345.png)

Expanded view showing redeploy of SVC endpoints (they get deleted and then redeployed since the SVC is still running.)
![argocd-endpoints](https://user-images.githubusercontent.com/3257594/90884795-4e8b8a00-e3a8-11ea-806b-91487a62c907.png)

**Version**

```shell
argocd: v1.6.1+159674e
  BuildDate: 2020-06-19T00:39:46Z
  GitCommit: 159674ee844a378fb98fe297006bf7b83a6e32d2
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment] 2020-08-24 17:31
I can reproduce it with K8S 1.18

**Comment by alexmt** [comment] 2020-08-24 18:10
I think this is related to https://github.com/kubernetes/kubernetes/issues/91287 . The issue is supposed to be fixed. I've upgraded minukube to v1.18.8 but still seeing the same issue.

**Comment by jessesuen** [comment] 2020-08-24 20:42
We notice that eventually kubernetes is able to delete the endpoint successfully, but it may last for minutes. Ultimately this appears to be a kubernetes bug but somehow exacerbated somehow by the way Argo CD deletes it

**Comment by Paragon1970** [comment] 2020-08-25 00:35
Reproduced by installing into fresh cluster within AWS and still seeing same issue though with additional deletion problems.
Firstly it hangs on deletion svc's and endpoints but once these are manually deleted it hangs deleting rolebindings, clusterrolebinding and roles. 

Tested with prometheus-operator 9.1.0 deployment cloned from helm stable https://kubernetes-charts.storage.googleapis.com repo.
K8s version 1.18.2

Applying 'force' removes the components but this can only be applied individually at not at the top level app which only allows for an checked / unchecked cascade option.

**Comment by jannfis** [comment] 2020-08-25 05:51
The stuck RBAC resources are actually a bug in the K8s Garbage Collector with K8s versions <= 1.18.4 when using foreground deletion. Argo CD usese foreground deletion for normal deletions, and background deletion when "force" delete is used. I'm unsure whether we should work around this.

Refer to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1183 and https://github.com/kubernetes/kubernetes/pull/90534

**Comment by Paragon1970** [comment] 2020-08-25 12:27
Thank you, 
I just checked the original cluster of which this bug was initially filed (its running locally under Proxmox) and realized its version is 1.18.4 which would explain why it never experienced the RBAC resource issue.

**Comment by alexmt** [comment] 2020-08-28 15:20
Found corresponding Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/90512 . The bug was fixed two days ago and will be cherry-picked into 1.18.

**Comment by alexmt** [comment] 2020-08-28 15:22
There is not much we can do on Argo CD side. Kubernetes v1.18.9 should resolve it when it is available. I think we can close it.

**Closed by alexmt** 2020-08-28 15:22 UTC
Labels: bug

**Comment by Xtigyro** [comment] 2021-05-15 17:15
This is still not resolved.

**Comment by jakirpatel** [comment] 2021-08-24 05:16
btw any fix for this ?

**Comment by batazor** [comment] 2023-01-01 19:02
<img width="1509" alt="Screenshot 2023-01-02 at 01 01 05" src="https://user-images.githubusercontent.com/1643797/210181902-5250395a-7391-49fb-9279-8f3412860972.png">

I encountered this problem, but I don't know how to fix it without reinstalling argocd

**Comment by batazor** [comment] 2023-01-01 19:03
<img width="1509" alt="Screenshot 2023-01-02 at 01 02 32" src="https://user-images.githubusercontent.com/1643797/210181937-5bb07d0a-c705-4b71-a198-927a1c40fe3d.png">
I encountered this problem, but I don't know how to fix it without reinstalling argocd

checked both on version 2.5 and on the latest 2.6
