### ISSUE TITLE
Via argo cli often get nil pointer dereference

### ISSUE THREAD

**Issue by hontarenko** [argoproj/argo-cd#11216] opened 2022-11-07 11:19 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Via argo cli often get nil pointer dereference

**To Reproduce**
Used command - `argocd app wait ${{ env.APP }} --operation --plaintext && argocd app sync ${{ env.APP }} --plaintext && argocd app wait ${{ env.APP }} --health --plaintext`

**Expected behavior**
The command was executed without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/94844601/200297440-7f03b955-08b5-4f98-994c-c5440ad7bd73.png)

**Version**

```shell
argocd:v2.4.11
```

**Logs**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x29baa06]

goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewApplicationSyncCommand.func1(0xc000e30c80?, {0xc000dd9200, 0x1, 0x2})
	/home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/app.go:1537 +0x1966
github.com/spf13/cobra.(*Command).execute(0xc000e30c80, {0xc000dd91e0, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000df0000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/home/runner/work/argo-cd/argo-cd/cmd/main.go:57 +0x2c5
Error: Process completed with exit code 2.
```

**Comment by reinvantveer** [comment] 2023-02-02 11:33
Similar, on 2.5.9:
```shell
argocd version --client

# argocd: v2.5.9+e5f1194
#  BuildDate: 2023-01-27T23:48:11Z
#  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
#  GitTreeState: clean
#  GoVersion: go1.18.10
#  Compiler: gc
#  Platform: linux/amd64

KUBECONFIG=/var/snap/microk8s/current/credentials/client.config argocd context micro8s
# panic: runtime error: invalid memory address or nil pointer dereference
# [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b5adae]

# goroutine 1 [running]:
# github.com/argoproj/argo-cd/v2/cmd/argocd/commands.NewContextCommand.func1(0xc001191680?, {0xc0011c3d40?, 0x1, 0x1})
#         /home/runner/work/argo-cd/argo-cd/cmd/argocd/commands/context.go:56 +0x36e
# github.com/spf13/cobra.(*Command).execute(0xc001191680, {0xc0011c3d10, 0x1, 0x1})
#         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
# github.com/spf13/cobra.(*Command).ExecuteC(0xc0010d6780)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
# github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
# main.main()
        /home/runner/work/argo-cd/argo-cd/cmd/main.go:57 +0x2c5
```
My command may be wrong, but I wouldn't expect a segfault...

**Comment by jgwest** [comment] 2024-03-29 07:27
Dupe of #7752

**Closed by jgwest** 2024-03-29 07:27 UTC
Labels: bug
