### ISSUE TITLE
When `Log in`/`Log out` wraps before the buttons wrap Health status gets clipped by whitespace

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#14141] opened 2023-06-20 19:01 UTC
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. https://cd.apps.argoproj.io/applications/argo-cd?view=network&resource=name%3Aargocd-redis-ha-server%2Cname%3Aargocd-redis-ha-server-0
2. Set window sufficiently narrow that `Log in`/`Log out` wrap but not that the view mode buttons wrap
3. Look at the health status

**Expected behavior**

Health shouldn't be clipped by the panel above it

**Screenshots**

<img width="1224" alt="image" src="https://github.com/argoproj/argo-cd/assets/2119212/bf7f8de3-1ec2-49e8-bd78-5856a4b04a41">

**Version**

```shell
{
    "Version": "v2.8.0+70473d2.dirty",
    "BuildDate": "2023-06-20T16:27:50Z",
    "GitCommit": "70473d264074f449e2f74ffc67ccb6f808fcfb66",
    "GitTreeState": "dirty",
    "GoVersion": "go1.20.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.12.0+gc9f554d",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Mqlfour** [comment] 2023-06-23 18:22
patrick@ifroggy.com

Kevin.Hager@tn.gov

https://www.reddit.com/r/BeginnerWoodWorking/comments/es0w8s/lumber_yards_for_newbies/mathews-v-burkeens https://github.com/chernikov/maps/blob/master/source/Common.Tools/GenerateData/Name.cshttps://discord.me/servers?page=865https://status.branch.io/https://github.com/decenomy/https://github.com/decenomy/CFLhttps://www.coppertubingsales.com/index.php?route=product/category&path=70_191_352https://www.vatican.va/archive/cod-iuris-canonici/eng/documents/cic_lib7-cann1400-1500_en.htmlhttps://discord.com/invite/bnbchainhttps://github.com/naomidiscord/naomihttps://books.apple.com/us/author/quinn-michaels/id521899383https://m.twitch.tv/theeholyman/clip/PuzzledMagnificentShallotNerfRedBlaster-mH26w-knNZ37ryv2https://www.wate.com/news/business/ap-business/what-is-discord-the-chatting-app-tied-to-classified-leaks/https://discord.com/invite/brawlstars

**Comment by crenshaw-dev** [comment] 2023-07-08 20:49
Duplicate of https://github.com/argoproj/argo-cd/issues/13512

**Closed by crenshaw-dev** 2023-07-08 20:49 UTC
Labels: bug
