### ISSUE TITLE
Disabling the GnuPG functionality in ArgoCD is not working even after setting the variable ARGOCD_GPG_ENABLED to false

### ISSUE THREAD

**Issue by Rami-Y** [argoproj/argo-cd#5308] opened 2021-01-25 20:20 UTC
**Describe the bug**
I upgraded my argo cd env from 1.6.2 HA to 1.7.11 HA. As per Argo CD [GnuPG documentation ](https://argoproj.github.io/argo-cd/user-guide/gpg-verification/#disabling-the-feature), I disabled GnuPG functionality by setting up environment variable ARGOCD_GPG_ENABLED to false in argocd-server, argocd-repo-server and argocd-application-controller deployments. But this feature is NOT disabled and giving following error in the UI while loading Settings -> Projects page, project edit page and GnuPG keys page.
![image](https://user-images.githubusercontent.com/67324739/105758186-f50e2500-5f1c-11eb-9451-15c722423521.png)

So, it seems like setting ARGOCD_GPG_ENABLED to false is not disabling the feature and also it showing up error while loading the project related pages.
Note: to get rid off the error and as a work around, i have added the RBAC entry p, role:rolename, gpgkeys, get, *, allow as suggested by Jann Fischer

**To Reproduce**
I Upgraded the Argo CD from 1.6.2 to 1.7.11 and open project related pages in argocd UI (Projects, edit project and GnuPg Keys page etc). it displays below error while loading these pages.
![image](https://user-images.githubusercontent.com/67324739/105758194-f8091580-5f1c-11eb-9fc1-58b27cec8662.png)

**Expected behavior**
Error related to gp keys should not show up on UI if GnuPG feature is disabled with ARGOCD_GPG_ENABLED set to false in argocd-server, argocd-repo-server and argocd-application-controller deployments. 

**Version**
v1.7.11

```

**Comment by kshamajain99** [comment] 2021-02-17 21:00
@Rami-Y I was able to reproduce the issue in v1.7 but was not able to reproduce it in latest v1.8.3. 
In v1.7, cause of error was that we were calling `/api/v1/gpgkeys` on projects list page 

In v1.8, `/api/v1/gpgkeys` is not being called anymore on projects list page. You still see above mentioned permission denied error on gpgkeys page which is expected. 

As mentioned above, in order to list gpgkeys add RBAC entry `p, role:rolename, gpgkeys, get, *, allow`

**Comment by jessesuen** [comment] 2021-02-17 21:25
Thanks for the investigation @kshamajain99. Will close as fixed in v1.8.3

**Closed by jessesuen** 2021-02-17 21:25 UTC
Labels: bug, bug/priority:medium, bug/severity:minor, workaround
