### ISSUE TITLE
Resources with tracking method annotation incorrectly marked as out-of-sync/requires pruning

### ISSUE THREAD

**Issue by jannfis** [argoproj/argo-cd#8683] opened 2022-03-04 14:42 UTC
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

One of the goals of using annotations for resource tracking is, that the resource should only be considered managed if the values of the annotation match the properties of the resource. However, this does not seem to be the case.

**To Reproduce**

1. Set `application.resourceTrackingMethod` to `annotation`
2. Create a new application, e.g. `kustomize-guestbook` from `https://github.com/argoproj/argocd-example-apps`, with a target namespace of `guestbook`
3. Sync the application. Make sure that Argo CD has put on tracking annotations on the live resources instead of the label, e.g. 
```yaml
  annotations:
    argocd.argoproj.io/tracking-id: 'guestbook:/Service:guestbook/kustomize-guestbook-ui'
```
4. Create a new dummy resource in namespace `guestbook`, for example a `ConfigMap`: 
```
kubectl -n guestbook create configmap foobar
```
5. Add annotations from another resource to dummy resource: 
```
kubectl -n guestbook annotate configmap foobar argocd.argoproj.io/tracking-id='guestbook:/Service:guestbook/kustomize-guestbook-ui'
```
6. Observe this resource being marked as out of sync and pruning required in the application:
![image](https://user-images.githubusercontent.com/3942683/156783242-df0e5ab5-0681-413b-9ebb-a690c59825ed.png)

**Expected behavior**

The resource should be ignored because the properties of the resource don't match the values in the annotation. The resource should not be considered to be managed by Argo CD, and neither marked out of sync nor for be marked for pruning.

**Screenshots**

**Version**

Latest HEAD as of the time of issue creation:

```shell
argocd-server: v2.3.0+f9b7384
  BuildDate: 2022-03-04T07:39:01Z
  GitCommit: f9b7384bf4d5b0197e726ca19e40518c97fd05fd
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment] 2022-03-04 20:05
> The resource should be ignored because the properties of the resource don't match the values in the annotation. The resource should not be considered to be managed by Argo CD, and neither marked out of sync nor for be marked for pruning.

When we introduced this feature, we intended it to handle the case where some parent resource created a child resource but:
1. did not set owner reference on the child resource
2. carried over labels/annotations (including our tracking label) to child resource

I think there might be two cases we need to consider:
1. if the tracking reference on the child is referencing a resource which **_is still being_** managed by Argo CD (in your example, it is `Service:guestbook/kustomize-guestbook-ui`), then I agree that the resource should not be considered OutOfSync or needing pruning and I agree with this bug.

2. However, if the tracking reference is referencing a resource that no longer exists, then I think it should be considered OutOfSync and required for pruning. This would handle the problem where the user deletes the parent object and is now left with an orphaned child object which they should see in the UI.

I think to fix this, we need to create an artificial parent-child relationship using the tracking-id reference, similar to what we do with Service->Endpoints, PVC->PV. Then in your example, the `foobar` ConfigMap would be considered a child of the Service:guestbook/kustomize-guestbook-ui.

**Comment by jessesuen** [comment] 2022-03-04 20:08
BTW, correct me if I'm wrong, but I think the annotation tracking method is no worse than the instance label method. But now that we have sufficient metadata in the annotation, we actually can do better about creating artificial parent/child relationships than the instance label.

In fact, I thought that was the entire point about incorporating the kind/namespace/name into the annotation.

**Comment by jannfis** [comment] 2022-03-04 20:34
> When we introduced this feature, we intended it to handle the case where some parent resource created a child resource but:
>
>    1. did not set owner reference on the child resource
>    2. carried over labels/annotations (including our tracking label) to child resource

This is actually what the reproduction steps do (e.g. a new resource that does not have ownerReferences and carries copy of another resource's annotations).

**Comment by jannfis** [comment] 2022-03-04 20:38
> if the tracking reference on the child is referencing a resource which is still being managed by Argo CD (in your example, it is Service:guestbook/kustomize-guestbook-ui), then I agree that the resource should not be considered OutOfSync or needing pruning and I agree with this bug.

Yes, this is the case.

> However, if the tracking reference is referencing a resource that no longer exists, then I think it should be considered OutOfSync and required for pruning. This would handle the problem where the user deletes the parent object and is now left with an orphaned child object which they should see in the UI.

I'm not sure whether we should do that, because it could lead to some kind of loop hole. E.g. user with permissions to update a certain resource (e.g. to add some annotations) could now implicitly delete this resource through Argo CD.

**Comment by jessesuen** [comment] 2022-03-04 21:44
> I'm not sure whether we should do that, because it could lead to some kind of loop hole. 

I share the same concern about the loophole. The same loophole would potentially exist with our label tracking. 

However, I seem to recall that we have some protection mechanism that excludes resources that are impossible to be part of the application (e.g. in a namespace outside of the project boundaries)

**Comment by jessesuen** [comment] 2022-04-28 00:25
So this issue comes down to the following question: What should we do when we encounter a resource with our annotation-based tracking label, but that tracking label **_is not self-referential_** (it's pointing to some parent resource)?

Here are some options/proposals.
1. Ignore the resource completely. Don't even show it. This is my least favorite option
2. Present the resource as a child of the parent resource (assuming the parent is part of the app). This is the same approach we do with Service -> Endpoints. Endpoints are not technically owned by Services, but functionally they are children of them
3. Present the resource like a top-level managed object, but as an extraneous object which should not be pruned. We already have two annotations which replicate this behavior.

```yaml
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
```

In general, I do not think we should be considering objects to be pruned, if it has our tracking annotation **_and the value is not self-referential_**. Because it is pretty obvious that the resource was automatically created, and not a managed resource from git.

**Comment by jannfis** [comment] 2022-06-05 09:56
Thanks for your insight, @jessesuen.

I'm also not in favor of option 1 and think the object should be somehow displayed to the user.

The major use case for me is when an Operator creates resources and copies all labels and annotations from its Operand onto the resources it creates. So if you manage the Operand via Argo CD, and the Operator creates a ConfigMap during reconciliation, that ConfigMap will carry the same labels and annotations as the Operand, including Argo CD's tracking labels.

Now, not all Operators create `ownerReferences` on the resources they create, and that's where the original problem stems from. In some scenarios, the Operator even isn't able to create `ownerReferences` on such resources, for example when Operand and the resource are in different namespaces, or when one of Operand or resource are cluster scoped, but the other is not.

So I'm in favor of a combination of option 2 and 3 above:

1) If the tracking label on a resource is not self-referencing, but instead references another resource in the same application, we create a parent/child relationship between the two.

2) If the tracking label on a resource is not self-referencing and refers to an otherwise unknown resource (e.g. a resource not managed by current application, or a resource outside the application's scope), we display it as top-level resource without owner.

I would also be fine to first go for the simple approach (e.g. displaying it as top-level resource) and if there's demand, we can see how to establish parent/child relationship from the UI's point of view.

WDYT?

**Comment by jessesuen** [comment] 2022-06-14 21:20
> I would also be fine to first go for the simple approach (e.g. displaying it as top-level resource) and if there's demand, we can see how to establish parent/child relationship from the UI's point of view.

I agree. I think showing it as a top-level resource is probably the most accurate and least surprising behavior. Option 2 (showing it as a child) might give a false impression that there is an ownership reference when there really is not. So my preference is for option 3 (top-level extraneous resource that will not be pruned or diffed).

Perhaps in the future, we might have a UI option/toggle to delineate between resources that are true owners of child objects, and ones that are pseudo-children by virtue of labels/annotations carried over to offshoots.

Sounds like we have a consensus about how to fix the issue. This bug/feature has become important to us since it affects our Crossplane UX, so I will prioritize fixing this for the next Argo CD release unless someone gets to it first.

**Comment by voidengineer** [comment] 2022-06-15 10:48
Maybe those "pseudo-children" could be displayed slightly different? Dotted borders, another background color, anything like that?

**Comment by jannfis** [comment] 2022-06-27 09:25
Fix for this issue: #9791

**Comment by ralf-cestusio** [comment] 2022-08-03 20:16
I have a question. 
I am on 2.4.8 so the fix for this should be in 
i have the following 2 objects (the network Claim "owns" the XNetwork) and from my understanding on how the tracking-id works XNetwork should not be considered for Pruning. 
But it does get pruned on synch.
Is there something i misunderstand? 
```
kind: NetworkClaim
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: crossplane-sample:aws.ops.umanaia.org/NetworkClaim:ralf-test/sample-network
  name: sample-network
  namespace: ralf-test



kind: XNetwork
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: crossplane-sample:aws.ops.umanaia.org/NetworkClaim:ralf-test/sample-network
  name: sample-network-lsq6d
```

**Comment by jessesuen** [comment] 2022-08-04 00:42
The fix doesn't seem to work in v2.4.8. Here is a repo which can reproduce the issue:
https://github.com/jessesuen/bug-self-ref-pruning

**Comment by jessesuen** [comment] 2022-08-04 00:49
Video proof:

https://user-images.githubusercontent.com/12677113/182739188-4b9483b8-ed56-4364-8fcd-18ddd7e5ba19.mov

**Comment by jannfis** [comment] 2022-08-04 09:26
I have found the bug and fixed it.

Will write some e2e test around it and then submit a PR.

**Comment by jannfis** [comment] 2022-08-04 12:13
In order to fix this, first https://github.com/argoproj/gitops-engine/pull/436 should be merged. Then, I'll update https://github.com/argoproj/argo-cd/pull/10198 to include new changes from gitops-engine.

After that, we can cherry-pick both changes into their appropriate release branches.

**Closed** 2022-08-08 17:37 UTC
Labels: bug, cherry-pick/2.4

**Comment by jannfis** [comment] 2022-08-10 08:03
@ralf-cestusio Just as a heads-up, the upcoming v2.4.9 release will contain a proper fix for the pruning bug.

**Comment by ralf-cestusio** [comment] 2022-08-10 12:45
Yes i saw the fix. Thank you for this really quick resolution!

**Comment by QuingKhaos** [comment] 2022-08-12 15:45
> > I would also be fine to first go for the simple approach (e.g. displaying it as top-level resource) and if there's demand, we can see how to establish parent/child relationship from the UI's point of view.
> 
> I agree. I think showing it as a top-level resource is probably the most accurate and least surprising behavior. Option 2 (showing it as a child) might give a false impression that there is an ownership reference when there really is not. So my preference is for option 3 (top-level extraneous resource that will not be pruned or diffed).

From an operator and user viewpoint, this is more confusing. We would have preferred the non-selfreferencing resource is shown as pseudo-child. When we see a top-level resource we expect that this resource is defined in the application source, but the copied resource is basically not.

A pseudo-child relationship would have made it more clear, e.g. from which secret a copied secret originates. Which would be similar to the wanted behavior of #5082, so parent-child relationships are not strictly only owner relationships.

**Comment by jannfis** [comment] 2022-08-12 16:40
> When we see a top-level resource we expect that this resource is defined in the application source, but the copied resource is basically not.

The distinction can be made from the sync status - a resource not existing in Git does not have a sync status, and the corresponding icon is also not displayed. I agree that rendering a parent/child relationship would be better, though. I think that we can use the resource that is fully qualified in the annotation to map to the "parent", but I need to think this through for a while.

**Comment by QuingKhaos** [comment] 2022-08-13 15:30
As an external operator which supports whole corporate teams with lesser experience, the distinction of the sync status on a top-level resource is not so obvious for most of my team. They wouldn't expect a top-level resource to be not a synced resource at the first look, as a small icon not present is not very clear from UX/DX standpoint vs. a clear parent-child relationship.

A clear pseudo parent-child relationship will not raise the "what is wrong with my deployment, where does this resource come from, what do I need to with this, how do I handle this" questions I got. While a parent-child relationship is what it is: a resource they to not care about it explicitly.

Maybe top-level non-synced resource vs. pseudo parent-child relationship can be configured as feature flag via `argocd-cm` config map or as an container argument/environment variable on the corresponding component. This would still support the use-case (by default), where operators would expext only real ownership references as parent-child relationships and can be revisited when the feature of configuring parent-child relationship by label selectors gets implemented.

**Comment by jannfis** [comment] 2022-08-13 17:29
Please feel free to open an enhancement request for this.

**Comment by leoluz** [comment] 2022-10-21 03:20
@jannfis We found an issue with this new logic in our servers when users update to newer APIGroups (going from extensions/Ingress to networking/Ingress for example). I described the issue with more details in my PR with a fix attempt (https://github.com/argoproj/argo-cd/pull/11012)
