### ISSUE TITLE
Forward git credentials to config management plugins

### ISSUE THREAD

**Issue by stevendborrelli** [argoproj/argo-cd#1628] opened 2019-05-20 21:46 UTC
We've been experimenting with configuration management plugins and have come across an issue when connecting to authenticated repositories. 

Could we do something similar to the kustomize code https://github.com/argoproj/argo-cd/blob/master/util/kustomize/kustomize.go#L118 and forward Git credentials to the config management plugins?

**Comment by alexec** [comment] 2019-06-03 15:51
@stevendborrelli do you have repo steps please?

**Comment by alexmt** [comment] 2019-06-03 16:25
I believe this is an enhancement not a bug. So there are no steps to reproduce. It definitely makes sense to support passing credentials to the config management plugins

**Comment by alexec** [comment] 2019-06-03 16:34
@alexmt I'm not familiar with the plugin code, are you able to provide any pointers to code?

**Comment by jessesuen** [comment] 2019-06-03 21:34
I had asked @stevendborrelli to file this issue in slack. Basically, we gave kustomize special treatment to set up a proper git environment whenever we run `kustomize build`, so that it could use its remote base feature.

Since users can additionally perform `kustomize build` as part of plugins, we need to extend this special treatment to custom plugins.

**Comment by jessesuen** [comment] 2019-06-03 21:35
> @alexmt I'm not familiar with the plugin code, are you able to provide any pointers to code?

Here is the feature which enabled forwarding git credentials to kustomize:

https://github.com/argoproj/argo-cd/commit/1d3ec93ec707464052db14961f046d98c3d1c753

**Comment by alexec** [comment] 2019-06-03 23:48
Do we need to include SSH too? Out of scope?

**Comment by jessesuen** [comment] 2019-06-05 10:17
SSH should be supported too. It should be easy to do once we support SSH kustomize remote bases.

**Comment by alexec** [comment] 2019-06-07 00:13
SSH out of scope of this issue. See https://github.com/argoproj/argo-cd/issues/827 instead.

**Comment by alexec** [comment] 2019-06-07 00:14
Here is where the change needs to be made:
https://github.com/argoproj/argo-cd/blob/d06303c432fff6fb1a7470ef633f537a9d317ff5/reposerver/repository/repository.go#L525

**Comment by alexec** [comment] 2019-06-08 01:29
Closed. Will be in v1.1

**Closed** 2019-06-08 01:28 UTC
Labels: enhancement
