### ISSUE TITLE
Undesired checkbox when Delete pod on application details pods

### ISSUE THREAD

**Issue by marcio-pessoa** [argoproj/argo-cd#12215] opened 2023-01-30 14:20 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

After login on Argo CD web interface...

1. Click on any app
2. On right top, click on Pods button (to change interface APPLICATION DETAILS PODS)
3. Click on any Pod
4. Select menu option Delete

The message "Are you sure you want to delete Pod" followed by the pod name and a floating, untitled checkbox will appear. See the screenshot below.

**Expected behavior**

The checkbox must have a description
Or...
The checkbox must not exist

**Screenshots**

![Screenshot from 2023-01-30 11-04-44](https://user-images.githubusercontent.com/30762851/215500654-7c8f6a16-4cf0-4d85-b5ea-89df3439d551.png)

**Version**

```shell
argocd: v2.5.9+e5f1194
  BuildDate: 2023-01-27T23:27:14Z
  GitCommit: e5f1194a6de78cc1124179a4c9bb1ae3484fb77d
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
...
```

**Comment by alexef** [comment] 2023-01-30 16:43
Closing as a duplicate of: https://github.com/argoproj/argo-cd/issues/11644

**Closed by alexef** 2023-01-30 16:43 UTC
Labels: bug
