### ISSUE TITLE
Deleted pod still appears in Web UI as "pending deletion" stage

### ISSUE THREAD

**Issue by mtanida** [argoproj/argo-cd#19560] opened 2024-08-16 00:58 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Pod has been delete, but ArgoCD web UI still shows the pod as in-progress, pending deletion, which is causing confusion. Attempting to force delete the Pod doesn't work since it's already deleted. There doesn't seem to be a good way to remove the graphical representation of the Pod in ArgoCD web UI. 

**To Reproduce**

Unfortunately, it's not clear how to reproduce this. We aren't sure how it got into this state

**Screenshots**

![pending-deletion-pod](https://github.com/user-attachments/assets/c62fbbcc-4dfd-45f0-83cc-8acd2c7f3ad6)

![failed-force-delete](https://github.com/user-attachments/assets/c2c48e9b-4113-4c6d-bafd-d1af294ce52f)

**Version**

v2.7.6+00c914a.dirty

**Logs**

**Comment by crenshaw-dev** [comment] 2024-08-16 01:13
Probably a duplicate of this: https://github.com/argoproj/argo-cd/issues/9226

**Comment by agaudreault** [comment] 2024-08-26 15:02
Closing as duplicate.

**Closed by agaudreault** 2024-08-26 15:02 UTC
Labels: bug
