### ISSUE TITLE
Reduce number of ls-remote requests for same repository

### ISSUE THREAD

**Issue by m-yosefpor** [argoproj/argo-cd#4925] opened 2020-11-28 00:30 UTC
# Summary

One git ls-remote shall be enough for a repository, when there are lots of apps referencing the same repository.

# Motivation

We are using a single mono-repo to save all the resources (Many people doing so with argocd), and referencing them with different `path` options. There is high number of git ls-remote operations, showed by argocd-repo-server metrics. Right now, there is one ls-remote for each app, every sync time (3 minutes by default), so in our case, there would be about 20*100=2000 ls-remotes per hour!

This will cause issues such as https://github.com/argoproj/argo-cd/issues/4451

# Proposal
I assume one `git ls-remote` would be enough for each repo.

How do you think this should be implemented?

`ls-remote` result can be cached in redis for each repo, and be updated every sync time (3 minutes). All the apps referencing the same repo can fetch the results from cache, so all the apps referencing same repo, will need only 1 `ls-remote` per sync time. This way we are sure the app state is synced with state within last 3 minutes time, although the last auto-sync might not give it the current state, and in worst case scenario, it might be within a 3 minutes lag. The same approach as prometheus scrape interval, and rule evaluation.

Manual syncs should do ls-remote, and do net fetch the results from cache to make sure they are always synced with the current state, not the state of last cache sync. (although they can still use the cache for other use-cases if it's needed.)

**Comment by jetersen** [comment] 2020-11-30 12:50
Worth to add that webhook should also trigger sync of ls-remote though preferably only once 🙈

**Comment by jessesuen** [comment] 2020-11-30 22:10
> Manual syncs should do ls-remote, and do net fetch the results from cache to make sure they are always synced with the current state, not the state of last cache sync. (although they can still use the cache for other use-cases if it's needed.)

 I agree, cached `ls-remotes` should work and be used most of the time, *except* in the case of syncs, in which we should *always* perform a ls-remote. @alexmt thinks this is currently done per application, but could be improved to do it per repository.

**Comment by jessesuen** [comment] 2020-11-30 22:10
@m-yosefpor do you want to work on this?

**Comment by m-yosefpor** [comment] 2020-12-01 07:07
> @m-yosefpor do you want to work on this?

Sure. I might need a little help as it would be my first contribution to Argo.

**Comment by ermazi** [comment] 2020-12-23 07:00
root cause: ssh limitation, so to resolve this, increase sshd cocurrency in on-premise gitlab:
file: /etc/ssh/sshd_config
...
MaxSessions 1000
MaxStartups 1000
...

add two opts, and then restart sshd.

it works for me.

**Comment by jetersen** [comment] 2020-12-23 07:22
@ermazi that doesn't really fix the root cause which is that argo-cd is making too many git calls when it is not needed.

**Comment by Aenima4six2** [comment] 2021-07-20 12:42
Any progress on this item? Executing a single set of git operations per repo (vs per app) would be huge. We are running ArgoCD `v2.0.4` and this behavior has brought down our BitBucket server on more than one occasion.

**Comment by alexmt** [comment] 2021-07-20 16:23
Thanks for reminding about this issue @Aenima4six2 . I forgot to post an update:

Caching had been implemented by https://github.com/argoproj/argo-cd/pull/6102 . We run pre-release version on an internal Argo CD instance and observed pretty good results. Chart below illustrates how number of `git ls-remote` changed after deploying the fix:

![image](https://user-images.githubusercontent.com/426437/126359616-aa3106c3-d188-409e-98c1-30ebcf71c449.png)

The v2.1.0-rc1 should be available in 2~3 days. Added https://github.com/argoproj/argo-cd/issues/4925 and https://github.com/argoproj/argo-cd/issues/4451 to get testing feedback. Based on feedback we can decide if any additional work is required.

**Comment by Aenima4six2** [comment] 2021-07-20 16:55
> Thanks for reminding about this issue @Aenima4six2 . I forgot to post an update:
> 
> Caching had been implemented by #6102 . We run pre-release version on an internal Argo CD instance and observed pretty good results. Chart below illustrates how number of `git ls-remote` changed after deploying the fix:
> 
> ![image](https://user-images.githubusercontent.com/426437/126359616-aa3106c3-d188-409e-98c1-30ebcf71c449.png)
> 
> The v2.1.0-rc1 should be available in 2~3 days. Added #4925 and #4451 to get testing feedback. Based on feedback we can decide if any additional work is required.

This is great! Thanks so much for the update.

**Comment by alexmt** [comment] 2021-07-29 15:55
The v2.1-rc1 is ready. https://github.com/argoproj/argo-cd/releases/tag/v2.1.0-rc1

@Aenima4six2 , @jetersen can you please give it a try and see if it resolves the issue?

**Comment by Aenima4six2** [comment] 2021-08-05 22:39
> The v2.1-rc1 is ready. https://github.com/argoproj/argo-cd/releases/tag/v2.1.0-rc1
> 
> @Aenima4six2 , @jetersen can you please give it a try and see if it resolves the issue?

 Installed v2.1-rc2 today. Will keep you posted.

**Comment by alexmt** [comment] 2021-08-20 05:32
Closing and will reopen if someone reproduce issue again

**Closed by alexmt** 2021-08-20 05:32 UTC
Labels: enhancement
