### ISSUE TITLE
ArgoCD Notifications for MS Teams may need newer implementation

### ISSUE THREAD

**Issue by multimodal-mc** [argoproj/argo-cd#18991] opened 2024-07-08 20:54 UTC
# Summary

It seems that Microsoft MS Teams is deprecating its WebHook way to connect with its MS Teams Channels. See blog post [here](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/). It will be deprecated relatively soon, in the blog post it mentioned

> We will gradually roll out this change in waves:
> Wave 1 – effective August 15th, 2024: All new Connector creation will be blocked within all clouds
> Wave 2 – effective October 1st, 2024: All connectors within all clouds will stop working

![image](https://github.com/argoproj/argo-cd/assets/159462612/ffd7f1d7-85d0-4acd-a904-956d904c14ee)

# Motivation

Microsoft MS Teams deprecating WebHook and in favor of Power Automation in the future. 

# Proposal

To be honest, unsure... Since I'm not too familiar with the underlying technology of `Power Automate`. But here are some reference links

* https://make.powerautomate.com/galleries/public/templates/d271a6f01c2545a28348d8f2cddf4c8f/post-to-a-channel-when-a-webhook-request-is-received?environment=Default-da9cbe40-ec1e-4997-afb3-17d87574571a
* https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1#microsoft-teams-webhook
* https://support.microsoft.com/en-us/office/browse-and-add-workflows-in-microsoft-teams-4998095c-8b72-4b0e-984c-f2ad39e6ba9a
* https://make.preview.powerautomate.com/connectors
* https://powerusers.microsoft.com/t5/Power-Automate-Community-Blog/Power-Automate-Fundamentals-10-Usage-of-workflow-Function-in/ba-p/1247789

**Comment by christianh814** [comment] 2024-07-08 21:43
Duplicate of https://github.com/argoproj/argo-cd/issues/18981

**Closed by christianh814** 2024-07-08 21:43 UTC
Labels: enhancement, component:notifications, type:enhancement
