### ISSUE TITLE
ServerSideApply breaks CreateNamespace

### ISSUE THREAD

**Issue by morey-tech** [argoproj/argo-cd#13874] opened 2023-06-01 15:30 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When `ServerSideApply` is enabled on a resource (e.g., a `ConfigMap` or `Deployment`) and the Application is using `CreateNamespace`, the sync will fail with `namespaces "<namespace>" not found`.

Based on [this thread](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1685621879077619) in the `#argo-cd` channel.

**To Reproduce**

Create new application using this spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kustomize-guestbook'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps/'
    path: general/kustomize-guestbook
    targetRevision: ssa-createnamespace-test
    kustomize:
      namespace: kustomize-guestbook
  destination:
    namespace: kustomize-guestbook
    name: kind
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

![Xnapper-2023-06-01-11 22 32](https://github.com/argoproj/argo-cd/assets/4213435/3fd28bfb-3a08-4427-a580-76e5407e71df)

**Expected behavior**

Without `ServerSideApply` on a resource, the sync creates the namespace and the resources without issue. I would expect the same here. Here's a working example (the [only difference is no SSA](https://github.com/morey-tech/argocd-example-apps/compare/main...ssa-createnamespace-test) on the deployment):

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'kustomize-guestbook'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps/'
    path: general/kustomize-guestbook
    targetRevision: HEAD
  destination:
    namespace: kustomize-guestbook
    name: kind
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

![Xnapper-2023-06-01-11 38 40](https://github.com/argoproj/argo-cd/assets/4213435/edc3b242-90aa-423c-8515-bcaa7ae2a7b5)

**Version**

```shell
{
    "Version": "v2.7.2+cbee7e6.dirty",
    "BuildDate": "2023-05-12T13:43:26Z",
    "GitCommit": "cbee7e6011407ed2d1066c482db74e97e0cc6bdb",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by morey-tech** [comment] 2023-06-01 15:36
@leoluz, is this expected behaviour with the implementation of https://github.com/argoproj/argo-cd/pull/9711?

**Comment by blakepettersson** [comment] 2023-06-02 07:18
Does this work when adding `managedNamespaceMetadata`, like 

```yaml
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      labels: {}
      annotations: {}
    syncOptions:
      - CreateNamespace=true
```

**Comment by nicl-dev** [comment] 2023-06-02 07:51
We tried that already. Unfortunately it doesn't.

**Comment by morey-tech** [comment] 2023-06-02 13:36
In my example, the addition of `spec.syncPolicy.managedNamespaceMetadata={}` does solve the problem.

```diff
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: 'kustomize-guestbook'
  spec:
    project: default
    source:
      repoURL: 'https://github.com/morey-tech/argocd-example-apps/'
      path: general/kustomize-guestbook
      targetRevision: ssa-createnamespace-test
    destination:
      namespace: kustomize-guestbook
      name: kind
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
++    managedNamespaceMetadata: {}
```
![Xnapper-2023-06-02-09 34 07](https://github.com/argoproj/argo-cd/assets/4213435/ea97a299-9d53-44d2-82c6-fd1795d024c2)

**Comment by morey-tech** [comment] 2023-06-02 16:19
@nicl-dev, can you provide the steps to reproduce the issue with `managedNamespaceMetadata` in use?

**Comment by nicl-dev** [comment] 2023-06-02 16:27
Yea sure, I will try to reproduce it on Monday. My colleague was 100% sure he tried that solution but I'll try it again.

**Comment by leoluz** [comment] 2023-06-02 17:15
> @leoluz, is this expected behaviour with the implementation of https://github.com/argoproj/argo-cd/pull/9711?

@morey-tech Not an expected behaviour. If it doesn't, it might be a bug.

> In my example, the addition of spec.syncPolicy.managedNamespaceMetadata={} does solve the problem.

@morey-tech That is surprising because enabling `managedNamespaceMetadata` will create the namespace with server-side apply.

**Comment by morey-tech** [comment] 2023-06-02 17:37
> In my example, the addition of spec.syncPolicy.managedNamespaceMetadata={} does solve the problem.
> 
> @morey-tech That is surprising because enabling `managedNamespaceMetadata` will create the namespace with server-side apply.

This almost makes sense then right? Without that, the Deployment is using SSA, but the namespace isn't. So SSA complains that the namespace doesn't exist. But with `managedNamespaceMetadata` both the deployment and namespace are included in the SSA, and therefore the cluster knows the namespace will exist before applying the deployment.

**Comment by nicl-dev** [comment] 2023-06-05 08:50
Alright, I just tested it again and `managedNamespaceMetadata` does indeed fix the problem. Sorry for the confusion.

**Comment by morey-tech** [comment] 2023-06-05 14:13
@jaideepr97 the resolution reached was merely a way to mitigate this issue's bug. I assume it's not the desired behaviour for any resource using `ServerSideApply` to cause `CreateNamespace` to malfunction when `managedNamespaceMetadata` is absent. 

It seems like automatically including `managedNamespaceMetadata: {}` when `CreateNamespace` is in use, along with `ServerSideApply`, would resolve this bug. But maybe there is a more intelligent solution.

**Comment by evs-ops** [comment] 2023-11-23 13:15
I can confirm that also in version v2.9.2 the problem exists. I tried to use managedNamespaceMetadata on an applicationset with ServerSideApply=true and it didn't do anything. Once I removed ServerSideApply it worked like a charm

**Comment by blakepettersson** [comment] 2024-01-12 19:38
@evs-ops can you show the `Application[Set]` that displays this issue?

> It seems like automatically including managedNamespaceMetadata: {} when CreateNamespace is in use, along with ServerSideApply, would resolve this bug. But maybe there is a more intelligent solution.

The issue is that gitops-engine [will already SSA](
https://github.com/argoproj/gitops-engine/blob/aba38192fb16c35a6731717d81454a219565bcce/pkg/sync/sync_context.go#L917) the namespace if the [whole] application itself has `ServerSideApply` as a sync option. In this example it's only the Deployment that has SSA applied to it and since the `Application` doesn't have SSA on it, the namespace in turn will not be SSA'd. Not sure what the right course of action should be here.

**Comment by leoluz** [comment] 2024-01-17 16:48
I ran some tests yesterday and I understand the problem:
1. Server side apply was implemented configuring the kubectl library to set [the ServerSideApply flag](https://github.com/argoproj/gitops-engine/blob/aba38192fb16c35a6731717d81454a219565bcce/pkg/utils/kube/resource_ops.go#L258) with what was defined in the sync context.
2. During sync Argo CD will first (by default) apply all resources in dry-run mode to make sure that all yamls are valid.
3. If sync context is set to run with ServerSideApply, it will also run the dry-run phase in that mode.
4. By the time the server-side apply was implemented, the dry-run phase was always executed with `dry-run=client` (which was [ignored by the kubectl lib here](https://github.com/kubernetes/kubectl/blob/2d05e1425e370640bfa343dc77d0997cf944351c/pkg/cmd/apply/apply.go#L565-L568)). 
5. This caused the [this bug](https://github.com/argoproj/argo-cd/issues/16177) and it was attempted to be fixed by setting the `dry-run=server` during ServerSideApply syncs [in this PR](https://github.com/argoproj/gitops-engine/pull/546).
6. Setting `dry-run=server` creates a new problem as it will validate if the namespace exists in the server during the dry-run phase. This fails syncs for apps that request to auto namespace creation.

In my opinion the better way to solve this problem is, regardless if the sync context is defined to sync with ServerSideApply, the dry-run phase should always run with client-side-apply and dry-run=client. This will address all the problems mentioned above and the implementation will be simpler. This direction should be taken instead of [this](https://github.com/argoproj/gitops-engine/pull/563), [this](https://github.com/argoproj/gitops-engine/pull/546) and [this](https://github.com/argoproj/gitops-engine/pull/548).

Related to https://github.com/argoproj/argo-cd/issues/16829

**Comment by MattiasAng** [comment] 2024-01-17 21:32
@leoluz I am not gonna say what's wrong or right in terms of implementation, but I think it is important to know that a server dry run will catch issues that would not be shown in a client dry run. For us, a client dry run is basically useless for what we're trying to test before applying a manifest.

A good example of this is when using any form of policy controller that validates the manifest, for example [Kyverno](https://kyverno.io/).

While I understand that the first reasoning behind implementing it might have been the wrong direction, I think having the ability to run with `dry-run=server` would be a nice-to-have feature.

**Comment by leoluz** [comment] 2024-01-17 21:54
> While I understand that the first reasoning behind implementing it might have been the wrong direction, I think having the ability to run with `dry-run=server` would be a nice-to-have feature.

@MattiasAng I agree with you and the feature that you described is already implemented and will be available as part of Argo CD 2.10 release. It is called ServerSide Diff and when enabled will calculate diffs using server-side apply in dryrun mode. This will take into consideration validation and mutation webhooks.

**Comment by MattiasAng** [comment] 2024-01-18 07:52
@leoluz Thanks for the clarification, seems like I was missing some context.

**Comment by leoluz** [comment] 2024-01-23 20:44
@morey-tech Given that we just merged the PRs with the fix [suggested here](https://github.com/argoproj/argo-cd/issues/13874#issuecomment-1896203996) can you give it another try with the latest master build?

**Comment by leoluz** [comment] 2024-02-06 20:48
Closing this for now as this is addressed by https://github.com/argoproj/gitops-engine/pull/564 and https://github.com/argoproj/argo-cd/pull/16942. 
@morey-tech please feel free to reopen if the issue remains.

**Closed by leoluz** 2024-02-06 20:48 UTC
Labels: bug, server-side-apply
