### ISSUE TITLE
Property URLs is not constructing the correct URL to the application

### ISSUE THREAD

**Issue by jochenhebbrecht** [argoproj/argo-cd#3623] opened 2020-05-20 12:11 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I've deployed an ArgoCD application and when I open the details of the application in the ArgoCD UI, I've noticed the property `URLs` is not being constructed correctly. It seems to be taking the hostname from my `Ingress` rule, and the port of my `Service`

**To Reproduce**

* deploy an application with an `Ingress` rule in which the rule points to to a `Service` (with service type `ClusterIP` in which a port is specified

**Expected behavior**

* actually, the bug is not easy to solve I'm afraid. You cannot know which protocol and which port should be used to access the application. A possible solution could be to add a custom annotation

**Screenshots**

![Screenshot from 2020-05-20 13-47-48](https://user-images.githubusercontent.com/2405227/82443540-f5a70f80-9aa1-11ea-9194-eb34b1aaf64e.png)

**Version**

```shell
$ argocd version
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T18:59:08Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:01:57Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by alexmt** [comment] 2020-05-20 17:14
I'm pretty sure this is duplicate of https://github.com/argoproj/argo-cd/issues/2318 . Let's use 2318 to track progress on the fix.

**Closed by alexmt** 2020-05-20 17:14 UTC
Labels: bug

**Comment by jochenhebbrecht** [comment] 2020-05-20 18:36
@alexmt yes indeed, sorry. Seems like a duplicate. I did some research before creating the ticket, but it feels that I haven't been thorough enough :-). Thanks for the pointer!
