### ISSUE TITLE
Apply only out of sync objects with auto sync

### ISSUE THREAD

**Issue by hintofbasil** [argoproj/argo-cd#4521] opened 2020-10-09 11:43 UTC
# Summary

Currently when syncing using auto sync ArgoCD applies every object in the application.  For applications containing thousands of objects this takes quite a long time as puts undue pressure on the api server.

A setting in the `syncPolicy` stanza which allowed auto sync to only apply out of sync objects would mitigate this.

We are running v1.6.2

# Motivation

Currently we have multiple applications with ~2000 objects in each.  These are hard to split up and make sense bundled together.  When making a small change (such as adding a single new object) it can take over 8 minutes for the application to reach a synced status

# Proposal

Add an option to the `syncPolicy` which allows auto sync to only sync out of sync objects.  Two example configs are presented below.

```
syncPolicy:
  automated:
    applyOutOfSyncOnly: true
```

```
syncPolicy:
  automated:
    syncOptions:
    - applyOutOfSyncOnly=true
```

**Comment by jessesuen** [comment] 2020-10-09 20:45
I think this proposal seems reasonable.

**Comment by hintofbasil** [comment] 2020-10-15 15:38
Yes, this also happens with manual sync.
It even happens when the only change is deleting objects.

**Comment by shaikatz** [comment] 2020-10-18 13:51
What is the reason to sync objects that are already in synced state anyway?

**Comment by OmerKahani** [comment] 2020-10-18 16:27
> Yes, this also happens with manual sync.
> It even happens when the only change is deleting objects.

So I think these settings should directly under `syncPolicy`, and not under  `automated`

**Comment by peterbosalliandercom** [comment] 2020-11-25 13:33
duplicate of https://github.com/argoproj/argo-cd/issues/3877

**Comment by kshamajain99** [comment] 2020-12-04 21:59
Looking into this.

**Comment by jessesuen** [comment] 2020-12-04 22:00
>duplicate of #3877

You're right. Let's dup it.

**Closed by jessesuen** 2020-12-04 22:00 UTC
Labels: enhancement
