### ISSUE TITLE
ArgoCD UI: Toolbar not clickable since v2.4.11

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-cd#10677] opened 2022-09-23 07:57 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The toolbar in ArgoCD UI does not react to clicking since v2.4.11 (also v2.4.12). When typing `/` I can search, but selecting either the search bar or the buttons nothing happen. On double clicking e.g. "NEW APP" button the text gets highlighted. Tested with Firefox, Chrome and Safari. It's the same for everyone in our company.

<img width="1373" alt="Screenshot 2022-09-23 at 09 53 30" src="https://user-images.githubusercontent.com/50194881/191915170-b2015df4-18f6-4952-b4a6-036db853e31d.png">

**To Reproduce**

Open ArgoCD UI try to click something in the toolbar.

**Expected behavior**

The related action should be triggered.

**Version**

```shell
argocd: v2.4.12+41f54aa.dirty
  BuildDate: 2022-09-16T03:20:31Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: dirty
  GoVersion: go1.19.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.12+41f54aa
```

**Comment by jessesuen** [comment] 2022-09-27 00:44
Duplicate of https://github.com/argoproj/argo-cd/issues/10461

**Closed by jessesuen** 2022-09-27 00:44 UTC
Labels: bug
