### ISSUE TITLE
Support Labels and Selectors for Namespace Destinations in AppProject Object

### ISSUE THREAD

**Issue by cite** [argoproj/argo-cd#12212] opened 2023-01-30 13:30 UTC
# Summary

It would be great if ArgoCD supported `labelSelector` to group namespaces with identical labels into a single `AppProject`.

# Motivation

We are using Rancher to manage our Kubernetes clusters, and the way that permissions in Rancher works is that namespaces are grouped into so called "Projects", where each project then contains the actual namespaces. This is realized by setting identical labels on these namespaces and then applying RBAC policies to these labels.

# Proposal

It would be great if ArgoCD would support [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

**Comment by cregev** [comment] 2023-02-19 12:23
Any update on this? We would also love this suggestion

**Comment by blakepettersson** [comment] 2023-09-30 14:10
Duplicate of #3192

**Closed by blakepettersson** 2023-09-30 14:10 UTC
Labels: enhancement
