### ISSUE TITLE
Issue with syncing of app due to conditional using semverCompare seemingly not being evaluated 

### ISSUE THREAD

**Issue by nils1k** [argoproj/argo-cd#5833] opened 2021-03-21 18:34 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
This bug/question was first raised in the [#argo-cd Slack channel](https://argoproj.slack.com/archives/CASHNF6MS/p1614593546406900).

When trying to sync an application to a namespace, then the deployment resource fails with the following error message: 
```
error validating data: ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[1]): unknown field "subPathExpr" in io.k8s.api.core.v1.VolumeMount
```

Here is an excerpt from the `deployment.yaml` template we're using:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  replicas: {{ .Values.replicaCount }}
  containers:
  - name: {{ .Chart.Name }}    
    volumeMounts:                
        - name: log
          mountPath: /app/logs
          {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.Version }}
          subPathExpr: {{ .Release.Name }}/$(APP)
          {{- else }}
          subPath: {{ .Release.Name }}/$(APP)
          {{- end }}
```

It looks like the conditional above isn't evaluated. Hence, `subPathExpr` is used , which causes the application sync to fail. The failure is correct, as the version of k8s in the target cluster is `v1.13.9+icp-ee`, i.e. `subPathExpr` is not present in that version

**Note!** When I created the app, I used the ArgoCD CLI and specified to use helm v3, like so:

```shell
argocd app create myApp --project myProject --repo https://somewhere/myApp.git --path . --dest-namespace myNamespace --dest-server myCluster  --revision HEAD --helm-version v3
```

**To Reproduce**
1. Add a `volumeMounts` section like the one above, including the `semverCompare` conditional, to a deployment template
2. Create a new app in ArgoCD, set the Helm version to v3 by using the `--helm-version v3` option
3. Try to sync the app to a namespace in a cluster with a k8s version < 1.14-0

I've tried to execute the exact same `helm template`command, which is being executed by Argo as a part of step 3 above, locally (see the **Logs** section below). When I do that, the template is able to render correctly, without any error message. 

I haven't tried adding a similar conditional to other sections of the deployment YAML, but I suspect the behaviour would be the same, i.e. that it isn't evaluated

Versions of helm and kubectl used locally are as follows. 

**Helm**
```shell
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

**kubectl**
```shell
Client Version: v1.20.4-dirty
Server Version: v1.13.9+icp-ee
```

**Expected behavior**

The template should be rendered without any error message, and the app be synced to the namespace.

**Screenshots**

![argo_error_message](https://user-images.githubusercontent.com/3519430/111909489-cf555600-8a5d-11eb-801a-3ae803311532.png)

**Version**

```shell
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T19:33:57Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

**argocd-repo-server logs**
```shell
time="2021-03-21T14:25:31Z" level=info msg=Trace args="[helm template . --name-template someName --namespace someNamespace --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions apps/v1beta2 --api-versions apps/v1beta1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions batch/v2alpha1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1alpha1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1beta1 --api-versions servicecatalog.k8s.io/v1beta1 --api-versions clickhouse.altinity.com/v1 --api-versions clusterhealth.ibm.com/v1 --api-versions comcast.github.io/v1 --api-versions helm.fluxcd.io/v1 --api-versions icp.ibm.com/v1 --api-versions monitoring.coreos.com/v1 --api-versions monitoringcontroller.cloud.ibm.com/v1 --api-versions oidc.security.ibm.com/v1 --api-versions velero.io/v1 --api-versions volumesnapshot.external-storage.k8s.io/v1 --api-versions argoproj.io/v1alpha1 --api-versions audit.policies.ibm.com/v1alpha1 --api-versions authentication.istio.io/v1alpha1 --api-versions bitnami.com/v1alpha1 --api-versions certmanager.k8s.io/v1alpha1 --api-versions forecastle.stakater.com/v1alpha1 --api-versions iam.policies.ibm.com/v1alpha1 --api-versions kubeapps.com/v1alpha1 --api-versions openebs.io/v1alpha1 --api-versions policies.ibm.com/v1alpha1 --api-versions rbac.istio.io/v1alpha1 --api-versions config.istio.io/v1alpha2 --api-versions networking.istio.io/v1alpha3 --api-versions admission.certmanager.k8s.io/v1beta1 --api-versions securityenforcement.admission.cloud.ibm.com/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds]" dir="/tmp/https:__myRemoteRepName" operation_name="exec helm" time_ms=63.299456000000006
```

**Comment by n888** [comment] 2021-03-24 20:11
Hi,

I'm seeing same issue with jenkinsci helm chart while creating the ingress:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-ingress.yaml
```
{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if .Values.controller.ingress.enabled }}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
```
![image](https://user-images.githubusercontent.com/5288135/112376630-ebe1d000-8ca1-11eb-9c29-ff1118dcbb7d.png)

From what I saw, the issue seems to be present in `v1.8.2 - v2.0.0-rc1`, and works as intended with `v1.8.1`

**Comment by davidkarlsen** [comment] 2021-03-24 21:58
Hm, I believe we see this on 1.8.1:
```
k get pods -o yaml|grep image:
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/dexidp/dex:v2.22.0
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/dexidp/dex:v2.22.0
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/redis:5.0.8
      image: fsnexus.evry.com:8085/redis:5.0.8
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
      image: fsnexus.evry.com:8085/argoproj/argocd:v1.8.1
```
@nils1k can you confirm?

**Comment by nils1k** [comment] 2021-03-25 18:59
Yes, thats correct. See the output from `argocd version` command in the opening post (I've pasted an excerpt below).

```shell
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
```

**Comment by TiagoJMartins** [comment] 2021-03-31 16:58
As far as I can see, there is no kubectl binary on the repo-server, doesn't this mean helm won't be able to correctly get the server capabilities [and will then default](https://github.com/helm/helm/blob/master/pkg/chartutil/capabilities.go#L30-L33)?

**Comment by nils1k** [comment] 2021-04-01 19:16
The `kubectl` binary exists in the `repo-server` pod, and the version can be seen from the output of the `argocd version`command, which I've included in the opening post:

> **Version**
> 
> ```shell
> argocd: v1.8.7+eb3d1fb.dirty
>   BuildDate: 2021-03-07T19:33:57Z
>   GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
>   GitTreeState: dirty
>   GoVersion: go1.16
>   Compiler: gc
>   Platform: darwin/amd64
> argocd-server: v1.8.1+c2547dc
>   BuildDate: 2020-12-10T02:59:21Z
>   GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
>   GitTreeState: clean
>   GoVersion: go1.14.12
>   Compiler: gc
>   Platform: linux/amd64
>   Ksonnet Version: v0.13.1
>   Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
>   Helm Version: v3.4.1+gc4e7485
>   Kubectl Version: v1.17.8
>   Jsonnet Version: v0.17.0
> ```

Also, here you can see the output of running the `kubectl version` command inside of the `repo-server` pod:

```shell
user@argo-cd-argocd-repo-server:/usr/local/bin$ ls -ltr | grep kubectl
-rwxr-xr-x 1 root root 43503616 Dec 10 02:49 kubectl
user@argo-cd-argocd-repo-server:/usr/local/bin$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:43:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9+icp-ee", GitCommit:"fccfecc454d446967475ce34d13d3d63d407bf09", GitTreeState:"clean", BuildDate:"2019-08-27T08:46:50Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by martinezleoml** [comment] 2021-04-06 13:37
Hi,

I'm facing the same issue with Argo CD v2.0.0-rc1 while trying to deploy the latest Chartmuseum helm chart on our AWS EKS cluster (v1.18+).

```
➜  ~ argocd version
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T20:25:24Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0-rc1+0ca643f
  BuildDate: 2021-03-19T21:27:59Z
  GitCommit: 0ca643f027b99e8a5b931bb8ee9df42c3e4b64bf
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Helm manifest:
![image](https://user-images.githubusercontent.com/759215/113718626-1fcee380-96ed-11eb-9a15-b5eb493fa33c.png)

Argo CD error: 
![image](https://user-images.githubusercontent.com/759215/113718733-3aa15800-96ed-11eb-9721-d694ef1499fd.png)

API version should be `networking.k8s.io/v1beta1` according to my cluster's version & the Helm manifest.

It seems that the `kubectl` client's version is taken into account instead of the server's one while helm chart is rendered, resulting is choosing the wrong API version for the ingress resource.

**Comment by jannfis** [comment] 2021-04-06 18:01
Addendum: There's an open PR already: https://github.com/helm/helm/pull/9040

**Comment by mkilchhofer** [comment] 2021-05-10 09:42
I think using the CLI argument `--validate` would do the trick:
```console
helm template -h
      (..)
      --validate                     validate your manifests against the Kubernetes cluster you are currently pointing at. This is the same validation performed on an install
      (..)
```
Rendering then takes longer because helm contacts the API server and validates the manifest against it. But capabilities are then set correctly.

**Comment by tiagomeireles** [comment] 2021-05-27 18:37
helm/helm#9040 has merged and helm [3.6.0](https://github.com/helm/helm/releases/tag/v3.6.0) has been released which should unblock fixing this issue.

**Comment by jannfis** [comment] 2021-05-27 19:03
Thanks for this heads-up @tiagomeireles. We'll start working on integrating Helm v3.6 and support passing `--kube-version` flag soon. 

Hate to lower everyone's expectation here, but I think the earliest release this comes with is v2.1, and not with a patch release of v2.0. We had bad experiences upgrading tools to new minor versions in previous releases, especially with Kustomize.

**Closed** 2021-05-29 06:46 UTC
Labels: bug

**Comment by rcjames** [comment] 2021-07-08 07:16
> I think the earliest release this comes with is v2.1, and not with a patch release of v2.0
Are you able to provide any more clarity on what this means in terms of a release timeline? I can't find anything in your docs about the significance of a minor version release, so I'm unsure about what this means.

**Comment by jannfis** [comment] 2021-07-08 17:18
@rcjames You can have a look at our [v2.1 release milestone](https://github.com/argoproj/argo-cd/milestone/22), it now has an (approx) release date attached to it.

As for the docs, it's not yet visible in the stable docs, but we have recently added something to the docs here: https://argo-cd.readthedocs.io/en/latest/developer-guide/release-process-and-cadence/

**Comment by mmerrill3** [comment] 2021-08-04 22:26
I see something very similar to the original reported issue, except on version 2.0.4 of argo-cd.  The default helm version for my helm2 chart (version v1.20.0) is always used as the value for .Capabilities.KubeVersion.GitVersion, no matter what the target cluster's version is.   
As far as I can tell, the version from the app.spec.destination.server should be the source of the kubernetes version, and that comes from the livestatecache (redis).  There seems to be an issue with 2.0.4 just always setting the target server kubernetes version to v1.20.0, which will mess up any expectations when using functions like semverCompare in a helm chart.

**Comment by jannfis** [comment] 2021-08-05 09:12
@mmerrill3 Argo CD v2 changed default version of Helm to v3 - so unless you explicitly have `.spec.helm.version` set to `2`, it is probably rendered using Helm v3 (and thus, passes a static version identifier for the target cluster's K8s version).
