### ISSUE TITLE
Finer control over Delete menu item

### ISSUE THREAD

**Issue by s50600822** [argoproj/argo-cd#3477] opened 2020-04-23 17:51 UTC
# Summary

Hide delete button when applicable.
<img width="956" alt="Screen Shot 2020-04-24 at 3 38 57 am" src="https://user-images.githubusercontent.com/5586453/80131268-51829380-85dd-11ea-81f4-e14021edd009.png">

# Motivation

Likely in a team, only special roles are supposed to be able to delete application and we don't want people to click it by mistake. It is quite close to refresh when you are in a hurry. 
I know we can prevent it by role like:
```
p, role:dev, applications, create, */*, allow
p, role:dev, applications, update, */*, allow
p, role:dev, applications, */*, allow
p, role:dev, applications, sync, */*, allow
p, role:dev, applications, override, */*, allow
p, role:dev, applications, action/*, */*, allow
p, role:dev, certificates, create, *, allow
p, role:dev, certificates, update, *, allow
p, role:dev, certificates, *, allow
p, role:dev, clusters, create, *, allow
p, role:dev, clusters, update, *, allow
p, role:dev, clusters, *, allow
p, role:dev, repositories, create, *, allow
p, role:dev, repositories, update, *, allow
p, role:dev, repositories, *, allow
p, role:dev, projects, create, *, allow
p, role:dev, projects, update, *, allow
p, role:dev, projects, *, allow
p, role:dev, accounts, update, *, allow

g, role:dev, role:readonly
g, hoa, role:dev
```
<img width="1552" alt="Screen Shot 2020-04-24 at 3 21 15 am" src="https://user-images.githubusercontent.com/5586453/80131679-eeddc780-85dd-11ea-8db4-d50022d39b89.png">

But I think if we don't want people to click this, the best thing is that the button isn't even there.

# Proposal
Optionally hide the button, at least per user role.
Though destructive operation like `delete` should be a hidden feature by default I think and only enabled when the administrator of argo explicitly want it there.
 
Also the text can be more descriptive about what it is deleting.

How do you think this should be implemented?
- a Sys env to decide whether to populate delete in the menu item or not (global config)
- a user/role based check to decide whether to populate delete in the menu item or not

**Comment by alexmt** [comment] 2021-06-09 22:53
Closing as duplicate of https://github.com/argoproj/argo-cd/issues/5013  . This issue was opened first but #5013 has the most generic description

**Closed by alexmt** 2021-06-09 22:53 UTC
Labels: component:ui, enhancement, type:usability
