### ISSUE TITLE
Add target_revision label to the argocd_app_info metric

### ISSUE THREAD

**Issue by reegnz** [argoproj/argo-cd#16469] opened 2023-11-28 17:15 UTC
# Summary

We want to monitor argocd projects, and identify what branches an application is refering to.

# Motivation

Sometimes app configuration becomes outdated and refers to branches that don't exist anymore (eg. development branches that have been merged).

We would like to corellate argocd applications with git metadata and identify misconfiguration issues through metrics.

# Proposal

Add a new label `target_revision` to the `argocd_app_info` time series, so it's also exposed as a metric.
This new label shouldn't cause significant cardinality changes.

**Comment by evankanderson** [comment] 2023-12-14 18:05
This would be useful for me as well.  Is someone working on this yet?  Would a PR be accepted?

**Comment by ebuildy** [comment] 2024-01-07 01:32
duplicate of https://github.com/argoproj/argo-cd/issues/4115 - fixed by https://github.com/argoproj/argo-cd/pull/15143

**Comment by reegnz** [comment] 2024-01-09 13:58
Closing as duplicate, thanks for noticing!

**Closed** 2024-01-09 13:59 UTC
Labels: enhancement
