### ISSUE TITLE
Username is required when using access token for git authentication

### ISSUE THREAD

**Issue by roelvdberg** [argoproj/argo-cd#6098] opened 2021-04-23 14:20 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It is required in ArgoCD to specify a git username even when the git authentication method only requires a password.
Bot Azure DevOps and Gitlab have a method where we can create a access token to authenticate ourselfs and access a private Git repository. There isn't any username involved in this process. When we register this in ArgoCD we get a message that authentication is required. It will work when we add a random username.

**To Reproduce**

A list of the steps required to reproduce the issue. Best of all, give us the URL to a repository that exhibits this issue.
1. Create a git repo with Token authentication.
2. Try to connect to the git repo with Argo CD, withouth adding a  username.

**Expected behavior**

The authentication should be successful when only the authentication token is used.

**Screenshots**

![save-repo-error](https://user-images.githubusercontent.com/5803989/115884062-ca196b80-a44e-11eb-89d7-3e00d3d06194.png)
Error when connecting withouth username.

![image](https://user-images.githubusercontent.com/5803989/115884627-66dc0900-a44f-11eb-8b59-8a8f4b4c723b.png)
Working example with a random username

**Version**

```shell
Paste the output from `argocd version` here.
```
argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+f5119c0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by jannfis** [comment] 2021-04-23 17:09
This is actually documented behavior, not a bug: https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#access-token

However, I agree that this behavior could be changed to accept empty usernames.

**Comment by kshamajain99** [comment] 2021-06-02 18:59
This error is from github directly. While accessing a repo, github returns fatal: Authentication failed error if username is not provided.

```
$ git clone https://github.com/username/Private-Repo-Test.git
Cloning into 'Private-Repo-Test'...
Username for 'https://github.com':
Password for 'https://github.com': <personal-access-token>
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/kshamajain99/Private-Repo-Test.git/'

$ git clone https://github.com/username/Private-Repo-Test.git
Cloning into 'Private-Repo-Test'...
Username for 'https://github.com': fakeusername
Password for 'https://fakeusername@github.com': <personal-access-token>
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), done.
```

**Comment by rouke-broersma** [comment] 2021-06-02 19:21
> This error is from github directly. While accessing a repo, github returns fatal: Authentication failed error if username is not provided.

 This error comes from Argo, not github. While github might require a username and might give a similar error message when the username is provided, this is not relevant when not using github as the git host. Neither azure devops nor git**lab** require a username.

**Comment by chetan-rns** [comment] 2021-08-19 12:45
@alexmt I'll investigate more. Could you please assign it to me?

**Closed** 2021-10-04 21:58 UTC
Labels: bug, workaround, bug/severity:minor, bug/priority:medium
