### ISSUE TITLE
Cilium endpointslice don't go away when an application is deleted

### ISSUE THREAD

**Issue by cyrilcros** [argoproj/argo-cd#4190] opened 2020-08-27 21:36 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When I delete an application, all ressources are deleted except for some Services which remain indefinitely. They have a matching Cilium [EndPointSlice ressource](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/), which is cycling quickly between getting killed/ regenerated.

**To Reproduce**

- Use [Cilium](https://docs.cilium.io/en/v1.8/) as your Kubernetes CNI (v1.8 I think), with the endpointslice feature enabled (default now)
- Using the argocd web interface, delete an app (`cascade` options).
- some services will hang; the name of the EndPointSlice will be changing quickly in the UI (as in endpoint.name-`hash`, with `hash` switching every 2-3s)

**Expected behavior**

The application's ressources, including the service, are all deleted.
I am not sure if this is an issue for ArgoCD or Cilium....

**Version**
1.7.1

PS: those were ClusterIP services, and it looks like this may be some sort of race condition, because the number of services seem to change with the same app (bitnami prometheus operator helm chart here).

PPS: looking at the docs ArgoCD should just be made to ignore that resource type lifecycle or maybe use the ` endpointslice.kubernetes.io/managed-by ` label.

**Comment by darshanime** [comment] 2020-08-28 14:53
duplicate of https://github.com/argoproj/argo-cd/issues/4138

**Closed** 2020-08-28 15:18 UTC
Labels: bug
