### ISSUE TITLE
The cluster xyz has no assigned shard

### ISSUE THREAD

**Issue by woehrl01** [argoproj/argo-cd#17124] opened 2024-02-07 15:34 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I just updated our ArgoCD version from 2.9.5 to 2.10.0 everything comes to a halt after that. I can see that the Redis is on full load since the update:

<img width="872" alt="Bildschirmfoto 2024-02-07 um 14 25 57" src="https://github.com/argoproj/argo-cd/assets/2535856/c287515c-2fcc-4637-ac8c-1d74a7f10edb">

 The application-controllers are using nearly no CPU at all.
redis-cli monitor gives the following actions: "set" "cluster|info|https://abcd.com/|1.8.3.gz"

The log is flooded with `The cluster xyz has no assigned shard`

![image](https://github.com/argoproj/argo-cd/assets/2535856/4d40d7b3-838a-467c-931c-37dfc906d1e3)

Looks like that the sharing is updated quite often:

![image](https://github.com/argoproj/argo-cd/assets/2535856/b449a465-9909-43bd-8139-aa010bc87293)

Sharding configuration is set to "round-robin". But no explicit sharding in the cluster secret.

Maybe related to #17016 see:
![Bildschirmfoto 2024-02-07 um 16 38 44](https://github.com/argoproj/argo-cd/assets/2535856/9264855c-e4a1-405d-9a9b-3b9b125fe63d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

2.10.0

**Logs**

```
Paste any relevant application logs here.
```

**Comment by leoluz** [comment] 2024-02-09 21:56
@woehrl01 Can you please confirm if you are deploying the Argo CD controller as a `StatefulSet` or as a `Deployment`?

**Comment by jetersen** [comment] 2024-02-09 23:04
I can confirm seeing the same with Argo CD controller using StatefulSet and 3 replica.

**Comment by woehrl01** [comment] 2024-02-10 05:21
Yes, I'm using a statefulset @leoluz

**Comment by AnubhavSabharwa** [comment] 2024-02-10 13:22
I also faced similar issue where apps are getting created and they are not getting created.

So, i removed ARGOCD_CONTROLLER_REPLICAS parameter and added controller.sharding.algorithm: round-robin 
and restarted the controller.

Everything looks good

I have 3000 helm based apps and refresh time is 3-5 secs and UI is also good

**Comment by woehrl01** [comment] 2024-02-10 13:33
@AnubhavSabharwa if you remove that env then you should only have one replica configured which should disable the sharding all together. At least this is how it has been in <2.10.

**Comment by AnubhavSabharwa** [comment] 2024-02-10 13:36
Yes, I removed that env and now due to round robin all request are going to all controller pods and my argocd performance is now very good

For 3000 helm based apps 
I have 2 controllers and 3 reposerver only
Refresh time is 3-5secs only

In previous version, I was using 10 controller and even ater that the refresh and sync was not giving expected results

**Comment by woehrl01** [comment] 2024-02-10 13:41
@AnubhavSabharwa thats because there must be a breaking change then I that behaviour. At least with statefulset you had to define that env in the past so that the algorithm knows how many replicas you have with statefulsets. Are you using statefulsets or the new deployment feature?

**Comment by AnubhavSabharwa** [comment] 2024-02-10 13:42
I am using statefulset for controllers

**Comment by jetersen** [comment] 2024-02-10 13:44
I guess it is on argocd helm to fix the sharding if there are changes to the behavior?

**Comment by AnubhavSabharwa** [comment] 2024-02-10 13:48
Agree to that, in previous versions when you enable that paramters then argocd matches 1 controller replica with 1 registered cluster to process all requests.

But now if you use that env everything will be in hault.

Its a breaking change lets see how new release will fix this

**Comment by woehrl01** [comment] 2024-02-10 13:48
@jetersen I don't think so, I'm using the default yaml with some kustomize. Of this env is not needed this is a breaking change which should be documented. It's also a different behaviour according to the docs. It's documented here that you have to set this variable to the number of replicas you have: https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/

**Comment by AnubhavSabharwa** [comment] 2024-02-10 13:55
I woul say the functionality is not working rather than a breaking change.

I removed that parameter which resolves my thing however, performing more testing on this version

**Comment by woehrl01** [comment] 2024-02-10 15:18
@AnubhavSabharwa I can't confirm that "removing ARGOCD_CONTROLLER_REPLICAS" works, according to the logs this causes that every replica of the statefulset is updating all clusters.


See one of our test instances with 25 clusters in total, every cluster is processing every cluster:
![Bildschirmfoto 2024-02-10 um 16 18 02](https://github.com/argoproj/argo-cd/assets/2535856/c63d5261-9bb9-497c-9922-ea25c59d2116)

**Comment by woehrl01** [comment] 2024-02-10 15:25
But what I can confirm is, that it should have something to do with that ENV because the behaviour has changed, to my observations of my last test.

**Comment by AnubhavSabharwa** [comment] 2024-02-10 15:26
Yes, removing that env allows request to processed by any controller.

I was saying about the hault that if you remove that env then the apps will sync.

In short sharding functionality is not working as same as it was working in previous version

**Comment by woehrl01** [comment] 2024-02-10 15:32
My logs show `Processing all cluster shards` for each controller replica. That means that every controller thinks that it is "shard=0".

@AnubhavSabharwa Beware of your setup because it could cause troubles with concurrent update of resources, from multiple controllers.

**Comment by woehrl01** [comment] 2024-02-10 15:40
Thanks for the idea @AnubhavSabharwa I think I know found the issue:

https://github.com/argoproj/argo-cd/blob/bb1c1ed44d3c802329c5437f3904852dc3ea98de/cmd/argocd-application-controller/commands/argocd_application_controller.go#L259C2-L286

"shardNumber" in line 259 will be `0` by default. that means no shard will be infered in line 277 (https://github.com/argoproj/argo-cd/blob/bb1c1ed44d3c802329c5437f3904852dc3ea98de/cmd/argocd-application-controller/commands/argocd_application_controller.go#L277)

That means there will be only the clusters of shard 0 processed.

**Comment by woehrl01** [comment] 2024-02-10 15:57
@AnubhavSabharwa absolutely. Your round-robin configuration has no effect, because it won't be used. With the current setup argocd assumes there is only a single shard, but there are multiple. Every shard thinks it has to manage all clusters, this results in every shard is updating every cluster.

**Comment by AnubhavSabharwa** [comment] 2024-02-10 18:26
Yes, correct however overall performance related to sync and app refresh is very good in comparison of previous versions.
But the concern here is to validate the consequences.

One of the issue I faced which might be related to this.

My application status is healthy however, the app is keep on syncing and throwing error whoch states that svc or deployment already exist and when I try to terminate it, it says ""No Operation In Progress"" but when I resunc the app the sync status is Sync Ok.



Note:- On terminate app page says 00:00 for the sync time.


This might be happening because at the same time or with the some millisec difference request reached out to 2 controllers and both tried to sync it.

**Comment by woehrl01** [comment] 2024-02-10 19:17
The performance should be better because of some fixes around caching.

You can have a look if the following fixes your issue until a proper fix has been released:
https://github.com/argoproj/argo-cd/issues/17016#issuecomment-1937079998

**Comment by wilsonwang371** [comment] 2024-02-10 19:53
I added ARGOCD_CONTROLLER_SHARD env var and finally got my similar issue fixed.

**Comment by wilsonwang371** [comment] 2024-02-10 22:52
> I added ARGOCD_CONTROLLER_SHARD env var with value -1 and finally got my similar issue fixed. Thanks for the investigation

still with this, the argocd still has problem when there is only one controller. i guess the corner cases are not well handled.

**Comment by woehrl01** [comment] 2024-02-11 06:18
@wilsonwang371 yes, you are only allowed to set this value to `-1` if there are more than 1 replica (via `ARGOCD_CONTROLLER_REPLICAS`) . Got a single replica case this value is not needed, or needs to be set to `0`.

If you set this to -1 with only a single replica, the actual shard number will not be inferred correctly and the shard gets the negativ index, will never match anything.

**Comment by woehrl01** [comment] 2024-02-11 10:23
What's still strange is that even though this now resolves that issue that apps are synced, I still see "Updating cluster shards" about every 3 minutes in the logs:

![Bildschirmfoto 2024-02-11 um 11 13 32](https://github.com/argoproj/argo-cd/assets/2535856/91c686c2-a834-4565-8427-a281c0afe7a4)

**Comment by jetersen** [comment] 2024-02-11 14:10
@woehrl01 just out of interest 😅 What tool/software are you using there to query?

**Comment by woehrl01** [comment] 2024-02-11 14:11
@jetersen that's NewRelic. A great piece of software. 😊

**Closed** 2024-02-13 16:51 UTC
Labels: bug

**Comment by crenshaw-dev** [comment] 2024-02-22 16:38
Is 2.10.1 working for y'all? 

Seems like maybe not. https://github.com/argoproj/argo-cd/issues/17257
