### ISSUE TITLE
don't throw error when logs haven't loaded yet 

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo-cd#6318] opened 2021-05-25 21:53 UTC
# Summary

Currently, when a new pod is coming up, if you click on the pod and then click logs, you will get greeted with a red error box describing an internal server error. While this is technically true because the pod logs don't exist yet - it would be nice if argocd would check to see if that's the issue (the pod just hasn't come up yet) and maybe display "waiting for container to start" instead.
# Motivation

Internal server error is something that makes me want to investigate an issue with argoCD, rather than just realizing that the pod is loading. Also impatient users will constantly see this and it's kind of an eyesore. This is obviously a cosmetic, non-important change.

# Proposal

Instead of displaying a red error box with "internal server error", show a tooltip or something displaying that the container is still starting.

**Comment by alexmt** [comment] 2021-05-25 21:59
Totally agree this the proposal. Similar ehnancement has been implemented by https://github.com/argoproj/argo-cd/pull/6273 and available in v2.0.2. Does implemented change look acceptable?

**Comment by alexmt** [comment] 2021-05-25 23:10
Closing it as a duplicate of https://github.com/argoproj/argo-cd/issues/6100  . Let me know if you want to reopen please

**Closed by alexmt** 2021-05-25 23:10 UTC
Labels: answered, enhancement
