### ISSUE TITLE
"Save" button should not be displayed when users don't have to permission to modify changes

### ISSUE THREAD

**Issue by dontreboot** [argoproj/argo-cd#6437] opened 2021-06-09 00:59 UTC
# Summary

When users don't have the permission to modify an ArgoCD app settings or any other ArgoCD resources, there should be a "Save" button displayed for users. It is misleading to users as they think they have permission to save the changes. Users don't know that they don't have permission until they hit "Save" and receive the permission error message.
![image (1)](https://user-images.githubusercontent.com/1145737/121276245-2ad7f880-c883-11eb-96b1-1cfded941abc.png)

# Motivation

Better user experience

# Proposal

Either not show the "Save" button or grey out the button to clearly indicate users don't have permission to modification.

**Comment by alexmt** [comment] 2021-06-09 22:53
Closing as duplicate of https://github.com/argoproj/argo-cd/issues/5013  .

**Closed by alexmt** 2021-06-09 22:53 UTC
Labels: enhancement
