### ISSUE TITLE
Possibility to use Git-versioned values with Helm applications

### ISSUE THREAD

**Issue by andrei-dascalu** [argoproj/argo-cd#6094] opened 2021-04-23 10:54 UTC
# Summary

At the moment it seems like deploying an application from a helm repository can't be combined with a values files taken from a Git repository. It would be good to be able to do so.

# Motivation

At the moment a Helm application take off a Helm chart repository can get values either through a versioned Application spec (where values overrides are stored in Git - making it technically a Git application rather than helm) or setup through Argo UI. It would be good to be able to provide a Git repository to independently version the values (and allow write-back from the image updated - which needs a Git repo).

# Proposal

Not entirely sure what would be a good approach in order to also play well with the image updater. Perhaps an option to provide a Git repository & path to specify the values file (at the moment you can specify the name of the file but the file itself is read from the Helm repository which are the defaults and any customised values must be provided as overrides).

**Comment by chgl** [comment] 2021-04-25 15:25
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/5826

**Comment by blakepettersson** [comment] 2024-01-21 10:44
Resolved with #10432

**Closed by blakepettersson** 2024-01-21 10:44 UTC
Labels: enhancement
