### ISSUE TITLE
UI crash on "big" applications (with many components) for Application Details page starting from v1.7.+

### ISSUE THREAD

**Issue by Subreptivus** [argoproj/argo-cd#4476] opened 2020-10-02 06:55 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrade to 1.7.x version, we’ve faced issues with UI for App Details page for more or less big applications. On small application all is working alright. Other parts of UI work well.
We’ve reverted back to 1.6.2 where everything is fine.
The problem is that I couldn’t find a way on how to describe this problem correctly to create an issue. For example in one case it throws React error: `Maximum call stack size exceeded`. On other App it won’t show even this little.

**To Reproduce**

1. Install ArgoCD v1.7.+
2. Add some big or huge Application. Clearly reproducible on Kubeflow - https://github.com/kubeflow/manifests
3. Sync the Application and wait for deployment.
4. Open Application Details page.

**Expected behavior**

No UI crash on Application Details page

**Screenshots**

![image](https://user-images.githubusercontent.com/17779448/94895460-1f326780-0494-11eb-94dd-3676742e3b6b.png)

<img width="867" alt="Screenshot 2020-10-01 at 16 14 05" src="https://user-images.githubusercontent.com/17779448/94895419-0fb31e80-0494-11eb-9b7b-b33bed5dc436.png">

**Version**

Any v1.7.+ of `argocd-server`

**Comment by rbreeze** [comment] 2020-10-08 23:21
Which Kubeflow manifest are you using? Do you have any other applications that cause this behavior?

**Comment by Subreptivus** [comment] 2020-10-09 07:29
> Which Kubeflow manifest are you using?

This one with some customizations: https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml
 > Do you have any other applications that cause this behavior?

Yes I do, unfortunately I can't share them, for now those are close sourced.

**Comment by rbreeze** [comment] 2020-10-09 18:25
Does the UI crash for both the networking and resource tree views, or just the resource tree view?

**Comment by Subreptivus** [comment] 2020-10-12 07:09
As the default view is tree one, hence it's surely happening on tree view. But I can't really tell about networking one, because there is no ability to change the view at all. Basically when I'm clicking on the application in application list view to go to application details page, just after a fraction of a second crash happens. Sometimes I can see some of the resources which are trying to be rendered withing page, sometimes I'm not even see anything, but it always finishes in crash.

**Comment by rbreeze** [comment] 2020-10-14 20:55
Would you mind including the dev console output when you get this error, and the API response from the `resource-tree` endpoint? 

If either contains sensitive information, feel free to reach out to me in the [Argo Project Slack channel](https://argoproj.github.io/community/join-slack)

**Comment by rbreeze** [comment] 2020-10-23 00:13
@Subreptivus Have you tried on the latest version? I'm unable to reproduce with the resource tree you sent me.

**Comment by Subreptivus** [comment] 2020-10-23 06:34
Sorry, there is no change. Just tried v1.7.8. Have sent details you were asking for in Slack DM.

Thanks!

**Comment by Subreptivus** [comment] 2020-10-27 10:21
Hey @rbreeze!
Just to let you know that we accidentally found a workaround. For completely another issue, we've risen the values of resource limits for `argocd-server` and now there are no UI crashes anymore on newer versions of ArgoCD.
Here are the limits we're using now:
```yaml
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
```
And here are the limits we were using previously:
```yaml
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
```
Curious thing, that there were no crashes or OOM kills of `argocd-server` with our previous limits configurations and no hints about unscientific resources in the logs as well.
Hope it will help you with the investigation.

**Comment by rbreeze** [comment] 2020-10-27 16:52
@Subreptivus Thanks for letting us know! Thanks to the data you sent me on Slack I've narrowed it down to a small segment of code, so this will be fixed even for those who don't want to increase the resource limits of their `argocd-server`.

**Closed** 2020-10-28 22:57 UTC
Labels: bug, bug/priority:high, cherry-pick/1.7, component:ui, regression, workaround
