### ISSUE TITLE
Migrate the Grafana dashboard (Angular deprecation)

### ISSUE THREAD

**Issue by marcofranssen** [argoproj/argo-cd#18447] opened 2024-05-29 12:23 UTC
# Summary

Migrate the Grafana dashboard to not use (Deprecated) AngularJS anymore.

# Motivation

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

# Proposal

https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

**Comment by tylerauerbeck** [comment] 2024-05-29 20:21
I think this is a duplicate of #18433 and is potentially resolved by #18434

**Comment by marcofranssen** [comment] 2024-05-30 07:14
Aaarf, sorry for that, I should have done a better search before submitting this. Thanks for this update.

**Closed** 2024-06-03 20:37 UTC
Labels: enhancement, good first issue
