### ISSUE TITLE
Sync: ssh: handshake failed: EOF

### ISSUE THREAD

**Issue by hamza-tumturk** [argoproj/argo-cd#4451] opened 2020-09-29 08:26 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Every 10-15 mins I'm getting "ssh: handshake failed: EOF" when running a sync. I'm also able to see it in the repo server logs when it's auto-syncing itself. It seems more likely to happen when I invalidate the cache on the clusters. I wonder if it does too many requests which causes ssh interruptions.

**To Reproduce**

ArgoCD server with 100+ apps and 4500+ resources. Running 5 AWS EKS clusters and sourcing repos from Bitbucket.

**Expected behavior**

Sync without ssh EOF failure.

**Screenshots**
![image](https://user-images.githubusercontent.com/19170248/94530837-95845f00-0233-11eb-818d-009ae593f22f.png)

**Version**

```shell
v1.7.6+b04c25e
```

**Logs**

```
rpc error: code = Unknown desc = ssh: handshake failed: EOF
```

**Comment by jannfis** [comment] 2020-09-29 10:29
I don't know whether Bitbucket has a rate limiting on Git requests via SSH, but with 100+ apps Git requests can become quite numerous with the default settings (especially the default refresh interval of 3m). The number of Git requests are exported as a metric from the repo-server, so this might give you a good indicator of how many they are indeed.

You could try to decrease the number of SSH requests by increasing the refresh-check interval to something more sensible, and set-up webhooks on your Bitbucket server for refreshing your applications whenever they change.

**Comment by hamza-tumturk** [comment] 2020-09-30 18:17
@jannfis thanks, I'll also raise a ticket with Bitbucket regarding this, and provide details here if any relevant to ArgoCD.

So far, I've run a continuous git clone with some verbose output on the same instance as the ArgoCD repo server is running, but even when I saw the ssh EOF error in ArgoCD, I wasn't able to see any interruptions in the ssh git clone.
Ran it as follows to catch any issues, but no luck:
```
while true; do
GIT_TRACE_PACKET=1 GIT_TRACE=1 GIT_SSH_COMMAND="ssh -v" GIT_CURL_VERBOSE=1 git clone git@bitbucket.org:org/repo.git || break
rm -rf repo
done
```
The hourly clone limit for bitbucket is 30.000, which I am not hitting anywhere close looking at the repo-server metrics.

**Comment by jannfis** [comment] 2020-10-04 15:40
> The hourly clone limit for bitbucket is 30.000, which I am not hitting anywhere close looking at the repo-server metrics.

You should also take a look at the `ls-remote` metrics from the repo-server, because I imagine they count into the limits of BitBucket as well.

However, an `eof` error with SSH almost always indicates that the peer (or some intermediate component in between) has abruptly dropped the connection. Maybe this could also be related to #3994.

**Comment by srearnold** [comment] 2020-10-27 10:52
same question in gitlab.
Gitlab said rate limit of download archives is 5 requests per minute per user whatever through the UI or the API.

**Comment by manfredliuactive** [comment] 2020-11-19 05:25
> > The hourly clone limit for bitbucket is 30.000, which I am not hitting anywhere close looking at the repo-server metrics.
> 
> You should also take a look at the `ls-remote` metrics from the repo-server, because I imagine they count into the limits of BitBucket as well.
> 
> However, an `eof` error with SSH almost always indicates that the peer (or some intermediate component in between) has abruptly dropped the connection. Maybe this could also be related to #3994.

hi i run argocd 1.7.5, but I don't see any metrics related to ssh on both argocd-metrics and argocd-server-metrics.

**Comment by m-yosefpor** [comment] 2020-11-27 23:49
We have the same issue, with argocd and gitlab (foss on-premise).

**Comment by ermazi** [comment] 2020-12-23 07:01
https://github.com/argoproj/argo-cd/issues/4925#issuecomment-749975526

**Comment by alexmt** [comment] 2021-07-20 16:24
The issues probably fixed in v2.1.0-rc1 (coming soon). See https://github.com/argoproj/argo-cd/issues/4925#issuecomment-883525567

Will update as soon as release is published

**Comment by alexmt** [comment] 2021-07-29 15:55
The v2.1-rc1 is ready. https://github.com/argoproj/argo-cd/releases/tag/v2.1.0-rc1

@ermazi  , @m-yosefpor can you please give it a try and see if it resolves the issue?

**Comment by alexmt** [comment] 2021-08-20 05:32
Closing and will reopen if someone reproduce issue again

**Closed by alexmt** 2021-08-20 05:32 UTC
Labels: bug, bug/in-triage

**Comment by mcwienczek** [comment] 2022-04-07 08:59
I am experiencing this issue since I upgraded to Argocd v2.3.3
