### ISSUE TITLE
Bump issue #15184 - deprecate argocd-notifications docs site

### ISSUE THREAD

**Issue by asaf400** [argoproj/argo-cd#18473] opened 2024-06-02 12:14 UTC
#15184

Old site is still running, and has no warning. /:

**Comment by ChristianCiach** [comment] 2024-06-02 14:35
Yep. As someone new to ArgoCD, I've read the wrong docs more than once.

**Comment by agaudreault** [comment] 2024-06-03 21:06
Closing as duplicate of https://github.com/argoproj/argo-cd/issues/15184. Please use original issue for updates and do not create a new one.

**Closed by agaudreault** 2024-06-03 21:06 UTC
Labels: bug
