### ISSUE TITLE
Fine-grained Permissions for exec  action

### ISSUE THREAD

**Issue by artarik** [argoproj/argo-cd#20526] opened 2024-10-24 17:28 UTC
# Summary
Native kubernetes RBAC can't grant access  to create pods/exec  resources which selected by wildcard (e.g. all pods from one Deployment) because every time when pod restart it change his name. 
Grant access to Web Terminal for these pods from argo-ui can be good choice.

# Motivation
It can be helpful every time when you should configure fine-grained permissions  to resources with dynamic names which managed by argocd
# Proposal
It already works for Update/Delete actions and fully described in [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#fine-grained-permissions-for-updatedelete-action)

How do you think this should be implemented?

**Comment by tooptoop4** [comment] 2024-10-29 20:25
dupe of https://github.com/argoproj/argo-cd/issues/13406

**Comment by andrii-korotkov-verkada** [comment] 2024-11-10 21:33
@artarik, check out my comment here https://github.com/argoproj/argo-cd/issues/13406#issuecomment-2466935801. Feel free to close this issue in favor of the pre-existing one.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-11 03:19
Closing as duplicate

**Closed by andrii-korotkov-verkada** 2024-11-11 03:19 UTC
Labels: enhancement
