### ISSUE TITLE
Different orders in the list are considered different and always be triggered, even by unrelated commit

### ISSUE THREAD

**Issue by Rosyya** [argoproj/argo-cd#13446] opened 2023-05-04 09:45 UTC
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

I create hpa with metric cpu and memory, but different orders in the list are considered different in argocd, and it will be always triggered, even by unrelated commit

**To Reproduce**

1. create kubernets application with hpa
2. add metric with both cpu and memory
3. deploy the application with argocd
4. create another unrelated application and deploy
5. the  application with hpa will also be triggered

**Expected behavior**

applications should always be triigered by his own configuration path

**Screenshots**
here is the diff which argocd checked every time
![image](https://user-images.githubusercontent.com/115975088/236169358-12c90b83-f1c4-416f-b413-f5d0168426c3.png)

**Version**
V2.3.4

**Logs**

```
Paste any relevant application logs here.
```

**Comment by blakepettersson** [comment] 2023-06-22 21:56
Duplicate of #7846

**Closed by blakepettersson** 2023-06-22 21:56 UTC
Labels: bug
