### ISSUE TITLE
Unable to load data: Internal error - accessing logs for container that couldn't start

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#6001] opened 2021-04-09 01:48 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

> Unable to load data: Internal error

**To Reproduce**

Set up a replicaset (e.g. 3 replicas) with pods w/ 2+ containers. The main container should be expensive and long running (e.g. neo4j/ongdb). The other containers should be `tail -f /path/to/a/log/file` 

Add an unreasonable resource limit to the replica set:
```yaml
resources:
  limits:
    cpu: 10m
    memory: 5
  requests:
    cpu: 5m
    memory: 3
```

Let argo apply it. It will stop a pod, and try to start it again, the tails will start, but the main pod will get stuck.

k9s reports:
NAME | PF | READY | RESTARTS | STATUS | CPU | MEM | %CPU/R↓ | %CPU/L | %MEM/R | %MEM/L | IP          
-|-|-|-|-|-|-|-|-|-|-|-
test-core-2 | ● | 3/4 |         0 | CreateContainerError  |   0  |  0  |      0  |   n/a |      0   |  n/a  | 10.52.5.148 

Visit argocd/applications/app?view=tree&node=%2FPod%2Ftest%2Ftest-core-2%2F3&tab=logs

You'll see a red box fly in at the bottom right:
> Unable to load data: Internal error

It's possible to click on the other containers to see their logs
Clicking the broken container will yield this error again

**Expected behavior**

The log content area should be replaced with a message explaining the container is broken and providing whatever information is available to debug the problem

**Screenshots**

![Unable to load data: Internal error](https://user-images.githubusercontent.com/2119212/114116410-aa147480-98b2-11eb-869b-159750266969.png)

**Version**

```shell
{
    "Version": "v2.0.0+d085636",
    "BuildDate": "2021-03-30T19:10:08Z",
    "GitCommit": "d085636fd72c170d0553a2db1f0de8e6ea0df398",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by alexmt** [comment] 2021-04-09 02:12
I think the correct behavior is to print the error message in logs so that the user can understand what is happening.

**Comment by alexmt** [comment] 2021-05-25 23:10
Closing it as a duplicate of #6100 . Let me know if you want to reopen please

**Closed by alexmt** 2021-05-25 23:10 UTC
Labels: bug
