### ISSUE TITLE
The 'repo add' command incorrectly requires upsert flag

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#2925] opened 2019-12-30 18:17 UTC
**Describe the bug**

The 'repo add' command incorrectly requires upsert flag even if `repo add` command does not introduce any changes if repo configuration

**To Reproduce**

1. Manually add repository https://github.com/argoproj/argocd-example-apps in argocd-cm config map.
1. Run `argocd repo add https://github.com/argoproj/argocd-example-apps`
1. Command fails with error `existing repository spec is different; use upsert flag to force update`

**Expected behavior**

The upsert should not be required in this case

**Screenshots**

**Version**

```shell
v1.3.6
```

**Comment by SabySen** [comment] 2021-08-24 16:31
Face this issue in 2.1.0 again. Unable to add the repo.
Unable to connect HTTPS repository: existing repository spec is different; use upsert flag to force update

**Comment by kj187** [comment] 2021-08-25 13:30
same here

**Comment by Jaydee94** [comment] 2021-09-07 13:48
Experienced the Same Problem with Version 2.1.2.

**Comment by matoszz** [comment] 2021-09-08 22:45
also experienced the same issue on v2.1.2

**Comment by neelk-s1** [comment] 2021-09-10 20:31
we had luck reverting to v2.0.2

**Comment by SabySen** [comment] 2021-09-10 21:16
> we had luck reverting to v2.0.2

@neelk-s1 2.0.4 is good as well. I am thinking the moment you go to the next minor version the trouble begins.

**Comment by pasha-codefresh** [comment] 2021-09-12 17:36
I can't reproduce this issue with steps as inside description. Could you please share details 
@SabySen @kj187 @neelk-s1 @matoszz @Jaydee94

**Comment by yogeek** [comment] 2021-09-13 10:44
Hi :)
Same problem with 2.1.1
here are the details :
```
$ argocd repocreds list
URL PATTERN                     USERNAME  SSH_CREDS  TLS_CREDS
git@$GIT_URL:  -         false      false

# Same repo, same key
$ argocd repocreds add git@$GIT_URL: --ssh-private-key-path ~/.ssh/argocd.pem
FATA[0002] rpc error: code = InvalidArgument desc = existing repository credentials spec is different; use upsert flag to force update

$ argocd repocreds rm git@$GIT_URL:
Repository credentials for 'git@code.tooling.prod.cdsf.io:' removed

$argocd repocreds add git@$GIT_URL: --ssh-private-key-path ~/.ssh/argocd.pem
Repository credentials for 'git@$GIT_URL:' added
```

**Comment by pasha-codefresh** [comment] 2021-09-13 11:05
Thank you @yogeek , i will check it today

**Comment by yogeek** [comment] 2021-09-13 11:11
@pasha-codefresh thanks
Side note : maybe the issue is only if argocd has been updated to a new version, not sure about that but I had the issue only on clusters where I did an upgrade, not fresh install

**Comment by SabySen** [comment] 2021-09-13 12:51
Seems to me that the issue is when you upgrade to the 2.1.x version. you can replicate the same from the UI as well.

**Comment by Jaydee94** [comment] 2021-09-13 12:55
I've Upgrades from 2.0.1 to 2.1.2. Seems to work with a fresh Installation. When upgrading from a prior version the issue appears.

**Comment by SabySen** [comment] 2021-09-13 13:02
IDK upgrading from 2.0.1 but 2.0.4 to 2.1.0 gives me this issue.

**Comment by pasha-codefresh** [comment] 2021-09-14 12:47
I have tried 
1. Install argocd v2.0.0
2. Execute argocd repocreds add git@$GIT_URL: --ssh-private-key-path ~/.ssh/id_rsa
3. Upgrade to stable kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
4. Execute argocd repocreds add git@$GIT_URL: --ssh-private-key-path ~/.ssh/id_rsa

As result I got: "repository credentials for added" without any error. 

Still cant reproduce it :(

**Comment by pasha-codefresh** [comment] 2021-09-14 12:48
I would propose improve this error message, "existing repository spec is different; use upsert flag to force update" with details what actually was changed

**Comment by alexisbel1** [comment] 2021-10-02 10:57
I had the same problem when upgraded from v2.0 to v2.1.4. I had to manually removed the repo-**** secret where the SSH key was  already defined.

**Comment by leoluz** [comment] 2021-11-05 14:17
There was a bug in the `argocd repo add` command that would return a misleading error message `existing repository spec is different; use upsert flag to force update` if the related secret was found in k8s without the proper label. This was addressed by https://github.com/argoproj/argo-cd/pull/7617 and now it will return a proper error message. For example:
```
FATA[0001] rpc error: code = InvalidArgument desc = secret "repo-412345316" doesn't have the proper "argocd.argoproj.io/secret-type" label: please fix the secret or delete it
```

@alexmt Do you think we can close this issue?

**Comment by leoluz** [comment] 2021-11-05 20:46
@siddana123 can you please check if in the secret associated with your repo the following label is defined?
```yaml
labels:
    argocd.argoproj.io/secret-type: repository
```

**Closed** 2021-12-08 18:05 UTC
Labels: bug, regression
