### ISSUE TITLE
CLI doesn't seem to pass --api-versions option to Helm template command

### ISSUE THREAD

**Issue by yann-soubeyrand** [argoproj/argo-cd#3594] opened 2020-05-15 14:19 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When using Argo CD CLI to diff or sync an app, the `--api-versions` option doesn't seem to be passed to the Helm template command which is executed.

**To Reproduce**

Create an application which deploys a chart (like [filebeat](https://github.com/helm/charts/tree/master/stable/filebeat)) making use of the `.Capabilities.APIVersions` feature (https://github.com/helm/charts/blob/master/stable/filebeat/templates/servicemonitor.yaml#L1) and sync this application. If the needed API versions are present in the cluster, Argo CD will deploy the resources depending on these (a `ServiceMonitor` in this example).

Once the application has been deployed, use the CLI to show the diff between what's deployed and your local computer (using `argocd app diff filebeat --local .` in this example). The CLI will output the Helm command which is executed and you can see that this command isn't passed the `--api-versions` option. Also, whereas the diff is expected to be empty since you didn't do any modification after the initial sync, it will contain the removal of the resources which are conditioned to API versions (in this case, the `ServiceMonitor` would be removed).

**Expected behavior**

Argo CD CLI should pass the `--api-versions` options when executing Helm just like the repository server does when generating the manifests.

**Screenshots**

```
❯ argocd app diff filebeat --local .

INFO[0000] helm template . --name-template filebeat --namespace cluster-logging --values values.yaml --values secrets.yaml --values /tmp/values-255546592.yaml --include-crds  dir=. execID=0LpKI
===== monitoring.coreos.com/ServiceMonitor cluster-logging/filebeat-prometheus-exporter ======
1,17d0
< apiVersion: monitoring.coreos.com/v1
< kind: ServiceMonitor
< metadata:
<   labels:
<     argocd.argoproj.io/instance: filebeat
<   name: filebeat-prometheus-exporter
< spec:
<   endpoints:
<   - targetPort: 9479
<   jobLabel: filebeat-prometheus-exporter
<   namespaceSelector:
<     matchNames:
<     - cluster-logging
<   selector:
<     matchLabels:
<       app.kubernetes.io/instance: filebeat
<       app.kubernetes.io/name: filebeat
```

**Version**

```shell
argocd: v1.5.4+36bade7
  BuildDate: 2020-05-05T18:59:08Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.5.4+36bade7
  BuildDate: 2020-05-05T19:01:57Z
  GitCommit: 36bade7a2d7b69d1c0b0c4d41191f792a847d61c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Comment by jaideepr97** [comment] 2020-09-03 23:07
Hi @yann-soubeyrand 

I'm trying to reproduce this issue locally, but I'm not seeing the same diff output as the one you have shown here
Steps I followed: 
- ```argocd app create filebeat --repo https://github.com/helm/charts.git --path stable/filebeat --dest-server https://kubernetes.default.svc --dest-namespace default ```
- Download a helm binary of v2.16.10 and called it helm2 (i faced errors for not having an executable called 'helm2' while trying to run the diff)
- argocd app diff filebeat --local .

The output I'm seeing is this:
```
INFO[0000] helm2 init --client-only --skip-refresh       dir=. execID=5a726
INFO[0000] helm2 template . --name filebeat --namespace default --kube-version 1.18  dir=. execID=bbwiL
```

however, I don't see a service monitor deployed on my UI [If I'm supposed to] 
![argo-issue](https://user-images.githubusercontent.com/21956986/92181860-43107800-ee18-11ea-8a9e-a017a21d1791.png)


my argocd version:
```
argocd: v1.7.2+c342d3f
  BuildDate: 2020-08-27T23:33:37Z
  GitCommit: c342d3fc9c9c9f0d1c18254b6ffa1e106984a76c
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v99.99.99+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit: 
  GitTreeState: 
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.17.8

```


Please let me know if I'm doing something wrong, or missing something, or if you would like any other information from me
Thanks

**Comment by yann-soubeyrand** [comment] 2020-10-03 17:16
Hi @jaideepr97,

To deploy Filebeat's ServiceMonitor, you need to add the following configuration to your values.yaml file:
```
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
```

With these values, Argo CD deploys the ServiceMonitor (if the ServiceMonitor CRD is present in the cluster). But when you do a local diff with Argo CD CLI, it tells you that the ServiceMonitor will be removed. That's because Argo CD CLI doesn't seem to pass the --api-versions flag to Helm.

**Comment by rra** [comment] 2021-04-27 20:58
I'm seeing what I think is a similar issue. I have an ingress that starts with a conditional to determine the `apiVersion`:
```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
```
On a cluster running Kubernetes 1.18, the conditional still evaluates to true and Argo CD then attempts to use the 1.19+ API version `networking.k8s.io/v1` so the sync fails. It looks like the API versions may be set to some default value and not determined dynamically from the cluster?

**Comment by randrusiak** [comment] 2021-04-28 09:24
It doesn't work because the above conditional only verify if a specified API is available. In this case, you should also check if a specific resource in this API is available .i.e: `.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"`.
But currently, it's not possible because it works only if `--validate` flag is passed to helm template command. 

I have the same problem with  k8s in 1.18 version. It evaluates this conditional as true because in this version of k8s there is networkpolicies resource in `networking.k8s.io/v1` API version. You can verify that: `kubectl api-resources | grep networking.k8s.io/v1`

**Comment by rra** [comment] 2021-04-28 23:16
Ah, thank you. So perhaps this issue is a duplicate of https://github.com/argoproj/argo-cd/issues/3640?

**Comment by cilindrox** [comment] 2021-07-05 17:53
Running into the same issue with the recently updated OAuth2-proxy chart. [The ingress resource makes a](https://github.com/oauth2-proxy/manifests/blob/f3a551d82348a9ce76f1bf0638c190c90c533db2/helm/oauth2-proxy/templates/ingress.yaml#L8) `.Capabilities.APIVersions.Has` call on `networking.k8s.io/v1/Ingress` and on k8s 1.20 and argo 2.0.4 this check fails and makes it fall back to the `extensions/v1beta1` API.

At this point is annoying and preventing the upgrade, but on clusters running version 1.21 this fails altogether and prevents installing any charts that have feature toggles based on capabilities.

There might be a workaround as mentioned on #5202 using a custom helm wrapper, but that's just too involved. Ideally, argo would support passing the `--validate` flag to the helm command.

**Comment by sathieu** [comment] 2021-09-24 08:12
I've filled a new bug, with a summary of problems about APIVersions (and a new one). See #7291.

**Closed** 2022-02-05 00:35 UTC
Labels: bug, bug/priority:medium, component:cli, component:config-management
