### ISSUE TITLE
Bad parameters retrieved for Helm files in UI and Notifications

### ISSUE THREAD

**Issue by paydaycay** [argoproj/argo-cd#9175] opened 2022-04-22 08:40 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Since v2.3.3 (I was in 2.2.5 before and didn't get the problem), values retrieved from Helm file in the UI are not the good ones. 
The values retrieved are the default values and not the ones in my overlay file.

For example, In my default value file, I have php.image.tag equals to "helm". 
The override value in my overlay file for php.image.tag is equal to "test-XXXXX". 

I retrieve "helm" instead of "test-XXXXX".

I encounter the same problem in ArgoCD Notifications when I attempt to retrieve a value from Helm file in my templates.

**To Reproduce**

Just create a Helm chart and create an overlay file to override the default values. When you click on the application in the interface and go to "Parameters" tab, you will see the default values and not the good ones.

With ArgoCD Notifications, you can retrieve it by calling this : 

```
{{ (call .repo.GetAppDetails).Helm.GetParameterValueByName "php.image.tag" }}
```

And you won't retrieve the correct ones. 

**Expected behavior**

I expect to retrieve the correct values that are in my overlay file as it was in v2.2.5.

**Screenshots**

In the UI :
![image](https://user-images.githubusercontent.com/8417078/164649814-a58db605-abad-4f6f-87b5-23975f0fd77f.png)
![image](https://user-images.githubusercontent.com/8417078/164649886-492ad0b1-cbf0-43c5-b714-a1d382a597d6.png)

In the values.yaml default file : 
![image](https://user-images.githubusercontent.com/8417078/164650559-9d65f6e6-3943-4115-ba0c-5814deda3de2.png)

In the test.yaml overlay file : 
![image](https://user-images.githubusercontent.com/8417078/164650051-86baceb0-20b4-4ee0-bd91-6f9136e96ad0.png)

Part of my notifications template : 
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/8417078/164651413-4661bf51-d97c-43c4-96cf-a5424c05d4ca.png">

Part of the notification received : 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/8417078/164651273-574c4240-dc17-485b-a792-419889db574b.png">

**Version**

```shell
argocd: v2.3.3+07ac038
  BuildDate: 2022-03-30T00:06:18Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
No relevant logs found.
```

**Comment by uniit** [comment] 2022-04-24 14:18
+1 Please prioritize this one b/c it misleads many people when they see different values on the parameters page and deployed applications. Otherwise please recommend a correct way how to use helm overrides in Argo.

**Comment by mihma** [comment] 2022-04-26 11:54
Similar issue after upgrading to 2.3.3. Is there a work around it?

**Comment by sgavrylenko** [comment] 2022-04-26 12:39
have the same problem

**Comment by fredfp** [comment] 2022-05-02 14:29
this seems to be a duplicate of https://github.com/argoproj/argo-cd/issues/8808

**Comment by crenshaw-dev** [comment] 2022-06-03 16:31
Agreed, duplicate. Thanks for reporting!

**Comment by crenshaw-dev** [comment] 2022-06-03 16:31
Yuck, I dislike GitHub's phrasing. It is planned, it's just a duplicate.  :-P

**Closed** 2022-06-03 16:31 UTC
Labels: bug, duplicate
