### ISSUE TITLE
Application detail view not correct when deploying application with multiple resources

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#918] opened 2018-12-10 15:38 UTC
When I deploy a role, rolebinding the argocd application detail treeview is correct, when I add a pod.yaml after this then the treeview only shows the pod in the view only. see screenshot 

![image](https://user-images.githubusercontent.com/9946020/49742912-dcd5e000-fc99-11e8-9189-f925210d1d9e.png)

and when adding the pod the role and rolebindings are gone:
![image](https://user-images.githubusercontent.com/9946020/49742961-f4ad6400-fc99-11e8-9de3-60fb3a9c8cf4.png)

**Comment by alexmt** [comment] 2018-12-10 17:04
Hello @peterbosalliandercom ! Can please specify argo cd version?

**Comment by alexmt** [comment] 2018-12-10 17:17
one more followup question. Can you please check if you have any filter applied?
![screen shot 2018-12-10 at 9 16 40 am](https://user-images.githubusercontent.com/426437/49749138-58b13780-fc5c-11e8-8196-be54cc4eb234.png)

**Comment by twz123** [comment] 2018-12-10 17:18
Just to rule this out: Did you check the filter settings in the upper right corner of the UI? It might be the case that roles and rolebindings are not shown by default, depending on which resource kinds are part of the app.

**Comment by alexmt** [comment] 2018-12-10 17:36
I think I know how that could happen. UI stores filter selection in browser local storage. UI ignore resource kinds in a stored filter if an application does not have such kind. Following steps are possible:

- user navigates to app which has pods and selects pod in resource filter.
- navigates to another app which has no pods. UI is showing everything (because pod kind is missing in app)
- user deploys pod and UI is showing only pods now

This behavior is confusing. UI should show nothing if pod kind is selected in filter even if UI don't have Pod kinds at all.

**Comment by peterbosalliandercom** [comment] 2018-12-11 08:21
It was release 0.11, I did not use or change any filter settings

**Comment by peterbosalliandercom** [comment] 2018-12-11 08:24
It appears that when adding the pod the filter automatically deselects role and rolebinding in the filter, this should probably not be happening. When I manually select role and rolebinding they are visible again.

**Comment by alexmt** [comment] 2018-12-11 20:57
Issue described at https://github.com/argoproj/argo-cd/issues/918#issuecomment-445903009 was fixed by https://github.com/argoproj/argo-cd-ui/commit/0d225965ff6642444e5b25633210e4babf261d86 . 

Closing issue. @peterbosalliandercom please reopen if you still able to reproduce incorrect behavior.

**Closed by alexmt** 2018-12-11 20:57 UTC
