### ISSUE TITLE
no auto healing of bootstrap-app when sub-app got deleted

### ISSUE THREAD

**Issue by jkleinlercher** [argoproj/argo-cd#3195] opened 2020-03-05 14:07 UTC
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x ] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

We use a app-of-apps pattern with self-heal and auto-sync enabled on the bootstrap-app and sub-apps. When deleting a sub-app, I would expect that the self-healing of the bootstrap-app creates the sub-app again. However, the health state of the bootstrap-app is "missing" , "sync ok".

**To Reproduce**

create a bootstrap app which contains another app. then delete this app.

**Expected behavior**

bootstrap-app should create the sub-app automatically again

**Screenshots**

![grafik](https://user-images.githubusercontent.com/11465610/75989105-f264a480-5ef2-11ea-92d4-405a73d35c03.png)

**Version**

v1.4.2+48cced9

**Logs**

time="2020-03-05T13:21:15Z" level=info msg="Updated sync status: Synced -> OutOfSync" application=bootstrap-application dest-namespace=argocd dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-03-05T13:21:15Z" level=info msg="Updated health status: Progressing -> Missing" application=bootstrap-application dest-namespace=argocd dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2020-03-05T13:21:15Z" level=info msg="Update successful" application=bootstrap-application
time="2020-03-05T13:22:02Z" level=info msg="client watch grpc context closed" application=bootstrap-application
time="2020-03-05T13:22:02Z" level=info msg="k8s application watch event channel closed" application=bootstrap-application
time="2020-03-05T13:21:15Z" level=info msg="Reconciliation completed" application=bootstrap-application dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=1 time_ms=580.3601000000001
time="2020-03-05T13:22:15Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=bootstrap-application
time="2020-03-05T13:22:15Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=bootstrap-application
time="2020-03-05T13:22:15Z" level=info msg="Skipping auto-sync: most recent sync already to 54cd7264f06d67190fce3529a7377412e4d05985" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Update successful" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Reconciliation completed" application=bootstrap-application dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=1 time_ms=991.160871
time="2020-03-05T13:22:16Z" level=info msg="Refreshing app status (controller refresh requested), level (1)" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Skipping auto-sync: most recent sync already to 54cd7264f06d67190fce3529a7377412e4d05985" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Update successful" application=bootstrap-application
time="2020-03-05T13:22:16Z" level=info msg="Reconciliation completed" application=bootstrap-application dest-namespace=argocd dest-server="https://kubernetes.default.svc" fields.level=1 time_ms=733.498609
time="2020-03-05T13:22:18Z" level=info msg="Refreshing app status (hard refresh requested), level (2)" application=bootstrap-application
time="2020-03-05T13:22:18Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=bootstrap-application
time="2020-03-05T13:22:20Z" level=info msg="Skipping auto-sync: most recent sync already to 54cd7264f06d67190fce3529a7377412e4d05985" application=bootstrap-application

**Comment by jgwest** [comment] 2024-02-08 21:25
Closing as not able to reproduce, and issue does not contain sufficient reproduction steps to make it any different from the generic case. Feel free to open a new issue if issue persists.

**Closed by jgwest** 2024-02-08 21:25 UTC
Labels: bug, type:usability, component:applications-set
