### ISSUE TITLE
Can't view Promote Full button on rollouts

### ISSUE THREAD

**Issue by wesbrownfavor** [argoproj/argo-cd#10355] opened 2022-08-16 19:23 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I recently updated from 2.3.3 to 2.4.9 and when I try to manually promote a rollout I am not presented with the button to do so.  I see the rollout in a paused state and the button does appear for a split second before disappearing.

**To Reproduce**

Click the settings icon on a rollout in ArgoCD v2.4.9+1ba9008

**Expected behavior**

I would expect to have the promote-full button under the options menu for rollouts in a paused state.

**Screenshots**
![Screen Shot 2022-08-16 at 1 57 17 PM](https://user-images.githubusercontent.com/87991518/184961720-7be2c09d-3fc8-496c-9c95-a656cd66a708.png)

**Version**

```shell
argocd: v2.4.9+1ba9008
  BuildDate: 2022-08-11T15:22:41Z
  GitCommit: 1ba9008536b7e61414784811c431cd8da356065e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
These logs are generated whenever I click the settings button for my rollout

```
time="2022-08-16T19:13:04Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims="{\"at_hash\":\"idk_if_this_is_a_secret\",\"aud\":\"argo-cd\",\"c_hash\":\"idk_if_this_is_a_secret\",\"email\":\"me@my_company.com\",\"email_verified\":true,\"exp\":1660762374,\"groups\":[\"my_company:Infrastructure\",\"my_company:Everybody\",\"my_company:My_Group\",\"my_company:pci-ncc\",\"my_company:My_Group\"],\"iat\":1660675974,\"iss\":\"https://argocd.devops.fvr.internal/api/dex\",\"name\":\"Me\",\"preferred_username\":\"my_user\",\"sub\":\"idk_if_this_is_a_secret\"}" grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2022-08-16T19:13:04Z" span.kind=server system=grpc
time="2022-08-16T19:13:04Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2022-08-16T19:13:04Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2022-08-16T19:13:04Z" level=info msg="received unary call /application.ApplicationService/ListResourceActions" grpc.method=ListResourceActions grpc.request.claims="{\"at_hash\":\"idk_if_this_is_a_secret\",\"aud\":\"argo-cd\",\"c_hash\":\"idk_if_this_is_a_secret\",\"email\":\"me@my_company.com\",\"email_verified\":true,\"exp\":1660762374,\"groups\":[\"my_company:Infrastructure\",\"my_company:Everybody\",\"my_company:My_Group\",\"my_company:pci-ncc\",\"my_company:My_Group\"],\"iat\":1660675974,\"iss\":\"https://argocd.devops.fvr.internal/api/dex\",\"name\":\"Me\",\"preferred_username\":\"my_user\",\"sub\":\"idk_if_this_is_a_secret\"}" grpc.request.content="name:\"feedback-app-qa\" namespace:\"runner\" resourceName:\"feedback-app-qa\" version:\"v1alpha1\" group:\"argoproj.io\" kind:\"Rollout\" " grpc.service=application.ApplicationService grpc.start_time="2022-08-16T19:13:04Z" span.kind=server system=grpc
time="2022-08-16T19:13:04Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2022-08-16T19:13:04Z" grpc.time_ms=8.158 span.kind=server system=grpc
time="2022-08-16T19:13:04Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2022-08-16T19:13:04Z" level=info msg="Ignore '/spec/preserveUnknownFields' for CustomResourceDefinitions"
time="2022-08-16T19:13:04Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListResourceActions grpc.service=application.ApplicationService grpc.start_time="2022-08-16T19:13:04Z" grpc.time_ms=18.979 span.kind=server system=grpc
time="2022-08-16T19:13:04Z" level=info msg="received unary call /account.AccountService/CanI" grpc.method=CanI grpc.request.claims="{\"at_hash\":\"idk_if_this_is_a_secret\",\"aud\":\"argo-cd\",\"c_hash\":\"idk_if_this_is_a_secret\",\"email\":\"me@my_company.com\",\"email_verified\":true,\"exp\":1660762374,\"groups\":[\"my_company:Infrastructure\",\"my_company:Everybody\",\"my_company:My_Group\",\"my_company:pci-ncc\",\"my_company:My_Group\"],\"iat\":1660675974,\"iss\":\"https://argocd.devops.fvr.internal/api/dex\",\"name\":\"Me\",\"preferred_username\":\"my_user\",\"sub\":\"idk_if_this_is_a_secret\"}" grpc.request.content="resource:\"exec\" action:\"create\" subresource:\"feedback-app/feedback-app-qa\" " grpc.service=account.AccountService grpc.start_time="2022-08-16T19:13:04Z" span.kind=server system=grpc
time="2022-08-16T19:13:04Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=CanI grpc.service=account.AccountService grpc.start_time="2022-08-16T19:13:04Z" grpc.time_ms=0.344 span.kind=server system=grpc
```

This seems similar to [#10327](https://github.com/argoproj/argo-cd/issues/10327)

**Comment by wesbrownfavor** [comment] 2022-08-16 19:50
Just to update reverting to 2.4.8 fixes the issue.

**Comment by crenshaw-dev** [comment] 2022-08-16 21:58
Thanks for the report! Closing as a duplicate of #10327. Putting up a fix soon...

**Closed by crenshaw-dev** 2022-08-16 21:58 UTC
Labels: bug
