### ISSUE TITLE
Multi source applications are incorrectly marked as healthy and synced

### ISSUE THREAD

**Issue by pdrastil** [argoproj/argo-cd#13737] opened 2023-05-25 08:39 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Multi source applications seems to not work properly with sync waves. All resources are marked as synced and healthy even when application is in progressing state which is causing problems with order of deployments.

**To Reproduce**

1) Create app-of-apps pattern with 2 applications (cert-manager, aws-load-balancer) that use multi-source feature
2) Set sync wave for cert-manager application so it should be synced and healthy before aws-load-balancer
3) Check that both applications are in progressing state even when parent application contains resources marked as synced and healthy

**Expected behavior**

Multi source Application have proper state so sync waves works properly.

**Version**

```shell
2.7.2
```

**Comment by crenshaw-dev** [comment] 2023-05-25 18:04
Can you provide an example app to reproduce the bug?

**Comment by pdrastil** [comment] 2023-05-25 22:47
Sure I'll try to make it short as possible as this is part of larger setup.

## External value files 

Most of content is omitted for brevity. All components runs as HA setup with 3 replicas distributed into 3 AZs. Mentioning this as it might be important to observe behaviour when applications are synced.

aws-load-balancer-controller.yaml
```yaml
# Enable cert-manager for webhooks
enableCertManager: true
replicaCount: 3
```

cert-manager.yaml
```yaml
global:
  priorityClassName: system-cluster-critical
  
installCRDs: true
replicaCount: 3
```

## Application template (deployed from root application)

```yaml
{{- range $name, $spec := .Values.addons }}
{{- if $spec.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  {{- with $spec.syncWave }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ . | quote }}
  {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.project }}
  revisionHistoryLimit: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $spec.namespace | quote }}
  sources:
    - repoURL: {{ $spec.repoURL }}
      targetRevision: {{ $spec.targetRevision | quote }}
      {{- with $spec.chart }}
      chart: {{ . }}
      {{- end }}
      {{- with $spec.path }}
      path: {{ . }}
      {{- end }}
      {{- if or $spec.parameters $spec.valueFiles $spec.values }}
      helm:
        {{- with $spec.parameters }}
        parameters:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with $spec.valueFiles }}
        valueFiles:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $spec.values }}
        values: |
          {{- tpl . $ | trim | nindent 10 }}
        {{- end }}
      {{- end }}
    - repoURL: {{ $.Values.source.repoURL }}
      targetRevision: {{ $.Values.source.targetRevision }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
{{- end }}
{{- end }}
```

values.yaml
```yaml
project: addons

# Source for value files
source:
  repoURL: https://private-repo/bootstrap.git
  targetRevision: HEAD

# Map of addons to deploy
addons:
  aws-load-balancer-controller:
    namespace: kube-system
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.5.x
    parameters:
      - name: clusterName
        value: 'some-cluster'
      - name: serviceAccount.name
        value: aws-load-balancer-controller
      - name: serviceAccount.create
        value: "false"
    valueFiles:
      - $values/aws/base/values/aws-load-balancer-controller.yaml

  cert-manager:
    syncWave: -10
    namespace: cert-manager
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.12.x
    parameters:
      - name: serviceAccount.name
        value: cert-manager
      - name: serviceAccount.create
        value: "false"
    valueFiles:
      - $values/aws/base/values/cert-manager.yaml
```

**Comment by pdrastil** [comment] 2023-05-25 22:56
These applications are marked as green and healthy but dashboard have apps in progressing state that is dead-locked as cert-manager waits for service web hook and aws lb waits for certificate.

<img width="708" alt="Screenshot 2023-05-26 at 0 54 06" src="https://github.com/argoproj/argo-cd/assets/19188617/04b192da-735d-41c7-9fb9-5a8ce44edecf">

**Comment by raghavi101** [comment] 2024-06-25 18:14
Hey @pdrastil
Could provide a detailed example to reproduce this bug? I am unable to reproduce the bug with the setup provided above.

**Comment by ishitasequeira** [comment] 2024-07-26 01:31
@pdrastil , would like to follow up and see if are we still seeing the issue?

**Comment by ishitasequeira** [comment] 2024-07-30 16:52
Closing this bug as it seems to be fixed. Please feel free to re-open if the issue still persists

**Closed by ishitasequeira** 2024-07-30 16:52 UTC
Labels: bug, multi-source-apps, type:bug, component:multi-source-apps

**Comment by pdrastil** [comment] 2024-07-30 21:22
@ishitasequeira Unfortunately I don't have live repro at this moment. It was resolved by using AppSets that were generated correctly.
