### ISSUE TITLE
Submit argo-cd to the CDF (CD foundation)

### ISSUE THREAD

**Issue by the-gigi** [argoproj/argo-cd#3265] opened 2020-03-23 04:09 UTC
# Summary

The [CDF](https://cd.foundation) is where all the cool CD kids hang out. Argo-cd should be there too.

# Motivation

In order to be recognized as a major CD solution argo-cd should join the CDF

# Proposal

Please submit argo-cd to the CDF. See https://github.com/cdfoundation/toc/blob/master/PROJECT_LIFECYCLE.md#project-proposal-requirements

**Comment by alexmt** [comment] 2020-03-23 22:11
We've considered it here https://github.com/argoproj/argo-cd/issues/3265 and decided to go with CNCF:   https://github.com/cncf/toc/pull/299

**Comment by alexmt** [comment] 2020-03-23 22:11
Closing as a duplicate of https://github.com/argoproj/argo-cd/issues/3265

**Closed by alexmt** 2020-03-23 22:11 UTC
Labels: enhancement
