### ISSUE TITLE
All apps stuck in refresh (greyed out)

### ISSUE THREAD

**Issue by KlavsKlavsen** [argoproj/argo-cd#16971] opened 2024-01-24 15:08 UTC
**Describe the bug**

All apps in argocd UI is stuck - with a grey'ed out refresh - not able to refresh.
It seems to be a duplicate of https://github.com/argoproj/argo-cd/issues/15519 - however we do not have any logs indicating the error.

**To Reproduce**

We have one app - which uses autosync. Our next step is to disable that, delete and re-add that app and see if it resolves the problem.

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/2737885/de3bdff0-6a12-4f74-8dd7-bbc4b59a20a6)

**Version**

```shell
argocd: v2.9.5+f943664
  BuildDate: 2024-01-19T17:57:57Z
  GitCommit: f9436641a616d277ab1f98694e5ce4c986d4ea05
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64

```

**Logs**

```
no logs of interest not - in server nor in repo-server app.
```

**Comment by ashish1099** [comment] 2024-01-25 06:21
I have also remove the automate syncpolicy from all the apps as well, but still same result

**Comment by KlavsKlavsen** [comment] 2024-01-30 07:38
We ended up having to remove argocd deployments/sts'es incl. PVs and roll it up again. (as CRDs, configmap etc. stayed - things could fairly easy be rolled up again).
We have now disabled the 1 auto-sync'ing app we had - to hopefully not hit this again.

**Comment by jgwest** [comment] 2024-02-12 15:21
Appears to be a dupe of #15519 , as mentioned in original post. The logs posted in that PR were from the `application-controller` `Pod`. If the issue occurs again, you can check that `Pod` to verify whether those error messages are present.

**Closed by jgwest** 2024-02-12 15:21 UTC
Labels: bug
