### ISSUE TITLE
Add a possibility of limiting access to logs tab in ArgoCD WebUI

### ISSUE THREAD

**Issue by danylohetmantsev** [argoproj/argo-cd#5380] opened 2021-02-02 18:52 UTC
# Summary

Add a possibility to disable log output for certain applications in WebUI by using RBAC.

# Motivation

Example: Application writes the private information to STDOUT and you don't want to be able to see that on the logs tab of the pod.

# Proposal

If user doesn't have the action "logs" -> "Logs" tab is shown on all apps by default.

If user have the action "logs" only for certain applications -> "Logs" tab is only available on them.

**Comment by jessesuen** [comment] 2021-02-02 21:24
The problem is: to introduce an `application/logs` sub resource in rbac policies, it implies that GET on application will no longer allow you to retrieve logs, thereby breaking everyone's RBAC after the upgrade.

Casbin has the possibility of using deny rules, but we rather use an additive way of controlling RBAC rather than mixing additive and subtractive.

**Comment by ziimon** [comment] 2021-02-03 09:07
@jessesuen Aren't there other sub-resources as well where DENY rules would be useful? I understand that sticking to additive rules as long as possible makes things easier, but especially for larger setups (e.g. corporate) a fine granular RBAC is crucial.  Especially for logs, that potentially can contain confidential customer information, this really is a problem. Are you considering that topic internally or are there any known workarounds?

**Comment by agaudreault** [comment] 2024-05-06 16:03
The `logs` resource in RBAC has been implemented for some time now. I will close this issue, but feel free to reopen and update the context with the latest version if necessary.

https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/

**Closed by agaudreault** 2024-05-06 16:03 UTC
Labels: enhancement, component:settings, component:ui
