### ISSUE TITLE
argocd throws unauthenticated just after `account update-password` command

### ISSUE THREAD

**Issue by Dentrax** [argoproj/argo-cd#6166] opened 2021-05-05 14:18 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

argocd error outs after successful password update command.

**To Reproduce**

1. `$ argocd account update-password`
2. Enter your current password and new passwords
3. See the both success and error logs:
```bash
Password updated
FATA[0011] rpc error: code = Unauthenticated desc = Invalid username or password
```

**Expected behavior**

I think the `Unauthenticated` error should not error out since we already updated the password successfully.

**Screenshots**

<img width="973" alt="Screen Shot 2021-05-05 at 17 13 52" src="https://user-images.githubusercontent.com/16493751/117155225-456f0b80-adc5-11eb-854b-ea237769d1c7.png">

**Version**

```shell
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T20:25:24Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by jannfis** [comment] 2021-05-06 10:32
Dupe of #5836, which was fixed in #5848 (available with v2.0 onwards).

Closing as dupe.

**Closed by jannfis** 2021-05-06 10:32 UTC
Labels: bug
