### ISSUE TITLE
Git Generator throwing errors when yaml config is commented out

### ISSUE THREAD

**Issue by flickers** [argoproj/argo-cd#17184] opened 2024-02-12 15:51 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
When using a git generator files we see errors even though key/value pair is commented out

applicationSet
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-test
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Org/gitops-apps.git
        revision: HEAD
        files:
          - path: "aws/cluster-apps/devops-hello-world-test/argocd-config.yaml"
  syncPolicy: {}
  template:
    metadata:
      name: 'test-{{ "{{" }} .path.basenameNormalized | replace "." "-" {{ "}}" }}-{{ "{{" }} index (splitList "/" .path.path) 0 {{ "}}" }}-{{ "{{" }} .cluster {{ "}}" }}'
    spec:
      project: cluster-apps-{{ "{{" }} .cluster {{ "}}" }}
      source:
        path: '{{ "{{" }} .path.path {{ "}}" }}'
        targetRevision: HEAD
        repoURL: https://github.com/Org/gitops-apps.git
      destination:
        namespace: '{{ "{{" }} .namespace {{ "}}" }}'
        name: 'test-{{ "{{" }} index (splitList "/" .path.path) 0 {{ "}}" }}-{{ "{{" }} .cluster {{ "}}" }}'
```

argocd-config.yaml (commented out is throwing errors)
```yaml
# - cluster: prod
#   namespace: devops
```

Causes this error
`validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps`

and applicaitonSet had Degraded status

**To Reproduce**

Use the yaml files described above to encounter the errors

**Expected behavior**

In ArgoCD v2.9.x this did not give any errors and if something was commented out in the argocd-config.yaml the application would simply not deploy to that server.
It's like ArgoCD is somehow taking the commented out key/value pairs into the generator but as it's commented out the values are empty and thus giving the <no value> errors like is shown below in the log section

**Screenshots**

**Version**

```shell
v2.10.0+2175939
```

**Logs**

```
time="2024-02-12T15:43:15Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:43:46Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:43:46Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:43:46Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:43:46Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:44:09Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:44:09Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
time="2024-02-12T15:44:09Z" level=error msg="validation error found during application validation: application references project cluster-apps-<no value> which does not exist" applicationset=argocd/cluster-apps
```

**Comment by wanddynosios** [comment] 2024-03-08 09:18
To me it looks like this PR made the relevant change: https://github.com/argoproj/argo-cd/pull/15661

There has been a discussion on [slack](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1678890329839499) which explains that folks sometimes rely on the existence of the file, and then just use default values.

My use-case (and yours as well if I understand correctly) relies on certain keys in the file being present instead. If I want to delete an app, I comment the relevant keys. If they want to delete an app, the delete/rename the file (which would also be a workaround).

I'm wondering we can find a common ground here?

**Comment by andrii-korotkov-verkada** [comment] 2024-11-11 12:39
ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

**Comment by alexkivars** [comment] 2024-11-11 13:33
> ArgoCD versions 2.10 and below have reached EOL. Can you upgrade and let us know if the issue is still present, please?

This issue seems to be resolved in the latest version.

**Closed** 2024-11-11 13:37 UTC
Labels: bug, component:application-sets, version:EOL
