### ISSUE TITLE
Version selector drop down has bug

### ISSUE THREAD

**Issue by gopikrishna7** [argoproj/argo-cd#12693] opened 2023-03-02 13:54 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

When I have gone through the [ docs](https://argo-cd.readthedocs.io/en/stable/)
There is  two "version selector drop downs" one at the top and one at the bottom left,  when I completely scroll down.
![Screenshot 2023-03-02 191715](https://user-images.githubusercontent.com/50741807/222446398-15075242-6389-47c3-889e-de16aabfcd7e.png)

I can change the versions from the button which is bottom left of my page.
![Screenshot 2023-03-02 184740](https://user-images.githubusercontent.com/50741807/222446741-c9ec0990-4003-4bbe-b684-dd2a06363659.png)

**To Reproduce**

Go to the [docs](https://argo-cd.readthedocs.io/en/stable/) and completely scroll down to the bottom of the page.

**Comment by 34fathombelow** [comment] 2023-03-04 15:22
Duplicate of #11999

**Closed by 34fathombelow** 2023-03-04 15:22 UTC
Labels: bug
