### ISSUE TITLE
Application Controller Log Level does not get applied 

### ISSUE THREAD

**Issue by renat1sakenov** [argoproj/argo-cd#17577] opened 2024-03-20 09:27 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Despite setting the attribute `controller.log.level: "error"`, warning logs get printed.
Within the application controller pod the environment variable ARGOCD_APPLICATION_CONTROLLER_LOGLEVEL=error is set.
Logs still contain:
```
W0320 08:44:22.204804 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:27.265380 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:32.338947 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:37.354734 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:42.201751 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:47.258019 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
W0320 08:44:52.224318 1 warnings.go:70] unknown field "metadata.app.kubernetes.io/component"
```

**To Reproduce**

1.  Setup Argo CD
2. Configure the application controller log level to be on error.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cmd-params-cm
data:
  controller.log.level: "error"
```
3. Add an Application which includes a malformed configmap such as 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  app.kubernetes.io/component: datasources
data:
  json-datasources.yaml: |-
    [...]
```
4. Warning logs (from the application controller pod) should start to be printed.

**Expected behavior**

Expected behavior is that application controller warning logs are not printed.

**Screenshots** - 

**Version**

```shell
$ argocd version
argocd: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:37:43Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
```

**Logs** -

**Comment by jgwest** [comment] 2024-03-28 17:52
Basically a dupe of https://github.com/argoproj/argo-cd/issues/6761: There are logs that are being output by external libraries consumed by Argo CD which do not respect the log level.

**Comment by renat1sakenov** [comment] 2024-04-01 09:55
Hello @jgwest,
thank you for the note, I glanced over that one, but wasn't too sure if it's really one and the same issue.

**Closed** 2024-11-11 07:17 UTC
Labels: bug, component:logging, component:application-controller
