### ISSUE TITLE
Error creating application from OCI helm chart in Harbor

### ISSUE THREAD

**Issue by eugentius** [argoproj/argo-cd#5282] opened 2021-01-20 12:17 UTC
Creating Helm chart and pushing to Harbor registry

```export HELM_EXPERIMENTAL_OCI=1    
helm registry login  harbor.mydomain.com  -u user -p password
helm chart save chart  harbor.mydomain.com/charts/app-chart:1.0.0
helm chart push harbor.mydomain.com/charts/app-chart:1.0.0
```

Output:
```The push refers to repository [harbor.mydomain.com/charts/app-chart]
ref:     harbor.mydomain.com/charts/app-chart:1.0.0
digest:  6357c5f858f209a2a10cdfecf92467fb8556340bd200124d86ef0e515ebee4e0
size:    6.2 KiB
name:    app
version: 0.1.0
1.0.0: pushed to remote (1 layer, 6.2 KiB total)
```

Trying to download:
```$ helm chart pull harbor.mydomain.com/charts/app-chart:1.0.0
1.0.0: Pulling from harbor.mydomain.com/charts/app-chart
ref:     harbor.mydomain.com/charts/app-chart:1.0.0
digest:  6357c5f858f209a2a10cdfecf92467fb8556340bd200124d86ef0e515ebee4e0
size:    6.2 KiB
name:    app
version: 0.1.0
Status: Chart is up to date for harbor.mydomain.com/charts/app-chart:1.0.0
```

ArgoCD repo list: 
```$ argocd repo list
TYPE  NAME                      REPO                                                                                             INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE
...
helm  charts-oci               harbor.mydomain.com                                                           false     true   false  true   Successful
...
```

Trying to create a new Application:
```
argocd app create test-app --repo harbor.mydomain.com --helm-chart charts/app-chart --revision 1.0.0 --dest-namespace argocd --dest-server https://kubernetes.default.svc --values values.yaml
```

Output:
```
FATA[0003] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `tar -zcvf /tmp/harbor.mydomain.com/charts_app-chart-1.0.0.tgz app-chart` failed exit status 2: tar: app-chart: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

If I repeat the same command, I will get another exception:
```argocd app create test-app --repo harbor.mydomain.com --helm-chart charts/app-chart --revision 1.0.0 --dest-namespace argocd --dest-server https://kubernetes.default.svc --values values.yaml
FATA[0002] rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = open /tmp/helm488790457/app-chart: no such file or directory
```

Getting the same errors if try to add App from ArgoCD GUI.

ArgoCD version:
```argocd version
argocd: v1.8.2+94017f2.dirty
  BuildDate: 2021-01-10T06:50:14Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: dirty
  GoVersion: go1.15.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.8.2+94017f2
  BuildDate: 2021-01-10T05:40:54Z
  GitCommit: 94017f2c8d97588d4aa2213713a71d51005ed62d
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

Harbor version: 2.1.1

**Comment by alexmt** [comment] 2021-02-02 22:20
Hello @eugentius , 

Tried to reproduce the issue. Pushed chart to `demo.goharbor.io` and successfully created application. Which Argo CD version are you using?

**Comment by eugentius** [comment] 2021-02-08 16:51
Found RC.
Chart name shouldn't contain "chart".
I renamed 
"charts/app-chart" 
to 
"charts/app".
and it worked

**Comment by Mobrockers** [comment] 2021-03-08 14:06
@alexmt We are running into this same issue. From our testing @eugentius is slightly wrong in their conclusion. The problem is not that the chart name contains chart. Dashes seem to be the problem. Application creation fails as soon as a dash exists in the chart name.

**Comment by fredleger** [comment] 2021-07-09 16:05
/reopen

Why this is closed ?
Seems to have a workaround but i guess this is not realy a wanted feature but sounds more like a bug ?

**Comment by m-yosefpor** [comment] 2021-08-14 19:46
Tested with argocd v2.1-rc3, dash nor "chart" in helm chart name is not an issue (anymore?). I could create apps with the name `health-chart` . The issue in our case was that the `name` in Chart.yaml, must exactly match the image name you have pushed in OCI registry.


Just in case, if you are using the same registry for both your application image and chart image, and want to make your chart image different than your app image, either add a prefix/suffic in both `Chart.yaml` and the image you push with `helm chart push`, or either use a suffix/prefix in **tag** instead.
e.g.

app container image: `hello:2.1`
chart container image: `hello:2.1-chart`

Chart.yaml:
```
apiVersion: v2
name: hello
description: A Helm chart for Kubernetes
type: application
version: 2.1
```

**Comment by fredleger** [comment] 2021-08-25 12:40
From our tests, i totally agree with the conclusion of @m-yosefpor.
The side effect we were facing is that the ci/cd workflow was using same names for both docker image and helm chart.
Once prefixed (we used a `charts/` sub-folder/repo inside the same OCI registry - so `myproject:1.2.3` for docker image and `charts/myproject:1.2.3` for helm chart) this work like a charm.

Then i guess it should be closed with maybe a simple note about it in docs if that make any good.

**Comment by rouke-broersma** [comment] 2021-08-25 12:52
I can confirm that we eventually realized the only issue was that our OCI image name was different from our chart name. Helm unpacks the image to a folder with the chart name, but argo doesn't know the chart name only the image name. So argo tries to look for a folder with the image name, which does not exist.

**Comment by jessesuen** [comment] 2021-11-15 21:30
Thanks for the updates. Closing

**Closed by jessesuen** 2021-11-15 21:30 UTC
Labels: bug, cherry-pick/1.8
