### ISSUE TITLE
ArgoCD fails to compare app if ServiceCatalog CRD is installed in target cluster

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#650] opened 2018-09-26 20:38 UTC
Application controller fails to load list of `servicecatalog` CRD with following error:

```
unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request
```

Looks like `servicecatalog` is different from regular CRD and api server might fail with timeout. We should investigate why timeout is happening and find way to exclude such CRDs from app reconciliation loop.

**Comment by jessesuen** [comment] 2018-09-28 07:14
Only other place where I see this message happening is in: 
https://github.com/kubernetes-incubator/service-catalog/issues/2104

In that instance, the service catalog pod did not even start up correctly. So I believe the root cause of this issue is environmental. 

That said, we should still try to handle it gracefully.

**Comment by alexmt** [comment] 2018-09-28 16:41
Agree, as a next step want to try to get reproduce issue locally, see if we can reliably detect it (probably special error code etc) and gracefully handle it.

**Comment by jessesuen** [comment] 2019-01-16 08:03
Fixed in https://github.com/argoproj/argo-cd/pull/1018.

Duping to https://github.com/argoproj/argo-cd/issues/1015.

**Closed by jessesuen** 2019-01-16 08:03 UTC
Labels: 3, P1
