### ISSUE TITLE
Nightly build fails to open a manifest page of any resource (newer ending redirects)

### ISSUE THREAD

**Issue by RomanBats** [argoproj/argo-cd#11662] opened 2022-12-12 10:02 UTC
Checklist:

* [*] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [*] I've included steps to reproduce the bug.
* [*] I've pasted the output of `argocd version`.

**Describe the bug**

I am using a nightly build (quay.io/argoproj/argocd@sha256:4c673e99f1c07238b348e06d8b49a8f6b576c38ef79bcc235990660a1ea77332) of argocd. And it seems I cannot open manifest for any resource, whether it is a pod, config map, or Argo Application itself. It constantly redirects me to the same page which tries to open a manifest, which again redirects me and it goes round and round non-stop.
There are no errors from the server. But there are errors in the console.

**To Reproduce**

Open a manifest of any resource.

**Expected behavior**

The manifest screen could be opened 😄.

**Screenshots**
![image](https://user-images.githubusercontent.com/5024978/207013614-b0d0a329-ee44-47a6-99dc-90f2beadf9fc.png)

**Version**

```json
{
    "Version": "v2.6.0+b4c1281",
    "BuildDate": "2022-12-09T23:25:36Z",
    "GitCommit": "b4c12815f0131b337404e67534eca54004ba47de",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.9",
    "Compiler": "gc",
    "Platform": "linux/arm64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**
![image](https://user-images.githubusercontent.com/5024978/207014007-c3923557-6a2a-49f7-95dd-997f1af32264.png)
![image](https://user-images.githubusercontent.com/5024978/207017231-dc614d60-d6c6-4c2d-a868-4be16791e1a1.png)

**Comment by alexef** [comment] 2022-12-12 10:06
This is a duplicate of: https://github.com/argoproj/argo-cd/issues/11601 mostly caused by React upgrade which is now being rolled back.

**Closed by alexef** 2022-12-12 10:06 UTC
Labels: bug
