### ISSUE TITLE
 non-inclusive terms in argocd 

### ISSUE THREAD

**Issue by jsonmp-k8** [argoproj/argo-cd#5976] opened 2021-04-06 18:54 UTC
# Summary

Currently some terms like `NamespaceResourceWhitelist` are used within the argocd project and in most organizations these terms will be blocked in the future and they needs to be remediated. An example is given below

```
clusterResourceWhitelist:   []metav1.GroupKind{{Group: "", Kind: "Namespace"}},
remote: 57890021ac1f6cd2ef0bba0bb671afb84a4a1f78:controllers/superproject_controller.go:79:			NamespaceResourceWhitelist: []metav1.GroupKind{},
remote: 57890021ac1f6cd2ef0bba0bb671afb84a4a1f78:controllers/superproject_controller.go:80:			NamespaceResourceBlacklist: []metav1.GroupKind{},
remote: WARNING: content you are pushing contains a non-inclusive term such as 'slave', 'blacklist', or 'whitelist'; it is strongly recommended that you replace these terms whenever possible with alternatives such as 'secondary', 'blocklist', or 'allowlist.'
```

# Motivation

Use more inclusive terms 

# Proposal

instead of using  non-inclusive term such as 'slave', 'blacklist', or 'whitelist'; it is recommended to use terms such as 'secondary', 'blocklist', or 'allowlist.'

**Comment by sbose78** [comment] 2021-04-06 18:57
+1

**Comment by madhukiranbr** [comment] 2021-11-04 17:24
Any movement on this?

**Comment by sumantripuraneni** [comment] 2021-11-04 18:12
+1

**Comment by snuggie12** [comment] 2021-12-30 01:35
allow/block are not natural opposites (could easily be allow/deny, permit/block, etc). I don't think the replacement should be of lower quality than the original.

If you are going to make this change, my company started using `yeslist` and `nolist` as it removes all ambiguity should you only see one value. I know it's not standard but perhaps one could make it the new standard?

**Comment by blakepettersson** [comment] 2023-09-30 13:46
Duplicate of #12657

**Closed by blakepettersson** 2023-09-30 13:46 UTC
Labels: enhancement
