### ISSUE TITLE
Creating custom namespaces in a destination cluster

### ISSUE THREAD

**Issue by dlecina** [argoproj/argo-cd#6429] opened 2021-06-08 17:22 UTC
# Summary

Allow the creation of namespaces with some customization (at least labels) in a destination cluster, different from the one where Argo is located.

# Motivation

In our case, we want to add the `istio-injection=enabled` label to the created namespace of Applications which have a `destination` outside of the cluster where Argo is located. This is required for Istio to [automatically inject sidecars](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection) to pods inside the created namespace.

We would like to define the namespace in the same place as the Application, but Namespaces do not have a `destination` field, so we cannot do that, as the namespace would be created in the ArgoCD cluster, rather than the one containing the Application.

# Proposal

An option would be to allow some customization of the namespace created by the `CreateNamespace=true` syncOption:
Either in the `destination.namespace` or `syncOptions`, allow embedding the full definition of a Namespace resource. Tekton does a similar thing with their Tasks, where they allow you to either [reference](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#specifying-the-target-custom-task) a Task, or [embed one directly](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#specifying-a-custom-task-spec-in-line-or-embedded). Alternatively, at least allow including the labels to be added to the created namespace somehow.

The above proposal has an issue where, if different applications attempt to create the same namespace with different labels, the conflict would have to be resolved somehow. Perhaps a better proposal would be to have some sort of **Namespace extension CRD which does allow a `destination` field**. That way, it could be defined in a single place, independently of the Applications.

**Comment by maltyxx** [comment] 2021-06-09 07:39
Good idea !

**Comment by rafilkmp3** [comment] 2022-08-17 18:41
would be nice have it

**Comment by leoluz** [comment] 2022-11-08 19:50
This is a duplicate of https://github.com/argoproj/argo-cd/issues/4628
We are currently implementing this issue and is targeted to Argo CD 2.6

**Closed by leoluz** 2022-11-08 19:50 UTC
Labels: enhancement
