### ISSUE TITLE
Sync gets stuck on error despite newer commit existing - configurable timeout, or improved algorithm

### ISSUE THREAD

**Issue by erikschul** [argoproj/argo-cd#15642] opened 2023-09-22 22:40 UTC
# Summary
Sometimes a bad yaml is pushed, and ArgoCD encounters and error during syncing. A fix is pushed, but ArgoCD doesn't abort the current sync, which is stuck. 

Possibly related to: https://github.com/argoproj/argo-cd/discussions/6208

# Motivation
It seems to automatically abort/retry after about 5-10 minutes, but that's too long.

# Proposal
Perhaps the algorithm needs to abort and retry if a newer commit is available? 
Or there should be a configurable timeout where it aborts if no progress is made within 60s.

**Comment by aslafy-z** [comment] 2023-09-23 00:29
I believe this is a duplicate of https://github.com/argoproj/argo-cd/issues/11494

**Comment by crenshaw-dev** [comment] 2023-09-27 19:42
Let's close this in favor of the other, unless @erikschul has a reason to split the conversation.

**Closed by crenshaw-dev** 2023-09-27 19:42 UTC
Labels: enhancement
