### ISSUE TITLE
argocd doesn't pass subchart's values while the same works with parameters.

### ISSUE THREAD

**Issue by srinath92** [argoproj/argo-cd#17532] opened 2024-03-14 16:47 UTC
### Discussed in https://github.com/argoproj/argo-cd/discussions/17341

<div type='discussions-op-text'>

<sup>Originally posted by **srinath92** February 28, 2024</sup>
I'm using Argo App to deploy an app and pass in values file to a chart that has default values.yaml. The below doesn't work and it won't pick the values from the key `airflow`

Application.yaml
```
  source:
    chart: apache/airflow
    repoURL: europe-docker.pkg.dev/helm-charts
    targetRevision: 0.1.1
    helm:
      releaseName: airflow
      valueFiles:
        - values.yaml
``` 

values.yaml
```
dagRepository:
  name: "dags"
  branch: "main"
airflow:
  defaultAirflowTag: "2.6.3-python3.7"
  airflowVersion: "2.6.3"
  data:
    metadataConnection:
      host: prod-airflow-db
      db: airflow
dnsNames:
  flower: airflow-flower-nprod
  airflow: airflow-nprod
``` 

However if I move the above valueFile to parameters, the values are overridden and the chart deploys as expected.
```
  source:
    chart: apache/airflow
    repoURL: europe-docker.pkg.dev/helm-charts
    targetRevision: 0.1.1
    helm:
      releaseName: airflow
      parameters:
      - name: dagRepository.name
        value: "dags"
      - name: dagRepository.branch
        value: "main"
      - name: airflow.defaultAirflowTag
        value: "2.6.3-python3.7"
      - name: airflow.airflowVersion
        value: "2.6.3"
      - name: airflow.data.metadataConnection.host
        value: prod-airflow-db
      - name: airflow.data.metadataConnection.db
        value: airflow
      - name: dnsNames.airflow
        value: airflow-nprod
      - name: dnsNames.flower
        value: airflow-flower-nprod
```

I'm running argocd v2.8.9. Did I miss something here or is this a bug?

Just running `helm template . --values values.yaml` renders the chart properly. Not sure why argo wouldn't render the chart as expected using valueFiles

</div>

**Comment by yuvale322** [comment] 2024-04-22 07:20
I also faced this when I tried to deploy an application using umbrella chart (empty self-made chart with the real charts as dependancies). I solved this by putting the name of the dependency chart as the highest key in the values.yaml file:

```yaml
# Chart.yaml
apiVersion: v2
name: my-umbrella-chart
description: A Helm chart for ....
type: application
version: X.Y.Z
dependencies:
  - name: my-dependency-chart
    version: X.Y.Z
    repository: .....
```

```yaml
# values.yaml
my-dependency-chart:
  dagRepository:
    name: "dags"
    branch: "main"
  airflow:
    defaultAirflowTag: "2.6.3-python3.7"
    airflowVersion: "2.6.3"
    data:
      metadataConnection:
        host: prod-airflow-db
        db: airflow
  dnsNames:
    flower: airflow-flower-nprod
    airflow: airflow-nprod
```

I hope it helps :)

**Comment by gcaracuel** [comment] 2024-07-10 13:39
@yuvale322 workaround works only when dependency is set at Application CRD which is not always, real umbrella Charts do use pure Chart.yaml dependencies.

Only workaround we find is to use values field in the UI to override/change those parameters if you already using it instead of values-files field.

Helm parameters are supposed to be just `--set` flag when templating Helm chart and ArgoCD is not doing this in the normal Helm way because they behave in a different way when using dependencies. This is definitely an issue in ArgoCD that may be affecting many Helm users which do use dependencies which is in fact may feature of Helm over other templating systems.

**Comment by crenshaw-dev** [comment] 2024-07-10 16:33
> works only when dependency is set at Application CRD

I must be missing something, I don't think it's possible to set dependencies in the Application CRD. I believe they're always set in the chart contents.

**Comment by crenshaw-dev** [comment] 2024-07-10 16:36
@srinath92 `source.helm.valueFiles` files' locations are relative to the contents of the Helm chart. So in this case, Argo CD would expect `values.yaml` to be in the Helm chart itself. My guess is that you're expecting Argo CD to pick up `values.yaml` from a file adjacent to where you're storing the Application manifest. But the Application is evaluated by Argo CD as an independent resource in Kubernetes, not as a file on a filesystem.

Closing since I think the issue is based on a misunderstanding of how that field works. Will reopen if there's further explanation.

**Closed by crenshaw-dev** 2024-07-10 16:36 UTC
Labels: bug, component:applications-set, type:bug
