### ISSUE TITLE
Failed to verify app state WQVEWYBeIO: EOF when trying to use GitHub SSO

### ISSUE THREAD

**Issue by lzm0** [argoproj/argo-cd#7648] opened 2021-11-08 15:19 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After logged in with GitHub SSO, the page shows 
```
Failed to verify app state WQVEWYBeIO: EOF
```
However, using incognito mode or clearing Argo CD site data would fix this issue.

**To Reproduce**

This is a rare issue and cannot be easily reproduced. The application reached this state from a healthy state.

**Expected behavior**

Login should be successful and applications should show up.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.2.0+a912611
  BuildDate: 2021-10-26T01:29:43Z
  GitCommit: a912611b7a80931c4329ec9550658d0b65b89010
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd
```

**Logs**

```
time="2021-11-08T14:05:48Z" level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.0.11.202:6379: connect: connection refused"
time="2021-11-08T14:06:48Z" level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.0.11.202:6379: connect: connection refused"
time="2021-11-08T14:07:48Z" level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.0.11.202:6379: connect: connection refused"
time="2021-11-08T14:08:48Z" level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.0.11.202:6379: connect: connection refused"
time="2021-11-08T14:09:48Z" level=warning msg="Failed to resync revoked tokens. retrying again in 1 minute: dial tcp 10.0.11.202:6379: connect: connection refused"
```

**Comment by jessesuen** [comment] 2021-11-09 00:44
Duplicate of https://github.com/argoproj/argo-cd/issues/5873

We plan to remove the redis requirement for login flow. After https://github.com/argoproj/argo-cd/issues/5873 is implemented this should no longer happen.

**Closed by jessesuen** 2021-11-09 00:44 UTC
Labels: bug
