### ISSUE TITLE
Version dropdown not working on docs

### ISSUE THREAD

**Issue by drozd-A** [argoproj/argo-cd#12119] opened 2023-01-24 19:20 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Switching ArgoCD versions often does not work on the [docs site](https://argo-cd.readthedocs.io/en/stable/).

We have occasionally seen it work -- we cannot explain the conditions for it.

**To Reproduce**

1. Go to https://argo-cd.readthedocs.io/en/stable/
2. Try to switch ArgoCD versions

**Expected behavior**

You should be able to switch versions for ArgoCD documentation to see different versions of the docs

**Screenshots**

https://user-images.githubusercontent.com/48000208/214387631-5424f77a-ed39-4834-8cb2-5446c7e5fbc2.mov

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Aym3nTN** [comment] 2023-01-31 22:53
A weird finding, where it does work there is this "Error: No ad placements found" error that appears twice in the browser console; when it doesn't work that error only appears once. Maybe this observation could be helpful to debug this behavior.

<img width="461" alt="Screen Shot 2023-01-31 at 11 49 49 PM" src="https://user-images.githubusercontent.com/1928890/215902045-a18cc4a2-106c-41ab-9eeb-5a5ceb757e6a.png">

**Comment by jannfis** [comment] 2023-02-01 00:33
This is actually a dupe of https://github.com/argoproj/argo-cd/issues/11999

**Closed** 2023-02-01 00:33 UTC
Labels: bug
