### ISSUE TITLE
UI error with helm charts parameters

### ISSUE THREAD

**Issue by OpenSourceZombie** [argoproj/argo-cd#966] opened 2018-12-30 00:21 UTC
I'm getting the below error in the browser console when I try to view the parameters of a helm chart

```js
TypeError: "(intermediate value).map is not a function"
	i https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:6:59452
	ParametersPanel https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:72:197105
	On https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:45681
	Jn https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:57845
	Kn https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:58153
	fr https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:61535
	ur https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:61044
	sr https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:60870
	or https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:60242
	Zn https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:59601
	enqueueSetState https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:55:22974
	setState https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:47:997
	loadData https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:55:420375
	r https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:55:418426
	n https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:55:417732
	a https://127.0.0.1:8080/main.b56e71ccbcbf20bb841e.js:55:417496
```

argocd: v0.11.0-rc2+ff2de56
  BuildDate: 2018-12-28T00:21:20Z
  GitCommit: ff2de5654327f03cf200b7bcf5befa88f0f9841e
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v0.11.0-rc2+ff2de56
  BuildDate: 2018-12-28T00:20:53Z
  GitCommit: ff2de5654327f03cf200b7bcf5befa88f0f9841e
  GitTreeState: clean
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.0

**Comment by jessesuen** [comment] 2018-12-30 09:45
Are you able to share your values.yaml or a redacted version of it?

**Comment by jessesuen** [comment] 2019-01-03 00:30
Hmm I just hit this when installing the minio helm chart from github.com/helm/charts and customizing service type to be LoadBalancer. The issue seems intermittent since a refresh will work.

**Comment by alexmt** [comment] 2019-01-03 18:44
Fixed by https://github.com/argoproj/argo-cd-ui/commit/5f32cae938eba64dafb9c11f8589191e30cd79c2 . Bug can be reproduced by quickly switching between SUMMARY and PARAMETERS tab. React was trying to reuse same instance of `DataLoader` component. Due to this response from SUMMARY tab dataloader was used in PARAMETERS data loader

**Closed by alexmt** 2019-01-03 18:44 UTC
