### ISSUE TITLE
Add more detailed parameters to resource.exclusions

### ISSUE THREAD

**Issue by h3poteto** [argoproj/argo-cd#3415] opened 2020-04-15 07:29 UTC
# Summary

Add `name`, `annotations` or `labels` parameter to `resource.exclusions` argument.

# Motivation
I want to exclude some `Job` resources, so I tried to set `resource.exclusions`:

```yaml
apiVersion: v1
data:
  resource.exclusions: |
    - apiGroups:
      - "batch"
      kinds:
      - "Job"
      clusters:
      - "*"
kind: ConfigMap
```
But this parameter can only specify `apiGroup`, `kinds` and `clusters`, so it ignores all Job resources. I don't ignore all Job resources, I want to exclude only specific Jobs.

Next, I tried to specify `argocd.argoproj.io/hook: Skip` to the Jobs. This is the desired behavior, but the application status is `missing` and `OutOfSync`. 

# Proposal

Add `name`, `annotations` or `labels` to `FilteredResource`, and implement match functions.
https://github.com/argoproj/argo-cd/blob/476b09cbbf/util/settings/filtered_resource.go

**Comment by LeartBeqiraj** [comment] 2022-08-31 12:23
Is this supported yet?

**Comment by phj-incom** [comment] 2024-03-26 13:05
Any updates on this? I am using kyverno to replicate resources in other namespaces, and this is causing argocd to show the generated objects as out of sync.

**Comment by AurimasNav** [comment] 2024-09-16 14:18
Would be really nice to have for all these 3rd party product operators that do not care much about gitops style deployments (like https://github.com/actions/actions-runner-controller/issues/3533).

**Comment by agaudreault** [comment] 2024-09-18 23:37
Reading all the comments above, this feature is mainly used to improve argo performance by watching less resources that  are not required to show in the UI (things like Endpoints, EndpointSlice, kyverno PolicyReport, etc.) and are never expected to be created as code, such as resources created by Kubernetes controller.

If an Argo Application detects these resources and they are OutOfSync state, that would mean that these resources desired state is in git, or they are wrongly configured with the [tracking method](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/) argo is configured with, but their real desired state is what the controller applies. If they are in git, but they are expected to be created and managed by a controller, you should remove them from git (with kustomize patch delete if you are using kustomize). If you want to define them partially in git, but the controller overrides some necessary initial configurations, the [ignoreDifferences](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/) can be configured on the Application so the resources appear in the UI, but not out of sync. If they are caused by the tracking method, it is highly suggested to configure the tracking by annotation. If the controller adds that annotation to the object it creates, the controller behavior will need to be fixed.

**Comment by unknownbanana** [comment] 2024-09-19 07:06
> Reading all the comments above, this feature is mainly used to improve argo performance by watching less resources that are not required to show in the UI (things like Endpoints, EndpointSlice, kyverno PolicyReport, etc.) and are never expected to be created as code, such as resources created by Kubernetes controller.
> 
> If an Argo Application detects these resources and they are OutOfSync state, that would mean that these resources desired state is in git, or they are wrongly configured with the [tracking method](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/) argo is configured with, but their real desired state is what the controller applies. If they are in git, but they are expected to be created and managed by a controller, you should remove them from git (with kustomize patch delete if you are using kustomize). If you want to define them partially in git, but the controller overrides some necessary initial configurations, the [ignoreDifferences](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/) can be configured on the Application so the resources appear in the UI, but not out of sync. If they are caused by the tracking method, it is highly suggested to configure the tracking by annotation. If the controller adds that annotation to the object it creates, the controller behavior will need to be fixed.

For us there was no desired state in git, since the resources were generated based on a CRD. Yet Argo still picked up the generated resources and marked them as OutOfSync. We cannot be expected to have all resources in git at all times especially with controllers that generate resources based on CRs.

**Comment by agaudreault** [comment] 2024-09-19 18:30
@unknownbanana Can you validate that the resources created by the controllers, that are not in git, **don't** contain the configured Argo Tracking label/annotations? 

The fix here is to configure your deployed resources not to conflict with argo internal tracking and/or configure argo to use tracking by annotations.

Closing the issue because it can be resolved with existing configurations.

**Closed** 2024-09-19 18:31 UTC
Labels: enhancement, type:usability, component:core

**Comment by andreaf74** [comment] 2025-01-27 17:28
> [@unknownbanana](https://github.com/unknownbanana) Can you validate that the resources created by the controllers, that are not in git, **don't** contain the configured Argo Tracking label/annotations?
> 
> The fix here is to configure your deployed resources not to conflict with argo internal tracking and/or configure argo to use tracking by annotations.
> 
> Closing the issue because it can be resolved with existing configurations.

Not sure how  this is a fix for the issue.

In my case I'm creating an ACM Governance policy using ArgoCD and the Policy get replicated, as part of the processing, in the managed clusters' namespaces.

This cause ArgoCD to complains about resources OutOfSync.

This is not addressed by IgnoreExtraneous annotation, as it seem not be working across namespaces.
Nor by IgnoreDifferences spec as it refers only to specific fields  in a resource ( not the whole resource).
Nor by resource.exclusions as I cannot pin point a specific namespace nor a resource name.

And not sure how the resource tracking should be changed to address this as the extra resources , causing the OutOfSync, are not generated by argocd.

Wouldn't track by annotation ends up to the same results? as the resources is copied as a whole across namespaces... including annotations?

**Comment by candour** [comment] 2025-02-13 06:15
Another example I have is Clickhouse. When you install with the operator, a configmap named chi-storage-clickhouse is automatically created by the operator which appears as out of sync in ArgoCd.

I was able to "fix" this by manually removing the "argocd.argoproj.io/instance" label from the ConfigMap, but this is something that should be done on the ArgoCD side as an accompaniment to the various other "ignore" policies rather than as an ad-hoc post-hoc fix.

**Comment by unknownbanana** [comment] 2025-03-14 07:39
> [@unknownbanana](https://github.com/unknownbanana) Can you validate that the resources created by the controllers, that are not in git, **don't** contain the configured Argo Tracking label/annotations?
> 
> The fix here is to configure your deployed resources not to conflict with argo internal tracking and/or configure argo to use tracking by annotations.
> 
> Closing the issue because it can be resolved with existing configurations.

Unfortunately, or fortunately depending on your viewpoint, I cannot reproduce this because I highlighted the issue with our enablement team and they fixed the issue (without telling me how). I assume that the Argo operator was configured to track resources with certain annotations.

In either case, I still believe that this functionality should be available as api-groups, kinds and clusters cannot always be enough for Argo to ignore resources generated at runtime.
