### ISSUE TITLE
Repository Service api is not working -  https://cd.apps.argoproj.io/api/v1/repositories/{repo} 

### ISSUE THREAD

**Issue by Sarvesh001112** [argoproj/argo-cd#20823] opened 2024-11-18 11:46 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

When I hit Repository Service rest api https://cd.apps.argoproj.io/api/v1/repositories/{rep} in postman . No response is coming (404)

**Expected behavior**
Get Api Repository Service is not working .

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by Sarvesh001112** [comment] 2024-11-18 11:47
Plz solve this issue.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-18 16:52
We'll need more information like ArgoCD version, how do you get to querying the endpoint etc.

**Comment by crenshaw-dev** [comment] 2024-11-18 17:34
If you're literally hitting the demo instance, it's expected that you wouldn't get anything at that URL. There are no repositories configured on that instance.

**Comment by Sarvesh001112** [comment] 2024-11-19 06:40
Hi, 
I am using argocd (https://localhost:8083) all api are working properly and data is coming on postman but when I hit Repository Service rest api https://cd.apps.argoproj.io/api/v1/repositories/{rep} in postman . No response is coming (404).

I am using local Argo cd server.

[Argo cd screenshot .pdf](https://github.com/user-attachments/files/17810684/Argo.cd.screenshot.pdf)

**Comment by anandf** [comment] 2024-11-19 09:41
@Sarvesh001112 Could you use an url encoded value for the git repo you are trying to query. I tried this url and it worked. `https://localhost:8080/api/v1/repositories/https%3A%2F%2Fgithub.com%2Fanandf%2Fargocd-examples.git`
<img width="1154" alt="Screenshot 2024-11-19 at 3 10 16 PM" src="https://github.com/user-attachments/assets/fad304d5-6123-4459-b610-f8aa70de1cb8">

**Comment by anandf** [comment] 2024-11-19 09:45
@Sarvesh001112 This is not a bug IMO, feel free to close it, if the issue is resolved. Thanks.

**Comment by Sarvesh001112** [comment] 2024-11-19 15:07
Thankyou for help .

**Comment by Sarvesh001112** [comment] 2024-11-19 15:07
Thankyou

**Closed** 2024-11-19 15:07 UTC
Labels: bug, more-information-needed
