### ISSUE TITLE
ellipsis menu in list view should be right aligned instead of overflowing to the right

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-cd#11804] opened 2022-12-21 20:49 UTC
1. Visit https://cd.apps.argoproj.io/applications/argocd/argo-cd?view=list&resource=
2. Click the ⋮ at the far right of one of the rows
<img width="1806" alt="image" src="https://user-images.githubusercontent.com/2119212/209000066-a33e9b93-30e6-4e03-9b34-1fbff03a0a45.png">

Expected results: the menu should be fully visible.

You can work around this problem by shrinking the window, opening the menu and then growing the window:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/2119212/209000248-c45cff51-ed81-469a-838b-71dd31309fa6.png">

**Comment by alexef** [comment] 2022-12-22 07:38
closing as duplicate of https://github.com/argoproj/argo-cd/issues/11602

**Closed by alexef** 2022-12-22 07:38 UTC
Labels: bug, component:ui
