### ISSUE TITLE
argocd api create cluster sync app fail

### ISSUE THREAD

**Issue by ZacharyU-1** [argoproj/argo-cd#13536] opened 2023-05-10 18:15 UTC
### Discussed in https://github.com/argoproj/argo-cd/discussions/10121

<div type='discussions-op-text'>

<sup>Originally posted by **catsyuan** July 27, 2022</sup>
error：
Duration:           0s
Message:            ComparisonError: error getting openapi resources: unknown;ComparisonError: error getting openapi resources: unknown
FATA[0000] Operation has completed with phase: Error    

cluster 
status： Failed
DETAILS:  error getting openapi resources: unknown

I create cluster via api：/api/v1/clusters
and manual create  "argocd-manager" in namespace "kube-system" ，ClusterRole "argocd-manager-role"，ClusterRoleBinding "argocd-manager-role-binding" created </div>

**Comment by todaywasawesome** [comment] 2023-06-28 20:38
Duplicate of https://github.com/argoproj/argo-cd/issues/13571

**Closed by todaywasawesome** 2023-06-28 20:38 UTC
Labels: duplicate
