### ISSUE TITLE
Add support for patching Kustomize values for application/applicationset yaml to work more like helm values

### ISSUE THREAD

**Issue by ciantfv456** [argoproj/argo-cd#11906] opened 2023-01-07 21:44 UTC
Why can't Kustomize values be patched like helm values
```yaml
spec:
  sources:
    - repoURL: https://github.com/helm/charts
      targetRevision: master
      path: foo/app
      kustomize:
        patch: |-
          - op: add
            path: /spec/foo
            value: bar
```
Or something like that.

Use case: 
Having an applicationset with a git generator that will change the application values by the generators values

**Comment by acelinkio** [comment] 2023-08-06 17:21
This is a duplicate of https://github.com/argoproj/argo-cd/issues/5114 and is fixed by https://github.com/argoproj/argo-cd/pull/14648

**Closed** 2023-08-07 14:45 UTC
Labels: enhancement
