### ISSUE TITLE
Application sync hang with "unable to fork off sideband demultiplexer"

### ISSUE THREAD

**Issue by ralfovelgoenne** [argoproj/argo-cd#9888] opened 2022-07-06 15:06 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Moving from ArgoCD 2.2.5 to 2.4.3. After that application gets stuck in sync with:
rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force` failed exit status 128: error: cannot create async thread: Operation not permitted fatal: fetch-pack: unable to fork off sideband demultiplexer

Connection status for all repositories is successful.

**To Reproduce**

**Expected behavior**

Same configuration used as in version 2.2.5. Before moving to 2.4.3 everything works normally. 

**Screenshots**

**Version**
2.4.3 (Helm chart 4.9.11):
{
    "Version": "v2.4.3+471685f",
    "BuildDate": "2022-06-27T21:02:55Z",
    "GitCommit": "471685feae063c1c2e36a5ff268c4da87c697b85",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

**Logs**

```
Paste any relevant application logs here.
```

**Comment by todaywasawesome** [comment] 2022-07-06 17:51
This could be a memory issue or a network issue. I haven't seen anyone else post this bug yet. 

Can you add more logs?

**Comment by ralfovelgoenne** [comment] 2022-07-06 18:56
Output from log of the repo-server, nothing really new:
![grafik](https://user-images.githubusercontent.com/8797158/177621813-29ea0dad-5bb2-46db-b589-f4d86f2174f5.png)

I also thought about a memory or network issue. I already raised memory limits for all pods comparing to the running status with version 2.2.5. Normally there were no network issues with version 2.2.5. 

What I did compared to the setup of 2.2.5 (Helm chart 3.33.8) is:
- Disabled Application Set controller
- Disabled Notifications controller
- Set: env: name: "ARGOCD_GPG_ENABLED", value: "false" - otherwise I got an GPG error during start

**Comment by nice-pink** [comment] 2022-08-22 09:22
I'm encountering the same issue only by setting ARGOCD_GPG_ENABLED as described in: https://argo-cd.readthedocs.io/en/stable/user-guide/gpg-verification/.
Tried with v2.3.6, v2.3.7, v.2.4.5

**Comment by nice-pink** [comment] 2022-08-22 09:34
@ralfovelgoenne are you experiencing this issue https://github.com/argoproj/argo-cd/issues/9809 when not adding the `ARGOCD_GPG_ENABLED` env var? Do you already found a fix?

**Comment by ralfovelgoenne** [comment] 2022-08-22 11:27
Thanks for the input. I will try out setting ARGOCD_GPG_ENABLED to true and give feedback.
I do not have a solution yet. I moved to version v2.4.7+81630e6. With this version and the same parameter values as before it does work on 2 environments as expected, but on one environments it still fails with this error.

**Comment by ralfovelgoenne** [comment] 2022-08-22 17:57
I tried out to not adding the ARGOCD_GPG_ENABLED env var. I got the same error as mentioned in [https://github.com/argoproj/argo-cd/issues/9809].

**Comment by ralfovelgoenne** [comment] 2022-08-22 18:04
@nice-pink: I did not get the meaning of this part of your post:
> This error is only shown for apps running in the same cluster and with code from the same git repo.

**Comment by nice-pink** [comment] 2022-08-23 07:02
> @nice-pink: I did not get the meaning of this part of your post:
> 
> > This error is only shown for apps running in the same cluster and with code from the same git repo.

I use the same Argo CD instance to manage multiple clusters. There is one repository containing the manifests for each cluster. Only the apps which are running in the same cluster than the Argo CD instance with their manifests saved in the same repository as the ones from Argo CD are showing the error "unable to fork off sideband demultiplexer". All other apps are synced properly.

**Comment by mdsjip** [comment] 2022-08-24 16:43
Changing `22.04` to `20.04` [here](https://github.com/argoproj/argo-cd/blob/master/Dockerfile#L1) fixed this issue for me.

**Comment by denysvitali** [comment] 2022-10-07 15:14
Doesn't work with:

- `v2.2.14`
- `v2.2.12`

Works with:

- `v2.2.5`
- `v2.2.9`
- `v2.2.11`

Therefore, something happened between v2.2.11 and v2.2.12

### v2.2.11

```
argocd@argocd-repo-server-v2.11 $ git --version
15:08:35.903602 git.c:444               trace: built-in: git version
git version 2.30.2

argocd@argocd-repo-server-v2.11 $ ldd $(which git)
	linux-vdso.so.1 (0x00007ffd4d59f000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f6918811000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f69187f5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f69187d3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69185e7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6918c27000)

argocd@argocd-repo-server-v2.11 $ dpkg-query -l libc6 git gpg gpg-agent
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version           Architecture Description
+++-==============-=================-============-=====================================================
ii  git            1:2.30.2-1ubuntu1 amd64        fast, scalable, distributed revision control system
ii  gpg            2.2.20-1ubuntu3   amd64        GNU Privacy Guard -- minimalist public key operations
ii  gpg-agent      2.2.20-1ubuntu3   amd64        GNU privacy guard - cryptographic agent
ii  libc6:amd64    2.33-0ubuntu5     amd64        GNU C Library: Shared libraries
```

### v2.2.12

```
argocd@argocd-repo-server-v2.12 $ git --version
15:12:14.779580 git.c:455               trace: built-in: git version
git version 2.34.1

argocd@argocd-repo-server-v2.12 $ ldd $(which git)
	linux-vdso.so.1 (0x00007ffeb5bae000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f2fbe15a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2fbe13e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2fbdf16000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2fbe598000)

argocd@argocd-repo-server-v2.12 $ dpkg-query -l libc6 git gpg gpg-agent
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version             Architecture Description
+++-==============-===================-============-=====================================================
ii  git            1:2.34.1-1ubuntu1.4 amd64        fast, scalable, distributed revision control system
ii  gpg            2.2.27-3ubuntu2.1   amd64        GNU Privacy Guard -- minimalist public key operations
ii  gpg-agent      2.2.27-3ubuntu2.1   amd64        GNU privacy guard - cryptographic agent
ii  libc6:amd64    2.35-0ubuntu3.1     amd64        GNU C Library: Shared libraries
```

---

Given the issue with `fork`, the missing libpthread linking is a good source for investigation

**Comment by denysvitali** [comment] 2022-10-07 16:04
Git cloning from `bitnami/git:2.30.2` works, same for `bitnami/git:2.34.1`

Both seems to be linked against `libpthread`, so this might be a distro issue:
```
bitnami@git-test-54846d9cf4-hcjmq:~$ git --version
git version 2.34.1
bitnami@git-test-54846d9cf4-hcjmq:~$ ldd $(which git)
	linux-vdso.so.1 (0x00007ffcc8fdd000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0a04169000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0a0415f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0a0413e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0a03f7d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0a047b2000)
```

**Comment by denysvitali** [comment] 2022-10-07 16:07
Oh and btw, between v2.2.11 and v2.2.12 the ArgoCD base image was updated in 44d8cb8bedec9c9064a637a1d8ec039792085cca:

```diff
diff --git a/Dockerfile b/Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,137 +1,137 @@
-ARG BASE_IMAGE=docker.io/library/ubuntu:21.04
+ARG BASE_IMAGE=docker.io/library/ubuntu:22.04
 ####################################################################################################
 # Builder image
 # Initial stage which pulls prepares build dependencies and CLI tooling we need for our final image
 # Also used as the image in CI jobs so needs all dependencies
 ####################################################################################################
 FROM docker.io/library/golang:1.16.11 as builder
```

**Comment by denysvitali** [comment] 2022-10-07 16:45
With this minimal `Dockerfile` I've created a somehow reproducible environment:

```Dockerfile
ARG VERSION=21.04
FROM ubuntu:$VERSION
COPY ./old-ubuntu-fix.sh /usr/bin/old-ubuntu-fix.sh
RUN chmod 755 /usr/bin/old-ubuntu-fix.sh && old-ubuntu-fix.sh
RUN apt update && apt install -y git && rm -rf /var/cache/apt/
RUN useradd user
USER 1000
```

`old-ubuntu-fix.sh`:

```bash
#!/bin/bash
set -x
UBUNTU_VERSION=$(cat /etc/lsb-release  | grep DISTRIB_RELEASE | cut -d = -f 2)

if [ "$UBUNTU_VERSION" == "21.04" ]; then
  sed -i -E 's/http:\/\/releases.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
  sed -i -E 's/http:\/\/archive.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
  sed -i -E 's/http:\/\/security.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
fi
```

Using as `VERSION`s:
- `21.04`
- `22.04`

### `21.04`

```
$ git clone ssh://...
...
Resolving deltas: 100% (348/348), done.
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
$ git --version
git version 2.30.2
$ ldd $(which git)
	linux-vdso.so.1 (0x00007ffe6ecf8000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fd41fcde000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd41fcc2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd41fca0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd41fab4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd4200f3000)
```

### `22.04`

```
$ git --version
git version 2.34.1
$ git clone ssh://...
Cloning into 'gitops'...
error: cannot create async thread: Operation not permitted
fatal: fetch-pack: unable to fork off sideband demultiplexer

$ ldd $(which git)
	linux-vdso.so.1 (0x00007fffd3bdf000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f9866c42000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9866c26000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f98669fe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f986707f000)

$ dpkg-query -l git
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version             Architecture Description
+++-==============-===================-============-===========================>
ii  git            1:2.34.1-1ubuntu1.4 amd64        fast, scalable, distributed
```

This effectively confirms that:

- The issue happens with a Docker Image based on Ubuntu 22.04 (when running on a `Ubuntu 16.04.7 LTS` / VMware Tanzu host?)
- The `git` binary without `libpthread` causes the issue
- The `git` version doesn't really matter (bitnami's git worked well there, but libpthread was present on the image I've tried)
- It seems to be an issue caused (or visible only) by missing linked library.

Now the question is:

- Is it really an issue with VMware Tanzu as an host? Can someone test this somewhere else?
- Where should we file this bug?
- Is this something that's already known to the Ubuntu /  VMware community?

**Comment by denysvitali** [comment] 2022-10-11 16:54
Opened an issue to the Ubuntu tracker, hopefully they can provide more insights:
https://bugs.launchpad.net/ubuntu/+bug/1992485

**Comment by yonahd** [comment] 2022-10-27 13:37
I got this issue when I set ARGOCD_GPG_ENABLED", value: "false"
Only in the repo server and not in the other deployments

**Comment by YanzhaoLi** [comment] 2022-11-02 06:02
@denysvitali  Have you tested your 22.04 images well against the vanilla ubuntu 16.04?    Looks like the ldd command in the container doesn't show libpthread. 
```
$ ldd $(which git)
	linux-vdso.so.1 (0x00007fffd3bdf000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f9866c42000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9866c26000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f98669fe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f986707f000)
```

> With this minimal `Dockerfile` I've created a somehow reproducible environment:
> 
> ```dockerfile
> ARG VERSION=21.04
> FROM ubuntu:$VERSION
> COPY ./old-ubuntu-fix.sh /usr/bin/old-ubuntu-fix.sh
> RUN chmod 755 /usr/bin/old-ubuntu-fix.sh && old-ubuntu-fix.sh
> RUN apt update && apt install -y git && rm -rf /var/cache/apt/
> RUN useradd user
> USER 1000
> ```
> 
> `old-ubuntu-fix.sh`:
> 
> ```shell
> #!/bin/bash
> set -x
> UBUNTU_VERSION=$(cat /etc/lsb-release  | grep DISTRIB_RELEASE | cut -d = -f 2)
> 
> if [ "$UBUNTU_VERSION" == "21.04" ]; then
>   sed -i -E 's/http:\/\/releases.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
>   sed -i -E 's/http:\/\/archive.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
>   sed -i -E 's/http:\/\/security.ubuntu.com\/ubuntu/http:\/\/old-releases.ubuntu.com\/ubuntu/g' /etc/apt/sources.list
> fi
> ```
> 
> Using as `VERSION`s:
> 
> * `21.04`
> * `22.04`
> 
> ### `21.04`
> ```
> $ git clone ssh://...
> ...
> Resolving deltas: 100% (348/348), done.
> $ cat /etc/lsb-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=21.04
> DISTRIB_CODENAME=hirsute
> DISTRIB_DESCRIPTION="Ubuntu 21.04"
> $ git --version
> git version 2.30.2
> $ ldd $(which git)
> 	linux-vdso.so.1 (0x00007ffe6ecf8000)
> 	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fd41fcde000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd41fcc2000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd41fca0000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd41fab4000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fd4200f3000)
> ```
> 
> ### `22.04`
> ```
> $ git --version
> git version 2.34.1
> $ git clone ssh://...
> Cloning into 'gitops'...
> error: cannot create async thread: Operation not permitted
> fatal: fetch-pack: unable to fork off sideband demultiplexer
> 
> $ ldd $(which git)
> 	linux-vdso.so.1 (0x00007fffd3bdf000)
> 	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f9866c42000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9866c26000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f98669fe000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f986707f000)
> 
> $ dpkg-query -l git
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name           Version             Architecture Description
> +++-==============-===================-============-===========================>
> ii  git            1:2.34.1-1ubuntu1.4 amd64        fast, scalable, distributed
> ```
> 
> This effectively confirms that:
> 
> * The issue happens with a Docker Image based on Ubuntu 22.04 (when running on a `Ubuntu 16.04.7 LTS` / VMware Tanzu host?)
> * The `git` binary without `libpthread` causes the issue
> * The `git` version doesn't really matter (bitnami's git worked well there, but libpthread was present on the image I've tried)
> * It seems to be an issue caused (or visible only) by missing linked library.
> 
> Now the question is:
> 
> * Is it really an issue with VMware Tanzu as an host? Can someone test this somewhere else?
> * Where should we file this bug?
> * Is this something that's already known to the Ubuntu /  VMware community?

**Comment by denysvitali** [comment] 2022-11-02 06:20
> @denysvitali  Have you tested your 22.04 images well against the vanilla ubuntu 16.04?    Looks like the ldd command in the container doesn't show libpthread. 

As per my comment above: yes, `ubuntu:22.04` from Docker (+ `apt-get install -y git`) shows that `libpthread` is missing.

This might (or might not) be the source of the problem. The strange thing is that it faiks only in a TKGi environment, for some reason.

**Comment by binboum** [comment] 2023-01-16 08:52
After having the same problem, it would come from the version of docker/containerd which is deployed.

The new GLIBC library in 22.04 uses CLONE3 for syscal which is not supported by SECCOMP profile older versions of Docker.

Workaround:

- Use base image 20.04
- Update docker/containerd

**Comment by jgwest** [comment] 2024-02-15 16:32
Closing as appears to be an OS version issue based on issue comments, rather than anything specific to Argo CD.

**Closed by jgwest** 2024-02-15 16:32 UTC
Labels: bug, help wanted, inquiry
