### ISSUE TITLE
fails to parse json when argocd handle jsonnet with a shared libary

### ISSUE THREAD

**Issue by foxracle** [argoproj/argo-cd#4541] opened 2020-10-13 06:59 UTC
I follow the step from this page to deploy jsonnet withe argocd:
https://github.com/prometheus-operator/kube-prometheus/tree/master/examples/continuous-delivery/argocd

argocd version:
I tried both 1.7.3 and 1.7.7, both can not work

**Describe the bug**
here is my content of my git. and the vendor dir and json files(jsonnetfile.json and jsonnetfile.lock.json) are created with jb install command:
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.6
.
├── kube-prometheus
│   ├── dm.jsonnet
│   ├── jsonnetfile.json
│   ├── jsonnetfile.lock.json
│   └── vendor

here is sample of definition of argocd application:

directory:
    recurse: true
    jsonnet:
      libs:
        - kube-prometheus/vendor

**error message:**
message: |-
      rpc error: code = FailedPrecondition desc = Failed to unmarshal "jsonnetfile.json": Object 'Kind' is missing in '{
        "version": 1,
        "dependencies": [
          {
            "source": {
              "git": {
                "remote": "https://github.com/prometheus-operator/kube-prometheus.git",
                "subdir": "jsonnet/kube-prometheus"
              }
            },
            "version": "release-0.6"
          }
        ],
        "legacyImports": true
      }'
    type: ComparisonError

after I deleted the two json files in the  kube-prometheus dir, the same error appeared but for different json files in the vendor dir which created with jb command.
it seems that argocd treats all json files found as k8s source?

**error message:**
status:
  conditions:
    - lastTransitionTime: '2020-10-13T06:42:57Z'
      message: >-
        rpc error: code = FailedPrecondition desc = Failed to unmarshal
        "jsonnetfile.json": Object 'Kind' is missing in '{
          "dependencies": [
            {
              "source": {
                "git": {
                  "remote": "https://github.com/grafana/grafonnet-lib",
                  "subdir": "grafonnet"
                }
              },
              "version": "master",
              "name": "grafonnet"
            },
            {
              "source": {
                "git": {
                  "remote": "https://github.com/ksonnet/ksonnet-lib",
                  "subdir": ""
                }
              },
              "version": "master",
              "name": "ksonnet"
            }
          ],
          "legacyImports": true
        }'
      type: ComparisonError

**Comment by jessesuen** [comment] 2020-10-13 20:46
Duplicate of https://github.com/argoproj/argo-cd/issues/4432. Will be fixed in 1.7.8.

**Closed** 2020-10-13 20:46 UTC
Labels: bug, duplicate

**Comment by peterbean410** [comment] 2022-01-19 05:51
This error happens again in my settings (v2.2), can we reopen this issue?
