### ISSUE TITLE
Support for helm chart and values.yaml located in separated repos

### ISSUE THREAD

**Issue by likaiwen123** [argoproj/argo-cd#3988] opened 2020-07-23 11:12 UTC
# Summary

Currently, we have to put chart.yaml and values.yaml together in a repo, as [doc](https://argoproj.github.io/argo-cd/user-guide/helm/#values-files) says. 

However, we want support for tracking two repos, one for helm chart (maybe a helm repo) and the other for values.yaml (a git repo).

# Motivation

We have established our only helm repo and saved our charts there. Currently, we are considering to use argo-cd to automatically deploy the charts to multiple clusters, and there are one values.yaml for each cluster. We don't want to move out the chart from our chart repo and store with the multiple values.yaml files.

We have tried the `--values-literal-file` option, but argo-cd seems to just insert the file into the application configuration, and therefore the changes of the values.yaml will not be tracked.

Besides, we are switching to the [helm registry](https://helm.sh/docs/topics/registries/), and the charts will be saved as OCI storage. According to [issue 3349](https://github.com/argoproj/argo-cd/issues/3349), this feature may be supported in version 1.7. At that time, the values.yaml will not be able to be stored with helm charts. So tracking two repos is requied.

# Proposal

Currently for the helm repo (not helm registry) and git repo, just add an option to track the chart repo (the original feature) and the values git repo. And users have to specify the location of the values.yaml for the app. 

When the chart repo or the values repo changed, mark the app as unsynced. And when re-deploy the app, the values.yaml should be re-downloaded.

**Comment by myspotontheweb** [comment] 2020-11-08 17:22
Could I suggest an alternative that would require no ArgoCD modifications? In a nutshell, use an Argo CD "Application" object to record the helm settings for each deployment. 

Here's what we do:

**Helm Charts** 

Our Helm charts are stored alongside the source code. So, the release of each helm chart is managed in lock-step with the code it deploys.  This idea is not mandatory, could just as easily use a separate repo to manage the helm charts. 

**ArgoCD deployment**

Deployment configuration is managed in a separate repository, which leverages to the ArgoCD "Application" custom resource to record the helm settings:

 ```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-project1
  destination:
    namespace: demo-project1-namespace 
    server: https://kubernetes.default.svc
  source:
    path: chart
    repoURL: git@github.com:myorg/demo-app1.git
    targetRevision: master
    helm:
      values: |
        env:
           ONE: "1"
           TWO: "1"
           THREE: "1"
```

**Cluster bootstrapping**

All the application declarations, stored in our gitops repository can be deployed on a target cluster using the ["App of Apps" pattern](https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/). We have a directory of applications, for each region (could alternatively use branches).

```
REGION=US

argocd app create apps --repo git@github.com:myorg/gitops-repo.git \
                       --path apps/$REGION \
                       --dest-server https://kubernetes.default.svc \
                       --dest-namespace default \
                       --sync-policy automated \
                       --self-heal \
                       --auto-prune
```

**Comment by kenske** [comment] 2020-12-16 21:12
| Could I suggest an alternative?

This seems like a workaround. Embedding configuration that could get pretty complicated inside another yaml file feels like a very fragile approach.

**Comment by sfatgc** [comment] 2021-02-05 17:09
Hey all!

Is there any progress on this issue?

We wish to use third party helm charts from third party git repos, providing them with our value files, in the way like this: 
```
source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.1.3
    helm:
      version: 1.1.3
      valueFiles:
        - helm-values.yaml
```

So requirement to put value files to the same repo as chart looks like a huge functionality restriction.

And yes - I give +1 for the point, about embedding complicated values structure into application manifest file. It looks like really ugly workaround in that case.

**Comment by likaiwen123** [comment] 2021-02-06 05:24
Maybe the methods above can act as workaround for this issue, but may not be that elegant. So could any maintainers or contributors express their considerations?

**Comment by sidewinder12s** [comment] 2021-05-21 01:43
Another reason to support values somewhere else, you cannot use the kustomized helm plugin if you have any helm parameter in the ArgoCD Application.

**Comment by bzlom** [comment] 2021-06-04 15:15
Also would like to see this feature request implemented, a lot of us use remotely stored Helm charts for easier upgrade maintenance process (especially when you are using lots of helm charts for different parts of your infrastructure).

**Comment by rouke-broersma** [comment] 2021-07-21 12:04
+1 we need this

**Comment by likaiwen123** [comment] 2021-07-21 15:51
Then with so many users posting their feature request on this, would developers make a response please? @andrei-dascalu or some other people?

**Comment by seizadi** [comment] 2021-07-22 23:23
I landed with this issue trying to get a PoC to work for our production environment. Since I can not share the details of our production environment and demonstrate the issues I made a public repos:
https://github.com/seizadi/cmdb
https://github.com/seizadi/dc-repo

I wanted to be able to add the two repos:
```bash
argocd repo add https://github.com/seizadi/cmdb --name cmdb
argocd repo add https://github.com/seizadi/dc-repo --name dc-repo
```

Add additional parameters for tracking the values from the dc-repo when creating an application:
```bash
argocd app create cmdb --repo https://github.com/seizadi/cmdb --path repo/cmdb --dest-server https://kubernetes.default.svc --dest-namespace cmdb --values-repo https://github.com//seizadi/dc-repo --values-path build/prod/seizadi-eks/cmdb.yaml
```

If we can agree on the proposal, I would be intersted in submitting a PR for this change.

**Comment by rouke-broersma** [comment] 2021-07-23 08:46
We use app-of-apps to provision all your helm apps. Ideally I would want to be able to reference a file sitting right next to the application manifest in the git repo and have argocd understand that they should do something with that values file when deploying the helm application manifest.

**Comment by seizadi** [comment] 2021-07-23 14:58
@rouke-broersma, If I understand your requirements, for your use case you would specify the --values-repo parameter to be the same value as your --repo parameter when creating an application.

**Comment by rouke-broersma** [comment] 2021-07-23 15:03
Yep we could do that, but the issue is that the values used could be out of sync with the sync action argo is doing at the moment. Argo could be sync'ing an application with the values from a later commit.

To fix this argo should be able to 'understand' using the same commit sha for the target revision as the commit sha used to create/update the argo application.

**Comment by seizadi** [comment] 2021-07-23 15:12
@rouke-broersma, You have a revision for the  chart repo and a revision for value repo, in your use case you need to set them to the same git commit e.g. tag or commit to get that desired behavior. In the above command line where I did not specify the revision it would track latest in main.

**Comment by rouke-broersma** [comment] 2021-07-23 15:41
@seizadi It is not the chart revision and the values.yaml revision that need to be the same. It is the gitops repo revision and the values.yaml revision that need to be the same.

It is like this:

- helm OCI repo
-- ingress chart: 3.2.1
-- ingress chart: 3.2.2

- gitops repo
-- commit 12345abcde
-- ingress application references ingress helm chart 3.2.1
-- ingress application references values.yaml in repo: this, with revision: main
-- values.yaml for ingress helm chart 3.2.1

- Argocd gitops repo application
-- sync revision 12345abcde
--- Update ingress application to revision 12345abcde referencing ingress helm chart 3.2.1
--- Use values.yaml revision main

- gitops repo
-- commit 67890fghij
-- ingress application references ingress helm chart 3.2.2
-- ingress application references values.yaml in repo: this, with revision: main
-- values.yaml for ingress helm chart 3.2.2

- Argocd ingress application
-- sync revision 3.2.1
-- use values.yaml from gitops repo with revision main (commit 67890fghij)

Now the wrong values.yaml is used for this deployment.

This is how I would want to see it:

- helm OCI repo
-- ingress chart: 3.2.1
-- ingress chart: 3.2.2

- gitops repo
-- commit 12345abcde
-- ingress application references ingress helm chart 3.2.1
-- ingress application references values.yaml in repo: this, with revision: same-as-application
-- values.yaml for ingress helm chart 3.2.1

- Argocd gitops repo application
-- sync revision 12345abcde
--- Update ingress application to revision 12345abcde referencing ingress helm chart 3.2.1
--- Use values.yaml revision: 12345abcde

- gitops repo
-- commit 67890fghij
-- ingress application references ingress helm chart 3.2.2
-- ingress application references values.yaml in repo: this, with revision same-as-application
-- values.yaml for ingress helm chart 3.2.2

- Argocd ingress application
-- sync revision 3.2.1
-- use values.yaml from gitops repo with revision: 12345abcde

**Comment by seizadi** [comment] 2021-07-25 03:43
@hi-usui Thx for the link to PR
https://github.com/argoproj/argo-cd/pull/6280
It looks like it addresses my issuses.

**Comment by jessesuen** [comment] 2021-09-30 22:50
Duplicating to https://github.com/argoproj/argo-cd/issues/2789

**Closed by jessesuen** 2021-09-30 22:50 UTC
Labels: enhancement
