### ISSUE TITLE
How to rename the argocd application name? Eg. I put the application name in the test I want to rename the application like test into dev?

### ISSUE THREAD

**Issue by tamilsaran** [argoproj/argo-cd#8307] opened 2022-01-28 11:52 UTC
### Discussed in https://github.com/argoproj/argo-cd/discussions/8305

<div type='discussions-op-text'>

<sup>Originally posted by **tamilsaran** January 28, 2022</sup>
How to rename the argocd application name? Eg. I put the application name in the test I want to rename the application like test into dev?</div>

**Comment by jannfis** [comment] 2022-01-28 13:41
Closing as duplicate of #8305. Please not open a discussion and an issue for the same topic. Thanks.

**Closed by jannfis** 2022-01-28 13:41 UTC
