### ISSUE TITLE
argocd-test-server does not get removed/deleted upon user interruption signal(Ctrl+c)

### ISSUE THREAD

**Issue by iam-veeramalla** [argoproj/argo-cd#4969] opened 2020-12-03 20:18 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
argocd-test-server does not get removed/deleted upon user interruption signal(Ctrl+c)

**To Reproduce**
`make start` wait for all the processes to come up. Once done, Use Ctrl+c to stop/Interrupt/terminate the processes.

**Expected behavior**
Remove all argo processes and containers

**Screenshots**
* User Interruption Signal
<img width="967" alt="Screenshot 2020-12-04 at 1 29 49 AM" src="https://user-images.githubusercontent.com/43399466/101082817-16fcc280-35d2-11eb-9d40-d8eec26e14f6.png">
* Argo Running Process after Users Interruption signal
<img width="1440" alt="Screenshot 2020-12-04 at 1 30 17 AM" src="https://user-images.githubusercontent.com/43399466/101082859-2a0f9280-35d2-11eb-9da4-f86c8d72754d.png">
* Running Docker Container
<img width="1440" alt="Screenshot 2020-12-04 at 1 30 38 AM" src="https://user-images.githubusercontent.com/43399466/101082865-2e3bb000-35d2-11eb-985e-3130b7832984.png">

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment] 2020-12-03 21:53
I think the issue is that `make start` is just a `docker run`, which if Control+C'd will not `docker kill` the started container(s). So we should trap Control+C and then do a docker kill.

**Comment by iam-veeramalla** [comment] 2020-12-04 02:32
> I think the issue is that `make start` is just a `docker run`, which if Control+C'd will not `docker kill` the started container(s). So we should trap Control+C and then do a docker kill.

Exactly !! Will have a look

**Comment by iam-veeramalla** [comment] 2020-12-04 03:42
I will raise a PR for this

**Comment by iam-veeramalla** [comment] 2020-12-08 03:26
@jessesuen  I see a couple of problems here ... we need to trap the SIGINT signal for the terminal where `make start` is initiated. 

1. If the underlying OS is windows, we will not be able to achieve this.
2. trap for SIGINT will remain forever in that terminal, This might cause an unintentional termination of argo-test-server running in other terminals when Ctrl+C'ed for other purposes.

I think we need to think of a different approach here.

**Comment by jannfis** [comment] 2020-12-08 11:53
I think the problem is, that our container has an entrypoint script which `exec`'s GNU make, effectively having `make` becoming PID 1 in the container. Since Linux handles PID 1 special regarding signals, the signal is passed down to the children of the `make` process, but does nothing for the PID 1 process itself.

The specific code can be found here: https://github.com/argoproj/argo-cd/blob/6b8867a582cdf9e6054983925fb5b933fd96ebda/test/container/uid_entrypoint.sh#L12

The fix is to replace `exec "$@"` by a simple `"$@"` - so that the spawned `make` does not replace the entrypoint script's process, but gets forked.

**Comment by jannfis** [comment] 2020-12-08 13:54
Just for future reference:

>     1. If the underlying OS is windows, we will not be able to achieve this.

IMHO, we should not make too much assumptions about Windows being used as a development environment. If anyone uses Windows as dev environment for Argo CD, they surely be using WSL.

**Comment by iam-veeramalla** [comment] 2020-12-09 20:54
> Just for future reference:
> 
> > ```
> > 1. If the underlying OS is windows, we will not be able to achieve this.
> > ```
> 
> IMHO, we should not make too much assumptions about Windows being used as a development environment. If anyone uses Windows as dev environment for Argo CD, they surely be using WSL.

Agree !!  Let me make create a PR for this and get this fixed.

**Comment by jannfis** [comment] 2020-12-10 07:05
Fixed via #5018

**Closed by jannfis** 2020-12-10 07:05 UTC
Labels: bug, component:test
