### ISSUE TITLE
Argocd doesn't use dest-server for Helm lookup function

### ISSUE THREAD

**Issue by ToxicWar** [argoproj/argo-cd#3661] opened 2020-05-27 14:37 UTC
**Describe the bug**

Argocd raises exception while trying to install the `couchbase-operator` Helm chart.

I suspect it because Argocd doesn't use dest-server for Helm lookup function and try to lookup `in-cluster` with a default service account (system:serviceaccount:argocd:default).
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

**To Reproduce**

Try to install couchbase-operator (https://github.com/couchbase-partners/helm-charts/tree/master/couchbase-operator)

```shell
argocd app create  --name=couchbase-operator  --project couchbase-operator  --repo https://github.com/couchbase-partners/helm-charts.git    --path couchbase-operator  --revision HEAD  --release-name couchbase-operator  --values values.yaml  --dest-server https://aks-my-dev-cluster-87654321.hcp.southeastasia.azmk8s.io:443  --dest-namespace couchbase-operator
```

**Expected behavior**

Helm lookup function should check resources in dest-cluster, and the chart should be installed successfully after that. 

**Version**

```shell
argocd: v1.5.1+8a3b36b
  BuildDate: 2020-04-06T15:53:49Z
  GitCommit: 8a3b36bd28fe278f7407b9a8797c79ad859d1acd
  GitTreeState: clean
  GoVersion: go1.14
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.12.3
  Kubectl Version: v1.14.0
```

**Logs**

```
time="2020-05-27T06:42:44Z" level=info msg="finished unary call with code InvalidArgument" error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `helm template . --name-template couchbase-operator --namespace couchbase-operator --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions azmon.container.insights/v1 --api-versions couchbase.com/v1 --api-versions monitoring.coreos.com/v1 --api-versions velero.io/v1 --api-versions druid.apache.org/v1alpha1 --api-versions custom.metrics.k8s.io/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status 1: Error: template: couchbase-operator/templates/couchbase-tls.yaml:1:22: executing \"couchbase-operator/templates/couchbase-tls.yaml\" at <include \"couchbase-cluster.tls\" .>: error calling include: template: couchbase-operator/templates/_helpers.tpl:218:22: executing \"couchbase-cluster.tls\" at <lookup \"v1\" \"Secret\" .Release.Namespace (include \"couchbase-cluster.tls.server-secret\" .)>: error calling lookup: secrets \"couchbase-operator-couchbase-cluster-server-tls\" is forbidden: User \"system:serviceaccount:argocd:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"couchbase-operator\"" grpc.code=InvalidArgument grpc.method=Create grpc.service=application.ApplicationService grpc.start_time="2020-05-27T06:42:43Z" grpc.time_ms=867.676 span.kind=server system=grpc
```

**Comment by igaskin** [comment] 2020-05-28 07:19
this issue is linked with proposal in https://github.com/argoproj/argo-cd/issues/3640

**Comment by blakepettersson** [comment] 2024-01-18 17:04
Duplicate of #5202

**Closed by blakepettersson** 2024-01-18 17:04 UTC
Labels: bug, bug/severity:major, bug/priority:medium, component:config-management
