### ISSUE TITLE
argocd-applicationset-controller doesn't start on arm64

### ISSUE THREAD

**Issue by rlipscombe** [argoproj/argo-cd#8394] opened 2022-02-05 12:00 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [n/a] I've pasted the output of `argocd version`.

**Describe the bug**

The v2.3.0-rc5 release (which adds arm64 support) doesn't _quite_ add complete arm64 support. The argocd-applicationset-controller pod enters CrashLoopBackoff.

**To Reproduce**

Run `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.0-rc5/manifests/install.yaml` on k3s, on a cluster of RPi4 nodes.

**Version**

v2.3.0-rc5

**Logs**

```
$ kubectl --namespace argocd logs argocd-applicationset-controller-9488fc486-jjt98
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by rlipscombe** [comment] 2022-02-05 12:08
I tried editing the install.yaml to point to the latest image on quay.io -- https://quay.io/repository/argoproj/argocd-applicationset/manifest/sha256:5cc0ac030f5ff218e8e41fd34501670624b67fd85f3dcb0f51baab41e0a1c108 -- but that still fails.

**Comment by rlipscombe** [comment] 2022-02-16 15:56
I noted a v0.4.0 tag on the image, so I tried that. Still seeing the same error.

**Comment by rlipscombe** [comment] 2022-02-19 11:30
Still no dice with the current 'latest' image w/SHA https://quay.io/repository/argoproj/argocd-applicationset/manifest/sha256:ea791980b0e2925e97492c4185a6319a28e7790a58392b3006e1961018ec0e02

**Comment by jr64** [comment] 2022-02-19 13:04
The problem here is that argocd does not yet provide arm64 builds of the applicationset image. We can easily verify that with `docker manifest inspect -v quay.io/argoproj/argocd-applicationset:latest`:

```json
{
        "Ref": "quay.io/argoproj/argocd-applicationset:latest",
        "Descriptor": {
                "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                "digest": "sha256:ea791980b0e2925e97492c4185a6319a28e7790a58392b3006e1961018ec0e02",
                "size": 2402,
                "platform": {
                        "architecture": "amd64",
                        "os": "linux"
                }
        },
```
I have investigated a bit and I think the problem is the different build system they use for that particular image. The other images use buildx for building which has integrated support for qemu making it easy to build cross-platform images for arm64. Argocd-applicationset however seems to use a custom build chain based on "make" which is fine for building a native image but probably not so easy to adapt for cross-compilation.

While we wait for official support, I have forked their repository and natively compiled it for arm64 on my Raspberry Pi 4. If you want you can directly use `ghcr.io/jr64/argocd-applicationset:v0.4.0` for testing (v0.3.0 is also provided, my preliminary tests show that both should work) however I would not recommend that for production use.

Alternatively, you can also build it yourself. Clone the applicationset repo, checkout the branch you want and run ` CONTAINER_REGISTRY=<your registry> IMAGE_NAMESPACE=<your namespace> IMAGE_TAG=<the tag you want> make image`. I had to install docker, make and gcc as dependencies first.

**Comment by rlipscombe** [comment] 2022-02-19 13:16
Fix #8400 is supposed to address the problem. What I was attempting to do was track whether the updated images included the fix or not. Maybe there's a better way to do that, but I don't see a good way to correlate the image tag/sha with the git tag/sha. I'll try your container later, thanks.

**Comment by jstewart612** [comment] 2022-02-28 21:32
Anything happening here?

**Comment by cubanp3te** [comment] 2022-03-06 18:10
Just updated today and experiencing the same issue on Raspberry Pi 4

**Comment by MrMYHuang** [comment] 2022-03-07 01:08
Experience the same issue with version 2.3 on Ubuntu 21 arm64 on Parallels on Apple Silicon M1.

**Comment by MrMYHuang** [comment] 2022-03-11 01:36
I know why applicationset don't support arm64 yet. It's because the arm64 support commit is not yet in release builds:
![image](https://user-images.githubusercontent.com/12458706/157784445-e3c8f319-3139-47b4-8e85-78ec26ed7e38.png)
So, in the meantime, we could wait it. We can watch its releases for notifications on https://github.com/argoproj/applicationset

**Comment by thiagotakehana** [comment] 2022-03-19 23:46
Same issue on OCI Oracle Cloud Ampere A1 compute

**Comment by narze** [comment] 2022-03-20 13:00
I got same issue, are there any possible manual fixes while waiting?

**Comment by narze** [comment] 2022-03-20 13:27
I patched @jr64's image in my argocd-autopilot and it's working now on my Pi 4
https://github.com/narze/home-cluster/commit/0f370548c4a0e3d09f4ca31c5ad233864ae97aba

**Comment by rishabhkalra** [comment] 2022-03-30 17:52
Still having the same issue with a PI 4B.

**Comment by btrepp** [comment] 2022-03-30 22:53
https://git.sr.ht/~btrepp/infrastructure/tree/main/item/bootstrap/playbooks/argocd.yml

Is how I have worked around it uses Jr's image

**Comment by SayakMukhopadhyay** [comment] 2022-04-10 11:13
Hello @crenshaw-dev , apologies for the ping but since you committed this (https://github.com/argoproj/applicationset/commit/a2b34681feb1d0a00b5a09f615e9716856c3c97b) change to the https://github.com/argoproj/applicationset repo I was wondering if you were aware of this issue still being present, probably because of the migration from the old repo to this repo.

**Comment by crenshaw-dev** [comment] 2022-04-12 16:31
No worries about the ping, sorry this hasn't been addressed yet.

@jgwest can we cherry-pick https://github.com/argoproj/applicationset/commit/a2b34681feb1d0a00b5a09f615e9716856c3c97b back and release 0.4.2?

**Comment by SayakMukhopadhyay** [comment] 2022-04-22 06:46
> @jgwest can we cherry-pick [argoproj/applicationset@a2b3468](https://github.com/argoproj/applicationset/commit/a2b34681feb1d0a00b5a09f615e9716856c3c97b) back and release 0.4.2?

@crenshaw-dev I looked around a bit and it doesn't seem like one can just cherry pick that commit as the CI setup for argo-cd is pretty different from the archived applicationset repo.

**Comment by crenshaw-dev** [comment] 2022-04-22 13:54
> I don't know if the current argocd actions generate arm images for all binaries.

Yeah with 2.4, applicationset will be on the same image as argocd, so it'll get arm for free. 

Agreed, pushing a 0.4.2 release would probably be easiest. @jgwest bumping this

**Comment by SayakMukhopadhyay** [comment] 2022-05-15 07:19
I have upgraded to the latest RC https://github.com/argoproj/argo-cd/releases/tag/v2.4.0-rc1 and things seems to be working fine now.

**Comment by christianclarke** [comment] 2022-06-06 23:41
When I attempt to install[ 2.4.0-rc5 or rc4](https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.0-rc5/manifests/install.yaml) on a Raspberry PI k3s cluster.  My understanding is that ARM support is in this release.  Here's the errors I get from a `kubectl describe pod`

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m2s                 default-scheduler  Successfully assigned argocd/argocd-application-controller-0 to k3s-master
  Normal   Pulling    99s (x4 over 3m)     kubelet            Pulling image "quay.io/argoproj/argocd:v2.4.0-rc5"
  Warning  Failed     98s (x4 over 2m59s)  kubelet            Failed to pull image "quay.io/argoproj/argocd:v2.4.0-rc5": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/argoproj/argocd:v2.4.0-rc5": no match for platform in manifest: not found
  Warning  Failed     98s (x4 over 2m59s)  kubelet            Error: ErrImagePull
  Warning  Failed     74s (x6 over 2m59s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    59s (x7 over 2m59s)  kubelet            Back-off pulling image "quay.io/argoproj/argocd:v2.4.0-rc5"
```

The strange thing I did this to work with RC4 a few days ago.

**Comment by eiden** [comment] 2022-06-07 07:27
`v2.4.0-rc5` was released less than 12 hours ago. When the release tag is created, it takes some time before the images are built and pushed to the docker registry. 

I had no problems when I upgraded to `v2.4.0-rc5` on my rpi4 5 minutes ago.

**Comment by crenshaw-dev** [comment] 2022-06-07 13:21
Strange. The quay UI shows all the various platforms as available. https://quay.io/repository/argoproj/argocd?tab=tags

**Comment by christianclarke** [comment] 2022-06-07 13:24
I know.  It is very peculiar.  I strongly suspect it's environmental problem isolated to myself since @eiden has been able run it.
I can run other arm containers (grafana/prometheus etc)

**Comment by eiden** [comment] 2022-06-07 13:28
@christianclarke Are you using raspberry pi 3 or 4 to run your cluster? The argo image is only available for `linux/arm64`. 

on my pi:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

**Comment by ChadiEM** [comment] 2022-06-07 13:29
The image used is `quay.io/argoproj/argocd-applicationset`
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L1969

It has no arm64 build.

https://quay.io/repository/argoproj/argocd-applicationset?tab=tags

So yea... it still fails.

**Comment by christianclarke** [comment] 2022-06-07 13:30
> @christianclarke Are you using raspberry pi 3 or 4 to run your cluster? The argo image is only available for `linux/arm64`.
> 
> on my pi:
> 
> ```
> pi@raspberrypi:~ $ uname -a
> Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
> ```

@eiden

**Comment by eiden** [comment] 2022-06-07 13:34
Ok, seems like you figured it out :) Grafana works on your system since they also build for `armv7`. 

```
$ docker manifest inspect grafana/grafana
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      [...]
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2197,
         "digest": "sha256:a2b2d67fd63ffd0ac694efe68e5506df79e7991f875dd87baa1d73f5270fb698",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```

**Comment by christianclarke** [comment] 2022-06-07 13:36
I was being dumb - as soon as I saw your `uname` .  <hangs head in shame>

**Comment by jstewart612** [comment] 2022-07-01 22:32
I can confirm that, as of at least ArgoCD 2.4.3 if not sooner, and the latest helm chart 4.9 or greater, the image used is "argocd" instead of "argocd-application-controller" and it works out of the box on my Pi 4s and CM4s both.

I would presume this was a natural win after consolidated the outer applicationset repository into the main argocd repository proper, thus combining the build processes of each release that build arm images because now the applicationset controller is in the main argocd image.

I believe this can be closed with the advisement with upgrade to ArgoCD 2.4.x series because that's when this seems to have occurred.

**Comment by crenshaw-dev** [comment] 2022-07-05 13:33
@jstewart612 that's exactly right. Closing!

**Closed by crenshaw-dev** 2022-07-05 13:33 UTC
Labels: bug
