### ISSUE TITLE
ArgoCD uses wrong key id when verifying commits

### ISSUE THREAD

**Issue by larsks** [argoproj/argo-cd#10732] opened 2022-09-28 20:11 UTC
**Describe the bug**

I configured ArgoCD to require GPG signatures on commits but ran into a number of problems. I'm signing my commits with this key:

```
pub   rsa2048/0x362D63A80853D4CF 2013-06-21 [SC]
      3E70A502BB5255B6BB8E86BE362D63A80853D4CF
uid                   [ultimate] Lars Kellogg-Stedman <lars@oddbit.com>
uid                   [ultimate] keybase.io/larsks <larsks@keybase.io>
sub   rsa2048/0x042DF6CF74E4B84C 2013-06-21 [S] [expires: 2023-07-01]
sub   rsa2048/0x426D9382DFD6A7A9 2013-06-21 [E]
sub   rsa2048/0xEE1A8B9F9369CC85 2013-06-21 [A]
```

From the above output, we see that the key ID is `0x362D63A80853D4CF`, and if I import this key into ArgoCD with `argocd gpg add`, we see:

```
$ argocd gpg list
KEYID             TYPE     IDENTITY
362D63A80853D4CF  RSA2048  Lars Kellogg-Stedman <lars@oddbit.com>
```

So I configured the `default` project to require commits signed using this key:

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  signatureKeys:
    - keyID: 362D63A80853D4CF
```

But when I push signed commits to a repository that is tracked by ArgoCD, I see the following error in the UI when syncing:

> ComparisonError: Found good signature made with RSA key 042DF6CF74E4B84C, but this key is not allowed in AppProject"

That is of course a lie: the referenced key is the signing *subkey* of the primary key id. ArgoCD should accept in the `signatureKeys` section the key ids listed in the output of `argocd gpg list`; to require anything else is crazy talk.

I ran into a secondary problem: even after erroneously "correcting" the `signatureKeys` block to use the subkey id, one of my applications refused to sync because:

> Target revision HEAD in Git is not signed, but a signature is required

It was complaining specifically about https://github.com/larsks/k8s-metallb (and in particular about commit [33fb135](https://github.com/larsks/k8s-metallb/commit/33fb135efbcbc1f44b011d57758eb4ba5663ce31), which as you can see has been signed with the same GPG key referenced above:

```
$ git log --show-signature
commit 33fb135efbcbc1f44b011d57758eb4ba5663ce31 (HEAD -> main, origin/main)
gpg: Signature made Wed 28 Sep 2022 10:15:23 AM EDT
gpg:                using RSA key FDE8364F7FEA3848EF7AD3A6042DF6CF74E4B84C
gpg:                issuer "lars@oddbit.com"
gpg: Good signature from "Lars Kellogg-Stedman <lars@oddbit.com>" [ultimate]
gpg:                 aka "keybase.io/larsks <larsks@keybase.io>" [ultimate]
Author: Lars Kellogg-Stedman <lars@oddbit.com>
Date:   Wed Sep 28 10:15:23 2022 -0400

    Initial commit
```

**Expected behavior**

I expected:

(a) ArgoCD to use the same key id presented in `argocd gpg list` in the `signatureKeys` section of the the project config, and
(b) I expected it to correctly recognize that a commit has a GPG signature attached.

**Version**

```shell
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitCommit: 3d9e9f2f95b7801b90377ecfc4073e5f0f07205b
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.12+41f54aa
  BuildDate: 2022-09-16T00:45:01Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.6

  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

Regarding the first part of this issue:

> time="2022-09-28T19:27:55Z" level=info msg="Sync operation to 8a83b887fcd29e4290a7f98561b79cf4295e117f failed: ComparisonError: Found good signature made with RSA key 042DF6CF74E4B84C, but this key is not allowed in AppProject (retried 2 times)." application=argocd dest-namespace=argocd dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning

And the second part:

> time="2022-09-28T19:30:53Z" level=info msg="Sync operation to 33fb135efbcbc1f44b011d57758eb4ba5663ce31 failed: ComparisonError: Target revision 33fb135efbcbc1f44b011d57758eb4ba5663ce31 in Git is not signed, but a signature is required (retried 1 times)." application=metallb dest-namespace=metallb-system dest-server="https://kubernetes.default.svc" reason=OperationCompleted type=Warning

**Comment by cleverhu** [comment] 2022-09-29 18:45
It looks like the crd lacks the fields defined by the private key, so it will not be verified.

**Comment by denispeyrusaubes** [comment] 2023-02-28 23:42
> It looks like the crd lacks the fields defined by the private key, so it will not be verified.

Can u be more explicit ? 
Do you mean That  the app deployment descriptor should mention something about signature verification ? 

I have the same pb :
```
ComparisonError: Target revision 430214cd675c305ff62d52be9ea3f895fc6ed072 in Git is not signed, but a signature is required
```

When I verify this commit, it has been signed...

**Comment by mihaigalos** [comment] 2023-05-13 07:55
Did you also add the GPG Public Key to ArgoCD?
This works for me:


<details>
  <summary>gpg-authorized-public-keys-configmap.yaml (generated with gpg --armor --export i@myself.me) - Click to expand!</summary>
  
```yaml
apiVersion: v1
data:
  DA6B8DBAC2739FC0: |-
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mQINBGRX+P4BEADFwBE5LuOlRWxLr4/p7izMITYmFD3VB13fP/YieXQNUZ6HK2W/
    YXFfk7TsdzXMlDzixLnDMRFbbkGbcDBbzF2MjJk+jt1g+AJrvNdu/o0L4Ku7LF/2
    zTgEOblj7A1cJQ8iloeyOCVomUZBQFyPTYHh8LtcVMcCogN1cP4ctfp1FFS00VZo
    h3PIVZco9ztBVDboD7UWTfg7WYiHtRvhqFvvN1sZO1fBKa16Ms5mI0aLnGekwS2u
    1sLcTwybOMpGsXNKC/f/rCj9nXwdQrbzxFvDz+Ma+cYuco4rNVglYUuwxTOhN0Sm
    6bsReB/TlpbEHK6a0Bs0OcJeBypu8IvMCpI0Hav6cLbFpX9YaFPY04nVVcQQad1J
    4WKLdAHJDVjy65H/ZO6HhhD/x8uwdud8Yle2oZwnpFhGQAQu3xZwi/iOjrELaDDl
    fS3bY26NaprXWx0Omi7tYNaKt0Yi60oKTZsW8Spv81UvTqXQtC6u65oH7MYCD9dx
    GY3ZKw3YSrtNCHPgrujQ5PTlyFc++VBTPoWPkujeidvniFO/1lQd/JK4Kj9LTLzp
    rg9IM5p2dYX69bjBVbRMm1xhDTzPuVcMlTfYGvP/Wqlla52eGXqIbBweZCBLbW69
    WirXhlEsb2TWz1tfKSpS62nNiaxI554qjYYnvjblbNdujwf7Z//5XOHdMQARAQAB
    tCJNaWhhaSBHYWxvcyA8bWloYWlnYWxvc0BnbWFpbC5jb20+iQJOBBMBCgA4FiEE
    V1YjTPaHCvwn4JUk2muNusJzn8AFAmRX+P4CGwMFCwkIBwIGFQoJCAsCBBYCAwEC
    HgECF4AACgkQ2muNusJzn8DDbg/9G8mSIpLZp0aBoZgcuWOFjACX7ORlFsiAGWgf
    85bwaxJcYDwNSsbHETcgdFQGPM6or1wViYzpoZ09eZtBccI/SYRHpa3iXy2Kwhd8
    V+1U6YbnrJ077TnEWz/upk006O5ZmdVY1P+b/IR22JTs/cWRBUQykJArMCx6Qjrb
    henZsaaAwaitSFoln/ADHKY4GlgOdeja6CqDLtBd2CgkMQYbPHhj/lbvxbJWMCBe
    ut63bfvjMlNyCZPWY1VfpX+kHXNMhp4OYADMYU6a5Xow37hWhxxfgVW0M+0mjlAj
    pCwRtLxOnGbU+/POu+/+uMqT8rfCaPwV4EgOwypxTe1Uqhq2hTn9FN5EDAi9uoQz
    sTRORH+whp7ML2zAa95DctGBk59z/YlmLnys6kSRMZelH8MbDb7wnoL1SoqrAjjF
    B/UI4lCHGTSUzkUvY+pL4lyFGiTbV1x7/U4HcnjCDImcnG3xdyW6jylFHgxOJdAQ
    gQ9sAZ/J6/CqVyMVHRh9XF88GdlCOoViOxtVz4GBP4famRAR83rcKHA9RXGaQ8G1
    9zr63sPh/7zucMJ7pWmOC6RWRfhSZU8KRkROvvJvY7gUlwwujoR8bFm6hkb4sN4S
    XoD/iP6A9YCgZ+R/t9mzlPloU/0odrBWB/hg1nPq1el0HiaNS12TSGdQm/1VdEpA
    uvwxdCG5Ag0EZFf4/gEQAK9/GlZK8Z62L6N+xEuLROEyZrjT2UrlcWeUKtZ1Z8wI
    xv6Jf4MR0qw0KxXTH6CQ+LXX3P3Oz16vInbbQwTVYCFijs1Sn5oNtHl23eGFxpnz
    UxzaltevCkwidOhalGvSonPT91bfBcEIOdFYXw7BdLVa9e1gSdSQos1amEJcxsmv
    53GBKupXNKiFyVAf0T/1QkbrYTpGmZ1+QCGujkzzJxx13+2hkY+hovYVtm9Wbfia
    7MYdHC1O92TYNyOMbaO53eqxWoHyUVwS6KoaTOZbGjJhxcZxi3RSZHW0/SASojs3
    ALyfVvrkpLDowcwPdRD6kBIVGr/LMPUk10cphkBebZAEAHKikrpooDK29ju53BGy
    CvArsbtD0dVuE8UJWrvg+s2m3x+mwGqQ7fsr3tPhMxt+4EUOOYp71up0Y/DC3wB7
    bspfJTv+wkgueckYlpiqW7fj5ANWIzTIc86DA1LpDsKmhaIZFRBntviZCkjdwe3C
    OVzLszO15id1/4d69jmt7hGfFVQ2oIXXCzipvFfWnnYJkRuGMMtfeZjpz/Z9l5zL
    xbwqLnQi6DD9NyNIfIXyqkOuHgWqcD1epbcpPlf9p9KeIjvEugVVHLjGmbFQJAyh
    PJ3Xosro3t11rSBGbkbIzJnGPySIrUf73cMgJ3+rYdrn4lEPhMHOE1DE4kspZLJ5
    ABEBAAGJAjYEGAEKACAWIQRXViNM9ocK/CfglSTaa426wnOfwAUCZFf4/gIbDAAK
    CRDaa426wnOfwFqVEACWWmfymPbtvi3cEZLX0NHvcqLdNZXAWza1WpNg+5yJRKb0
    06D5pnBVRxuHk3TyeGNXpOFe9Ai3vDDPiWyQnMd+c4en5evAMSome9Aq+mlHvL4Z
    Oyi872f1oPkxAKxFeD7izJi7bDOcxVj2KHOb+jdOSxATFQ1Ear2Wes/tkaiZ+JbM
    iC1b3E6GcXBEErCHuKBc0jFEcM+/UhyvipXjto4fdClaNljj9KKHkwiVTXzg933C
    /rS3VJ0UvCTyY0k/F4lgOD/1NY6UQvRsIAFGapuf5/PukVbmX3SWa0PyDTc+6hEG
    S3PggiRbeoOM4Gz2IUP5Lniklxm47CtTBR5RcINiMMzHYfiV8gEewTYf7oid2cX8
    nwBeLaMQpQoHj44b1yNoZ297h+unAGJaRyknG1sDX+eBMiwKlh8oVLwAQ/TDRe7u
    YXMQttysA6er1A7kAt3sDe6AUt+DqwnB48Qypo/I699reWa7YpqhIAILmpkKpk5u
    UqqhSvSs8V8oIc0afkbnFpo+yOYwY9sVre+rsSazwex+ehjFdizOX60X9MqEdWws
    a0M7C5qtTfWDPtDZ0FckmGI2xQZk2R7jXX1kDeWhvTLoL15k/F7ZovRZ29ZVkERr
    era37/SJYDFFaXQp2r0wDzRGweMp+4zkDlexYmiq5AaYqej16QRHArGXDgIwRQ==
    =32e/
    -----END PGP PUBLIC KEY BLOCK-----
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-gpg-keys-cm
  namespace: argocd
  ```
</details>
  

<details>
  <summary>gpg-appproject.yaml - Click to expand!</summary>

  ```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: GnuPG verification
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  signatureKeys:
  - keyID: DA6B8DBAC2739FC0
  sourceRepos:
  - '*'
  ```
</details>

Result:
![image](https://github.com/argoproj/argo-cd/assets/16443090/463842ec-c8d5-4ed8-b0b1-21d2fce6d030)

**Comment by james-callahan** [comment] 2023-05-18 00:48
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/4930

**Closed** 2023-05-18 14:58 UTC
Labels: bug
