### ISSUE TITLE
Declarative helm repositories with missing secret causes all repositories in ArgoCD to lock

### ISSUE THREAD

**Issue by Cyanopus** [argoproj/argo-cd#3492] opened 2020-04-27 07:47 UTC
**Describe the bug**

When adding a private helm reposistory in argocd-cm using declarative git way like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: management
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # v1.3 or later use `repositories` with `type: helm`
  repositories: |
    - type: git
      url: https://example1
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: example1
    - type: helm
      url: https://example2
      name: example2
      usernameSecret:
        name: example2
        key: username
      passwordSecret:
        name: example2
        key: password
```
Secret example 2 is missing in the cluster. This leads to ArgoCD totally block the rest of the configured repositories( in this case examples) and not able to load them. Its giving exception for missing secret and from this point no other correctly configured repository can be synced so apps stay in Unknown state immediately after this happens.

**To Reproduce**

Take the definition in the Description and modify it to have one private helm repo and one public plain. Configure non-existing secret parameters. Sync ArgoCD and check the result. It was tested with 1.4.2 and 1.5.2

**Expected behavior**

When a secret is not correctly setup, Argo should not bother for the rest of the correct setup repositories. It should continue to function as expected.

**Screenshots**

**Version**

1.4.2 , 1.5.2

**Comment by jannfis** [comment] 2020-04-27 10:52
Thank you, I could reproduce it. It is not affecting Helm repos only, but also Git repositories as it seems.  I agree that a missing secret should only result in that specific repository not being available, and not all repositories become invalid.

**Comment by Cyanopus** [comment] 2020-04-28 12:28
@jannfis Its a nasty one, because if you are using the whole declarative setup, your setup is basically empty which means that the production of environments is impaired. We've managed to work around it but it's not very good looking. :)

**Comment by jaideepr97** [comment] 2020-09-12 16:42
@jannfis 
Hi! @gaganhegde and I would be interested in taking a closer look at this issue
Is this still an open issue and in need of being addressed?

**Comment by jannfis** [comment] 2020-09-13 10:37
@jaideepr97 It would be much appreciated if you take on this issue :)

**Comment by jangraefen** [comment] 2021-01-31 10:10
@jannfis @jaideepr97 Since there does not seem to be that much traction on this issue, would it be okay for me to take this one to get more familiar with the code base?

**Comment by jannfis** [comment] 2021-01-31 12:57
@jangraefen I suppose since @jaideepr97 gave a thumbs up on your request, work has not been started yet. So, feel free to take over and thanks a lot for your offer!

**Comment by alexmt** [comment] 2021-03-15 20:32
Fixed by https://github.com/argoproj/argo-cd/pull/5363

**Closed by alexmt** 2021-03-15 20:32 UTC
Labels: bug, bug/priority:medium, bug/severity:minor, component:git, good first issue
