### ISSUE TITLE
Run Argo CD operator local to managed Application (multi-cluster)

### ISSUE THREAD

**Issue by dcioccarelli** [argoproj/argo-cd#6145] opened 2021-05-02 09:51 UTC
# Summary

I was experimenting with the use of Argo CD in a multi-PaaS, geographically distributed environment. I was able to get Argo CD installed on the "master" cluster and then add a "slave" cluster via "argocd cluster add ...". I was then able to easily assign applications to the remote cluster by updating the "destination" in the Application manifest. So functionally speaking I was able to achieve what I wanted. From an implementation perspective though, I was surprised to find that there was no "Application" CRD on the slave cluster and instead the applications that were deployed on the slave cluster had their custom resources on the master cluster.

The master cluster has the custom resource for "production3" even though it is running on a remote cluster:

![image](https://user-images.githubusercontent.com/3922777/116809332-c0be8c00-ab3d-11eb-8e75-da40287c443a.png)

On the remote cluster, the "production3" application is running:

![image](https://user-images.githubusercontent.com/3922777/116809473-7a1d6180-ab3e-11eb-9062-bed70101a879.png)

... but there is no corresponding Argo CD custom resource / operator:

![image](https://user-images.githubusercontent.com/3922777/116809367-f82d3880-ab3d-11eb-9864-430b77e0a9ad.png)

I would prefer an implementation (or at least implementation option) whereby the Argo CD operator could run on the slave cluster but still have the master cluster responsible for the overall management, git integration, etc. It would be simply that application manifest updates would be propagated to the slave clusters and the operator running on the slave PaaS would be responsible for converging the environment towards the new desired state.

# Motivation

Having the Argo CD operator on the slave cluster but keeping the overall UI and orchestration on the master would allow for a good balance between overall useability and reliability: having the operator run on the slave would mean that it could deal with any divergence from the desired state without a dependency on the master (which could be in a separate region). 

# Proposal

argocd cluster add... would install the Argo CD CRD on the managed cluster (in addition to the ServiceAccount and ClusterRole). When an Application manifest was targeting a non-local cluster, it would be sent to that cluster for implementation rather than relying on an operator running on the master cluster.

**Comment by blakepettersson** [comment] 2024-01-23 00:12
Sounds like this is a duplicate of #4512

**Closed by blakepettersson** 2024-01-23 00:12 UTC
Labels: enhancement
