### ISSUE TITLE
Logs of finished init containers are repeating indefinitely

### ISSUE THREAD

**Issue by der-eismann** [argoproj/argo-cd#4619] opened 2020-10-20 16:35 UTC
**Describe the bug**

When looking at the logs of a finished init container it first only shows the original log output . After 3 seconds the same output is appended at the end. After another 3 seconds again. This goes on indefinitely and makes the logs endlessly long even though the container has finished already.
This happened after we upgraded from 1.7.4 to 1.7.8.

**To Reproduce**

Open the log tab of a pod which has a finished init container. 

**Expected behavior**

Just seeing the actual logs of the container instead of repeating them.

**Screenshots**

When I open the logs tab it looks like this
![argocd_bug_1](https://user-images.githubusercontent.com/10406217/96616210-93796180-1302-11eb-986d-e685051256d1.png)
After 10 seconds the same entry (as you can see at the time of the migration, it's exactly the same) is already repeated 3 times.
![argocd_bug_2](https://user-images.githubusercontent.com/10406217/96616204-92483480-1302-11eb-88d5-e35a3f9e0968.png)

**Version**

```shell
argocd: v1.7.8+ef5010c
  BuildDate: 2020-10-15T22:33:00Z
  GitCommit: ef5010c3a0b5e027fd642732d03c5b0391b1e574
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
```

**Comment by darshanime** [comment] 2020-10-21 14:36
@alexmt I think [this commit](https://github.com/argoproj/argo-cd/pull/4315/files) introduced the regression. What do you think about adding back this [here](https://github.com/argoproj/argo-cd/pull/4315/files#diff-884cea1f0a354998c12cefc2b8097a881fe6d621fa91c1c549d241d6023fa5b5R70):

```ts
            let opened = false;
            eventSource.onopen = msg => {
                if (!opened) {
                    opened = true;
                } else {
                    eventSource.close();
                    observer.complete();
                }
            };
```

**Comment by tetchel** [comment] 2020-10-22 14:19
I noticed this same problem in https://github.com/argoproj/argo-cd/issues/4450 - I expect a fix for this would fix that too.

**Comment by alexmt** [comment] 2020-10-24 00:23
Thank you for the investigation, @darshanime ! 

I've removed the above code because it appears that SSE API restart request automatically when it get closed and totally forgot about logs API where we need to avoid automatic restart.

I've changed code above because SSE API does not provide a reliable way to detect closed streaming connection so application watch API was flaky. I've changed the applications related code but  totally forgot about logs loading case where we need to prevent restarting request. 

Not sure what is the best possible way to fix it. One idea is to change logs API so that it explicitly notify UI that it is closed.  To do it we can add e.g. `required last boolean` field to logEntry message:

https://github.com/argoproj/argo-cd/blob/41ab92fbddab69549c5b8c6a6a41003546ae3b8e/server/application/application.proto#L163-L166

And `PodLogs` method should send message with `last` set to true before existing here:

https://github.com/argoproj/argo-cd/blob/41ab92fbddab69549c5b8c6a6a41003546ae3b8e/server/application/application.go#L1110

The UI should check `last` field and explicitly close SSE request when it is set to true

```typescript
    public getContainerLogs(applicationName: string, namespace: string, podName: string, containerName: string): Observable<models.LogEntry> {
        const entries = requests
            .loadEventSource(`/applications/${applicationName}/pods/${podName}/logs?container=${containerName}&follow=true&namespace=${namespace}`)
            .map(data => JSON.parse(data).result as models.LogEntry);
        return new Observable(observer => {
            const subscription = entries.subscribe(
                entry => {
                    if (entry.last) {
                        observer.complete();
                        subscription.unsubscribe();
                    } else {
                        observer.next(entry);
                    }
                },
                err => observer.error(err),
                () => observer.complete()
            );
            return () => subscription.unsubscribe();
        });
    }
```

What do you think ?

**Comment by darshanime** [comment] 2020-10-24 05:08
Hmm, that seems like a good idea, I can raise a PR for this. 

An alternative is avoiding client retries and solving the long lived connection timeouts(for which client retries were introduced afaik) with the server sending keepalive pings(see [this](https://github.com/argoproj/pkg/pull/30) and [this](https://github.com/argoproj/argo-cd/pull/4564)). 

What do you think we should proceed with?

**Closed** 2020-10-29 16:38 UTC
Labels: bug, regression
