### ISSUE TITLE
Can't create 2 applications with same name but on different projects and different cluster destinations

### ISSUE THREAD

**Issue by KrustyHack** [argoproj/argo-cd#9630] opened 2022-06-10 09:04 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm trying to create an ArgoCD application through the UI which has the same name than another one but which is on another ArgoCD project and with another Kubernetes cluster destination.

**To Reproduce**

Create two ArgoCD applications on 2 ArgoCD projects and 2 differents clusters for destination.

**Expected behavior**

ArgoCD application is created.

**Version**

```shell
argocd: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:17:09Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.3+07ac038.dirty
  BuildDate: 2022-03-30T05:17:09Z
  GitCommit: 07ac038a8f97a93b401e824550f0505400a8c84e
  GitTreeState: dirty
  GoVersion: go1.18
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Unable to create application: existing application spec is different, use upsert flag to force update
```

**Comment by KrustyHack** [comment] 2022-06-10 09:11
More context : I'm using one ArgoCD instance to manage my production and my staging.

I have an app which is on both environment, imagine name is "myapp".

I've created 2 ArgoCD projects, on for staging and one for production.

On staging ArgoCD project I've created my app "myapp" which is deployed on K8S cluster "staging".

Now I'm trying to create a second app "myapp" on production ArgoCD project and which should be deployed on K8S cluster "production".

And I can't choose another app name as the app name is used for the Helm chart name too by ArgoCD when deploying it.

**Comment by hmehta** [comment] 2022-06-13 06:02
I can confirm this on v2.3.4+ac8b7df.

**Comment by wofr** [comment] 2022-06-13 09:00
I wrote an enhancement report reagarding this topic. Maybe you can support this by adding your ideas how this could be solved  https://github.com/argoproj/argo-cd/issues/9442

**Comment by crenshaw-dev** [comment] 2022-06-13 15:21
Thanks for the issue, @KrustyHack! I'm going to close as a duplicate of https://github.com/argoproj/argo-cd/issues/3709 (and several others). If I'm wrong that this is a duplicate, just lmk!

**Closed by crenshaw-dev** 2022-06-13 15:21 UTC
Labels: bug
