### ISSUE TITLE
Disable amimations

### ISSUE THREAD

**Issue by tebaly** [argoproj/argo-cd#7740] opened 2021-11-18 10:54 UTC
Hello. 

https://medium.com/iporaitech/css-background-animation-avoiding-high-cpu-usage-58947ff50900

# Your running stripes are killing my processor

FIX this **BUG** or or provide an option to disable animation in the settings.

![Screenshot_20211118_144619 (2)](https://user-images.githubusercontent.com/9466814/142402285-a8e76bb1-7da6-484e-82fc-b5bf2212f268.png)

**Comment by alexmt** [comment] 2021-11-18 17:58
I think it is a duplicate of https://github.com/argoproj/argo-cd/issues/5982 . Let's keep one ticket. Thanks for the link - we might try to use `translateZ`!

**Closed by alexmt** 2021-11-18 17:58 UTC
Labels: bug
