### ISSUE TITLE
Application Name Length Limits

### ISSUE THREAD

**Issue by Lemmons** [argoproj/argo-cd#5595] opened 2021-02-24 20:22 UTC
# Summary

There is an implicit length limit on Argocd Application names because the application name is used as kubernetes labels on resources, which have a maximum value length of 63 characters.  Applications should be able to optionally specify the value used in this label (and/or truncate it to 63 characters).

# Motivation

We are using a large Argocd deployment which manages multiple kubernetes clusters.  Because Argocd Applications must all be in the same namespace in which Argocd is running, all application names must be unique.  Since we are deploying the same set of charts to all clusters, we prefix the Argocd Applications with context to make the names unique, such as the name of the cluster the application is being deployed to, the cloud account name, etc.  This results in very long application names which occasionally are longer than the 63 character limit imposed by the kubernetes labels.

# Proposal

At least, there should be a way to override the application instance label so a user could have an application with a name longer than 63 character, but still be able to stick with the 63 character limit for kubernetes labels.

Additionally, truncation of the application name when being used in the labels might be ok, though it could result in some unexpected behavior if two applications end up with the same truncated names.  As right now if an application name is longer than 63 character it results in sync errors, so truncating would likely be better than the existing behavior.

**Comment by jannfis** [comment] 2021-02-24 20:41
I know this topic had been discussed at least once before, but I cannot find the respective issues. Also, there was a bug opened just 2 hours ago with the same topic, #5594. I think an enhancement is the better issue to track for this, so I'm thinking of closing the other as dupe in favor for this enhancement. Since they correlate in time, are you @Lemmons and @sidewinder12s somehow associated?

Anyway, I think this can be relatively easy solved by using a collision-free hash algorithm as the value for the instance label. The actual plain text application name could also be put to an annotation without the 63 chars limit for providing a human-readable indicator of the application the resource belongs to. However, we need a label to programmatically select all resources belonging to an application. 

I'm pretty sure something similar to using a hash has been proposed earlier, but as already said, I'm unable to find the issue. But happy to discuss it further. Maybe someone is even able to find the previous issue(s) :)

**Comment by Lemmons** [comment] 2021-02-24 21:15
Thanks for the reply.  Yes, we are associated, sorry we didn't coordinate on the issue submission.

A hash for the label and extra annotation sounds like an elegant solution, and would certainly work for our use case.

**Comment by jessesuen** [comment] 2021-02-24 21:25
There's a PR to allow annotations to be used instead of labels, but I don't think it has made progress in some time. 

https://github.com/argoproj/argo-cd/pull/4123

**Comment by jannfis** [comment] 2021-02-24 21:39
Ah you found it. There's even another one: https://github.com/argoproj/argo-cd/pull/4051

And here's the original issue: https://github.com/argoproj/argo-cd/issues/4045

**Comment by jannfis** [comment] 2021-02-24 21:46
I think going to use a hash will be definitely the cleaner option than to use an annotation (we can still inject an annotation for readability purposes). And if we can provide a way to manually generate the hash for an application name by the CLI, would also allow to retrieve all resources for an application by a label selector - something that's to my knowledge not possible with annotations.

**Comment by sidewinder12s** [comment] 2021-02-25 06:03
Ya, it sounds like using a collision-free hash label + adding an annotation which does not have the length limits threads the needle between these issues and the proposed PRs while making the change consistent rather than conditional on folks hitting the limit.

**Comment by sbose78** [comment] 2021-04-01 14:15
Agreed. Is this something one of you would like to contribute :) ?

**Comment by NargiT** [comment] 2021-06-21 07:05
the hash it really a good option with annotation for readability :tada: which I knew golang :pray:

**Comment by alexmt** [comment] 2021-10-04 21:42
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/4045 as @jannfis  pointed out. Let's close this issue.

**Closed by alexmt** 2021-10-04 21:42 UTC
Labels: enhancement
