### ISSUE TITLE
can't open https://cd.apps.argoproj.io/

### ISSUE THREAD

**Issue by sugesslee** [argoproj/argo-cd#9192] opened 2022-04-24 11:33 UTC
https://github.com/argoproj/argo-cd/discussions/9191

**Comment by gaeljw** [comment] 2022-04-24 19:30
Duplicate of #9185

**Comment by michtek** [comment] 2022-07-29 16:54
The site is down again

**Comment by crenshaw-dev** [comment] 2022-07-29 17:16
@leoluz do you have time to take a look?

**Comment by leoluz** [comment] 2022-07-29 20:36
Issue is remediated. Need to invest time to fix the root cause.

**Closed by leoluz** 2022-07-29 20:36 UTC
Labels: bug, duplicate
