### ISSUE TITLE
applicationset won't recreate application after manually deleted

### ISSUE THREAD

**Issue by matan-legit** [argoproj/argo-cd#18982] opened 2024-07-08 14:36 UTC
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

my application was erroring because the oci repo was not configured correctly in argocd, i have added the configuration but the application kept erroring, so i deleted the application manually from argo ui and it never recreated 

**To Reproduce**

pretty much described in the description. have an app error -> delete it -> ??? -> no profit 

**Expected behavior**

the app should've been recreated

**Screenshots**

**Version**

```shell
argocd: v2.9.1+58b04e5.dirty
  BuildDate: 2023-11-14T18:19:24Z
  GitCommit: 58b04e5e11d007b0518853029ff7612c24a2eb35
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.0+d3f33c0
```

**Logs**

```
Status:
  Conditions:
    Last Transition Time:  2024-07-08T14:09:51Z
    Message:               applications.argoproj.io "issues-dev" not found
    Reason:                UpdateApplicationError
    Status:                True
    Type:                  ErrorOccurred
    Last Transition Time:  2024-07-08T10:29:24Z
    Message:               Successfully generated parameters for all Applications
    Reason:                ParametersGenerated
    Status:                True
    Type:                  ParametersGenerated
    Last Transition Time:  2024-07-08T14:09:51Z
    Message:               applications.argoproj.io "issues-dev" not found
    Reason:                UpdateApplicationError
    Status:                False
    Type:                  ResourcesUpToDate

```

```
time="2024-07-08T14:15:28Z" level=error msg="failed to unchanged Application" action=unchanged app=argocd/issues-dev applicationset=argocd/dev-services-application-set error="applications.argoproj.io \"issues-dev\" not found"
```

bypass: restart appset controller fixed it

**Comment by christianh814** [comment] 2024-07-08 19:56
Do you have a sample of the ApplicationSet that was used?

**Comment by blakepettersson** [comment] 2024-07-08 21:06
Duplicate of #17312

Please add a repro there, if I can get a consistent repro I can work on it this week.

**Closed by blakepettersson** 2024-07-08 21:06 UTC
Labels: bug, component:applications-set, component:ui, type:bug
