### ISSUE TITLE
[feature] OCI Kustomize support

### ISSUE THREAD

**Issue by NissesSenap** [argoproj/argo-cd#13085] opened 2023-04-03 06:33 UTC
# Summary

Today you can more or less bundle anything in to OCI which make it really easy to package for maintainers.
In the flux community, people have started to bundle Kustomize manifests in OCI charts https://fluxcd.io/flux/components/source/ocirepositories/
I would like to have the same functionality in ArgoCD.

# Motivation

Instead of using helm, I use Kustomize in many locations, but it's painful to manually download manifest files from different repositories.
To be able to point to an OCI repository in a specific repo would solve this problem.

# Proposal

Leaning towards adding an oci url to `application.spec.source.kustomize` but I'm a bit unsure where it might be the best place.

It might also be worth to add a CLI option called artifact or similar, https://fluxcd.io/flux/cmd/flux_pull_artifact/.
This due to that you can't download a Kustomize OCI manifests through docker, and it's nice to be able to debug the manifest by downloading them.
But to me this is a separate feature.

**Comment by blakepettersson** [comment] 2023-09-30 18:28
Duplicate of #13085

**Closed by blakepettersson** 2023-09-30 18:28 UTC
Labels: enhancement
