### ISSUE TITLE
Append repository via declarative approach

### ISSUE THREAD

**Issue by jmclean-starburst** [argoproj/argo-cd#6230] opened 2021-05-13 16:27 UTC
# Summary

It would be great to add repositories to Argo CD in a declarative way. To do this, currently, an update would be need to made to `argocd-cm` via the `repositories` key; however this infers that the patch would add the `argocd-cm` as a base (in Kustomize), which isnt easily structured (especially if the `argocd-cm` is already an overlay).

# Motivation

Imagine **Repo A** has a structure like the below:
```
- base/kustomization.yml
- base/argocd-server.yml
- base/argocd-cm.yml
- env/dev/kustomization.yml
- env/dev/patch/argocd-cm.yml
```

**Repo B** wants to append a repository to `argocd-cm.yml` in a declarative way. It does not want to inherit a parent repository (ie have a base point to **Repo A** at `/env/dev/`); rather **Repo B** wants to add a config map with the repository  definition it needs (more of a Service Oriented Architecture).  AFAIK, there is no way to do this

# Proposal

Add an annotation to a configMap manifest like `argocd.argoproj.io/repo: append` which will then identify to Argo CD that a new repo should be added.

With the above, I can apply an application manifest that points to this repository and no further actions (ie adding the repository) will need do be done via Argo CLI/API

**Comment by jannfis** [comment] 2021-05-19 06:11
Possible dupe of #5436

**Comment by sanzenwin** [comment] 2021-06-11 04:11
I'm facing this situation too, can't find a way to extend argocd-cm file.

**Closed** 2023-05-19 16:48 UTC
Labels: duplicate, enhancement
