### ISSUE TITLE
OCI Helm Chart Application with Version Range  is Not Working

### ISSUE THREAD

**Issue by suresh-sivanantham-irm** [argoproj/argo-cd#6686] opened 2021-07-09 18:09 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to deploy a Helm Chart with version range as "*" and automated sync policy. It works fine if the chart is HTTPS hosted but does not work if the chart is OCI registry hosted

**To Reproduce**

* Create a kind Cluster
* Deploy Argo CD 
* Add OCI Helm Repository with command `argocd repo add <oci helm repo> --type helm --name repo_name --enable-oci --username ${GITLAB_USERNAME=} --password ${GITLAB_ACCESS_TOKEN}`
* Deploy Helm Application (with below manifest)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tva
spec:
  destination:
    name: ''
    namespace: tva
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: <Helm repo added above>
    targetRevision: "*"
    chart: tva-helm-chart
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
```

**Expected behavior**

The latest version of the chart must be deployed instead error is seen in Argo CD UI 

**Screenshots**

![image](https://user-images.githubusercontent.com/73496952/125119060-8a156c80-e0be-11eb-8985-5a56db769209.png)

**Version**

```shell
argocd@argocd-server-744cbfb89-rn5b4:~$ argocd version
argocd: v2.0.4+0842d44
  BuildDate: 2021-06-23T01:27:53Z
  GitCommit: 0842d448107eb1397b251e63ec4d4bc1b4efdd6e
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
```

**Comment by sidewinder12s** [comment] 2021-08-05 19:49
I thought I was only running into permissions issues when trying to use a range with Harbor OCI (It has some RBAC bugs) but it appears that might not be the only issue. Mine fails with:

```
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `helm chart pull harbor.cloud.aurora.tech/helm/aws-core:2.0.*` failed exit status 1: Error: unexpected status code [manifests 2.0.*]: 401 Unauthorized
```

So, I'm not sure what API path ArgoCD is attempting to resolve. I was assuming this is the _catalog endpoint under the hood in the registry API.

**Comment by suresh-sivanantham-irm** [comment] 2021-08-05 19:59
@sidewinder12s I think this issue is not specific to argocd but it is how OCI charts work in helm as of now. Helm charts backed by OCI registry requires version

So if we need to use wildcards, we need to move away from OCI registry.

ref: https://github.com/helm/helm/blob/88554882726eaec7a9949fadc5bd77265ab611f2/internal/resolver/resolver.go#L124

**Comment by sidewinder12s** [comment] 2021-08-05 22:24
That seems like a.... big regression compared to non-OCI :sob: 

https://github.com/helm/helm/issues/9694

**Comment by erickaby** [comment] 2022-04-05 00:19
This issue still exists in `v2.3.3`. Argocd's autosync and new application manifests work with OCI version ranges from examples in this PR https://github.com/helm/helm/pull/10527.

However when running manual sync through either the UI or CLI we get an error of:
```
Unable to deploy revision: rpc error: code = Unknown desc = Get "harbor.example.com/index.yaml": unsupported protocol scheme ""
```

The current state is okay, but for whatever reason an autosync fails it is not possible to recover without having to edit the application manifest and apply a static version, syncing, then edit the manifest back to the OCI version range.

**Comment by pkrishnath** [comment] 2022-04-26 10:55
Even though if are using latest helm version using download-tools init container , argocd-server still throws above exception when we click on sync button , Only workaround  is , hitting hard refresh via UI !!

**Comment by pkrishnath** [comment] 2022-04-26 10:55
Even though if are using latest helm version using download-tools init container , argocd-server still throws above exception when we click on sync button , Only workaround  is , hitting hard refresh via UI !!

**Comment by rowi1de** [comment] 2022-05-27 10:55
Helm is able to pull from OCI without any version:

```shell 
helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.0.15
Digest: sha256:bc6290e6daa73fdb4f4db0aa0c7b8e79f04b42599e4c5c4c73bb3c2d1aaf1fed
```

ArgoCD just doesn’t support it.
Also see  https://github.com/argoproj/argo-cd/discussions/9509

**Comment by hrobertson** [comment] 2022-06-21 15:51
@suresh-sivanantham-irm since https://github.com/helm/helm/pull/10527 this should be able to work.

My charts are all private so I'll use rowi1de's as an example with a semver `~` constraint:
```
$ helm pull oci://ghcr.io/rowi1de/graphql-reactive/graphql-reactive --version "~0.1.0"
Pulled: ghcr.io/rowi1de/graphql-reactive/graphql-reactive:0.1.13
Digest: sha256:792b75098737288ebd432811205b2c2fd33697eb2c97e0c1fe7d962b382e5301
```
Thanks!

**Comment by hrobertson** [comment] 2022-06-21 23:20
Perhaps ArgoCD could use the helm registry package.
https://pkg.go.dev/helm.sh/helm/v3/pkg/registry#Client.Tags

**Comment by jmabecassis** [comment] 2022-08-11 16:01
+1 for having OCI helm urls + Wildcard tag tracking working on ArgoCD.
Is there an ETA on the Argo side to have this fixed by any chance? We desperately need it for what we are implemented...

**Comment by alexef** [comment] 2022-09-19 23:08
I'm taking a stab at it in https://github.com/argoproj/argo-cd/pull/10641 - feedback is welcome.

**Closed** 2022-11-25 21:51 UTC
Labels: bug

**Comment by rowi1de** [comment] 2022-11-26 06:45
@crenshaw-dev awesome , thanks for fixing 🚀

**Comment by ahaw023** [comment] 2023-02-13 05:16
carets also work ^ and are apparently closer to what SemVer specs recommend
