### ISSUE TITLE
SealedSecret status stuck "Progressing" even when unsealed successfully

### ISSUE THREAD

**Issue by mbouchenoire** [argoproj/argo-cd#5991] opened 2021-04-08 10:31 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading to `v2.0.0`, SealedSecret resources are stuck in the "Progressing" state, even when the secret was unsealed successfully by the controller.

**To Reproduce**

1. Install `quay.io/bitnami/sealed-secrets-controller:v0.15.0`
2. Create an Argo CD Application containing a `SealedSecret` resource
3. Wait for the resource to be synced by Argo CD and unsealed by the controller
4. The `SealedSecret` managed by Argo CD has a "Progressing" health and "Waiting for Sealed Secret to be decrypted" as health details

**Expected behavior**

The `SealedSecret` health should be "Healthy"

**Screenshots**

![Screenshot from 2021-04-08 12-08-19](https://user-images.githubusercontent.com/8810050/114009541-8544e080-9863-11eb-85d1-5275b6ff943d.png)

The `SealedSecret` manifest:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"bitnami.com/v1alpha1","kind":"SealedSecret","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"xxxx"},"name":"xxxxx","namespace":"xxxxx"},"spec":{"encryptedData":{"xxxxx"}}}}
  creationTimestamp: '2021-03-29T17:40:00Z'
  generation: 1
  labels:
    app.kubernetes.io/instance: secrets-v3-1
  name: xxxxx
  namespace: xxxxx
  resourceVersion: '239233797'
  selfLink: /apis/bitnami.com/v1alpha1/namespaces/xxxxx/sealedsecrets/xxxxx
  uid: e66a6863-4b1d-43f2-96e0-fc687cdaabd6
spec:
  encryptedData:
    xxxxxxx
  template:
    metadata:
      creationTimestamp: null
      name: xxxxx
      namespace: xxxxx
```

**Version**

```json
{
    "Version": "v2.0.0+f5119c0",
    "BuildDate": "2021-04-07T06:00:33Z",
    "GitCommit": "f5119c06686399134b3f296d44445bcdbc778d42",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
```

**Comment by queil** [comment] 2021-04-08 10:33
@mbouchenoire Thanks for that. We've upgraded to v2.0 2 minutes ago and facing the same issue.

**Comment by queil** [comment] 2021-04-08 10:43
It looks like [the lua script](https://github.com/argoproj/argo-cd/pull/5503/commits/139a2a59d231a8a1f734697ca3330382ac9f8a3f) checks the `status` field. However, in our case `status` is empty.

**Comment by jannfis** [comment] 2021-04-08 11:18
Hey - you checked "I've searched the FAQ" but you seem to have missed https://argo-cd.readthedocs.io/en/stable/faq/#why-are-resources-of-type-sealedsecret-stuck-in-the-progressing-state :)

**Comment by queil** [comment] 2021-04-08 11:25
@jannfis Yeah, we also have just found it in Sealed Secrets [release notes](https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0150). Thanks

**Comment by mbouchenoire** [comment] 2021-04-08 11:58
> Hey - you checked "I've searched the FAQ" but you seem to have missed https://argo-cd.readthedocs.io/en/stable/faq/#why-are-resources-of-type-sealedsecret-stuck-in-the-progressing-state :)

Indeed ! I think I made this mistake because I assumed the answer would be included in this chapter : [Why is my application stuck in Progressing state?](https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-application-stuck-in-progressing-state). Is it worth considering merging these two ?

Tank you for the link :)

**Comment by jannfis** [comment] 2021-04-08 12:15
@mbouchenoire Yeah, good suggestion about merging them - or at least, linking to the SealedSecrets FAQ entry from the "Why is my application stuck..." one. Do you mind sending a PR?

Also, we hoped for SealedSecrets to release v0.16.0 (which is supposed to have the status update enabled by default again) before our 2.0 release. Unfortunately, we were quicker :)

**Comment by jef** [comment] 2021-04-13 05:17
Related: https://github.com/bitnami-labs/sealed-secrets/issues/555, https://github.com/argoproj/argo-cd/issues/5971

**Comment by YevheniiPokhvalii** [comment] 2021-05-25 15:42
This might help:

Set the SEALED_SECRETS_UPDATE_STATUS variable to "1" in the sealed-secrets deployment yaml file https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml

```
apiVersion: apps/v1
kind: Deployment
```
```
    spec:
      containers:
      - args: []
        command:
        - controller
        env:
        - name: SEALED_SECRETS_UPDATE_STATUS
          value: "1"
```

**Comment by jef** [comment] 2021-05-27 15:22
Yep, looks like this is fixed now in the latest v0.16.0 release. Either use the env var like @YevheniiPokhvalii mentioned or the `--update-status` flag. It should be on by default in v0.17.0.

**Comment by haim-ari** [comment] 2021-08-01 08:41
I'm using flux to install sealed-secrets with Helm Release.

```bash
helm search repo sealed-secrets/sealed-secrets --versions
```

```
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
sealed-secrets/sealed-secrets	1.16.1       	v0.16.0    	Helm chart for the sealed-secrets controller.
sealed-secrets/sealed-secrets	1.16.0       	v0.16.0    	Helm chart for the sealed-secrets controller.
sealed-secrets/sealed-secrets	1.13.2       	0.13.1     	A Helm chart for Sealed Secrets
```

I upgraded to 1.16.1 (app v.0.16.0) and added the following:

```yaml
  chart:
    spec:
      chart: sealed-secrets
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  interval: 10m
  values:
    fullnameOverride: sealed-secrets-controller
    controller:
      env:
      - name: SEALED_SECRETS_UPDATE_STATUS
        value: "1"
```

but when I'm checking the `deployment` I don't see the Env Var added even though I can see that the controller was restarted:

```
pod/sealed-secrets-controller-68f997cf86-xg2gs   1/1     Running   0          37m
service/sealed-secrets-controller            ClusterIP   10.43.123.203   <none>        8080/TCP                       24d
deployment.apps/sealed-secrets-controller   1/1     1            1           24d
replicaset.apps/sealed-secrets-controller-5c56b54f8f   0         0         0       24d
replicaset.apps/sealed-secrets-controller-68f997cf86   1         1         1       37m
```

Should I manually delete the crd :

`sealedsecrets.bitnami.com                                    2021-05-25T07:44:35Z`

What is the right way to set `--update-status` with Helm ?

**Comment by ismailyenigul** [comment] 2021-08-01 15:43
Hi @haim-ari 
I had the same issue on argo-cd.
Just upgrade sealed-secrets to 1.16.1 helm char with the following value `commandArgs`.  then argocd stop progressing and reports Healthy. 

```
# secretName: The name of the TLS secret containing the key used to encrypt secrets
secretName: "sealed-secrets-key"
commandArgs:
  - "--update-status"
 ```

**Comment by haim-ari** [comment] 2021-08-01 16:22
> Hi @haim-ari
> I had the same issue on argo-cd.
> Just upgraded sealed-secrets to 1.16.1 helm chart with the following value `commandArgs`. then argocd stop progressing and reports Healthy.
> 
> ```
> # secretName: The name of the TLS secret containing the key used to encrypt secrets
> secretName: "sealed-secrets-key"
> commandArgs:
>   - "--update-status"
> ```

Yes, I tried that as well, same result:
```
Waiting for Sealed Secret to be decrypted
```
But a new secret was created successfully:

```
type: 'Normal' reason: 'Unsealed' SealedSecret unsealed successfully
```

**Comment by haim-ari** [comment] 2021-08-01 17:04
Seems that this was related to CRD somehow (not sure why but could be related to the fact that this is was an upgrade of Helm) 
removed the CRD and manually added it back.

Now ArgoCD shows the correct state.

**Comment by haim-ari** [comment] 2021-08-01 17:15
I can confirm this also worked on another cluster.
After deleting and re-creating CRD.

**Comment by shibumi** [comment] 2021-08-05 14:45
@haim-ari  you said you added a new command flag to sealed-secrets version 1.16.1. However, I cannot find it in the sealed secrets repository:

https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets

Did you speak about a private fork?

**Comment by iyenigul** [comment] 2021-08-05 15:37
Hi @shibumi 
yes simply we are adding value to `commandArgs` in values.yml of helm chart
it is defined at https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L49

**Comment by ismailyenigul** [comment] 2021-08-05 15:38
Hi @shibumi 
yes simply we are adding value to `commandArgs` in values.yml of helm chart
it is defined at https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L49

**Comment by pmorch** [comment] 2021-09-03 10:27
I can confirm that this works:

```
$  helm upgrade --install --namespace kube-system sealed-secrets-controller sealed-secrets/sealed-secrets \
     --version 1.16.1 --set 'commandArgs[0]=--update-status'
```

My `SealedSecret`-s are no longer progressing

**Comment by ismailyenigul** [comment] 2021-12-10 13:42
> removed the CRD and manually added it back.

I experienced the same issue. I deleted helm chart that already had `--update-status` and created again 
but argo-cd was still reporting `Waiting for Sealed Secret to be decrypted`
deleting manually CRD did not help.
deleted with helm uninstall did not help too.

I deleted everything about sealed-secret with
kubectl delete -f `https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml` 
and created with
`kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml`
not argo-cd reports Healthy and stop infinitive progressing!

deleted again with kubectl and installed with helm and it is still good.
I don't understand what is going on with CRD but it is definitely a CRD issue!

**Comment by dirien** [comment] 2021-12-31 19:03
Hi @ismailyenigul @haim-ari @shibumi,

can confirm with the `commandArgs` is working fine! Finally no Lua stuff needed :) thanks!

**Comment by anggutie-dev** [comment] 2022-01-10 18:10
upgrading sealed secrets tov0.17.1 did the trick, Argocd is now showing "Healthy"

**Comment by dirien** [comment] 2022-01-10 18:18
Hi @anggutie-dev, so its safe to use the latest version of the chart?

**Comment by vaibhavjain882** [comment] 2022-01-18 13:59
> Hi @ismailyenigul @haim-ari @shibumi,
> 
> can confirm with the `commandArgs` is working fine! Finally no Lua stuff needed :) thanks!

What are you getting in your sealed secret object events in the agro UI? I can see it is healthy but in the events, its shows "Failed to unseal: no key could decrypt secret".

**Comment by ismailyenigul** [comment] 2022-01-18 14:08
> Hi @anggutie-dev, so its safe to use the latest version of the chart?

Yes. because it is not sealed-secret code update. it is just helm update.

**Comment by ismailyenigul** [comment] 2022-01-18 14:09
> > Hi @ismailyenigul @haim-ari @shibumi,
> > can confirm with the `commandArgs` is working fine! Finally no Lua stuff needed :) thanks!
> 
> What are you getting in your sealed secret object events in the agro UI? I can see it is healthy but in the events, its shows "Failed to unseal: no key could decrypt secret".

This is not something about sealed-secrets configuration. 
Maybe you signed secret with non-existed key or sealed for different namespace.
How did you create this key?

**Comment by MaxWinterstein** [comment] 2022-01-29 14:37
Same here, after few rollouts it was stuck while waiting for something of sealed sealed secrets.

Updating from `1.6.x` to `1.7.3` seems to fix it for me.

**Comment by TobiasGoerke** [comment] 2022-03-31 12:20
> Same here, after few rollouts it was stuck while waiting for something of sealed sealed secrets.
> 
> Updating from `1.6.x` to `1.7.3` seems to fix it for me.

Can confirm, the current version of SealedSecrets does not cause this issue (though the correct version is v0.17.3)

**Comment by crenshaw-dev** [comment] 2023-07-07 15:04
Looks like there's a documented workaround for <=1.16 and everything Just Works in >=0.17. Let me know if I need to reopen!

**Closed by crenshaw-dev** 2023-07-07 15:04 UTC
Labels: bug
