### ISSUE TITLE
Trigger argocd pipeline on every new image push

### ISSUE THREAD

**Issue by chiragthaker** [argoproj/argo-cd#2532] opened 2019-10-21 18:13 UTC
We are doing CI in Google cloud , using cloudbuild and pushing containers to GCR.

We are using helm charts for application and have started evaluating argocd for deployment to multiple GKE clusters.

SO i have source Code in seperate repo and application manifests or helm chart in my GitOps repo which is synced to argocd .

My question is how do i trigger pipeline based on my image sha whenever there is a new image pushed to the GCR , how does Gitops repo know about the sha of the image or even how to acheive this ?
Any guide document etc would really help , cannot see much on documentation right now.

**Comment by simster7** [comment] 2019-10-21 19:18
You can use [Auto-Sync](https://argoproj.github.io/argo-cd/user-guide/auto_sync/).

Whenever you push a new image, you will have to update your deployment repo with the new image tag. With Auto-Sync, whenever your deployment repo is updated Argo will perform a new sync.

Does this help?

**Comment by chiragthaker** [comment] 2019-10-21 19:25
Sure about auto-sync but i dont want dev to update image in gitops repo every single time whenever there is new image , i am trying to find a way to automate it from ci stage itself like hook or something which takes image sha and update the tag

**Comment by simster7** [comment] 2019-10-21 19:34
> i am trying to find a way to automate it from ci stage itself like hook or something which takes image sha and update the tag

See [Automation from CI Pipelines](https://argoproj.github.io/argo-cd/user-guide/ci_automation/)

The way to do this is by using Jenkins or some similar CI/Job platform. For example, when commiting to master, your CI job would build the image and then update the deployment repo with the new tag automatically.

**Comment by simster7** [comment] 2019-10-24 15:57
Closing this, feel free to reopen if needed

**Closed by simster7** 2019-10-24 15:57 UTC
Labels: enhancement

**Comment by alexec** [comment] 2019-10-24 16:29
I think this is a dupe of another ticket.  #1648 ?

**Comment by chiragthaker** [comment] 2019-10-24 20:03
@alexec - any plans to fix that ticket #1648 ?
We are planning to use argocd in production but this is blocking us to use it

**Comment by alexec** [comment] 2019-10-24 20:56
Please see my comment for how to do this in that ticket. In short - we recommend you pin your tags in production and have the CI commit the updated tag to your manifests

**Comment by unckleg** [comment] 2021-10-31 04:38
Any news ?

**Comment by shimont** [comment] 2022-01-09 17:58
A much needed feature :)

**Comment by survivant** [comment] 2022-02-04 20:06
just to be sure.  Argocd doesn't have a hook that I could call from Jenkins to tell ArgoCD to start a sync ?  I know of the auto-sync feature, that I use.  I use the default 3 min sync.  Most of the time the develops won't push code that often, but when they do, they want to see there modification asap in the cluster.

It will be useful to notify argocd to start syncing for an Application on demand.

**Comment by hichamov** [comment] 2022-02-14 09:40
You can update your deployment file with you ci tool by using 'yq' tool.

**Comment by survivant** [comment] 2022-02-14 13:20
@hichamov that will be pickup on the next sync (each 3 minutes), so it will not launch it right away.

**Comment by ksaffarian** [comment] 2022-07-28 13:43
> Like argocd checks the git repo for changes, it should also check the docker registry for changes to the image. For example, if the kubernetes manifest says `myimage:latest` then argocd should periodically check whether the sha256 of the currently running image is same as sha256 of `myimage:latest`. If different, it should pull and deploy the new image.

Is "ArgoCD Image Updater" a suitable solution for you? https://argocd-image-updater.readthedocs.io/en/stable/

**Comment by moriyahazan** [comment] 2022-09-15 10:29
> Like argocd checks the git repo for changes, it should also check the docker registry for changes to the image. For example, if the kubernetes manifest says `myimage:latest` then argocd should periodically check whether the sha256 of the currently running image is same as sha256 of `myimage:latest`. If different, it should pull and deploy the new image.

This can be achieved only by `argocd-image-updater`, right?

**Comment by rcfja** [comment] 2022-10-03 20:39
Keel can also solve this problem - https://keel.sh

**Comment by joelgriffiths** [comment] 2022-10-14 17:37
> This can be achieved only by `argocd-image-updater`?
This is not production ready, and it hasn't been updated in months.

The fact that ArgoCD doesn't do this out of the box is mind-blowing to me.

**Comment by ileixe** [comment] 2022-11-18 00:48
How would other deal with this problem? I think it's core primitive to achieve "continuous deploy", and one of the most unclear part for user.

**Comment by markmcgookin** [comment] 2022-12-12 14:23
I am also in this situation. I am aware that this will be picked up every 3 minutes or so... but I've seen some delays in this. I just did an experiment there. Updated the repo with a new image tag and it took 5m 34s for the sync to kick off. We are using azure devops for builds, but source is in github, so I can use github webhooks to post to our argo instance if need be, but I don't know of any endpoint in the argo setup that I could hit. Is there such a thing?

**Comment by tirelibirefe** [comment] 2023-11-24 10:54
> We are doing CI in Google cloud , using cloudbuild and pushing containers to GCR.
> 
> We are using helm charts for application and have started evaluating argocd for deployment to multiple GKE clusters.
> 
> SO i have source Code in seperate repo and application manifests or helm chart in my GitOps repo which is synced to argocd .
> 
> My question is how do i trigger pipeline based on my image sha whenever there is a new image pushed to the GCR , how does Gitops repo know about the sha of the image or even how to acheive this ? Any guide document etc would really help , cannot see much on documentation right now.

Spinnaker works that way. I have been using this feature on dozens of pipelines. When a new image is pushed into ECR repo, the pipeline starts automatically. "Image.tag" in Helm Chart is just a #var in  Helm Chart. Spinnaker replace tag variable with the new image tag in the ECR repository.

**Comment by joebowbeer** [comment] 2023-11-24 17:14
[Kargo](https://github.com/akuity/kargo) leverages ArgoCD's image updater
