### ISSUE TITLE
Parameters passed declaratively needs to be quoted

### ISSUE THREAD

**Issue by MeNsaaH** [argoproj/argo-cd#4428] opened 2020-09-25 11:39 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Parameters passed to helm's chart declaratively needs to be quoted

**To Reproduce**
This works
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.4
    chart: redis
    helm:
      releaseName: redis
      parameters:
        - name: "usePassword"
          value: "false"
        - name: "cluster.slaveCount"
          value: "1"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
But when I use the manifests below it fails
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.4
    chart: redis
    helm:
      releaseName: redis
      parameters:
        - name: "usePassword"
          value: false
        - name: "cluster.slaveCount"
          value: 1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Expected behavior**

Passing variables without quotes should infer the type of the variables

**Error**

```
The Application "redis" is invalid: 
* spec.source.helm.parameters.value: Invalid value: "boolean": spec.source.helm.parameters.value in body must be of type string: "boolean"
* spec.source.helm.parameters.value: Invalid value: "integer": spec.source.helm.parameters.value in body must be of type string: "integer"

```

**Version**
 1.7.6 Installed from Helm's Chart version 2.7.4

**Comment by alexmt** [comment] 2020-09-25 16:15
The helm parameters eventually translated to `helm template --set` so all parameters either way must be formatted as strings. There is an opposite issue: values like '1' or 'true' will be converted to integer or boolean. To force string type you can use `forceString`:

```yaml
      parameters:
        - name: "usePassword"
          value: "false"
          forceString: true
```

Add example to documentation: https://github.com/argoproj/argo-cd/pull/4431/files

**Comment by MeNsaaH** [comment] 2020-09-25 23:30
Also the error should be more clear. It should state the values been affected if possible.

**Comment by MeNsaaH** [comment] 2020-09-25 23:32
I'll like to work on the error string. Can you please help point me to any useful resource @alexmt in the code I can start from

**Comment by Keralin** [comment] 2020-10-15 09:50
I'm using ArgoCD 1.7.7 version and this behaviour it's happenning.
```yaml
- name: "HTTProxy.create"
  value: "false"
  forceString: true
```

And the answer from ArgoCD stills like @MeNsaaH 
```bash
spec.source.helm.parameters.value: Invalid value: "boolean": spec.source.helm.parameters.value in body must be of type string: "boolean"

I'm doing something wrong? Looks like this is the way to solve this problem but looks like it isn't working.

**Comment by michaelessaf** [comment] 2023-01-13 17:11
I ran in to a similar problem when using a _Helm Template_ to resolve the value in my Argo Application Helm chart. If you are using the App-of-Apps pattern it's likely you will be doing this. 
When using a template, the `forceString` option didn't work, neither did piping the value result to the  `toString` function. The issue is that the helm template that you render will still have your values unquoted even if they are taken as strings. Since Argo specifically expects quoted strings, I piped the result of my query into the `| quote` function, which works! For example: 
`values.yaml`
```
clusters:
  formal_cluster_name:
     flag: false
```
`app-of-apps.yaml`
```     
parameters:
- name: flag_enabled
  value: {{ index $.Values.clusters $formal_cluster_name "flag_enabled"  | quote }}
```
results in this rendered template, with quotes:
```
parameters:
- name:flag_enabled
  value: "false"
```

**Comment by disparo13** [comment] 2023-05-01 12:58
@alexmt I must say it: forcing people to convert all their variables to strings is unnecessary and unprofessional!

Instead of using just

`{{- if eq .Values.create_appset_application }}`

I have to use

`{{- if eq (default "false" .Values.create_appset_application) "true" }}`

in my template!

**Comment by vl-kp** [comment] 2023-06-13 02:05
how to control syncPolicy.automated.prune and syncPolicy.automated.selfHeal

**Comment by V2arK** [comment] 2024-10-17 20:52
for argocd, something like the following should work:
```
params.append({"name": k, "value": str(v) if v is not None else None, "forceString": isinstance(v, str)})
```

**Comment by crenshaw-dev** [comment] 2024-10-17 21:03
> forcing people to convert all their variables to strings is unnecessary and unprofessional

It's necessary. Argo CD passes parameters to the Helm CLI using golang's `exec.Command` utility. That utility [only accepts strings](https://pkg.go.dev/os/exec#Command). When you invoke `helm template` in a CLI, you're passing it strings. Helm then interprets those strings as best it can. This is just a limitation of how CLIs work. The CRD's typing is consistent with the underlying behavior. To accept non-string types, we'd probably need to implement a custom type with a custom unmarshaler. The UX would probably be worse than the simple requirement "use a string."

If you're using Helm to generate an Application resource (or any CR for that matter), you must be careful to quote booleans that you're using in string fields (such as parameters.value) and not quote booleans that you're using in non-string fields (such as syncPolicy.automated.prune).

Closing since the issue seems to be mostly about using Helm to generate Applications, and the answer is: "make sure Helm produces a YAML string."

**Closed by crenshaw-dev** 2024-10-17 21:03 UTC
Labels: enhancement, component:ui
