### ISSUE TITLE
CiliumIdentiy resource being marked as OutOfSync

### ISSUE THREAD

**Issue by luismiguelsaez** [argoproj/argo-cd#11080] opened 2022-10-26 18:09 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After upgrading from ArgoCD v2.4.11 to v2.5.0 with the Helm chart version 5.8.0, most of the applications ( defined from Application resource ) are continuously OutOfSync. It seems that the `CiliumIdentity` resources are being removed, because if I check `OutOfSync` resources for the application in the UI, I always see the `CiliumIdentity` maked as `Out of sync, needs prune`.

For some reason, ArgoCD v2.5.0 is taking `CiliumIdentity` resources into account, whereas previous version was ignoring them.

**To Reproduce**

- Update a cluster with Cilium as CNI from ArgoCD v2.4.x version to v2.5.0 ( Helm chart 5.4.3 to 5.8.0 )
- Wait for all components to be updated and running
- Check applications to see if they are always in an `OutOfsync` status
- Check application details and filter by state `OutOfsync`
- Check that `CiliumIdentity` resource is always out of sync

**Expected behavior**

The new version is deployed and all the previously synced applications remains in the same status

**Screenshots**

N/A

**Version**

```shell
argocd: v2.4.15+05acf7a.dirty
  BuildDate: 2022-10-17T22:41:03Z
  GitCommit: 05acf7a52e377eacfee29c68e3e5e79a172ea013
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.0+b895da4
```

**Logs**

- Application controller logs ( debug )
```
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Initialized new operation: {\u0026SyncOperation{Revision:1.4.3,Prune:true,DryRun:false,SyncStrategy:nil,Resources:[]SyncOperationResource{SyncOperationResource{Group:cilium.io,Kind:CiliumIdentity,Name:22681,Namespace:,},},Source:nil,Manifests:[],SyncOptions:[Validate=true CreateNamespace=true PrunePropagationPolicy=foreground PruneLast=true SkipDryRunOnMissingResource=true],} { true} [] {10 \u0026Backoff{Duration:5s,Factor:*2,MaxDuration:2m,}}}","time":"2022-10-27T05:47:04Z"}
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Tasks from managed resources","resourceTasks":"[Sync/0 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)]","syncId":"00046-iSDMw","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Tasks (dry-run)","syncId":"00046-iSDMw","tasks":"[Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)]","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","dryRun":true,"level":"info","msg":"Pruning","syncId":"00046-iSDMw","task":"Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Filtering out non-pending tasks","syncId":"00046-iSDMw","tasks":"[Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)]","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Filtering tasks in correct phase and wave","phase":"Sync","syncFailTasks":"[]","syncId":"00046-iSDMw","tasks":"[Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)]","time":"2022-10-27T05:47:05Z","wave":1}
{"application":"argocd/aws-load-balancer-controller","level":"info","msg":"Wet-run","syncId":"00046-iSDMw","tasks":"[Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)]","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","dryRun":false,"level":"info","msg":"Pruning","syncId":"00046-iSDMw","task":"Sync/1 resource cilium.io/CiliumIdentity:/22681 obj-\u003enil (,,)","time":"2022-10-27T05:47:05Z"}
{"level":"debug","msg":"Refreshing app argocd/aws-load-balancer-controller for change in cluster of object (cluster-scoped)/22681 of type cilium.io/v2/CiliumIdentity","time":"2022-10-27T05:47:05Z"}
{"application":"argocd/aws-load-balancer-controller","kind":"CiliumIdentity","level":"info","msg":"Adding resource result, status: 'Pruned', phase: 'Succeeded', message: 'pruned'","name":"22681","namespace":"","phase":"Sync","syncId":"00046-iSDMw","time":"2022-10-27T05:47:05Z"}
{"level":"debug","msg":"Refreshing app argocd/aws-load-balancer-controller for change in cluster of object (cluster-scoped)/22681 of type cilium.io/v2/CiliumIdentity","time":"2022-10-27T05:47:05Z"}
{"level":"debug","msg":"Refreshing app argocd/aws-load-balancer-controller for change in cluster of object (cluster-scoped)/22681 of type cilium.io/v2/CiliumIdentity","time":"2022-10-27T05:47:05Z"}
```

- Cilium agent logs
```
level=warning msg="Unable update CRD identity information with a reference for this node" error="identity (id:\"561\",key:\"[k8s:app.kubernetes.io/component=controller k8s:app.kubernetes.io/instance=ingress-nginx-internal k8s:app.kubernetes.io/name=ingress-nginx k8s:infra/app=ingress-nginx-internal k8s:infra/component=controller k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress-internal k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx-internal k8s:io.kubernetes.pod.namespace=ingress-internal]\") does not exist" identity=561 labels="[k8s:app.kubernetes.io/component=controller k8s:app.kubernetes.io/instance=ingress-nginx-internal k8s:app.kubernetes.io/name=ingress-nginx k8s:infra/app=ingress-nginx-internal k8s:infra/component=controller k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress-internal k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx-internal k8s:io.kubernetes.pod.namespace=ingress-internal]" subsys=crd-allocator

level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ingress-internal]" subsys=crd-allocator

level=warning msg="Unable update CRD identity information with a reference for this node" error="identity (id:\"4349\",key:\"[k8s:app.kubernetes.io/component=controller k8s:app.kubernetes.io/instance=ingress-nginx-internet-facing k8s:app.kubernetes.io/name=ingress-nginx k8s:infra/app=ingress-nginx-internet-facing k8s:infra/component=controller k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress-internet-facing k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx-internet-facing k8s:io.kubernetes.pod.namespace=ingress-internet-facing]\") does not exist" identity=4349 labels="[k8s:app.kubernetes.io/component=controller k8s:app.kubernetes.io/instance=ingress-nginx-internet-facing k8s:app.kubernetes.io/name=ingress-nginx k8s:infra/app=ingress-nginx-internet-facing k8s:infra/component=controller k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=ingress-internet-facing k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=ingress-nginx-internet-facing k8s:io.kubernetes.pod.namespace=ingress-internet-facing]" subsys=crd-allocator

level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ingress-internet-facing]" subsys=crd-allocator

level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager

level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager

level=warning msg="Unable update CRD identity information with a reference for this node" error="identity (id:\"13071\",key:\"[k8s:app.kubernetes.io/component=metrics k8s:app.kubernetes.io/instance=prometheus-stack k8s:app.kubernetes.io/managed-by=Helm k8s:app.kubernetes.io/name=kube-state-metrics k8s:app.kubernetes.io/part-of=kube-state-metrics k8s:app.kubernetes.io/version=2.6.0 k8s:helm.sh/chart=kube-state-metrics-4.18.0 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=monitoring k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=prometheus-stack-kube-state-metrics k8s:io.kubernetes.pod.namespace=monitoring k8s:release=prometheus-stack]\") does not exist" identity=13071 labels="[k8s:app.kubernetes.io/component=metrics k8s:app.kubernetes.io/instance=prometheus-stack k8s:app.kubernetes.io/managed-by=Helm k8s:app.kubernetes.io/name=kube-state-metrics k8s:app.kubernetes.io/part-of=kube-state-metrics k8s:app.kubernetes.io/version=2.6.0 k8s:helm.sh/chart=kube-state-metrics-4.18.0 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=monitoring k8s:io.cilium.k8s.policy.cluster=dev-lok-k8s-main k8s:io.cilium.k8s.policy.serviceaccount=prometheus-stack-kube-state-metrics k8s:io.kubernetes.pod.namespace=monitoring k8s:release=prometheus-stack]" subsys=crd-allocator

level=info msg="Skipped non-kubernetes labels when labelling ciliumidentity. All labels will still be used in identity determination" labels="map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:monitoring]" subsys=crd-allocator

level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
level=info msg="regenerating all endpoints" reason="one or more identities
```

**Comment by luismiguelsaez** [comment] 2022-10-28 05:45
Found this fix in [Cilium docs](https://docs.cilium.io/en/stable/configuration/argocd-issues/#argo-cd-deletes-customresourcedefinitions)

It fixed the issue applying that configuration, but I don't understand why we didn't experience this issue with previous ArgoCD versions <v2.5.0 and same identical Cilium configuration and version.

It is still worth to keep this issue open?

**Comment by cedi** [comment] 2022-10-28 17:47
Can confirm the fix @luismiguelsaez mentioned works. I was running into the same issue as OP when updating my cluster with Cilium from v2.4.* to v2.5.
Never experienced this behaviour before.
feels I have to mention this: I did not install cilium via ArgoCD in the first place, but via the cilium-cli. I only reconcile the cilium config via ArgoCD.

**Comment by lukas-unity** [comment] 2022-11-09 10:23
I've had this same issue with 2.4.14 and fixed it by adding `resource.exclusions` that's mentioned above.

**Comment by jgwest** [comment] 2024-02-13 15:32
Dupe of https://github.com/argoproj/argo-cd/issues/10456

**Closed by jgwest** 2024-02-13 15:32 UTC
Labels: bug
