### ISSUE TITLE
Skip health check on aggregate API (template.openshift.io)

### ISSUE THREAD

**Issue by kevchu3** [argoproj/argo-cd#6241] opened 2021-05-14 17:36 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

I've created an ArgoCD application that creates a project template CRD defined by template.openshift.io [^1].  The template CRD deploys just fine, but it shows a state of OutOfSync because there is no app healthcheck.  Thus, the entire resource that's created shows up in the diff, so setting spec.ignoreDifferences [^2] doesn't seem to apply.

It makes sense to create a custom health check for this resource type [^3], but I noticed that my template.openshift.io doesn't have a status field.  The template CRD doesn't capture any state, and the resource either exists or not.  Thus, is there a way to disable the health check for a given resource to prevent the OutOfSync state?

As a use case, it makes sense to apply a project template to a cluster, whether it be to set up multitenancy as a NetworkPolicy [^4], or to apply ResouurceQuotas and LimitRanges to developer namespaces [^5].  ArgoCD would be a sensible choice of applying these day 2 infrastructure configurations.

[^1]: https://docs.openshift.com/container-platform/4.7/rest_api/template_apis/template-template-openshift-io-v1.html
[^2]: https://argoproj.github.io/argo-cd/user-guide/diffing/
[^3]: https://argoproj.github.io/argo-cd/operator-manual/health/#custom-health-checks
[^4]: https://docs.openshift.com/container-platform/4.7/networking/network_policy/default-network-policy.html
[^5]: https://docs.openshift.com/container-platform/4.7/applications/quotas/quotas-setting-per-project.html#configuring-explicit-resource-quotas_quotas-setting-per-project

**To Reproduce**

The template.openshift.io CRD is part of OpenShift, so this issue is reproduced via the `oc cli` as follows:
```
oc adm create-bootstrap-project-template -o yaml > template.yaml
oc apply -f template.yaml
```

In the ArgoCD UI, the resource shows it is successfully synced, but the template stays in Running state and status shows:
```
waiting for healthy state of template.openshift.io/Template/project-request
```

**Expected behavior**

Using some sort of annotation, one would expect to be able to skip the health check once the resource is created, so that the resource can successfully complete its sync.  Creating a custom health check for this CRD doesn't make sense, because there is no status field to query off of.

**Version**

ArgoCD 2.0.0

**Comment by jessesuen** [comment] 2021-05-14 20:26
This might be a specific bug/interaction with openshift. @sbose78 is there someone on your team who can take a look at this?

**Comment by iam-veeramalla** [comment] 2021-05-18 11:29
@jannfis @jessesuen @sbose78 I can take a look at this. Please assign this to me:)

**Comment by jannfis** [comment] 2021-05-18 11:35
Thanks @iam-veeramalla

**Comment by iam-veeramalla** [comment] 2021-05-19 03:42
Hi @kevchu3 ,

Thanks for raising an issue with us :).  Can you try using OpenShift **_Template Instance_** instead of OpenShift _Templates_?
**Reference:**
https://docs.openshift.com/container-platform/4.7/rest_api/template_apis/template-apis-index.html

**TemplateInstance requests and records the instantiation of a Template.**

**Comment by sbose78** [comment] 2021-05-19 04:50
Abhishek, thanks for chipping in!

 I wonder if Kevin is actually speaking about skipping the health check on creation of a Template object ( and not necessarily the TemplateInstance object ). Could we also retitle the issue accordingly?

Do note that the Template API is not a CRD, it is an aggregated API.

**Comment by iam-veeramalla** [comment] 2021-05-19 06:25
> Abhishek, thanks for chipping in!
> 
> I wonder if Kevin is actually speaking about skipping the health check on creation of a Template object ( and not necessarily the TemplateInstance object ). Could we also retitle the issue accordingly?
> 
> Do note that the Template API is not a CRD, it is an aggregated API.

Thanks @sbose78 , I will take a look at how Argo CD handles Aggregated APIs. I do not have enough permissions to edit the title. @kevchu3 Can you edit the title accordingly :)

**Comment by kevchu3** [comment] 2021-05-19 18:04
Looking through `Template` vs `TemplateInstance`, it's unclear to me how I'd convert my `Template` object to be a `TemplateInstance` instead, and how that would work with respect to applying a using it as a project request template.  The two resources have different fields that don't map directly.

How I would use the template is it would need to be referenced here and dropped into the openshift-config namespace:
```
$ oc edit project.config.openshift.io/cluster

apiVersion: config.openshift.io/v1
kind: Project
metadata:
  ...
spec:
  projectRequestTemplate:
    name: <template_name>
```

**Comment by iam-veeramalla** [comment] 2021-05-20 02:36
> Looking through `Template` vs `TemplateInstance`, it's unclear to me how I'd convert my `Template` object to be a `TemplateInstance` instead, and how that would work with respect to applying a using it as a project request template. The two resources have different fields that don't map directly.
> 
> How I would use the template is it would need to be referenced here and dropped into the openshift-config namespace:
> 
> ```
> $ oc edit project.config.openshift.io/cluster
> 
> apiVersion: config.openshift.io/v1
> kind: Project
> metadata:
>   ...
> spec:
>   projectRequestTemplate:
>     name: <template_name>
> ```

Hi @kevchu3 ,

 I am looking at the possible ways to fix the issue :). 
 
 Coming to template instance, you need to copy the whole template into the .spec.template field of template instance. 

An Example is shown [here](https://github.com/esmallwood9/Openshift-Origin/blob/20a4c42c71536dc802c97c2f9f0db8d6025900bf/test/extended/testdata/templates/templateservicebroker_bind.yaml#L10)

You can input your template into template instance as shown [here](https://github.com/esmallwood9/Openshift-Origin/blob/20a4c42c71536dc802c97c2f9f0db8d6025900bf/test/extended/testdata/templates/templateservicebroker_bind.yaml#L16)

**Comment by kevchu3** [comment] 2021-05-20 15:33
So, I had some mixed success.  I was able to convert my Template to a TemplateInstance, and the object syncs fine in ArgoCD.  However, when I go to log in with a user and attempt to create a new project, it's unable to locate the template because it's looking for a `Template` and not a `TemplateInstance`, and the error I receive is this: `templates.template.openshift.io "multitenant-quotas-project-template" not found`.  Thus, based on my requirements, I don't think that `TemplateInstance` will work for me.

From the `openshift-config` namespace:
```
# oc get template
No resources found in openshift-config namespace.
# oc get templateinstance
NAME                                  TEMPLATE
multitenant-quotas-project-template   multitenant-quotas-project-template
```

**Comment by kevchu3** [comment] 2021-05-20 17:57
I'm trying to apply this setting as a cluster admin:
https://docs.openshift.com/container-platform/4.7/networking/network_policy/default-network-policy.html

Regular users would inherit whatever project permissions are applied by the cluster admin via the project template.

**Comment by kevchu3** [comment] 2021-06-08 18:10
@iam-veeramalla any suggestions on this?  I'm unable to replace `TemplateInstance` with `Template` as my new project creation is expecting a `Template` resource.  From my original ask, is there a way to skip the health check?

**Comment by iam-veeramalla** [comment] 2021-06-09 05:47
@kevchu3 Sorry to know this, I will update you on the feasibility by EOD :)

**Comment by iam-veeramalla** [comment] 2021-06-10 08:11
@kevchu3 Alex raised a PR #6446  to handle the resources that do not have status fields like ConfigMaps. I am checking with him if #6446 would cover Aggregated resources like Templates.

**Comment by iam-veeramalla** [comment] 2021-06-10 18:51
Thanks @jessesuen for the response. @kevchu3 can you please provide the required screenshots.

**Comment by kevchu3** [comment] 2021-06-10 19:42
I have two clusters which I was testing Red Hat OpenShift GitOps (ArgoCD under the covers) against.  Up until yesterday, it was using the openshift-gitops-operator:v1.1.1, and yesterday it updated to v1.1.2 when the new image was released [^1].  I've retested against both of my clusters, and they seem to be working just fine now with no OutOfSync errors.  Unfortunately, I can't provide a screenshot of the issue in v1.1.2 but fortunately, it suggests that the issue may have just already been fixed.


[^1]: https://catalog.redhat.com/software/containers/openshift-gitops-1/gitops-rhel8-operator/604292365a00810ecaf7bcfe


![Screenshot from 2021-06-10 15-26-32](https://user-images.githubusercontent.com/48225327/121586942-41588e00-ca02-11eb-96c2-a328bdd1c15f.png)

**Comment by jessesuen** [comment] 2021-06-10 20:27
Ok thanks for the update. Lets close this out unless we can reproduce with needed information

**Closed by jessesuen** 2021-06-10 20:27 UTC
Labels: bug

**Comment by GerbenWelter** [comment] 2022-05-29 14:52
Sorry to bump this almost year old issue but I'm running into exactly this problem. I know ArgoCD manages the resource because changes are applied but afterwards it seems that ArgoCD doesn't know where to find the resource. If you open the resource in ArgoCD the Live Manifest is empty:

![image](https://user-images.githubusercontent.com/4222258/170875632-2e26d1a5-fbf4-4659-a82f-836b7aca57d5.png)

If you look at the diff ArgoCD thinks it needs to sync the whole manifest.

This is on OpenShift 4.9 with GitOps operator 1.5.1.

**Comment by Reamer** [comment] 2022-06-21 12:09
@GerbenWelter 
Have you created a ticket in Bugzilla?

**Comment by GerbenWelter** [comment] 2022-06-21 14:18
@Reamer Thanks for reminding me. I've been busy with other things. In the meantime the operator has been updated to 1.5.2. The live manifest is still shown as empty but ArgoCD shows it as in sync. I don't know if it was fixed by the operator update because Red Hat is bad at keeping the GitOps release notes up to date. See https://github.com/redhat-developer/gitops-operator/issues/328.

**Comment by Reamer** [comment] 2022-06-22 07:12
I am not using the GitOps operator from RedHat nor the ArgoCD operator. Currently I install ArgoCD with kustomize.
Currently I have the behavior that my stage cluster sees the resource as synced, but the productive cluster does not.
The live manifest is empty in both systems. The software state is identical on both systems.
Since this issue is already closed, I will open a new issue.
