### ISSUE TITLE
Failed to unmarshal manifest if it doesn't have Kubernetes api definition (api, kind, metadata)

### ISSUE THREAD

**Issue by danylohetmantsev** [argoproj/argo-cd#4695] opened 2020-10-28 15:18 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have argo application with two files in directory. One of them is a valid kubernetes manifest (eg. ingress), another one is helm values.yaml file (which is not the kubernetes manifest). The problem appears when argo tries to sync the application. It goes to Unknown state while doing the comparison, because my non-valid yaml file doesn't have the api definition inside of it.

The possible solution would be that we will just skip files with no definition inside and would not do a diff on them.

**To Reproduce**

Create the application which is pointed to a folder with yaml file (which is not the kubernetes manifest).

**Expected behavior**

Non-kubernetes yaml files are ignored and only valid manifests are compared to in-cluster objects.

**Screenshots**

<img width="1631" alt="Screenshot" src="https://user-images.githubusercontent.com/42934251/97455833-ee353d80-1940-11eb-99dc-df95b3c0d298.png">

**Version**
Appears on 1.7.0 and higher (with the new diff functionality).

My version is 1.7.6

**Logs**

```
time="2020-10-28T15:16:41Z" level=warning msg="finished unary call with code FailedPrecondition" error="rpc error: code = FailedPrecondition desc = Failed to unmarshal \"test.yaml\": failed to unmarshal manifest: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{\"chart\":\"nginx-ingress\",\"name\":\"external-ingress\",\"namespace\":\"infra-ingress\",\"repository\":\"https://kubernetes-charts.storage.googleapis.com\",\"values\":[\"values.yaml\"],\"version\":\"1.37.0\"}'" grpc.code=FailedPrecondition grpc.method=GenerateManifest grpc.request.deadline="2020-10-28T15:17:39Z" grpc.service=repository.RepoServerService grpc.start_time="2020-10-28T15:16:39Z" grpc.time_ms=1255.701 span.kind=server system=grpc
```

**Comment by jessesuen** [comment] 2020-10-28 20:48
This behavior is expected. We don't yet have an exclusion feature to ignore non-kubernetes manifests. #4432 will address the ability to exclude/ignore other yaml files.

Duplicate of #4432

**Comment by torstenwalter** [comment] 2020-10-28 21:47
@jessesuen If I understand it correctly then #4432 is mainly about dot files. The goal of this one would be to have an option to ignore yaml files which are not Kubernetes manifests.

A simple way would be to check for `apiVersion` and `kind` fields and only treat yaml files, which contain both as Kubernetes manifests.

It's kind of blocking us from upgrading to newer Argo CD version as we have quite some applications, which work with older Argo CD versions as they ignore those yaml files.

**Comment by jessesuen** [comment] 2020-10-29 21:18
We discussed this and we agree that if we encounter a object that "looks like" a K8s object, and by "look like" it has fields: `kind`, 'apiVersion`, 'metadata`, and that object fails to unmarshal, then we will error. Otherwise we will ignore the file.

**Closed** 2020-11-03 23:47 UTC
Labels: bug

**Comment by qhyun2** [comment] 2023-04-14 01:02
The fix for this was only based on sub-string matches. It is still possible for non manifest files to pass the check and cause the unmarshalling issue.

Not a huge issue for me personally but just an FYI for future readers.

An example of this is in the default prometheus values file: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1080

**Comment by avilesj** [comment] 2023-12-10 22:01
As of ArgoCD v2.9.3, this still happens with the default prometheus `values.yaml` file.

**Comment by malachid** [comment] 2024-06-02 03:44
I just ran into this with the default prometheus values files on ArgoCD v2.11.2+25f7504.

@jessesuen does you statement above indicate that we should not expect to be able to deploy prometheus to ArgoCD unless we use the default settings?

**Comment by Glaaj** [comment] 2024-08-20 07:28
Is there a way to ignore the files that cause argocd to throw errors?

**Comment by crenshaw-dev** [comment] 2024-08-20 13:50
@Glaaj you can exclude the problematic file(s). https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L167-L170

**Comment by Glaaj** [comment] 2024-08-21 06:37
> @Glaaj you can exclude the problematic file(s).
> 
> https://github.com/argoproj/argo-cd/blob/74af92fd95499d6aace679ce2104e38ce292df0c/docs/operator-manual/application.yaml#L167-L170

But if the file is ignored during manifest generation then the helm chart values aren't being included at all or is that done after the generation?
