### ISSUE TITLE
Argocd 1.7.6 - Unable to update namespaces list from the UI for an external cluster 

### ISSUE THREAD

**Issue by rayanebel** [argoproj/argo-cd#4536] opened 2020-10-12 14:04 UTC
**Describe the bug**

Hi, 

I'm trying to deploy a new instance of argocd in my kubernetes cluster. When I've finish the installation I've added a new external k8s cluster by creating a new secret. 

Now in the UI, I saw my external cluster but with an `Unknown state` and with this message in the details:

`Cluster has no application and not being monitored.`

My first question is why I have this message, normally (in the previous version), argocd try to connect to this external cluster to determine it's initial state ?

Next, when I try to edit this cluster to add for example a new namespace in the list of allowed namespaces, I'm disconnected from the application with this error:

```
Unable to save changes: the server has asked for the client to provide credentials
```

I don't understand why when I update this external cluster I'm disconnected from the application with a 401. I'm not using an OIDC or Oauth provider I'm logged with the default admin user.

Can you help about this issue ?

**To Reproduce**

- Add an external cluster in namespace scope
- Go on the UI and edit the cluster
- Add a new namespace and save 

**Expected behavior**

An external cluster with a successful state.

**Version**

```shell
argocd-server: 1.7.6
```

**Logs**

```
the client to provide credentials" grpc.code=Unauthenticated grpc.method=Update grpc.service=cluster.ClusterService grpc.start_time="2020-10-12T14:00:45Z" grpc.time_ms=75.114 span.kind=server system=grpc
argo-cd-argocd-server-c5b774475-97j9r server time="2020-10-12T14:00:45Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims="{\"iat\":1602511105,\"iss\":\"argocd\",\"nbf\":1602511105,\"sub\":\"admin\"}" grpc.request.content= grpc.service=session.SessionService grpc.start_time="2020-10-12T14:00:45Z" span.kind=server system=grpc
argo-cd-argocd-server-c5b774475-97j9r server time="2020-10-12T14:00:45Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2020-10-12T14:00:45Z" grpc.time_ms=0.699 span.kind=server system=grpc
```

**Comment by jessesuen** [comment] 2020-10-13 20:41
Variation of the same duplicate

**Comment by alexmt** [comment] 2020-10-14 05:03
Closing as duplicate of #4405 (fix is on the way: https://github.com/argoproj/argo-cd/pull/4553)

**Closed by alexmt** 2020-10-14 05:03 UTC
Labels: bug
