### ISSUE TITLE
Normal logs should not go to stderr

### ISSUE THREAD

**Issue by chanzxxx** [argoproj/argo-cd#3491] opened 2020-04-27 05:54 UTC
# Summary
Normal logs should not go to stderr.

# Motivation

Some people including me detect critical issues on k8s by watching pods' stderr logs. But argocd applications are printing their all logs to stderr, and I think this is confused. 

# Proposal

Basically we should respect the purpose of each stream. Errors go stderr, and normal activity logs go stdout.

**Comment by alexmt** [comment] 2020-05-11 19:59
This is not intended behavior. If some CLI commands are using stderr it is a bug.

**Comment by whdckszxxx** [comment] 2020-05-18 01:36
@alexmt 
I think this is related to `logrus` package. Its default output stream is `stderr`.

**Comment by l15k4** [comment] 2020-09-17 06:00
Most of argo-events components also logs to stderr. This should be revisited across the whole argoproj.

**Comment by mrfelton** [comment] 2020-12-11 23:11
Would love to see this resolved. My stackdriver logs are cluttered with inordinate amounts of error messages coming from argocd, which aren't actually errors - just that info level messages are being output to stderr. And since the messages themselves don't include the severity in a format that stackdriver recognises they default to being logged as errors since they went to stderr. If they go to stdout as they should they would have been logged as info rather than error.

**Comment by iam-veeramalla** [comment] 2021-02-18 11:05
@jannfis , I am happy to contribute to this. Can you assign this to me ?

**Comment by jannfis** [comment] 2021-02-18 11:26
Thanks @iam-veeramalla, much appreciated! I have assigned issue to you :)

**Comment by iam-veeramalla** [comment] 2021-02-18 18:03
If I am understanding this issue correctly, It can be fairly easy fix by changing the default log from stderr to stdout. The default logging standard of logrus is stderr and can be modified to stdout by setting `log.SetOutput(os.Stdout)`

The real difficulty may be in testing this. Identify the different places where it outputs to stderr and change it to stdout.

**Comment by edgarkz** [comment] 2021-04-19 12:35
same issue here with argocd: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z

Running with the following params "app patch-resource --kind Deployment --patch"   logs to sdterr instead of stdout

**Comment by phelinor** [comment] 2021-06-01 14:48
Same issue

**Comment by olvesh** [comment] 2021-08-24 10:05
Also just ran into this, been open a while... Any known simple workarounds?

**Comment by iam-veeramalla** [comment] 2021-08-24 10:35
> Also just ran into this, been open a while... Any known simple workarounds?

@olvesh not yet, we are exploring options for a different logging package as the current project `logrus` is no longer active. It would continue as a maintenance project.

**Comment by olvesh** [comment] 2021-08-24 14:16
Ok. I will try to upgrade to 2.1 tomorrow. As I understand I can set the log-format to json in that version. Perhaps that will remedy some of the logging issues in GKE (the other ones being that GKE fluentbit does not ingest the key=values as separate fields)🤞 

On the other hand - why not then log structured logging to stdout and unstructured errors unhandled exeptions to stderr?
Surely that can be done even if not continuing to use logrus, as most apps I have come across logs all structured logging to stdout? And I know that logrus can be configured to use either stdout or stderr. (```log.SetOutput(os.Stdout)```)

Guess that this surely has been discussed somewhere, I just havent stumbled over it yet. 😄

**Comment by whdckszxxx** [comment] 2021-08-30 13:25
I'm willing to contribute to addressing this issue.
Replacing `logrus` to another looks like best solution. What alternative packages do we have?

**Comment by iam-veeramalla** [comment] 2021-08-30 14:33
@whdckszxxx 
https://github.com/golang/glog
https://github.com/kubernetes/klog (fork of glog)

**Comment by whdckszxxx** [comment] 2021-08-30 15:06
@iam-veeramalla 
I was asking for packages under your consideration now.
If you had your research, plz share with me :)

**Comment by iam-veeramalla** [comment] 2021-08-30 15:11
> @iam-veeramalla
> I was asking for packages under your consideration.
> If you had your research, plz share with me :)

Yes,
https://github.com/golang/glog
https://github.com/kubernetes/klog (fork of glog)

we also had a discussion to explore the above packages in the contributors meeting

**Comment by chanzxxx** [comment] 2021-08-30 15:23
Thanks, `klog` looks good to me.
I will post a PR soon

**Comment by olvesh** [comment] 2021-08-30 16:27
It has been a while since I programmed in Golang...
But - does it exists a logging lib that can log sympathetic to the cloud it runs in? I.e. so that running in GCE will log in a format native to Google Logging (https://cloud.google.com/logging/docs/setup/go) and similar for AWS, Azure etc? 
At least so that it can be configured to tell the library that it is logging in a such-and-such environment?

**Comment by kpiroddi-yieldstreet** [comment] 2022-01-17 12:57
Any update on this issue? Thanks

**Comment by Piroddi** [comment] 2022-01-17 12:58
Any update on this issue? Thanks

**Comment by mbhnyc** [comment] 2022-05-25 15:10
Ping, this is definitely a weird thing.

**Comment by anjuls** [comment] 2022-07-26 05:05
any idea when this is going to be fixed?

**Comment by crenshaw-dev** [comment] 2022-07-26 13:43
@iam-veeramalla did [some research](https://github.com/sirupsen/logrus/issues/403) and put up a [draft PR](https://github.com/argoproj/argo-cd/pull/5574). The conclusion of the PR review seems to have been that the performance hit associated with getting logrus to split output between stdout and stderr was not worth it and that we should just change loggers (which needs to happen anyway).

I think all that's reflected above, but hasn't been summarized here yet.  :-)

If anyone has time to work on swapping out the logger, I'd be happy to review a PR! Also, please 👍 the issue so it's prioritized.

**Comment by iam-veeramalla** [comment] 2022-07-26 13:45
> @iam-veeramalla did [some research](https://github.com/sirupsen/logrus/issues/403) and put up a [draft PR](https://github.com/argoproj/argo-cd/pull/5574). The conclusion of the PR review seems to have been that the performance hit associated with getting logrus to split output between stdout and stderr was not worth it and that we should just change loggers (which needs to happen anyway).
> 
> I think all that's reflected above, but hasn't been summarized here yet. :-)
> 
> If anyone has time to work on swapping out the logger, I'd be happy to review a PR! Also, please 👍 the issue so it's prioritized.

True, we did not evaluate the modern day loggers and choose one which is a best fit.

**Comment by crenshaw-dev** [comment] 2022-09-08 12:26
[zap](https://github.com/uber-go/zap) and [zerolog](https://github.com/rs/zerolog) look like strong candidates.

**Comment by edoger** [comment] 2022-10-10 01:51
logrus can't solve this problem, maintainers don't seem interested in fixing this problem, I built a new log library for this: [zkits-logger](https://github.com/edoger/zkits-logger) , the library is now stable, and the API style is consistent with logrus.

```
Logger.SetLevelOutput() // Set different output writers for different log levels.
```

**Comment by iam-veeramalla** [comment] 2022-10-10 05:54
@edoger true, I was evaluating zap logger. I found it good and also recommended by others in the community. I have started migrating in steps, I can collaborate if you are interested.

**Comment by edoger** [comment] 2022-10-10 07:05
@iam-veeramalla 
Is there a fixed plan? If not I will start devising a solution and I need to fix this asap.

**Comment by iam-veeramalla** [comment] 2022-10-10 07:09
@edoger I already started migrating to the new log system. Please give me a couple of days time and I will let you know the progress. 
I am looking at getting the PR asap.

**Comment by iam-veeramalla** [comment] 2022-10-10 07:31
Sure, Thanks

**Comment by iam-veeramalla** [comment] 2022-10-10 11:38
@edoger did you also evaluate zap logger or zero logger ? what is your thought on them ?

**Comment by crenshaw-dev** [comment] 2022-10-10 13:06
Aside: looks like structured logging is coming to the standard library, but probably not for a while. https://github.com/golang/go/discussions/54763

**Comment by edoger** [comment] 2022-10-11 01:56
> @edoger did you also evaluate zap logger or zero logger ? what is your thought on them ?

@iam-veeramalla 
Zap is very powerful and adaptable to a variety of application scenarios. It is very suitable for large business applications. The disadvantage is that it must be understood how to use it correctly, and it is not suitable for small applications and libraries (because most of the functions are not used).
The performance of zerolog is very good. It uses many techniques to optimize memory allocation. Before using it, you need to make a clear trade-off between ease of use and performance.

We use zap a lot in large-scale applications, but we find that it is difficult to replace the log library once it is used, because zap will explicitly enter various places in the application, and the reconstruction cost is very high. Engineers prefer to use logrus, a logging library with very low entry cost, but since the logrus library is no longer updated a few years ago, we built zkits-logger to replace logrus and zap. The reason is: For applications, the log library The performance of the log library is not an important issue, the customizability and ease of use of the logging library are very important indicators.

**Comment by iam-veeramalla** [comment] 2022-10-11 03:35
@edgarkz Thanks for the very detailed information.

I just started implementing zap yesterday but because you have already worked with zap and zero log. I think it will be better if you or your team member picks this up. I will be happy to collaborate and be a co-author if required.

Does that work ?

**Comment by edoger** [comment] 2022-10-11 03:54
@iam-veeramalla 
Okay, I first need to spend some time understanding the logging module of this library, and then replace the logging library without breaking the existing usage style as much as possible, what do you think of this attention? I don't mind which logging library to use, if you guys have come to a conclusion, just let me know and I'll decide when it's done.

**Comment by iam-veeramalla** [comment] 2022-10-11 03:57
@edoger I think the most popular suggestion here is Zap , so we can start with it. We can also sync up over a call or bring this up in the next community meeting which takes place on Thursday.

**Comment by edoger** [comment] 2022-10-11 06:53
@iam-veeramalla OK, I'll provide a patch asap.

**Comment by edoger** [comment] 2022-10-14 02:17
@iam-veeramalla I will finish this this weekend.

**Comment by edoger** [comment] 2022-10-16 16:10
@iam-veeramalla 
I've created a corresponding patch, which requires further discussion before a global replacement. Unit tests I will complete after the discussion.

**Comment by iam-veeramalla** [comment] 2022-10-17 14:20
> ore a global

Hi @edoger, Do you want to bring this discussion in our next community meeting which is on the thursday ?

**Comment by edoger** [comment] 2022-10-17 15:41
> Hi @edoger, Do you want to bring this discussion in our next community meeting which is on the thursday ?

@iam-veeramalla OK! 

- Whether the new application logging subpackage is approved.
- Use the new Logger interface to decouple the log driver library and the application.
- Wraps zap into existing logging styles to reduce refactoring costs.
- Whether to provide configuration items to split log output to standard error and standard output.
- Whether the log format and log level need to be modified while the application is running.

Do you have any other discussion points?

**Comment by iam-veeramalla** [comment] 2022-10-17 17:47
> > Hi @edoger, Do you want to bring this discussion in our next community meeting which is on the thursday ?
> 
> @iam-veeramalla OK!
> 
>     * Whether the new application logging subpackage is approved.
> 
>     * Use the new Logger interface to decouple the log driver library and the application.
> 
>     * Wraps zap into existing logging styles to reduce refactoring costs.
> 
>     * Whether to provide configuration items to split log output to standard error and standard output.
> 
>     * Whether the log format and log level need to be modified while the application is running.
> 
> 
> Do you have any other discussion points?

Sounds Great :) .. Do you have the link for the contributors meeting ? Please let me know, I can share the invite.

**Comment by edoger** [comment] 2022-10-18 01:44
> Sounds Great :) .. Do you have the link for the contributors meeting ? Please let me know, I can share the invite.

@iam-veeramalla Please email to share with me. O(∩_∩)O~~~

**Comment by iam-veeramalla** [comment] 2022-10-18 04:07
> 

@edoger you can find it here Contributors Office Hours: [Every Thursday](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) | [Agenda](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8)

**Comment by edoger** [comment] 2022-10-20 02:08
> @edoger you can find it here -> Contributors Office Hours: [Every Thursday](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) | [Agenda](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8)

@iam-veeramalla I don't have access to Google 😞 and may need your help with the results of the discussion.

**Comment by iam-veeramalla** [comment] 2022-10-20 04:50
> > @edoger you can find it here -> Contributors Office Hours: [Every Thursday](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) | [Agenda](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8)
> 
> @iam-veeramalla I don't have access to Google 😞 and may need your help with the results of the discussion.

I can add this to the agenda .. no problem. You will lead the discussion at the contributors meeting right ?

**Comment by edoger** [comment] 2022-10-20 12:34
> > > @edoger you can find it here -> Contributors Office Hours: [Every Thursday](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) | [Agenda](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8)
> > 
> > 
> > @iam-veeramalla I don't have access to Google 😞 and may need your help with the results of the discussion.
> 
> I can add this to the agenda .. no problem. You will lead the discussion at the contributors meeting right ?

@iam-veeramalla  I don't have the right amount of free time to attend and I support the outcome of any of your discussions. 
I can't understand English conversations and can only read English documents.

**Comment by iam-veeramalla** [comment] 2022-10-20 12:36
> > > > @edoger you can find it here -> Contributors Office Hours: [Every Thursday](https://calendar.google.com/calendar/u/0/embed?src=argoproj@gmail.com) | [Agenda](https://docs.google.com/document/d/1xkoFkVviB70YBzSEa4bDnu-rUZ1sIFtwKKG1Uw8XsY8)
> > > 
> > > 
> > > @iam-veeramalla I don't have access to Google 😞 and may need your help with the results of the discussion.
> > 
> > I can add this to the agenda .. no problem. You will lead the discussion at the contributors meeting right ?
> 
> @iam-veeramalla  I don't have the right amount of free time to attend and I support the outcome of any of your discussions. 
> I can't understand English conversations and can only read English documents.

Ok, I will see if I can get this into today's agenda and get back to you with the outcome of the meeting:)

**Comment by iam-veeramalla** [comment] 2022-10-21 05:26
Hi @edoger, Please find the response from the community meeting.

 > Whether the new application logging subpackage is approved.
 Yes. Do we also want to support Sugar logging with Zap ? Do you see any advantages ?

> Use the new Logger interface to decouple the log driver library and the application.
Yes. There is already a log package, if possible we can leverage that.

> Wraps zap into existing logging styles to reduce refactoring costs.
Yes

> Whether to provide configuration items to split log output to standard error and standard output.
Yes

* Whether the log format and log level need to be modified while the application is running.
No opinion, You can take this decision.

**Comment by edoger** [comment] 2022-10-21 05:48
@iam-veeramalla thank you very much!
I have seen the feedback and understand it. I'll make all the changes this weekend and can do a code review next Monday.
If you have any other questions or comments, feel free to email me at any time.

**Comment by edoger** [comment] 2022-10-25 02:18
@iam-veeramalla 
There are some frustrating issues in this project.

The internal grpc interceptor seems to have to rely on the logrus implementation. Many functions utilize logrus' global logger for log output capture (which is almost impossible to dynamically modify the output of the global logger in zap). Some test cases rely on logrus' log detection and test modules.

I can't quite understand why some source code needs to be designed this way.
These modules may need to be rewritten and replaced by dependent third-party library implementations.
https://github.com/argoproj/argo-cd/blob/309654cece2292fb09959055e8602b9b6dc68077/util/grpc/logging.go#L73-L93

**Comment by leoluz** [comment] 2022-11-03 15:11
> The internal grpc interceptor seems to have to rely on the logrus implementation. Many functions utilize logrus' global logger for log output capture (which is almost impossible to dynamically modify the output of the global logger in zap). Some test cases rely on logrus' log detection and test modules.

@edoger We are aware and discussed this in the contributors when @iam-veeramalla presented this issue. This will require a huge refactor in Argo CD. We will need help coordinating all this work. I believe that it is better to map every package that needs to be migrated and provide smaller PRs. This way we will be able to gradually migrate to the new log approach and refactor everything. 

@iam-veeramalla would you be willing to take this governance task to map and track all work that needs to be done in order to get this 100% implemented?

**Comment by Kerwood** [comment] 2023-02-07 13:35
How did it go with this issue ? Did you get started on it?
I currently git 450k log lines an hour on stderr which is a bit problematic.

**Comment by nicl09** [comment] 2023-03-02 09:50
Any update on this? We are looking at hundreds of thousands of log entries per hour in GCP. This costs us and our customers more and more resources and money. Maybe there is a workaround for the time being?

**Comment by vermin1** [comment] 2023-03-15 11:54
Any update on this,please. We are in the same boat.

**Comment by griseau** [comment] 2023-05-25 07:52
Did anybody found a workaround ? 
We can exclude them from cloud logging, but this is quite annoying

**Comment by crenshaw-dev** [comment] 2023-05-25 19:26
Quick note that the proposed go-native structured, leveled logging library is available as an experimental package: https://pkg.go.dev/golang.org/x/exp/slog

**Comment by edoger** [comment] 2023-05-30 03:34
The change of complete refactoring is very huge, (╯﹏╰)b, I suggest forking logrus and adding LevelOutput function (I once submitted a function patch, but the author seems not very interested in new functions), and then in go mod replace the package.

**Comment by Kerwood** [comment] 2023-06-01 06:55
> The change of complete refactoring is very huge, (╯﹏╰)b, I suggest forking logrus and adding LevelOutput function (I once submitted a function patch, but the author seems not very interested in new functions), and then in go mod replace the package.

Apparently not...
![image](https://github.com/argoproj/argo-cd/assets/4029521/fbcba40b-1802-4f9b-880f-b6e3c063ebfc)

**Comment by markcheret** [comment] 2023-06-28 10:42
Is there any chance this logging issue could be resolved?

**Comment by crenshaw-dev** [comment] 2023-06-28 13:50
@edoger I'm not completely opposed to the idea of a fork. Fully replacing the logger is a huge undertaking, and I don't think anyone is currently doing it. If logrus isn't accepting new features, then maintaining a fork should be relatively low-effort.

Unless someone wants to take on the full-replacement task. :-)

**Comment by crenshaw-dev** [comment] 2023-06-28 14:14
Seems like a reasonable opt-in approach, for folks who aren't worried about a little CPU overhead. Maybe even fine as a default, idk how expensive the wrapper is.

**Comment by jannfis** [comment] 2023-06-28 15:17
I haven't done any performance tests, but the major part of the overhead would be calling two functions instead of one. There's not much compute involved in that, I guess.

**Comment by jannfis** [comment] 2023-06-28 15:20
If it would be acceptable to just log everything (including levels error and fatal) to stdout, it's just a matter of calling logrus' `SetOutput()` function before starting to log.

**Comment by alvarogonzalez-packlink** [comment] 2023-06-28 18:27
> If it would be acceptable to just log everything (including levels error and fatal) to stdout, it's just a matter of calling logrus' `SetOutput()` function before starting to log.

I think this is OK for JSON logging. _Theoretically_ , if ouy're doing structured login, you can just filter by the value of the `level` key.

**Comment by crenshaw-dev** [comment] 2023-06-28 19:49
Should definitely be fine as an opt-in.

**Comment by jannfis** [comment] 2023-06-29 00:34
We still have some external dependencies doing their own logging, such as `argoproj/pkg` and potentially others.

**Comment by smaftoul** [comment] 2023-08-29 11:39
The go standard library package `log/slog` has been released as part of go 1.21. Is this the way to go to fix this issue ?

**Comment by griseau** [comment] 2023-09-26 18:46
If anyone is interested in a workaround in the meantime (thanks to @smaftoul 🎉 ), we configured argocd to log as json with the following config :
```
  - applicationsetcontroller.log.format=json
  - controller.log.format=json
  - notificationscontroller.log.format=json
  - reposerver.log.format=json
  - server.log.format=json
```

That way logs are correctly parsed by GCP even if going to stderr.

**Comment by leoluz** [comment] 2024-09-05 19:20
Getting back here to point out that logs should indeed keep going to `stderr`. There are many libraries that already do that by default (zap, logrus, etc). The reason is because `stdout` should only contain the output from an executed command. If we run a command like `argocd app list` we should only get the list of applications and not getting it mixed with logs. Even if it is a bit counter intuitive, diagnostics type of output do belong to `stderr`: https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

**Closed by leoluz** 2024-09-05 19:20 UTC
Labels: bug, bug/severity:minor, bug/priority:medium, type:supportability

**Comment by mananpreetsingh** [comment] 2025-02-14 00:51
> Getting back here to point out that logs should indeed keep going to `stderr`. There are many log libraries that do that by default (zap, logrus, etc) for a reason. The reason is because `stdout` must only contain the output from the executed command. For example, if we run a command like `argocd app list` we should only get the list of applications and not getting it mixed with logs. Doing so, would break scripts that depend on Argo CD CLI with no easy path to fix.
> 
> Even if it is a bit counter intuitive, diagnostics output like logs do belong to `stderr`. See: https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

@leoluz This reasoning is **partially true** but not an absolute rule. The idea that logs go to stderr by default comes from Unix philosophy, where:

- **stdout** should contain only the **expected program output** (i.e., data/results the program was meant to return).
- **stderr** should contain everything else, including logs, errors, and debug information.

This **prevents logs from interfering** with tools that rely on stdout for structured output like CLI tool, Containerized applications etc.

If you are saying **INFO** and **DEBUG** level logs should always go to **stderr** then sorry mate, I do not agree with you. If other libraries are doing it that should not be the reason to excuse not to do it properly.

**Comment by chanzxxx** [comment] 2025-02-20 01:02
@leoluz 
What is the expected output if the program is server application?

For cli commands, I agree with you but I don't think the api servers left their log that way.
