### ISSUE TITLE
IgnoreDifferences should be applied for auto-sync (sync on git commit)

### ISSUE THREAD

**Issue by ntin90** [argoproj/argo-cd#4912] opened 2020-11-26 04:01 UTC
# Summary

`ignoreDifferences` should be applied for automatic sync (webhook/polling)

Currently, `ignoreDifferences` is only applied for selfHeal, when doing comparision. But it is not applied for the automatic sync (triggered from git webhook or polling). The fact is, we are using Gitops, the repo will have plenty of commits everyday. So even we set Argo to ignore some certain differences, Argo still apply it whenever there is a commit. Hence, it's actually not ignored at all.

# Motivation

I want to edit a resource to troubleshoot, let say a deployment. I change the command in the deployment. Assume I already set Argo to ignore all the differences in my deployment. I expect it to use my troubleshooting command. But in the meantime, someone else push a commit to the repo (it happens all day) and Argo blindly apply my deployment to the cluster which will revert my command.

# Proposal

I haven't look at how Argo implement automatic sync yet, but I think have a diff for those resources that have set `ignoreDiffences` before applying should work.

**Comment by jessesuen** [comment] 2020-11-30 21:51
Duplicate of https://github.com/argoproj/argo-cd/issues/2913

This is by design. Ignore differences only affects the sync status reporting, but does nothing with regards to applying the manifests from git (which is simply a kubectl apply).

https://github.com/argoproj/argo-cd/issues/2913 is the request to not apply differences during the kubectl apply. Will dup to that issue.

**Closed by jessesuen** 2020-11-30 21:51 UTC
Labels: enhancement
