### ISSUE TITLE
[SPIKE] Controller fails to update deployment history

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-cd#449] opened 2018-07-23 17:58 UTC
Controller fails to execute Patch on Application CRD. Following error was returned by K8S API : 
```
unable to find api field in struct Unstructured for the json field "metadata"
```

Unfortunately no clear steps to reproduce. Probably related to https://github.com/kubernetes/kubernetes/issues/58017

**Comment by jessesuen** [comment] 2018-08-02 18:31
TODO: grep for frequency to evaluate level of impact.

**Comment by jessesuen** [comment] 2018-08-15 21:12
This was occurring in pre v0.7 instances. Since then, we've reduced the PATCH calls to the K8s API server. I also grepped the logs for occurrences of this message and did not find any recently. Closing this issue until can be reproduced.

**Closed by jessesuen** 2018-08-15 21:12 UTC
Labels: 2, P1, bug
