### ISSUE TITLE
Unexpected Namespace Deletion

### ISSUE THREAD

**Issue by avdhoot** [argoproj/argo-cd#17440] opened 2024-03-07 17:21 UTC
**Describe the bug**

Today, we encountered an unusual problem where argocd removed all namespaces associated with two argocd apps. The deletion was limited to namespace resources and did not delete other resources like secret, configmap.

- Verified that argocd triggered the namespace deletion. Please refer to the attached log for confirmation.
- Verified that there were no changes in the Git repository that could have triggered the deletion.
- Confirmed that no one accessed the Argo web interface.
- Confirmed that no one executed 'kubectl exec' in the argocd pod.

Need help investigate why/how?

**To Reproduce**
NA

**Expected behavior**

It should not delete any resource unless it is deleted from tracking git repo.

**Version**

```shell
argocd-version: 2.7.3
```

**Logs**

```
kubernetes/$Format	I0306 23:52:32.125600      12 cacher.go:752] cacher (*core.Namespace): 2 objects queued in incoming channel {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"49f114ab-eb81-41f6-9d48-ac358b6f932a","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/foo-bar-uat","verb":"delete","user":{"username":"system:serviceaccount:kube-system:argocd-user","uid":"e7f95f6c-6c1b-417c-a45c-9f1de09a77a1","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]},"sourceIPs":["x.x.x.x"],"userAgent":"argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"namespaces","namespace":"foo-bar-uat","name":"foo-bar-uat","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestReceivedTimestamp":"2024-03-06T23:52:31.938586Z","stageTimestamp":"2024-03-06T23:52:32.088784Z","annotations":{"authentication.k8s.io/legacy-token":"system:serviceaccount:kube-system:argocd-user","authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"argocd-user\" of ClusterRole \"cluster-admin\" to ServiceAccount \"argocd-user/kube-system\""}}
```

**Comment by jannfis** [comment] 2024-03-07 20:12
You'd actually need to look in the log files of argocd-application-controller to see why Argo CD thought it had to delete those namespaces.

Then, it's pretty much important how you are rendering the manifests. Are you using plain YAMLs in Git, Kustomize, a Plugin etc.

As a heads up, Argo CD 2.7.3 is pretty outdated and not in support anymore.

**Comment by avdhoot** [comment] 2024-03-07 21:02
Sadly, our log level was set to warning. I have attached a log file containing logs 2 minutes before/after incident. Let me know if more logs are needed.  [search-results-2024-03-07T12_39_44.899-0800.csv](https://github.com/argoproj/argo-cd/files/14530032/search-results-2024-03-07T12_39_44.899-0800.csv) 

we are using plain YAML in git. Also auto prune was enabled for the app. 

We are planning to update it soon.

**Comment by jannfis** [comment] 2024-03-07 21:55
Without meaningful logs, you're probably going to have a very hard time to find out why this happened. Alas, the logs you have are not very helpful. Sorry.

You could look through your Git history. Do those deleted namespaces still exist in Git? Were there any changes to Git during the time frame of the incident that potentially triggered an auto-sync of your affected apps (i.e. when your apps point to HEAD in a mono-repo a failed auto-sync could resume on a new commit SHA, reconciling to whatever state there is in Git, even if the commit did not affect that particular app).

**Comment by avdhoot** [comment] 2024-03-08 02:35
There was no change in git repo around that time. Yes, all deleted namespaces are still in the repo. Also checked github webhook push event to confirm the same.

**Comment by ncdc** [comment] 2024-06-26 16:47
I believe have determined the root cause of this issue, which is probably the same as at least one of the reports in https://github.com/argoproj/argo-cd/issues/15058.

There are two parts to this issue. The first is https://github.com/argoproj/gitops-engine/issues/171. The lack of concurrency protection for this field is partially responsible.

The other part is a very specific sequence of events that causes a race condition.

First, I believe you have to have at least two Applications. Here is the sequence that causes the bug:

1. AppOne has `spec.destination.namespace` set, and it starts a sync with prune enabled. It doesn't matter if this is an automatic or manual sync.
2. AppOne's sync gets to https://github.com/argoproj/gitops-engine/blob/4386ff4b8df9627c10efc2513871856f94434383/pkg/sync/reconcile.go#L80 and tries to determine if each target object is namespaced or not.
3. The `clusterCacheResyncDuration` has elapsed, meaning the next time something interacts with the cluster cache, it will re-sync https://github.com/argoproj/argo-cd/blob/dafb37c88d677527022ed8c8a7cfc9e875853d73/controller/cache/cache.go#L78
4. AppTwo starts a sync and gets to https://github.com/argoproj/gitops-engine/blob/4386ff4b8df9627c10efc2513871856f94434383/pkg/cache/cluster.go#L808, which resets `c.namespacedResources` to an empty map
5. Back at AppOne, the invocation of `kubeutil.IsNamespacedOrUnknown` proceeds ([link](https://github.com/argoproj/gitops-engine/blob/4386ff4b8df9627c10efc2513871856f94434383/pkg/utils/kube/kube.go#L62-L65))
```go
func IsNamespacedOrUnknown(provider ResourceInfoProvider, gk schema.GroupKind) bool {
	namespaced, err := provider.IsNamespaced(gk)
	return namespaced || err != nil
}
```
7. The implementation of `provider.IsNamespaced()` ([link](https://github.com/argoproj/gitops-engine/blob/4386ff4b8df9627c10efc2513871856f94434383/pkg/cache/cluster.go#L1011-L1017)) is this:
```go
// IsNamespaced answers if specified group/kind is a namespaced resource API or not
func (c *clusterCache) IsNamespaced(gk schema.GroupKind) (bool, error) {
	if isNamespaced, ok := c.namespacedResources[gk]; ok {
		return isNamespaced, nil
	}
	return false, errors.NewNotFound(schema.GroupResource{Group: gk.Group}, "")
}
```
8. Because the `sync()` from step 4 is still in flight, it's entirely possible that `IsNamespaced` can't find the `GroupKind` in `c.namespacedResources` and returns an error to the code in step 5.
9. `IsNamespacedOrUnknown` returns `true` because it doesn't know if it's namespaced or not (it got an error).
10. The code in `Reconcile` does **not** set `ns = ""` because it thinks the object is namespaced.
11. It then creates an incorrect resource key. For a cluster-scoped resource such as a `Namespace`:
    1. gvk.Group = ""
    2. gvk.Kind = "Namespace"
    3. ns = whatever the Application's `spec.destination.namespace` is <-------- this is the bug
        1. This is because `ns := text.FirstNonEmpty(obj.GetNamespace(), namespace)` returns a non-empty value, `namespace`, which is passed in to this method and it's `spec.destination.namespace` 
    4. obj.GetName()
12. Because the resource key is incorrect, it's not found in `liveObjByKey`, and so the key/value pair is **not** removed from `liveObjByKey`
13. After the first for loop exits, any values remaining in `liveObjByKey` are supposed to be those where it couldn't find a match between target object and live object; i.e. there is a live object but no target object. But because of this bug, there can also be live objects that do have matching target objects, except it couldn't make the match because of the incorrect resource key
14. When the [second for loop runs](https://github.com/argoproj/gitops-engine/blob/4386ff4b8df9627c10efc2513871856f94434383/pkg/sync/reconcile.go#L91-L94), it adds `nil` entries to the `targetObjs` slice for each live object. While this is correct for target objects that used to exist and have now legitimately been removed from the source, it is incorrect for target objects that still exist but it couldn't find a match because of this race condition
15. When the sync tasks execute, all the cluster-scoped objects that were impacted by this race condition now have `nil` target objects, and when pruning is enabled, they get deleted incorrectly.

**Comment by ncdc** [comment] 2024-06-26 16:58
While fixing the lack of a mutex guarding `c.namespacedResources` is important, I think a possible small fix for this issue could be:

```go
if namespaced := kubeutil.IsNamespacedOrUnknown(resInfo, obj.GroupVersionKind().GroupKind()); !namespaced {
			ns = ""
		}

		// If IsNamespacedOrUnknown returned namespaced=true because it's actually unknown, there is a chance that we incorrectly use
		// a non-empty value for ns for a cluster-scoped resource for the resource key, when it should actually be empty. This happens
		// if the namespace parameter passed in to this method has a value. Therefore, we check a key both with and without the
		// namespace set. Otherwise, we risk indicating that the live object does not exist when it in fact does, which then
		// incorrectly appends a nil to targetObjs and potentially causes data loss.
		keys := []kubeutil.ResourceKey{
			kubeutil.NewResourceKey(gvk.Group, gvk.Kind, ns, obj.GetName()),
			kubeutil.NewResourceKey(gvk.Group, gvk.Kind, "", obj.GetName()),
		}
		
		found := false
		for _, key := range keys {
			if liveObj, ok := liveObjByKey[key]; ok {
				managedLiveObj[i] = liveObj
				delete(liveObjByKey, key)
				found = true
				break
			}	
		}
		if !found {
			managedLiveObj[i] = nil
		}
```

**Comment by ncdc** [comment] 2024-07-01 19:16
This should be fixed by https://github.com/argoproj/gitops-engine/pull/597, assuming it's approved, merged, and pulled into ArgoCD.

**Comment by andrii-korotkov-verkada** [comment] 2024-11-11 12:15
We should be using this gitops-engine PR in new versions. I'll close it, but please let me know if it's still an issue in versions 2.11+.

**Closed by andrii-korotkov-verkada** 2024-11-11 12:15 UTC
Labels: bug, component:core, type:bug
