### ISSUE TITLE
helm dependency build` failed exit status 1

### ISSUE THREAD

**Issue by vieirajluis** [argoproj/argo-cd#7766] opened 2021-11-22 17:21 UTC
Hello,

We have ArgoCD v2.0.0+f5119c0, on a Azure Kubernetes Cluster
{
    "Version": "v2.0.0+f5119c0",
    "GitTreeState": "clean",
    "GoVersion": "go1.16",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.9.4 2021-02-09T19:22:10Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.4",
    "JsonnetVersion": "v0.17.0"
}
There are argocd-repo-server pod, argo-server pod, argo-redis pod, argo-dex-server pod. After, clear argo cache, we started experiencing issues to load helm repos and git/bitbucket repos in the repo-server as following

**level=error msg="`helm dependency build` failed exit status 1: Error: no cached repository for helm-manager-*********

time="2021-11-22T14:20:10Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): `helm dependency build` failed exit statu │
│ s 1: Error: no repository definition for https://XXXXXXXXX. Please add the missing repos via 'helm repo add'" grpc.code=Unknown grp │
│ c.method=GenerateManifest grpc.request.deadline="2021-11-22T14:23:08Z" grpc.service=repository.RepoServerService grpc.start_time="2021-11-22T14:20:08Z" grpc.time_ms=165 │
│ 4.161 span.kind=server system=grpc   

and

time="2021-11-22T14:53:47Z" level=info msg=Trace args="[helm repo add stable https://charts.helm.sh/stable]" dir=/tmp/git@bitbucket.org_xxxx_helm-charts/xxxxx │

│ time="2021-11-22T14:53:48Z" level=info msg=Trace args="[helm repo add incubator https://charts.helm.sh/incubator]" dir=/tmp/git@bitbucket.org_xxxxx_helm-charts/yyyyyyy │

│ time="2021-11-22T14:53:49Z" level=info msg=Trace args="[helm repo add argo https://argoproj.github.io/argo-helm]" dir=/tmp/git@bitbucket.org_xxxxxxx_helm-charts/zzzzzzzz │

and all others private repos we have: 
git@bitbucket.org*/*

Thanks for any help.

**Comment by liangyuanpeng** [comment] 2021-11-23 06:43
Duplicate #7768

**Comment by chetan-rns** [comment] 2021-11-23 13:40
Closing this issue since it's a duplicate of #7768

**Closed by chetan-rns** 2021-11-23 13:40 UTC
