### ISSUE TITLE
Unable to create application from a connected Azure DevOps server repository

### ISSUE THREAD

**Issue by nilic** [argoproj/argo-cd#6362] opened 2021-05-29 06:51 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After not being able to connect a private Azure DevOps server repository to ArgoCD via username and password (with error returned "Unable to connect HTTPS repository: authentication required)", I have successfully connected the repo via Personal Access Token (PAT):

![image](https://user-images.githubusercontent.com/6827325/120060368-c71a2800-c057-11eb-8524-dfdabd95ae21.png)

When I try to create an application using the repository, I get the following error:

`Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to fetch 493dd952d54b8817daa972adc056d32a1f31231a: `git fetch origin --tags --force` failed exit status 128: fatal: Authentication failed for '<redacted>/_git/argocd-apps/'`

PAT used has Full Access scope and works with `git` operations to the repo, which was tested locally with `git clone` and `git fetch origin --tags --force` which is reported in the ArgoCD error message.

My guess is that this is related to Azure DevOps not allowing PAT authentication with a non-empty username (tested locally with `git`), while ArgoCD requires username to be a non-empty string when adding repository credentials. ArgoCD is probably passing this username to Azure DevOps which results in the mentioned error. Related issue: #6098  

**To Reproduce**

* Create a repository on Azure Devops server
* Create an Azure DevOps server Personal Access Token (PAT) with Full Access scope
* Add the repository to ArgoCD via HTTPS using the PAT
* Try to create an ArgoCD application using the added repository

**Expected behavior**

ArgoCD application is successfully created.

**Screenshots**

![image](https://user-images.githubusercontent.com/6827325/120060805-3133cc80-c05a-11eb-921e-aa0093fdfd78.png)

**Version**

```shell
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Comment by nilic** [comment] 2021-06-02 11:46
I'm not sure how this is related to my issue, since I'm not using GitHub, but Azure DevOps server. Although I agree that this seems to be a backend-specific problem.

After reading the following on authenticating to Azure DevOps through HTTPS using PAT:

- [Azure DevOps documentation - Use personal access tokens](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat)

- [Azure DevOps: No example on how to use PAT to access git repositories](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455)

I've decided to workaround the issue by adding the Azure DevOps repository via SSH, in which case new app creation works fine.

**Comment by rouke-broersma** [comment] 2021-06-03 07:36
@nilic we have successfully used azure devops with argo by creating the PAT from the clone window. There it specifies the exact username to use. This does work, random username does not:

![image](https://user-images.githubusercontent.com/3595932/120606088-13e27200-c44f-11eb-80dd-f2cc78caa286.png)

**Comment by nilic** [comment] 2021-06-03 08:10
That's interesting - it seems that this is an Azure DevOps Services feature, since I don't have that option in Azure DevOps Server 2020:

![image](https://user-images.githubusercontent.com/6827325/120608992-0e3a5b80-c452-11eb-9884-22f5ea685797.png)

I have created the PAT as described [here](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#create-a-pat) and no username was given. Here are some findings:

- `git v2.9.2.windows.1`: I can `git clone` the repo using empty username and PAT (in clear text, not base64 encoded). Non-empty username is a no go.
- `git v2.18.4`: I am unable to `git clone` the repository using any combination of non-base64 encoded username and PAT (tried with empty username, my AzDO username with the domain name, my AzDO username without the domain name, random string, event the token name). The only way to clone is as described [here](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat).

So it's seems the behavior also depends on the `git` version (possibly also on the OS?). I'd say that currently the safest way to use AzDO Server with ArgoCD is by adding the repo via SSH.

**Comment by lucheng-wh** [comment] 2021-06-23 07:31
I met same problem with nilic

**Comment by Kraego** [comment] 2021-07-07 06:36
Same Problem here #6289

**Comment by Kraego** [comment] 2021-07-08 07:14
Duplicate of #6289

**Comment by bdzanko17** [comment] 2021-08-20 12:29
I am having the same problem, did someone figured this out?

**Comment by AtzeDeVries** [comment] 2022-01-06 12:58
So if you create a PAT for a user (not just a PAT for a specific repo, which is only available in non azdo server) and then create a random username it works.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: azdo-<redacted>-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://dev.azure.com/<redacted>
  password: <redacted>
  username: argocd
```

**Comment by fr3man1** [comment] 2022-03-29 06:27
@AtzeDeVries Does this work on AzDO Server?

**Comment by rouke-broersma** [comment] 2022-03-29 10:51
> @AtzeDeVries Does this work on AzDO Server?

We could not get this working on azdo server because apparently azdo server requires some git extensions that the go got client does not support.

Only works on azdo cloud.

**Comment by luber** [comment] 2022-05-13 00:42
Any updates on this? Did anyone find any workarounds?
We are running Azure DevOps Server 2020 Update 1.1. But the same issue here.

Looks like MS is the only who requires multi-ack functionality and `go-git` can't provide it.
https://github.com/plumber-cd/terraform-backend-git/issues/15#issuecomment-712512364

**Comment by willbush** [comment] 2022-06-22 23:31
> Did anyone find any workarounds?

@luber I think using ssh. However, expect problems.

Firstly, with on-prem hosting. You're going to run into: https://argo-cd.readthedocs.io/en/release-2.0/user-guide/private-repositories/#unknown-ssh-hosts

Fix for me by doing:

```
ssh-keyscan your-server-host-name | argocd cert add-ssh --batch
```

Then, because [ArgoCD removed support for SHA-1 signature hash algorithm](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.3-2.4/#support-for-private-repo-ssh-keys-using-the-sha-1-signature-hash-algorithm-is-removed) and Azure Devops still seems to be on SHA-1 [[1](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#q-what-do-i-do-if-im-still-prompted-for-my-password-and-git_ssh_commandssh--v-git-fetch-shows-no-mutual-signature-algorithm)] [[2](https://developercommunity.visualstudio.com/t/support-non-rsa-keys-for-ssh-authentication/365980)]

Think you may need to modify argocd install to support signature hash algorithm AzDO supports sort of like this https://github.com/argoproj/argo-cd/issues/6812#issuecomment-1073918267

I got to this point and we decided to start migrating off Azure Devops to Github instead because we doubt Microsoft is going to continue to support Azure Devops on the same level as Github in the future.

**Comment by nilic** [comment] 2022-11-01 12:18
For Azure DevOps Server 2020 Update 1.1 this workaround is needed: https://github.com/argoproj/argo-cd/issues/6812#issuecomment-1166957798, just replace `ssh.dev.azure.com` with the name of your Azure DevOps server and remove line `User git`.

Azure DevOps Server 2022 RC2 adds support for additional signature algorithms besides `ssh-rsa` so hopefully this workaround won't be necessary after upgrading to the new version - [Azure DevOps Server 2022 RC2 Release Notes](https://learn.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2022?view=azure-devops#azure-devops-server-2022-rc2-release-date-october-25-2022)

**Comment by nilic** [comment] 2022-11-02 08:16
I have tested ArgoCD v2.5.0+a765c14 with Azure DevOps 2022 RC2 and can confirm that the `ssh-rsa` workaround is no longer needed.

**Comment by andrescolodrero** [comment] 2023-01-04 14:22
@nilic Hi, do you have the instruccions to connect to Azure devops? IM starting to get lost with many 
I have both AZDO on prem (2020) and cloud, and trying connection from https or git, I´d rather prefer to setup https than SSH

**Comment by rouke-broersma** [comment] 2023-01-04 17:13
> @nilic Hi, do you have the instruccions to connect to Azure devops? IM starting to get lost with many 
> I have both AZDO on prem (2020) and cloud, and trying connection from https or git, I´d rather prefer to setup https than SSH
> 

Azdo 2020 does not work, if you upgrade to 2022 it will work.

**Comment by nilic** [comment] 2023-01-04 19:27
AFAIK, AzDO Server (aka on-prem) can't work with HTTPS, only SSH. AzDO Server 2020 works as described in https://github.com/argoproj/argo-cd/issues/6362#issuecomment-1298430651, while AzDO Server 2022 doesn't need that workaround (works out of the box).

A few additional notes on adding AzDO Server to ArgoCD via SSH:
* you need to add SSH fingerprint of your AzDO Server to ArgoCD Settings - Certificates - Add SSH known hosts; fingerprint needs to be in the `known_hosts` format and the easiest way to get this is by running `ssh-keyscan <your AzDO Server address>`
* repository is added to ArgoCD without the `ssh://` prefix
* repo connection status of "Successful" in ArgoCD doesn't necessarily mean that everything is fine - you need to try to create an ArgoCD app from the repo; I've had "successful" repos failing when ArgoCD tries to pull from the repo;
* to troubleshoot adding the repo to ArgoCD you can use the logs of `argocd-repo-server` pod

I don't use Azure DevOps Services (aka cloud) so can't comment on its interoperability with ArgoCD.

**Comment by rouke-broersma** [comment] 2023-01-04 20:04
Azure devops services is fully working

**Closed** 2023-02-01 18:11 UTC
Labels: bug
