### ISSUE TITLE
Native Helm integration

### ISSUE THREAD

**Issue by shinebayar-g** [argoproj/argo-cd#12253] opened 2023-02-02 05:23 UTC
# Summary

Currently ArgoCD uses `helm template` to render yaml files. This means that we lose additional capabilities like `helm ls` etc.. `helm` cli becomes useless. Fortunately, Helm has a native [Golang SDK](https://helm.sh/docs/topics/advanced/#go-sdk) which would allow ArgoCD to integrate with Helm natively.

# Motivation

If this feature is implemented, ArgoCD users will be able to use `helm` cli features.

# Proposal

Use Helm [Golang SDK](https://helm.sh/docs/topics/advanced/#go-sdk).

**Comment by leoluz** [comment] 2023-02-02 15:32
Argo CD interfaces with helm in order to get manifests generated. That is the operation required in order to have the desired state applied in Kubernetes. Can you please describe which helm CLI features would you like to be able to use inside Argo CD and why that would be beneficial?

**Comment by crenshaw-dev** [comment] 2023-02-02 16:14
I think this is a duplicate of https://github.com/argoproj/argo-cd/issues/8591. Let's move discussion over there.

**Closed by crenshaw-dev** 2023-02-02 16:14 UTC
Labels: enhancement
