### ISSUE TITLE
Make multiple different Argo CD projects using a single repository

### ISSUE THREAD

**Issue by d7volker** [argoproj/argo-cd#9581] opened 2022-06-04 13:26 UTC
# Summary

The developers should be able to define the repositories on their own. That is why we use scoped repositories in this case. Now it can happen that developers out of two different Argo CD projects use the same repository even with different repository credentials. As you know it is impossible to define a repository twice. I would say it is a problem for us that a repo can't be defined twice or more times. As I understood you use the repo URL as the key to refer to it.

Why it is not possible to use the repo URL and the Argo CD project it is bound to as a key?

Are there other possibilities to achieve that two different Argo CD projects use same repository without bother the admins of Argo CD? For example with a dedicated RBAC rule?

# Motivation

That would also be of help in the following: Imaging a Argo CD project which is able to deploy its code on development and integration but not on production. The deployment on to production will be handled by a different Argo CD project using the same repository as the developers in the first project.

# Proposal

As I understood you use the repo URL as the key to refer to it.
Why it is not possible to use the repo URL and the Argo CD project it is bound to as a key?

**Comment by m-yosefpor** [comment] 2022-08-14 06:28
We have the same problem and it is causing many troubles for devs. Also I think the project of each repo should be showed in argocd UI (setting > repositories).

**Comment by crenshaw-dev** [comment] 2022-08-15 21:09
I think a lot of Argo CD code assumes that a repo (of a given URL) is a repo. I agree, we should provide a mechanism to use the same repo using different credentials. It would take some work on the backend, but should be possible.

**Comment by alemnew** [comment] 2023-03-09 14:58
Has there been any update on this? I also got this issue, and wouldn't appreciate if there has been a mechanism.

**Comment by dario-lab** [comment] 2023-04-07 10:18
Hi,
I have an issue where:
1. I added via UI repository to the project: Project1 HELM: helm.repo.io and this repository is working properly.
After it I tried add the same repository to the Project-2, but I have an issue:
Unable to connect HTTPS repository: existing repository spec is different; use upsert flag to force update; difference in keys "Name,Project"

What can i do to use the same repository in many projects?

**Comment by lacrimal** [comment] 2023-08-27 18:55
Is it idea similar to Google Anthos multi-repo ?
I'm looking something similar in argo-cd and stuck, at beginning was getting this feature obvious.

**Comment by FsRiachos** [comment] 2023-08-31 09:56
Hi there,

since there any update to the issue is there any workaround?

Thank you

**Comment by manali14** [comment] 2023-09-04 12:51
Hi,

Is there a workaround that people are using for this?

**Comment by m-yosefpor** [comment] 2023-09-04 15:48
You can use global repos and limit access with approj  (the old way).  Though this renders the whole point of scoped repositories useless

**Comment by SakaYK** [comment] 2023-12-17 09:49
as mentioned by m-yosefpor, you can use global repo and chose the repository in the project.
i'm using this method since v2.4.8, to use the same helm repository in multiple project environment.

1. Go to repositories menu and create helm repository connection but don't attach it to any project.
2. Create/Edit your project, Find the `SOURCE REPOSITORIES` and click the `edit` button., and chose the helm repository that you create earlier.
3. Repeat Step-2.

**Comment by yyzxw** [comment] 2024-03-27 01:54
Hi, is there any way to make different `appProject` contain different `repository`, or the same repoURL can have different credentials, for example, the same repoURL can create different Argocd applications in the same repository but different directories

**Comment by blakepettersson** [comment] 2024-05-20 10:03
Hi, see #18290 - let me know what you think

**Comment by blakepettersson** [comment] 2024-06-06 14:19
Reopening since that was the spec that got merged, not the actual implementation :)

**Closed** 2024-06-08 01:47 UTC
Labels: enhancement

**Comment by salcic** [comment] 2025-02-17 14:49
We just create the same repo with a slightly modified url by adding slashes:
e.g. https://github.com/testproject becomes https://github.com/**/**testproject
