### ISSUE TITLE
Child applications should not effect parent application's health by default

### ISSUE THREAD

**Issue by rdelpret** [argoproj/argo-cd#3781] opened 2020-06-16 15:32 UTC
**Describe the bug**

Currently, when you have an application of applications (parent, children) if the child application is unhealthy the parent application becomes unhealthy. There is currently a workaround to use a resource customization to do this but after discussing with Alex on slack he asked me to file a bug report to make this the default.

**To Reproduce**

Create an application that manages applications, take some action that forces a child application to an unhealthy state. The parent application will become unhealthy.

**Expected behavior**

I would like the parent application to remain healthy. it seems redundant for most peoples use cases to bubble up child application health to the parent.

**Version**

1.5.2

**Comment by rdelpret** [comment] 2020-06-16 15:32
Relevent slack convo: https://argoproj.slack.com/archives/CASHNF6MS/p1585143412031500

**Comment by sfynx** [comment] 2020-06-20 00:38
I guess a case can be made for both. I have app-of-apps where independent apps are installed and I don't really care about the overall health, but I also have apps that consist of multiple component apps which must all be there for the entire thing to work (essentially being one system semantically), so in that case I'm interested in its overall health. Just like when an app is degraded when some resource in it is also degraded.

Whichever scenario is most used should be the default I guess, which is fine to me as long as I can configure otherwise ;)

**Comment by rdelpret** [comment] 2020-07-22 16:34
Yeah, the discussion in slack leaned towards this being the default because it is the most common use.

**Comment by keithchong** [comment] 2020-09-28 02:24
Hi @alexmt, please assign this to me

**Comment by raelga** [comment] 2020-09-28 10:46
+1

**Comment by keithchong** [comment] 2020-09-29 01:13
Is that slack link correct?  I'm seeing a thread that talks about issue 2924

Note, currently, if the child's health state is missing or unknown, it will not affect the parent's health state.

So, if the child app's health state is "degraded", then the parent app should still be healthy.

Before:

<img width="852" alt="3781-before" src="https://user-images.githubusercontent.com/7726022/94499728-7651e700-01cb-11eb-9e39-78bb3cce205d.png">

After (Desired behavior):

<img width="904" alt="3781-after" src="https://user-images.githubusercontent.com/7726022/94499760-823da900-01cb-11eb-8243-b084961be5a6.png">

**Comment by keithchong** [comment] 2020-09-29 18:33
Hi @alexmt , could you comment on this bug and whether there should be a setting of some sort to make the behaviour configurable, perhaps a preference setting from the Projects summary settings page (settings/projects/<projectName>) or somewhere else?  IMHO, I think anything elaborate like this should be considered an enhancement, and not a bug.

**Comment by keithchong** [comment] 2020-10-06 13:52
This is how the child applications will appear now with the changes.  There is no health status.  You must open the child app to see it's health state.

<img width="703" alt="StatusRemoved" src="https://user-images.githubusercontent.com/7726022/95210395-751b4e00-07b9-11eb-9f2d-3afff81368bc.png">

**Comment by keithchong** [comment] 2020-10-06 14:07
Hi @alexmt , can this issue now be closed?

**Closed** 2020-10-29 16:39 UTC
Labels: bug

**Comment by sfynx** [comment] 2020-12-03 00:10
What is the recommended way to configure the old behavior now, where you have a composite app whose parent should only be healthy when all children are healthy (just like it works with non-Application resources inside an Application)? I'm not sure it is really wise to override any built-in health check for the Application CR itself...

**Comment by trown** [comment] 2020-12-04 17:23
@sfynx https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.7-1.8/#health-assessement-of-argoprojioapplication-crd-has-been-removed worked for me.

**Comment by sjentzsch** [comment] 2021-10-06 18:16
As a note: Configuration to customize resource behavior should now be configured via splitted sub keys, so the proper link to set up the health assessement should be found here now: https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app
