### ISSUE TITLE
Incorrect conversion between integer types

### ISSUE THREAD

**Issue by martin-nolan-2020** [argoproj/argo-cd#18432] opened 2024-05-28 11:56 UTC
Incorrect conversion of an integer with architecture-dependent bit size from strconv.ParseInt to a lower bit size type int32 without an upper bound check.

**Comment by martin-nolan-2020** [comment] 2024-05-28 11:56
I will work on this issue

**Comment by mbaldessari** [comment] 2024-05-29 07:22
Dupe of https://github.com/argoproj/argo-cd/issues/18435 ?

**Comment by jsoref** [comment] 2024-09-22 01:43
https://github.com/argoproj/argo-cd/issues/18435#issuecomment-2365408891

**Closed by jsoref** 2024-09-22 01:43 UTC
Labels: enhancement, component:core
