### ISSUE TITLE
Multi-sourced Application auto-sync only works for one of the sources

### ISSUE THREAD

**Issue by mulhotavares** [argoproj/argo-cd#12939] opened 2023-03-20 17:23 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
When using Multi-sourced Application in Argocd, changes to one of the sources is not auto-synced.

In my scenario, I have 2 sources: one source contains the helm chart, and the other a values file. If I change the values file, the application will show as OutOfSync, but auto-sync is not triggered.

**To Reproduce**
Create an application like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-helm-chart
  namespace: argocd
spec:
  project: test-project
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Validate=true
  destination:
    namespace: test-helm
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com/mulho/values-repo.git
      targetRevision: main
      ref: valuesRepo
    - repoURL: git@github.com/mulho/simple-helm-chart.git
      targetRevision: main
      path: chart
      helm:
        valueFiles:
          - $valuesRepo/environments/dev/values.yaml
        values: |
          someValue: hola
```
Edit the value in the `values-repo` and wait for some time. The application will be marked as OutOfSync in the UI.
You can describe the ConfigMap and validate the configmap does not reflect the new value.

**Expected behavior**
Changes to both sources should trigger a sync given that Auto-Sync is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/103086251/226418703-e02b7723-d3e7-42bc-b3b3-1e100653aa40.png)

**Version**

```shell
argocd: v2.6.6+6d4de2e.dirty
  BuildDate: 2023-03-17T00:05:38Z
  GitCommit: 6d4de2ec5d49fa2c6823f2b7d101607a839be3fa
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.6+6d4de2e.dirty
  BuildDate: 2023-03-17T00:05:38Z
  GitCommit: 6d4de2ec5d49fa2c6823f2b7d101607a839be3fa
  GitTreeState: dirty
  GoVersion: go1.20.2
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:28:01Z
  Helm Version: v3.10.0+gce66412
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by mulhotavares** [comment] 2023-03-20 17:57
Note a workaround is to enable `selfHeal`...

**Comment by caseyg-ronin** [comment] 2023-04-12 21:46
Having the same issue on `v2.6.7` and `v2.7.0-rc2`. Also confirmed (on `v2.7.0-rc2`) that setting `syncPolicy.automated.selfHeal: true` enables value file changes to be detected and auto-synced.

FWIW, this ticket seems like #12366 was a dupe.

**Comment by gaeljw** [comment] 2023-05-04 07:09
I'm having the same issue (v2.6.7).

**Comment by crenshaw-dev** [comment] 2023-06-07 15:31
There is logic that "requests a refresh" in the controller. I feel like that code is solid. I spent a lot of time working out the bugs.

So there's likely a problem with the code that says "oh hey, the refresh resulted in out-of-sync. Now it's time to sync."

**Comment by IanKWatts** [comment] 2023-07-17 19:54
I've confirmed that enabling Self-Heal resolves the problem of auto-sync not running following an update to one of two source repos.
However, I still have an issue with a post-sync job.  It only runs if there was an update in the same repo as that job.  I was hoping to have a user-controlled resource in repo 1 and an admin-controlled post-sync job in repo 2, but I haven't been able to get the job to run when only repo 1 has an update, even though the auto-sync does run.  Any suggestions?

**Comment by yukccy** [comment] 2023-10-10 00:15
In my case, I have a public Helm repo and private Git repo for values.yaml as sources. After I pushed new changes to the Git repo, it is still showing Synced. I cannot even see a OutofSync.

**Comment by kimminw00** [comment] 2024-03-28 08:11
For me, I used airflow helm chart(1.11.0) and edited <code>[extraSecrets](https://github.com/apache/airflow/blob/142e67c45485b25e988aced3cc37dd9cb2a8ab71/chart/values.yaml#L327)</code> from values.yaml file.
The application was marked as Synced in the UI. But the secret does not reflect the new value.
The value changed only when I press the sync button in the UI.

Environments:
ArgoCD : 2.6.7
Airflow helm chart : 1.11.0

**Comment by adberger** [comment] 2024-04-02 04:40
Any updates on this?

**Comment by Mangaal** [comment] 2024-04-29 10:49
Hi all, I tried to reproduce this issue with ArgoCD v2.9 with the same application Yaml mentioned above, after updating the second source the application got synced successfully.

**Comment by gaeljw** [comment] 2024-04-29 11:24
> Hi all, I tried to reproduce this issue with ArgoCD v2.9 with the same application Yaml mentioned above, after updating the second source the application got synced successfully.

I didn't pay attention to it but I also think it's fixed for a few versions already. I have several apps with this setup and they sync successfully when changing either source. (Currently using v2.9.5)

**Comment by ishitasequeira** [comment] 2024-04-29 12:08
Thanks @Mangaal and @gaeljw for confirming.

**Closed by ishitasequeira** 2024-04-29 12:08 UTC
Labels: bug, multi-source-apps
