### ISSUE TITLE
Docs should provide instructions on the newest version of the Argo CD CLI

### ISSUE THREAD

**Issue by christianh814** [argoproj/argo-cd#15469] opened 2023-09-12 19:09 UTC
**Describe the bug**

Argo CD cli instructions downloads v2.6, it should download the latest.

**To Reproduce**

```shell
$ wget -q https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /tmp/argocd
$ chmod +x /tmp/argocd
$ /tmp/argocd version --client 
argocd: v2.6.15+2f7922b
  BuildDate: 2023-09-07T18:15:17Z
  GitCommit: 2f7922be9c8f364fec435eec4860b49279be77da
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
```

**Expected behavior**

It should download the latest version of the newest release

**Other**

Other projects address this by having a `newest_latest.txt` (or something like that) and that has the "latest" of the "newest" version so you can do something like...

```shell
export ARGOCD_VERSION=$(curl -L -s https://some.web.site/release/newest_latest.txt)
wget -q https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-amd64
```

**Comment by torqu3e** [comment] 2023-09-13 02:59
Do you know what was latest pointed to at the time of that command being run? The issue isn not replicable
```
$ wget -q https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /tmp/argocd
$ chmod +x /tmp/argocd
$ /tmp/argocd version --client 
argocd: v2.8.3+77556d9
  BuildDate: 2023-09-07T17:39:16Z
  GitCommit: 77556d9e64304c27c718bb0794676713628e435e
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
```

If you browse to https://github.com/argoproj/argo-cd/releases/latest it will show where is the latest tag pointing to. In case there is an issue where a release is not marked as latest I can see the above happening.

**Comment by jannfis** [comment] 2023-09-13 14:55
Unfortunately, `latest` is not a tag, but some kind of internal GitHub pointer. And it will always point to the release that has been published most recently, not taking semver into account.

At the time @christianh814 tried, 2.6.15 was set as latest release (it was the one most recently released), but meanwhile somebody seems to have set 2.8.3 manually as the `latest` (can be done from the GitHub releases page).

**Comment by christianh814** [comment] 2023-09-13 15:01
> And it will by default point to the release that has been published most recently, not taking semver into account.

Yes, that's the issue. Some people can experience when following the documentation to install the cli.

**Comment by jannfis** [comment] 2023-09-13 15:16
> Other projects address this by having a newest_latest.txt (or something like that) and that has the "latest" of the "newest" version so you can do something like...

We have the `stable` tag, pointing to the current stable release (it's meanwhile updated automatically by the release process).

So we could have:

```
export ARGOCD_VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)
```

**Closed** 2024-01-24 03:32 UTC
Labels: bug, type:docs, component:cli
