### ISSUE TITLE
Application and deployment are stuck in degraded despite everything is healthy 

### ISSUE THREAD

**Issue by PercevalCox** [argoproj/argo-cd#16478] opened 2023-11-29 10:47 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

One replicaset was in "Degraded" state, but is now healthy. However, the application state is still Degraded despite all resources are Healthy.
Moreover, the deployment is marked as "Degraded" but in the UI, when we click on it, deployment is marked as Healthy (screenshot 3)

**Expected behavior**
Application should by "Healthy" and not "Degraded"

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/142888562/7f6e6a2c-a36a-4df7-8f4b-52ee792a4431)
![image](https://github.com/argoproj/argo-cd/assets/142888562/4250a0cd-01e2-4fcb-87be-f9b0e34d063b)
![image](https://github.com/argoproj/argo-cd/assets/142888562/3de2a04a-b817-498a-bfe6-1b19a8c0d767)

**Version**

```shell
argocd-server: v2.9.2+c5ea5c4
  BuildDate: 2023-11-20T17:18:26Z
  GitCommit: c5ea5c4df52943a6fff6c0be181fde5358970304
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```
chart version : 5.51.4

**Logs**

```
time="2023-11-29T10:26:39Z" level=info msg="Refreshing app status (normal refresh requested), level (3)" application=argocd/dev-test-template-golang-master
time="2023-11-29T10:26:39Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: coresre)" application=argocd/dev-test-template-golang-master
time="2023-11-29T10:26:39Z" level=info msg="getRepoObjs stats" application=argocd/dev-test-template-golang-master build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=8 unmarshal_ms=7 version_ms=0
time="2023-11-29T10:26:39Z" level=info msg="Skipping auto-sync: application status is Synced" application=argocd/dev-test-template-golang-master
time="2023-11-29T10:26:39Z" level=info msg="Updated health status: Degraded -> Healthy" application=dev-test-template-golang-master dest-namespace=coresre dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal
time="2023-11-29T10:26:39Z" level=error msg="Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"image\"" application=argocd/dev-test-template-golang-master
time="2023-11-29T10:26:39Z" level=info msg="Reconciliation completed" application=argocd/dev-test-template-golang-master dedup_ms=0 dest-name= dest-namespace=coresre dest-server="https://kubernetes.default.svc" diff_ms=30 fields.level=3 git_ms=8 health_ms=0 live_ms=5 patch_ms=0 setop_ms=0 settings_ms=0 sync_ms=0 time_ms=78     
```

**Comment by PaulSonOfLars** [comment] 2024-01-02 10:10
This looks like a duplicate of #15126 to me; more info in that thread

**Comment by jgwest** [comment] 2024-03-28 19:24
Closing as above

**Closed by jgwest** 2024-03-28 19:24 UTC
Labels: bug
