### ISSUE TITLE
Allow Helm plugins in applications with multiple sources to use 'ref' variable

### ISSUE THREAD

**Issue by bjunker99** [argoproj/argo-cd#15795] opened 2023-10-03 14:51 UTC
# Summary

Currently for applications that are configured for multiple sources, the 'ref' variable in limited to the beginning of the value.

# Motivation

Helm downloader plugins allow for the extension of the features provided by helm.  Plugins are already supported by ArgoCD and single source application configurations according to the documentation here: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-plugins

# Proposal

Since you have to take additional custom steps to in order to include plugins in ArgoCD with additional configuration, I believe that the default way the 'ref' variable is handled should remain default.  However, if it is detected that a plugin is authorized by comparing the protocol portion of the value against the `helm.valuesFileSchemes` configuration, allow the variable to be substituted.

I put together an implementation of what I am describing here: https://github.com/argoproj/argo-cd/compare/master...bjunker99:argo-cd:feat/multi-source-plugins#files_bucket

**Comment by crenshaw-dev** [comment] 2023-10-03 15:26
I believe this is a duplicate of https://github.com/argoproj/argo-cd/issues/12476

Let me know if I'm incorrect, and I can reopen!

**Closed by crenshaw-dev** 2023-10-03 15:26 UTC
Labels: enhancement
