### ISSUE TITLE
Kustomize installation manifests don't include ApplicationSet controller

### ISSUE THREAD

**Issue by mikesmitty** [argoproj/argo-cd#8734] opened 2022-03-09 23:34 UTC
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

The ApplicationSet controller isn't bundled with ArgoCD 2.3.0 when installing via kustomize, only in the generated yaml files

**To Reproduce**

```shell
$ curl -sL https://github.com/argoproj/argo-cd/raw/v2.3.0/manifests/ha/install.yaml |grep -m1 ApplicationSet
    kind: ApplicationSet
```
```shell
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.3.0
$ kustomize build . |grep -m1 ApplicationSet
$
```

**Expected behavior**

Expected that the ApplicationSet controller is installed along with ArgoCD when installing via kustomize remote

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.3.0+fe42780
  BuildDate: 2022-03-06T06:27:40Z
  GitCommit: fe427802293b090f43f91f5839393174df6c3b3a
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment] 2022-03-10 14:00
Duplicate of https://github.com/argoproj/argo-cd/issues/8699

**Closed by crenshaw-dev** 2022-03-10 14:00 UTC
Labels: bug
