### ISSUE TITLE
ArgoCD application.instanceLabelKey values limited to Kube Label limit of 63 characters

### ISSUE THREAD

**Issue by sidewinder12s** [argoproj/argo-cd#5594] opened 2021-02-24 18:05 UTC
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Found this issue that seems related: #1482

We've been trying to build out some newer EKS clusters with an App of Apps pattern of a core app that then manages apps for various cluster components like AWS LB controller, Ambassador, aws-node-termination-handler, etc.

Most of our initial clusters had short cluster names, but we've needed to create longer cluster names to deal with the increasing number of clusters. As part of App of Apps, we construct ArgoCD App names based on the following: `<aws account name>-<cluster name>-<app>`

This can result in something like this: my-scratch-account-my-scratch-cluster-aws-loadbalanacer-controller
Which is over the 63 character limit of labels in Kubernetes. 

This was originally because ArgoCD Apps as far as we've seen must be uniquely named within each ArgoCD instance. Once we started getting longer cluster names we ran into Helm issues due to resource names/labels being too long. We can get around that by setting releaseName on the helm chart to the explicit chart name and move on. 

We are setting application.instanceLabelKey in the `argocd-cm.yaml` to the recommended `argocd.argoproj.io/instance` to avoid issues with the helm release rename.

It doesn't appear you can set this value however at the app level if you need to deal with a long name that might be inherited by the ArgoCD App name.

**To Reproduce**

Name an ArgoCD app longer than 63 characters.

**Expected behavior**

This label shouldn't be limited by 63 characters or should be configurable at the app level similar to Helm releaseName

Is there a recommended workaround for this limitation? Could that tracking label be converted to using an Annotation so we're not limited to 63 characters?

**Screenshots**

-

**Version**

```shell
argocd version
argocd: v1.8.4+28aea3d
  BuildDate: 2021-02-05T17:54:42Z
  GitCommit: 28aea3dfdede00443b52cc584814d80e8f896200
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.8.1+c2547dc
  BuildDate: 2020-12-10T02:59:21Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.1 2020-07-16T00:58:46Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0

```

**Comment by jessesuen** [comment] 2021-02-24 21:24
Duplicate of https://github.com/argoproj/argo-cd/issues/5595

**Closed by jessesuen** 2021-02-24 21:24 UTC
Labels: bug
