### ISSUE TITLE
Cannot add application via UI, errors in console log

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#1061] opened 2019-01-24 07:27 UTC
Argocd version : 0.11.1

When trying to add a helm application the browser turns grey when trying to add a namespace (last field)

![image](https://user-images.githubusercontent.com/9946020/51661630-b651d700-1fb1-11e9-9cb3-2e9a882e0789.png)

![image](https://user-images.githubusercontent.com/9946020/51661397-0da37780-1fb1-11e9-86ad-fd6619651c45.png)

**Comment by alexmt** [comment] 2019-01-25 06:56
Fixed by https://github.com/argoproj/argo-cd-ui/commit/4bcef1bc679704d9a2361a17dad156235a77e97e


@peterbosalliandercom , the issue is reproducible in app project has a destination with an empty namespace. ( project could be created using `argocd proj add-destination inpai '<server-url>' ''`  ). As workaround you might remove destination with empty namespace. Use '*' instead of empty string In case you wanted to whitelist all cluster namespaces.

**Closed by alexmt** 2019-01-25 06:56 UTC

**Comment by peterbosalliandercom** [comment] 2019-01-25 15:48
Thanks!
