### ISSUE TITLE
getting this error every minute

### ISSUE THREAD

**Issue by dmaneru** [argoproj/argo-cd#14572] opened 2023-07-18 13:53 UTC
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by crenshaw-dev** [comment] 2023-07-18 13:55
Closing for lack of details. Edit and then tag me, and I'll reopen.

**Comment by dmaneru** [comment] 2023-07-18 14:23
from openshift gitops operator, argoCD version: Argo CD 2.7.6

Log output:
TypeError: Cannot read properties of undefined (reading 'podGroup')
    at https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:1746120
    at Array.forEach (<anonymous>)
    at https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:1746050
    at Array.forEach (<anonymous>)
    at https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:1745987
    at $m (https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:1746449)
    at Jr (https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:808335)
    at Bs (https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:817184)
    at ya (https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:855459)
    at pl (https://openshift-gitops-server-openshift-gitops.apps.cluster-r6t7f.r6t7f.sandbox19.opentlc.com/main.b9cc0848a3a3b1aa5306.js:2:847016)

**Comment by dmaneru** [comment] 2023-07-18 15:01
> Closing for lack of details. Edit and then tag me, and I'll reopen.

@crenshaw-dev

**Comment by crenshaw-dev** [comment] 2023-07-18 15:03
Can you describe tests to reproduce the issue?

**Comment by crenshaw-dev** [comment] 2023-07-18 15:03
Basically, please edit and fill out the issue template. :-)

**Comment by dmaneru** [comment] 2023-07-18 15:28
I just get this randomly... I am doing tests of integrations with applicationSets through argoCD in an openshift 4.12 with ACM
![image](https://github.com/argoproj/argo-cd/assets/84586848/c4b92621-4ec3-4c7a-a917-a29936c32181)

**Comment by dmaneru** [comment] 2023-07-18 15:28
i have installed acm and gitops through operators

**Comment by crenshaw-dev** [comment] 2023-07-18 15:39
To reproduce the issue, I'll need the steps you take to get to that window.... I see that you're looking at a particular application. Did the error appear after you clicked something in the application UI?

**Comment by dlydiard** [comment] 2023-07-28 18:12
i get the same error for our management cluster Application, but not Applications for other clusters. All i do is click on the Application and after the screen loads i get the same podGroup error. The screen initially renders and looks fine and after around 3 seconds the podGroup error appears. We are on v2.7.6+00c914a.


```
TypeError: Cannot read properties of undefined (reading 'podGroup')
    at https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:1746120
    at Array.forEach (<anonymous>)
    at https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:1746050
    at Array.forEach (<anonymous>)
    at https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:1745987
    at $m (https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:1746449)
    at Jr (https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:808335)
    at Bs (https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:817184)
    at ya (https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:855459)
    at pl (https://openshift-gitops-server-openshift-gitops.apps.aw-ue1-mt1.fvip.p1.openshiftapps.com/main.b9cc0848a3a3b1aa5306.js:2:847016)

```

**Comment by crenshaw-dev** [comment] 2023-07-28 18:40
Is the app small/simple enough to create a public repo to reproduce the issue?

**Comment by dlydiard** [comment] 2023-07-28 18:41
No, it's a full cluster repo, it's very large.

**Comment by dlydiard** [comment] 2023-07-28 20:15
Update: I noticed I had an OLM `Subscription` for openshift-pipelines 1.10 in an unhealthy state, where it said an OLM install plan was not found. I removed the Subscription, and re-installed the operator, and the podGroup error went away.

So this issue might be related to health checks and unhealthy statuses? This might also explain why this issue did not popup on our other clusters, since no Subscriptions were in a unhealthy status.

**Comment by mcouthon** [comment] 2023-11-07 08:44
This is happening for me as well, whenever I open _some_ of the apps. I haven't found a connecting through line between the apps for which it happens and for those where it doesn't happen.

![CleanShot 2023-11-07 at 10 43 47@2x](https://github.com/argoproj/argo-cd/assets/844807/f5cc63bb-5290-4ee7-9587-4c6587e46f4b)

**Comment by winterrobert** [comment] 2023-11-29 13:06
It happened for me as well on helm chart version 5.36.1. After upgrading to the latest (5.51.4) it started working.

**Comment by jgwest** [comment] 2024-02-10 11:28
Duping to https://github.com/argoproj/argo-cd/issues/13416

**Closed by jgwest** 2024-02-10 11:28 UTC
Labels: bug
