### ISSUE TITLE
Failed to deploy app in v0.10.5 with v1.12.1 kubernetes

### ISSUE THREAD

**Issue by kuznero** [argoproj/argo-cd#774] opened 2018-11-14 10:04 UTC
Linked to #718 (created as new issue).

Here is what I get trying to deploy most trivial things (in kube-system ns, but still):

```
> argocd app sync admin
KIND  NAME  STATUS  HEALTH  HOOK  OPERATIONMSG

Application:        admin
Operation:          Sync
Phase:              Failed
Start:              2018-11-14 09:35:24 +0100 CET
Finished:           2018-11-14 09:35:36 +0100 CET
Duration:           12s
Message:            one or more objects failed to apply (dry run)

KIND            NAME        STATUS     HEALTH   HOOK  OPERATIONMSG
ServiceAccount  admin-user  OutOfSync  Missing        Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=serviceaccounts", GroupVersionKind: "/v1, Kind=ServiceAccount"
Name: "admin-user", Namespace: "kube-system"
Object: &{map["apiVersion":"v1" "kind":"ServiceAccount" "metadata":map["labels":map["applications.argoproj.io/app-name":"admin"] "name":"admin-user" "namespace":"kube-system" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]]]}
from server for: "STDIN": serviceaccounts "admin-user" is forbidden: User "system:anonymous" cannot get resource "serviceaccounts" in API group "" in the namespace "kube-system"
ClusterRoleBinding  admin-user  OutOfSync  Missing       Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io "admin-user" is forbidden: User "system:anonymous" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

The requested helm chart only has service account and a role binding (to cluster-admin).

After downgrading Argo CD to v0.10.4 deployments of apps start working again. But getting back to original issue of not being able to delete resources in kubernetes v1.12.x (according to #718).

**Comment by kuznero** [comment] 2018-11-14 14:37
So far, workaround is to use:

* Argo CD: v0.10.4
* Kubernetes Cluster: v1.11.2

To be able to use latest v1.12.x Kubernetes it will be necessary to fix it.

**Comment by arnarg** [comment] 2018-11-14 15:01
I'm also seeing this on `v1.10.3-eks` while `v0.10.4` works fine.

**Comment by jessesuen** [comment] 2018-11-14 19:59
This is related to the upgrade of the go-client to v9.0 and affects deploying to apps in cluster (https://kubernetes.default.svc). The root cause is that there was a change in behavior in the go-client where the new client will no longer return bearer tokens when getting a rest config. See relevant discussion:

https://github.com/kubernetes/kubernetes/pull/69270

The change caused problems for apps which serialize the in-cluster restconfig to a file, to subsequently use by kubectl.

The solution is to explicitly set the path to the service account token (var/run/secrets/kubernetes.io/serviceaccount/token) in the case of an in-cluster REST config, instead of relying on the call to InClusterConfig() to return a serializable config.

**Comment by kuznero** [comment] 2018-11-14 20:54
So, do I understand correctly that it can be worked around by setting `TokenFile` in `kubeconfig` to value found in `/var/run/secrets/kubernetes.io/serviceaccount/token` file (please provide some more info if possible)? And otherwise, what would be the proper solution to cope with this Kube change? Is it planned for v0.11? @jessesuen , do you need help with this?

**Comment by jessesuen** [comment] 2018-11-14 22:10
@kuznero We will put out another patch today

**Comment by jessesuen** [comment] 2018-11-15 03:54
Release v0.10.6 with the fix for this issue:
https://raw.githubusercontent.com/argoproj/argo-cd/v0.10.6/manifests/install.yaml

Sorry for the trouble!

**Closed by jessesuen** 2018-11-15 03:54 UTC

**Comment by kuznero** [comment] 2018-11-15 09:13
Thanks! Tested now. Works perfectly!
