### ISSUE TITLE
Docs always report being for an unreleased version / version selection broken

### ISSUE THREAD

**Issue by der-eismann** [argoproj/argo-cd#19320] opened 2024-07-31 15:35 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When browsing [https://argo-cd.readthedocs.io/en/stable/](), the page always says
> You are viewing the docs for an unreleased version of Argo CD, [click here to go to the latest stable version.](https://argo-cd.readthedocs.io/en/stable/)

However the link in the banner points to the same address, so the banner always stays there. At the same time the version dropdown menu is broken and doesn't open, IIRC it allowed to view docs for an older version. Not sure if something went wrong when deploying the latest docs.

**To Reproduce**

Browse https://argo-cd.readthedocs.io/en/stable/

**Expected behavior**

No banner or a link to the latest released version

**Screenshots**

![screenshot-20240731-173109](https://github.com/user-attachments/assets/44ede15c-037b-4160-9351-7d412739852b)

**Comment by ChristianCiach** [comment] 2024-07-31 16:02
Duplicate of https://github.com/argoproj/argo-cd/issues/18407

**Closed** 2024-07-31 17:18 UTC
Labels: bug, type:bug, component:documentation

**Comment by der-eismann** [comment] 2024-08-01 07:09
Sorry, had trouble finding this, thanks for linking.
