### ISSUE TITLE
Web Terminal link is shown for Deployment/Replicaset objects

### ISSUE THREAD

**Issue by gaurav517** [argoproj/argo-cd#10337] opened 2022-08-15 15:28 UTC
Version: `v2.4.9`.

Web Terminal link is shown for Deployment/Replicaset objects. Which fails. On the left side, containers section does not show the containers (it same if we go to logs link).

![image](https://user-images.githubusercontent.com/15346341/184664873-4e734add-12f9-416f-a6b6-f0c4f168c48d.png)

**Comment by ashutosh16** [comment] 2022-09-09 16:56
duplicate of [9980](https://github.com/argoproj/argo-cd/issues/9980). The issue is fixed in this PR[pull/10556](https://github.com/argoproj/argo-cd/pull/10556)
@crenshaw-dev Can we close the issue? thx!

**Comment by crenshaw-dev** [comment] 2022-09-09 17:56
Yep! The fix will be in 2.4.12.

**Closed by crenshaw-dev** 2022-09-09 17:56 UTC
Labels: bug, component:ui, component:web-terminal
