### ISSUE TITLE
argocd cli needs to work on multi-source apps

### ISSUE THREAD

**Issue by PerfiX** [argoproj/argo-cd#12318] opened 2023-02-07 13:41 UTC
# Summary

argocd cli does not work on multi-source apps at the moment

# Motivation

argocd multi-sources are a wonderful enrichment. Unfortenately the argocd cli (I used argoproj/argocd:v2.6.0) isn't able to sync multi-source apps.

`FATA[0000] argocd cli does not work on multi-source app`

Is it planned to add this feature?

**Comment by blakepettersson** [comment] 2023-02-07 15:40
That's definitely the plan, AFAIK it's targeted for 2.7.

**Comment by kksudo** [comment] 2023-03-09 01:28
Is there any chance to start syncing applications (like `argocd sync` cmd) not through the UI for multi-source apps?

**Comment by njohnstone2** [comment] 2023-03-14 20:25
Is there a rough ETA for when we could expect v2.7? I'm planning to use the `sync` and `set` commands to automate version promotion between environments as part of a CI pipeline, but this is blocking me from being able to move to argoCD from an existing CD solution.

**Comment by kksudo** [comment] 2023-03-14 20:27
> Is there a rough ETA for when we could expect v2.7? I'm planning to use the `sync` and `set` commands to automate version promotion between environments as part of a CI pipeline, but this is blocking me from being able to move to argoCD from an existing CD solution.

[Argo CD Roadmap](https://github.com/orgs/argoproj/projects/25/views/14)

> Release 2.7 (2023-5-1)

**Comment by reginapizza** [comment] 2023-03-29 14:36
@Yaytay you are correct, it is not in RC1. I'm able to start working on the proposal next week but it will still take some time to have it approved and then implemented. I think it's more likely to go into 2.8. I will be bringing this up in the community meeting tomorrow.

**Comment by talitz** [comment] 2023-05-03 07:07
Hi, are there any recent updates about this feature?

**Comment by TechDawg270** [comment] 2023-06-01 19:06
To be able to use multiple source apps but not use the CLI for automation based on that setup is a big deal in my opinion, and it does not appear to be addressed as of v2.7

**Comment by crenshaw-dev** [comment] 2023-06-01 20:36
We gated CLI actions on multi-source apps behind that error because we were concerned that certain CLI commands would have surprising behavior when encountering a multi-source app.

I think we could selectively un-gate the `sync` command, because I can't imagine any surprising misbehavior. Other commands will need to be analyzed and either un-gated or fixed on a case-by-case basis.

**Comment by reginapizza** [comment] 2023-06-02 14:01
FYI I started on a proposal for this yesterday, should have it up soon!

**Comment by TechDawg270** [comment] 2023-06-02 15:32
Related question - From what I have attempted and gather unless mistaken based on that is that this also renders `argocd app set ...` somewhat useless when using multiple repo sources. It looks like I have to run the command from where the Helm chart lives, and when I reference the values file via a relative file path I get the error `<values file> resolved to outside repository root`. It seems like this would go back to gating CLI commands for multi-source apps and isn't necessarily unexpected behavior based on that

**Comment by tjouno** [comment] 2023-06-27 09:55
Thanks a lot @reginapizza because we are very frustrated ;-) The "sync" command works between ArgoCD server 2.7.6 and ArgoCD CLI 2.5.19 but not with the last version of CLI. It's a feature highly anticipated by us because this block the CI/CD processes.

Thanks all for your work

**Comment by john-jam** [comment] 2023-07-11 04:17
Possible related comment: When using `argocd app set` with `-p` option to update a value, only the **first** source in the `sources` list is updated/reachable. Is there currently a way to update the values of the **second** source in the list?

For example, updating values for `values2.yml` for `repo2`:
```yaml
  sources:
    - repoURL: https://github.com/user/repo1.git
      path: helm_chart1
      helm:
        valueFiles:
          - values1.yaml
    - repoURL: https://github.com/user/repo2.git
      path: helm_chart2
      helm:
        valueFiles:
          - values2.yaml
```

**Comment by njohnstone2** [comment] 2023-07-11 06:30
The roadmap linked above shows this is currently targeted for `Release 2.9 (2023-11-6)`. Hopefully it makes the cut as its been getting pushed back since 2.7 🙏

**Comment by s7an-it** [comment] 2023-07-17 04:59
This was initially set for 2.8, a lot of people jumped on the multi-source train and it kind of was left half-baked. I think a lot of less priority items were handled this release so is kind of disappointing that this was not prioritized.

**Comment by crenshaw-dev** [comment] 2023-07-17 12:05
> I think a lot of less priority items were handled this release so is kind of disappointing that this was not prioritized.

Speaking just for me and not all maintainers: I generally give priority to open pull requests before issues (even high priority issues), which is why some changes make it and not others: it was high enough priority for someone to write the code. The Roadmap is not a guarantee by any person or organization that they will complete a feature by a certain date - that kind of guarantee would have to be negotiated (and almost certainly paid for) separately. 

There is also a documented path for users to become contributors and then maintainers. Having more maintainers available to help review in-flight work would free up development time for bugfixes.

I see that someone opened a PR to un-gate the sync command. I'll try to review ASAP. If merged, I'll cherry-pick it to patch releases so you don't have to wait another quarter.

**Comment by crenshaw-dev** [comment] 2023-07-19 17:14
`argocd app sync` now works for multi-source apps when neither `--local` nor `--revision` are set. The fix will be in these versions:
* 2.8.0-rc5 (queued)
* 2.7.8 (released)
* 2.6.13 (queued)

**Comment by lhriley** [comment] 2023-07-19 23:17
I was just able to test this out using the `2.7.8` version from `brew upgrade argocd` and it works with backwards compatibility for `2.6.x` which we are running.

Thanks for the extra effort @crenshaw-dev

**Comment by s7an-it** [comment] 2023-07-20 01:26
Great, thanks a lot, I will need some time fully testing it out as for me this unlocks a lot of pending changes like move away from ots model.

**Comment by jcogilvie** [comment] 2023-08-16 18:04
Seconding @TechDawg270 's question.  Is there a way to target the second or third (or every) source with `argocd app set`?

**Comment by crenshaw-dev** [comment] 2023-08-16 19:42
Not currently. That feature still needs to be designed/implemented.

**Comment by lauragra-y** [comment] 2024-04-05 11:47
@crenshaw-dev Is there a plan for that work at all? In particular `argocd app sync --local` for a multisource app would be very useful for us.

**Comment by ishitasequeira** [comment] 2024-06-18 01:27
Summary of commands added/supported for multi-source applications based on the above table

| Done               | Command                | Flag(s)      | Notes                                                        |
|--------------------|------------------------|--------------|--------------------------------------------------------------|
| :white_check_mark: | `argocd app sync`      |         |
| :x:                | `argocd app sync`      | `--local`    | Not going to be supported as sync operation needs access to revisions for all sources while syncing        |
| :white_check_mark:                | `argocd app sync`      | `--revisions`, `--source-position` |                     |
| :white_check_mark:                | `argocd app diff`      | `--revisions`, `--source-position` |                     |
| :white_check_mark:                | `argocd app manifests` | `--revisions`, `--source-position` |                     |
| :white_check_mark:                | `argocd app history`   |              |                        |
| :white_check_mark:                | `argocd app rollback`  |              |             |
| :white_check_mark:                | `argocd app set`       |   `--source-position`           |  |
| :white_check_mark:                | `argocd app unset`     |    `--source-position 1`          |  |
| :white_check_mark:                | `argocd app add-source`     |    `--source-position 1`          |  |
| :white_check_mark:                | `argocd app remove-source`     |    `--source-position 1`          |  |

**Comment by ishitasequeira** [comment] 2024-06-18 01:28
Closing the ticket as CLI support for multi-source applications has now been added.

**Closed by ishitasequeira** 2024-06-18 01:28 UTC
Labels: enhancement, multi-source-apps
