### ISSUE TITLE
patch level updates helm charts are not synced

### ISSUE THREAD

**Issue by peterbosalliandercom** [argoproj/argo-cd#2391] opened 2019-10-01 15:01 UTC
**Describe the bug**

We use helm dependency charts based on a patch-level version match:
version: ~1.2.3
Argocd does not detect a new version.

**To Reproduce**

1. create helm chart version x 
2. create argoapp with helm chart with a subchart, requirements.yaml:
```
dependencies:
- name: openshift-generic-valuestream
  version: ~0.1.57 (important bit is ~)
  repository: xxxxxx
```
**Example**
same as helm-dependency on https://github.com/argoproj/argocd-example-apps
but then with ~5.0.2
**Expected behavior**

When a new version of the subchart is created (5.0.3) in this case argocd should get out of sync
automatically

**Version**
1.2.2

**Comment by alexec** [comment] 2019-10-01 17:10
Argo CD is only trigger by changes to the Git repo or the cluster. Changes in the repository are not tracked, and this is by design.

**Comment by alexmt** [comment] 2019-10-01 21:40
I think this behavior is similar to kustomize remote base. Argo CD caches manifest using commit sha as a key and do not try to watch for remote base change. @peterbosalliandercom can you try running `argocd app get <appName> --hard-refresh` (or click 'Hard Refresh' button in UI)? This should invalidate the cache

**Comment by peterbosalliandercom** [comment] 2019-10-02 05:54
Yes I understand but in the end we'd like to have no-ops when a minor version is upgraded. Now we have to upgrade each app manually and this is against the goal of continuous delivery right?

**Comment by alexec** [comment] 2019-10-02 17:45
I'd highlight this is something we might consider for labs project. We state that both Kustomize and Helm are first-class support, but people want to bring in updates from unusual places. What about a third-trigger? Once every N Git fetches, we re-generate even if there is no changes to Git?

**Comment by OmerKahani** [comment] 2019-10-03 07:27
@alexec Once in every N can be confusing, how can I now when it will happen, when I view the application in the UI?

**Comment by alexec** [comment] 2019-10-18 21:12
You can now reduce the `--repo-cache-expiration` option as documented in https://argoproj.github.io/argo-cd/operator-manual/high_availability/ and your charts will update more often.

**Comment by alexec** [comment] 2019-10-18 21:13
I've labelled this as workaround/wontfix. Please try out the new flag and see if it works for you.

**Comment by peterbosalliandercom** [comment] 2019-10-22 06:59
Nice! will test this today

**Closed** 2020-05-08 18:57 UTC
Labels: bug, workaround
