### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'chart')

### ISSUE THREAD

**Issue by JanMezey** [argoproj/argo-cd#16464] opened 2023-11-28 12:48 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After trying to sync one of our applications that is currently out of sync we get redirected to a page with the following output

Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).

Stacktrace:

TypeError: Cannot read properties of undefined (reading 'chart')
    at Xm (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:1764173)
    at Jr (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:808335)
    at Bs (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:817184)
    at ya (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:855459)
    at pl (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:847016)
    at ul (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:846941)
    at il (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:843971)
    at https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:795750
    at t.unstable_runWithPriority (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:870798)
    at Uo (https://argocd.luna.cmddev.thermofisher.com/main.4c7fc665b39044302151.js:2:795459)

Try to simply sync our application

**Screenshots**

![image](https://github.com/argoproj/argo-cd/assets/97164482/5ef4a263-1114-4c9d-a713-4df31fa8b0b4)

**Version**
    Chart version
    targetRevision: 5.34.6

**Logs**
<img width="299" alt="image" src="https://github.com/argoproj/argo-cd/assets/97164482/f0519d53-3652-4830-8021-5a970ab435ac">
inspecting the element of the page i also found this error...

**Comment by jgwest** [comment] 2024-02-10 11:40
Dupe of https://github.com/argoproj/argo-cd/issues/15545

**Closed by jgwest** 2024-02-10 11:40 UTC
Labels: bug
