### ISSUE TITLE
Expose force sync in SyncOption on the ApplicationSpec

### ISSUE THREAD

**Issue by rumstead** [argoproj/argo-cd#5214] opened 2021-01-08 21:43 UTC
# Summary

I would like the ability for ArgoCD to automatically force sync applications without having to use the argocd cli or UI. 

# Motivation

When a developer makes a change to an immutable object in their manifests, they shouldn't need to take manual steps to sync their applications, if they don't wish to. 

# Proposal

I implemented this feature as described here, https://github.com/argoproj/argo-cd/discussions/5172. 

I would like to have it natively supported by exposing the force option in the [SyncOptions](https://github.com/argoproj/argo-cd/blob/v1.8.1/pkg/apis/application/v1alpha1/types.go#L624) on the [ApplicationSpec](https://github.com/argoproj/argo-cd/blob/v1.8.1/pkg/apis/application/v1alpha1/types.go#L69).

**Comment by jessesuen** [comment] 2021-01-08 22:08
Coincidentally, just filed an issue about consolidating all sync options so will dupe to https://github.com/argoproj/argo-cd/issues/5215

FYI: force syncing CRDs is *extremely* dangerous. If the CRD is forcibly synced (due to immutability), it results in the CRD itself being deleted and all CR instances. I know this from experience.

**Comment by jessesuen** [comment] 2021-01-08 22:08
Duplicate of https://github.com/argoproj/argo-cd/issues/5215

**Closed by jessesuen** 2021-01-08 22:08 UTC
Labels: enhancement

**Comment by rumstead** [comment] 2021-01-09 00:22
Appreciate the note about Cards @jessesuen I will definitely keep that in mind
