### ISSUE TITLE
argocd v2.3.0 forgets list view

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-cd#8715] opened 2022-03-08 15:16 UTC
Login to argocd ui

It is in default tiles mode

Click list modes

Click an app

Click manage your applications, and diagnose health problems

Apps are back in tiles mode

Similarly, Summary mode does not persist

**Comment by rwong2888** [comment] 2022-03-08 15:16
@alexmt

**Comment by rodrigo14miguel** [comment] 2022-03-08 16:24
duplicate of #8702

**Closed** 2022-03-08 18:59 UTC
Labels: bug
