### ISSUE TITLE
Run jobs and cronjobs on-demand

### ISSUE THREAD

**Issue by jan-ludvik-deltatre** [argoproj/argo-cd#5844] opened 2021-03-23 17:54 UTC
# Summary

When I have cronjob and job resource in UI, I would like to have a button that would run these immediately. Not really sure if this is in scope of ArgoCD - if not please close the issue :)

# Motivation

I am testing some cronjobs and I have to manually edit the cron expressions in UI to the next minute to have them running.

# Proposal

Not really sure - maybe a new job would be created when a cronjob is ran with this feature?

**Comment by jsoref** [comment] 2021-05-26 21:35
duplicate of #4116

**Closed** 2021-05-27 06:13 UTC
Labels: enhancement
