### ISSUE TITLE
use management with OIDC provider seems not working (argo-cd v1.7.11)

### ISSUE THREAD

**Issue by tonythomasm** [argoproj/argo-cd#6539] opened 2021-06-23 16:45 UTC
Our argo-cd deployment is running with verison 1.7.11 (Deployed using helm ctart). We have an OIDC provider, and configured it with argo for user management as per  https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#existing-oidc-provider. 

From the `argocd-server` log  I could see 

```time="2021-06-23T16:24:11Z" level=info msg="Web login successful. Claims: {............```
(taking part of the log above as it containes sensitive data)

after this it logs as below:

```time="2021-06-23T16:24:11Z" level=info msg="received unary call /version.VersionService/Version" grpc.method=Version grpc.request.claims=null grpc.request.content= grpc.service=version.VersionService grpc.start_time="2021-06-23T16:24:11Z" span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Version grpc.service=version.VersionService grpc.start_time="2021-06-23T16:24:11Z" grpc.time_ms=0.211 span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = invalid session: json: cannot unmarshal array into Go struct field StandardClaims.aud of type string" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2021-06-23T16:24:11Z" grpc.time_ms=0.469 span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="received unary call /cluster.SettingsService/Get" grpc.method=Get grpc.request.claims=null grpc.request.content= grpc.service=cluster.SettingsService grpc.start_time="2021-06-23T16:24:11Z" span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-06-23T16:24:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=Get grpc.service=cluster.SettingsService grpc.start_time="2021-06-23T16:24:11Z" grpc.time_ms=0.976 span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="received unary call /session.SessionService/GetUserInfo" grpc.method=GetUserInfo grpc.request.claims=null grpc.request.content= grpc.service=session.SessionService grpc.start_time="2021-06-23T16:24:11Z" span.kind=server system=grpc
time="2021-06-23T16:24:11Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetUserInfo grpc.service=session.SessionService grpc.start_time="2021-06-23T16:24:11Z" grpc.time_ms=0.517 span.kind=server system=grpc
```

argocd-cm configmap is as below:

```apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-23T15:10:04Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.13.0
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  oidc.config: |
    name: IAM_OIDC
    issuer: https://<hostname>.com
    clientID: 60xxxxxxxxxxxxxxx
    clientSecret: mxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxO
    auth_url: https://<hostname>.com/api/iam/v3/oidc/default/authorize
    token_url: https://<hostname>/api/iam/v3/oidc/token
    requestedScopes: ["openid", "profile", "email"]
```

kubernetes Version: `v1.17.17+IKS`

argocd-version

```MacBook-Pro argocd % helm list argo-cd
NAME                 	REVISION	UPDATED                 	STATUS  	CHART                     	APP VERSION	NAMESPACE
argo-cd              	1       	Wed Jun 23 20:40:03 2021	DEPLOYED	argo-cd-2.13.0            	1.7.11     	argocd
```

Please help to solve this problem. If its already fixed in some latest versions, kindly let me know.

**Comment by jannfis** [comment] 2021-06-27 07:14
Duplicate of #3462

**Closed by jannfis** 2021-06-27 07:14 UTC
Labels: bug, duplicate
