### ISSUE TITLE
ANSI color support in pod log view

### ISSUE THREAD

**Issue by yujunz** [argoproj/argo-cd#6237] opened 2021-05-14 09:05 UTC
# Summary

Bring back ANSI color support in pod log view.

More context in https://github.com/argoproj/argo-cd/pull/5233#pullrequestreview-571889737

# Motivation

ANSI colored logs are hard to read at the moment

<img width="716" alt="Screen Shot 2021-05-14 at 5 00 04 PM" src="https://user-images.githubusercontent.com/6813397/118248031-6ecf1c00-b4d6-11eb-916c-e2e794b02865.png">

# Proposal

Either cleanup ANSI color control words or support display color.

**Comment by jessesuen** [comment] 2021-05-14 20:22
Duplicate of #5990

**Closed by jessesuen** 2021-05-14 20:22 UTC
Labels: enhancement
